### PR TITLE
Android: Remove obsolete files: eclipse

### PR DESCRIPTION
**Pull request by Florin9doi**

### CODE REVIEW

**Comment by hrydgard** [comment]
Nope. A few developers still use this path. Well, maybe the eclipse stuff can go, but not ant.

**Comment by Florin9doi** [comment]
Are you sure about Ant? 
Ant support has been removed more than a year ago : https://stackoverflow.com/questions/42912824/the-ant-folder-is-suddenly-missing-from-android-sdk-did-google-remove-it

**Comment by hrydgard** [comment]
It's officially done indeed, but it can still work. @unknownbrackets is for example not going to be happy if we kill this support.

**Comment by unknownbrackets** [comment]
I mean, all I want is a build tool that outputs the build log realtime, has sane logging levels (not just a `--info` that logs too little and `--debug` that logs too much), and lets me specify the number of concurrent threads in an obvious way that's not committed to vcs.

I actually don't really like `ant`, but it seems like `gradle` can't even get the basics right, or more likely that I'm just an outdated fool and the things I listed above - all obvious features of every other build tool - aren't considered the basics anymore.  Go figure.  I'm sure it's way better in a lot of less basic ways.

I suppose android/README.txt should be updated or just removed as well...

-[Unknown]

**Pull request merged**
