### PR TITLE
Update the README for 1.5.

### PR DESCRIPTION
**Pull request by hrydgard**
As always, I probably forgot something important?

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Worth calling out sustained performance mode (#9901), adhoc server (#9984), Linux controller mappings (#9997)?

Should we add " * Assorted minor compatibility fixes, code cleanup and performance improvements" like 1.4.0 had?  It's true this time around too.

-[Unknown]

**Comment by zminhquanz** [comment]
That's look good , should be release

**Comment by hrydgard** [comment]
Yeah, bit busy but I'll try to get it out tomorrow or the day after.

**Comment by DJScias** [comment]
I know 1.5 introduced Vulkan feature parity with other renderers like buffered rendering, stencil support, etc..

Is this meant to be understood through the fact Vulkan support is now enabled in Android? Because I don't think it's part of multithreading Vulkan.

Personally, but I could be wrong, the fact it's feature-parity is nearly (if not completely) the same as the other renderers is something of note? Or am I literally blind and reading over it without realizing?

Kind regards,
DJScias

**Comment by hrydgard** [comment]
It is of note mainly because 1.4 had basic but very far from feature-complete Vulkan support on Windows only.

**Comment by DJScias** [comment]
Well, I figured it was of note. Just didn't see it in the PR readme change written down unless I missed it. :)

Kind regards,
DJScias

**Comment by iOS4all** [comment]
My wishlist on version 1.5
Support iOS Metal api

**Comment by hrydgard** [comment]
1.5 is released tomorrow, not gonna start and finish Metal in that time :P  Maybe for 1.6, depends.

**Pull request merged**
