### PR TITLE
GPU: Add setting to control inflight frame usage

### PR DESCRIPTION
**Pull request by unknownbrackets**
So that users can turn it off and be sure it's not a source of input lag.

Not super confident about the checkbox title, "Allow gameplay ahead of display (faster, input lag)", open to competing ideas...

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
"Buffering" or "Queue" can indicate a cause of latency - maybe "graphics command buffering" or "max queued frames" or something? Hm..

**Comment by unknownbrackets** [comment]
I've changed it to "Buffer graphics commands (faster, input lag)".  I think it makes sense...

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, that's OK. 

Hm, I'm wondering if it's interesting to allow a value of 2 as well? Might be useful as a compromise. Just figure thinking about this before we lock down the translation string...

**Comment by unknownbrackets** [comment]
Okay, added that.  Used "Up to 2" to try to make it clear that it's not fixed at that.

-[Unknown]

**Comment by iota97** [comment]
On Linux at least changing this in game cause all sort of problem (Missing tris, flicker, weird frame in between, emulator become unresponsive and need to be killed). It can even cause problem if you go in game, exit to main menu, change it and start another game (didn't manage to see any of them if changed before starting a game at all).

May be better to disable in game (and may require a restart like graphical API change)?

**Comment by unknownbrackets** [comment]
Hm, I hadn't reproduced that before but I'm seeing it now.  Ideally, we should restart graphics (similar to when you resize on Android), but this will only work on some platforms.  For example, Windows / OpenGL doesn't really have a way to restart graphics... we may have to restart indeed.

-[Unknown]

**Pull request merged**
