### PR TITLE
More header cleanups

### PR DESCRIPTION
**Pull request by unknownbrackets**
Includes #13268.  The timing didn't seem to improve much (I didn't average any runs, though), but Config.h as an include is now showing up and the overall stats look better.

Now we have:
25514 ms: Core/Config.h (included 178 times, avg 143 ms)

Surprisingly, SDLVulkanGraphicsContext.cpp.o  (833 ms) spent a lot on Config.h somehow.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
I think on the top, now that the biggest fish have been fried, you're gonna get common headers that are often early in the include sequence and include common heavy system headers like <map> (since other headers after this one in the cpp files won't also end up including them). I don't see anything obviously super expensive in Config.h...

**Comment by iota97** [comment]
I was curios to try as well (using latest master, AKA c45b6c5ac6cd85f7fd4070f4e0d72b2da6411281).

On x86_64 Linux I get from slowest:

```
44908 ms: ext/armips/./stdafx.h (included 52 times, avg 863 ms)

[Various standard C++ header]

14016 ms: Core/Config.h (included 178 times, avg 78 ms)
```

Might not be too much of interest, but I see no harm in uploading my capture result: [build_capture.zip](https://github.com/hrydgard/ppsspp/files/5052250/build_capture.zip).

**Comment by unknownbrackets** [comment]
Yeah, I'm going to update armips a bit later (as long as it passes travis), which should help that.

 -[Unknown]

**Comment by unknownbrackets** [comment]
Hmm, trying a new armips it actually builds a little slower...

-[Unknown]

**Pull request merged**
