### PR TITLE
Fix issue in #12145

### PR DESCRIPTION
**Pull request by tbocek**
* fixed issue with: [libretro ERROR] [G3D] glewInit() failed 
* No need to call video_cb if there is no image

Please test first!

### CODE REVIEW

**Review by hrydgard — APPROVED** [review]

**Comment by hrydgard** [comment]
Tested enough? should I go ahead and merge?

**Comment by tbocek** [comment]
My last tests were back in May, I would like to get feedback from @soredake @i30817 before merging -> (https://github.com/hrydgard/ppsspp/issues/12145)

**Comment by twinaphex** [comment]
This would be very welcome if it fixes Wayland context (which previously was not working) while also still working with DRM/KMS context mode.

**Comment by hrydgard** [comment]
I'm just gonna merge it, we can always revert if it causes problems.

**Pull request merged**
