### PR TITLE
Add atrac looping hack for 4 games

### PR DESCRIPTION
**Pull request by sum2012**
helps https://github.com/hrydgard/ppsspp/issues/13773
(leave this to check) https://github.com/hrydgard/ppsspp/issues/7601
helps https://github.com/hrydgard/ppsspp/issues/11586
helps https://github.com/hrydgard/ppsspp/issues/10139
helps https://github.com/hrydgard/ppsspp/issues/12083
We have tried 7 years still do not get fixed.
So that I think that we can add in compat.ini

### CODE REVIEW

**Comment by LunaMoo** [comment]
I'd say as for hacks like that compat.ini are better than toggle since people will just activate it and forget breaking stuff in other games.

**Comment by Gamemulatorer** [comment]
Yeah compat.ini is better and I already said that also 😅 https://github.com/hrydgard/ppsspp/pull/13793#issuecomment-1009578212

**Comment by hrydgard** [comment]
I changed "fix" to "helps" so that the issues don't automatically close. I still think this should be considered a temporary measure, and hopefully someone will come up with a real fix at some point...

**Comment by AryzenRS** [comment]
> (leave this to check) #7601

Just tried it, it loops in the wrong part of the song. About 8 bars in for the title menu. If left for long enough it will start looping a different part of the song.

**Comment by sum2012** [comment]
The atrac need to re-write by someone to fix.
#15838
> > (leave this to check) #7601
> 
> Just tried it, it loops in the wrong part of the song. About 8 bars in for the title menu. If left for long enough it will start looping a different part of the song.

**Comment by Catarax** [comment]
Stable 1.14 (Windows)
Jackass (Europe), the music still loop every 2 seconds, and then you get no sound on the next game. Emulator crash on exit.
The main menu music also stop all the music after 2 seconds of listen.

**Comment by sum2012** [comment]
please download newest version in
https://buildbot.orphis.net/ppsspp/index.php

在 2022年12月16日週五 上午12:22，Catarax ***@***.***> 寫道：

**Comment by sum2012** [comment]
Let me check

**Comment by FATCatAndroid12** [comment]
This hack atrac loop can be remove now because https://github.com/hrydgard/ppsspp/pull/20098 is fixes the 4 games that needed this compat?

**Comment by hrydgard** [comment]
@FATCatAndroid12 nah, the old implementation will still be used for old savestates, so the hacks stay (but will not be enabled anymore for new game bootups)

**Pull request merged**
