### PR TITLE
Support vsync in all hardware backends, support runtime update

### LINKED ISSUE #7929: D3D vsync prevents unthrottle from working right (plus, fixed hotkey bug)
1.If you set any hotkey for "Save State",pressing F2 anywhere except the game pause screen,it will bring the language selection menu(I check the source but I didn't find anywhere anything about hotkey and that many)

2.If VSync is enabled while the video backend is Direct3D9,the unthrottle\alternative speed will be limited to 200% on 30fps games and 100% on 60fps games and to disable the vsync effect,you have to disable it and restart ppsspp(it won't work by just disabling it).
In my nvidia control panel,vsync is set to "Use the 3D application settings")

### LINKED ISSUE #12493: dx11 vsync not implemented
### What happens?
dx11 vsync is broken on 1.9.3
runs fullspeed
enabled or disabled, it always tears screen like hell.
opengl vsync works though..
it happens on every game...

### What *should* happen?
idk

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

windows 10 1903 64bit
ppsspp 1.9.3
intel iris6100 with latest driver

### PR DESCRIPTION
**Pull request by unknownbrackets**
This does a few things:
 * Uses FIFO on Vulkan when vsync enabled, assuming this will be more reliable than MAILBOX.
 * Forces frameskip for unthrottle on Vulkan when vsync enabled.
 * Skips vsync for all other backends when unthrottled (like OpenGL.)  Fixes #7929.
 * Enables vsync on Direct3D 11.  Fixes #12493.
 * Ensures all backends can enable/disable vsync without a restart (previously D3D 9 required a restart.)

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Looks good!

**Comment by MojoJojoDojo** [comment]
Finally no micro stuttering anymore.

**Comment by unknownbrackets** [comment]
Probably, the affect on OpenGL was because I moved the vsync interval setting to BeginHostFrame, where it should've been.  That just means the driver didn't like when we were updating the value, I guess.

That's not relevant to the other backends, though, because their APIs are different.

-[Unknown]

**Comment by MojoJojoDojo** [comment]
Also , Vsync on DX9 no longer disables the "unthrottle" button from working.
Previously it was always stuck on 60 fps even if you tried to unthrottle.

**Comment by unknownbrackets** [comment]
That's what "Skips vsync for all other backends when unthrottled (like OpenGL.) Fixes #7929." meant.

-[Unknown]

**Pull request merged**
