### PR TITLE
Fix game save in yugioh

### LINKED ISSUE #7914: yugioh ppsspp stuck (corrupt save)
hi guys
i'm new here and i'm using ppsspp v1.0.1
now i'm playing this yugioh gx tag force 1
everything is fine, the duel,the card,the field..
but there is 1 thing that bothers me, i can't save my game when i've been this far.
Everytime i save the game, it always stuck in checking memory card and it won't proccess any further,
and it does feel uncomfortable if i use "save state" option to save the game
please help me to solve this problem and recover my save
Thanks

### PR DESCRIPTION
**Pull request by sum2012**
When use save\load status without game save in a long time
,the game would not allow to save to hang.
This change make the save to fix corrupt.
Fix #7914

### CODE REVIEW

**Comment by sum2012** [comment]
hang save log:
https://gist.github.com/sum2012/a88185554c01040a165e

**Comment by unknownbrackets** [comment]
This isn't really a fix, I don't think we should introduce hacks like this at all.

What this means is another dialog is supposedly active - maybe networking.  This could simply be a bug in networking.  I don't want to hack up the save code just for that.

What if you change:

WARN_LOG(SCEUTILITY, "sceUtilitySavedataInitStart(%08x): wrong dialog type", paramAddr);

To:

WARN_LOG(SCEUTILITY, "sceUtilitySavedataInitStart(%08x): wrong dialog type %d", paramAddr, currentDialogType);

What dialog is in progress?

-[Unknown]

**Comment by sum2012** [comment]
56:56:179 user_main    N[UTIL]: HLE\sceUtility.cpp:189 sceUtilitySavedataInitStart(09c0c0f0): wrong dialog type 4

**Comment by unknownbrackets** [comment]
It's as I predicted - UTILITY_DIALOG_NET.  This is probably caused by a bug in sceUtilityNetconf*, and triggered when you activate network functionality.

-[Unknown]

**Comment by sum2012** [comment]
Do that mean that someone play in netplay then save status -make dialog corrupt ?

**Comment by unknownbrackets** [comment]
Yes.  It could be that saving state isn't even important - maybe just playing in netplay makes it so you can't ever save again, or something?

Another possibility is that a save state was created while the network dialog is open, and then that was loaded later.  Maybe it doesn't clean up properly.

Anyway, for sure the game must've called `sceUtilityNetconfInitStart` at some point before that savestate was created.  After that, something went wrong, and the game never called `sceUtilityNetconfShutdownStart`.  That's the problem here.  It needs to call `ShutdownStart` once for every time it calls `InitStart` - the same is required on a real PSP.

-[Unknown]

**Comment by sum2012** [comment]
I cannot netplay this game :(

**Pull request closed without merging**
