### PR TITLE
GLES: Simplify the framebuf offset detection

### LINKED ISSUE #12869: Breath of Fire 3 ULES00193 constant screen flickering
Flickering started from build PPSSPP_v1.9.3-260-g81118454f and still exist on all builds till PPSSPP_v1.9.3-731-gf82e7a4e7 . 
It's not the same as it was on previous issue with this game, other games don't have this issue but maybe it breaks something else. Attached video for the problem. https://youtu.be/avHnW7TL8oQ

Iphone 7 plus iOS 13.4.1 
Open GL rendring

### PR DESCRIPTION
**Pull request by unknownbrackets**
The logic related to the target framebuf made no sense, and I think the code was generally confusing.  Figured a bunch of comments would either help or at least not make it worse...

The real problem is that `SetOffsetTexture()`, like `SetTexture()` can change the "to be applied" texture.  That doesn't work in GLES, where we have to apply the texture before software transform, for state reasons.

The interdependencies are a pain there, so I just added a result flag to apply the texture again for GLES.  Then reapply draw state in this uncommon case.  We should've set flags if anything needs resetting.

There was also a difference in handling of the texture offset, for similar reasons.  To simplify this, I just changed it to reverse the offset change so the original shader/etc. can be used.

Fixes #12869.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
We could possibly break `SoftwareTransform()` up, so that the actual transform is part 1 (which relies only on texture state.)

Then we'd have a part two that would expand rectangles/lines/whatever, detect the clear stencil value, and handle flipped viewports as needed.  We even already have a "step 2" comment.

Then we could do step 1 before `ApplyDrawState()` safely, apply the texture, and then do step 2.  Might also move the texture offset detection out too (feels like it should live on texture cache, really.)  That might be better but all the interdependencies are tricky.  Wasn't sure about making that change right now...

-[Unknown]

**Comment by unknownbrackets** [comment]
Something like this:
https://github.com/hrydgard/ppsspp/commit/7d6acad6333d946886b9182d757d4cc312cb2688

Which seems to be working fine...

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, something like that definitely seems like the way to go. This is all so messy right now...

**Comment by hrydgard** [comment]
I think let's do this for ease of user bisection: I'm going to review this one change a little closer later and then we'll merge this, and then I would be happy to merge your refactoring on top of that.

**Comment by hrydgard** [comment]
Nice work, code makes more sense and very well commented.

**Pull request merged**
