### PR TITLE
SDL: support HiDPI on wayland

### PR DESCRIPTION
**Pull request by hch12907**
Not sure if this is correct, I am familiar with neither SDL nor the codebase of PPSSPP. Tested on X11 and Wayland though, both seem to work just like before.

### CODE REVIEW

**Comment by hrydgard** [comment]
Cool, I'm gonna test on my Linux laptop where I had some DPI issues soon.

**Comment by hrydgard** [comment]
It doesn't help the weird DPI I'm getting, but also it doesn't break anything. Let's get it in.

**Review by hrydgard — APPROVED** [review]

**Comment by hrydgard** [comment]
Hm, this somehow made things gigantic on OSX, so gonna have to add some checks, or figure out what's going on..

**Comment by hrydgard** [comment]
Actually, I'm going to revert this. It's clearly not tested enough. For example, on OSX, you get a different rendered DPI after the first window resize, plus it's wrong.

**Comment by hch12907** [comment]
That's a bummer, because I don't have a MacOS machine to test the code on :/

**Comment by hrydgard** [comment]
I may resurrect and debug this myself on Mac in the near future, I just didn't want to leave it in such a broken state. That's probably a good place to start looking yeah.

**Pull request merged**
