### PR TITLE
Interpolate bezier patch colors/UVs using bernstein

### LINKED ISSUE #4551: Coded Arms vertice issue
It appears to be when playing Coded Arms that it has some sort of vertice error which throws stuff around while playing. I would explain, but it is much better demonstrated with the video I recorded of gameplay (linked). This issue is both on Android and PC.
http://www.youtube.com/watch?v=Prze2K41Vus

I know this is not a glaring issue and there are probably better things to deal with this moment, so don't worry I won't chivvy people about it.

### LINKED ISSUE #7525: dai-2-ji super robot taisen z saisei-hen graphical problem (Bezier issue?)
It's always happening.

savestate(rename jpg to 7z)
after loading the savestate press circle button.
ppsspp_state

PPSSPP

PSP

GE debugger

more tabs
https://gist.github.com/daniel229/913e8052f26d2814d7ec

### PR DESCRIPTION
**Pull request by unknownbrackets**
This matches my tests almost exactly.  I suspect it will help #7525.

~~I have not yet tested UV coords, they're probably interpolated this way too~~.  UV coords were also improved (exact match to my test) by using this.  Did not measure the speed impact, but I don't really think it'll be bad.  Hopefully.  This is high quality anyway.

The colors this produces are only slightly off - in a blend between red and blue, this produces e.g. (108, 0, 147) but should produce (108, 0, 148).  Pretty acceptable - otherwise it's 1:1.

Fixes #7525, fixes #4551.

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
Yeah,fixed https://github.com/hrydgard/ppsspp/issues/7525

**Comment by daniel229** [comment]
Also fixed https://github.com/hrydgard/ppsspp/issues/4551

**Comment by unknownbrackets** [comment]
Nice catch with #4551, that makes sense, that's exactly the sort of error I was seeing with the UVs in my testing.

-[Unknown]

**Comment by hrydgard** [comment]
Very nice! And nice work with the test!

**Pull request merged**
