### PR TITLE
[Adhoc] Fix PSP2i unable to enter dungeon when using RadminVPN issue.

### LINKED ISSUE #13648: Phantasy Star Portable 2 Infinity Adhoc Multi Mode Issue
### What happens?
When attempting to start a mission in Phantasy Star Portable 2 Infinity only the host is able to enter the dungeon. Other players attempting to enter the dungeon are stuck on loading screen. This issue is not present in the latest stable version.

### What *should* happen?
When attempting to start a mission in Phantasy Star Portable 2 Infinity all players should be able to enter the dungeon.

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
Both computers I'm testing on have nearly identical hardware. Only difference is that one machine has a 2060 SUPER and the other has a 1070.
Operating System
	Windows 10 Enterprise 64-bit
CPU
	Intel Core i7 7700 @ 3.60GHz
	Kaby Lake 14nm Technology
RAM
	32.0GB
Motherboard
	Micro-Star International Co. Ltd. Z390-A PRO (MS-7B98) (U3E1)
Graphics
	VG248 (1920x1080@144Hz)
	4095MB NVIDIA GeForce GTX 1070 (EVGA)
Storage
	465GB Samsung SSD 850 EVO 500GB (SATA (SSD))
	465GB Samsung SSD 850 EVO 500GB (SATA (SSD))
	2794GB TOSHIBA HDWD130 (SATA )
Optical Drives
	ASUS DRW-24B1ST j
Audio
	Realtek High Definition Audio

### PR DESCRIPTION
**Pull request by anr2me**
Fix https://github.com/hrydgard/ppsspp/issues/13648

### CODE REVIEW

**Comment by ANR2ME** [comment]
Hmm.. multiplying the socket buffer size like this approach might not be the best solution for VPN issue due to small buffer size, since there are games that use buffer size as small as 4 bytes.

**Comment by Anuskuss** [comment]
@ANR2ME Why is this (or more specifically `TCP_NODELAY`) not enabled by default? I understand that Nagle's is supposed to improve throughput but for Adhoc it feels like getting the packets ASAP is much more important (even over the internet).

**Comment by ANR2ME** [comment]
> 
> 
> @ANR2ME Why is this (or more specifically `TCP_NODELAY`) not enabled by default? I understand that Nagle's is supposed to improve throughput but for Adhoc it feels like getting the packets ASAP is much more important (even over the internet).

Because PSP have syscall to Flush PTP (TCP) connection, it means Nagle algo wasn't enabled by default, otherwise Flushing won't be needed.

Unlike most PC games where nagle algo usually being disabled for performance reason.

**Comment by Anuskuss** [comment]
> it means Nagle algo wasn't disabled by default on real PSP

That's tricky. I feel like it's probably better to leave it enabled then to correctly emulate the PSP but on the other side it would probably be beneficial and improve Adhoc (like most advanced features like resolution scaling and shaders which aren't technically correct either but improve the experience). Well, I'm glad I don't have to make such decisions 😛

**Pull request merged**
