### PR TITLE
Fix many symbols on jpn0.pgf.

### PR DESCRIPTION
**Pull request by nassau-tk**
I fixed some major symbols on jpn0.pgf.
Parenthesis,Circle,Square,Triangle,Numbers in the circle,etc...and more symbols.

### CODE REVIEW

**Comment by hrydgard** [comment]
I see you force-pushed a new version of this - what else changed? Is this ready to go?

**Comment by nassau-tk** [comment]
Yes, I fixed symbols.

But, I had a time untill merged.
So,  when I checked about 40,000 kanji and I found 3 broken kanji and repair it.

**Comment by nassau-tk** [comment]
Probably, It will finish the work for jpn0.pgf.

- Numbers
- Alphabet
- Greek
- Russian
- Roman Numbers
- Hiragana / Katakana (Japanese)
- Kanji (Japanese&Chinese)
- Symbols

Thank you for your kind!!:wave::grinning:

**Comment by hrydgard** [comment]
awesome!

**Pull request merged**
