### PR TITLE
Resample mp3 in 32000Hz

### LINKED ISSUE #5213: Hanayaka Nari Wa ga Ichizoku strange MP3 mono voice
Accordance to http://www.emunewz.net/forum/showthread.php?tid=149045
the voice is a mono MP3.

06:59:370 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2180 sceKernelStartThread(thread=298, argSize=0, argPtr=00000000)
06:59:418 Sound Thread I[ME]: HLE\sceAtrac.cpp:1272 0=sceAtracSetDataAndGetID(08a6c3c0, 00126424)
06:59:418 Sound Thread W[ME]: HLE\sceAtrac.cpp:1162 This is an atrac3+ stereo audio
06:59:419 NowLoading   I[KERNEL]: HLE\sceKernelThread.cpp:2299 sceKernelExitDeleteThread(0)
06:59:488 user_main    I[IO]: HLE\sceIo.cpp:837 stdout: 071.gim Loaded
06:59:622 user_main    I[IO]: HLE\sceIo.cpp:837 stdout: 700.gim Loaded
06:59:654 user_main    I[IO]: HLE\sceIo.cpp:837 stdout: 071.gim CountPlus
06:59:687 user_main    I[IO]: HLE\sceIo.cpp:837 stdout: 071.gim CountPlus
07:09:431 user_main    E[ME]: HLE\sceMp3.cpp:589 sceMp3ReleaseMp3Handle: bad mp3 handle 00000000
07:21:643 user_main    E[ME]: HLE\sceMp3.cpp:589 sceMp3ReleaseMp3Handle: bad mp3 handle 00000000
07:23:646 user_main    E[ME]: HLE\sceMp3.cpp:589 sceMp3ReleaseMp3Handle: bad mp3 handle 00000000
07:25:564 user_main    E[ME]: HLE\sceMp3.cpp:589 sceMp3ReleaseMp3Handle: bad mp3 handle 00000000
07:27:516 user_main    E[ME]: HLE\sceMp3.cpp:589 sceMp3ReleaseMp3Handle: bad mp3 handle 00000000
07:34:206 user_main    E[ME]: HLE\sceMp3.cpp:589 sceMp3ReleaseMp3Handle: bad mp3 handle 00000000
07:34:573 user_main    I[ME]: HLE\sceMp3.cpp:533 sceMp3GetInfoToAddStreamData(09FFF5B8, 08A615C4, 09FFF5DC, 09FFF5D8)
07:34:589 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2180 sceKernelStartThread(thread=280, argSize=4, argPtr=08a621ac)
07:34:611 ThreadCtrl   I[KERNEL]: HLE\sceKernelThread.cpp:2273 sceKernelExitThread(0)
07:34:623 user_main    I[ME]: HLE\sceMp3.cpp:561 sceMp3NotifyAddStreamData(09FFF5B8, 29232)
07:41:180 user_main    E[ME]: HLE\sceMp3.cpp:589 sceMp3ReleaseMp3Handle: bad mp3 handle 09fff5b8
07:43:816 user_main    E[ME]: HLE\sceMp3.cpp:589 sceMp3ReleaseMp3Handle: bad mp3 handle 09fff5b8
07:44:383 user_main    I[ME]: HLE\sceMp3.cpp:533 sceMp3GetInfoToAddStreamData(09FFF5B8, 08A615C4, 09FFF5DC, 09FFF5D8)
07:44:400 user_main    I[KERNEL]: HLE\sceKernelThread.cpp:2180 sceKernelStartThread(thread=280, argSize=4, argPtr=08a621ac)
07:44:401 ThreadCtrl   I[KERNEL]: HLE\sceKernelThread.cpp:2273 sceKernelExitThread(0)
07:44:433 user_main    I[ME]: HLE\sceMp3.cpp:561 sceMp3NotifyAddStreamData(09FFF5B8, 37008)

### PR DESCRIPTION
**Pull request by sum2012**
Helps #5213

Hope merge in v1.11 so that chinese people 1 more reason to update

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Does this fix it or is it just theoretical?  What is the sample rate of the mp3s included in the game?

Looks backwards to me; this is the sample rate of the data.  We want it to resample to 44.1kHz always, presumably.  This line seems to assume the input is always 44.1kHz:
```
Au->decoder = new SimpleAudio(Au->audioType);
```

But my tests had shown that non-44.1kHz mp3s were rejected by sceMp3 anyway.

-[Unknown]

**Comment by sum2012** [comment]
The second sound is old woman but "current master is male and the sound like robot"
This patch is really fix it.

48:09:122 user_main    N[ME]: HLE\sceMp3.cpp:411 sceMp3Init(): channels=1, samplerate=32000Hz, bitrate=48kbps

How about only resample for channels==1 ?

**Comment by sum2012** [comment]
Read again my jpcsptrace
https://gist.github.com/sum2012/e2d513c55342c40f5e12
This game's SamplingRate (32000Hz) is not rejected
Your test is something wrong

**Comment by hrydgard** [comment]
Leave the 48000 check in place but also allow 32000 for now then...  So that we don't change what gets called for the 44100 case.

**Pull request merged**
