### PR TITLE
Add basic support for loongarch64

### PR DESCRIPTION
**Pull request by KatyushaScarlet**
Can run properly on loongarch64 CPU with FakeJIT for now.
Can get correct thread count and features of Loongson 3A5000 (4c4t) and 3A6000 (4c8t).
Because cpu_features added support for loongarch64 recently, it needs to be upgraded to the latest version.
Tested on 3A5000 and 3A6000

### CODE REVIEW

**Review by hrydgard — APPROVED** [review]

**Comment by hrydgard** [comment]
ios build says:

```
/Users/runner/work/ppsspp/ppsspp/ext/cpu_features/src/impl_aarch64_macos_or_iphone.c:23:2: error: "Darwin needs support for sysctlbyname"
#error "Darwin needs support for sysctlbyname"
 ^
```

I think this is separate from the loongson changes and comes just from the cpu_features upgrade.

I'm going to make a separate PR that we should merge first, that just upgrades cpu_features.

**Comment by hrydgard** [comment]
Right, so exactly as suspected: https://github.com/hrydgard/ppsspp/pull/18057 

I'll see if I can figure it out.

**Comment by hrydgard** [comment]
OK, I've merged an upgrade of cpu_features.

Can you rebase this on master?

**Comment by hrydgard** [comment]
Seems the conflict is about LOONGARCH64 vs LOONGARCH. What do you think?

**Comment by KatyushaScarlet** [comment]
> Seems the conflict is about LOONGARCH64 vs LOONGARCH. What do you think?

I think using LOONGARCH would be fine.

**Comment by KatyushaScarlet** [comment]
By the way, should the tag be "LoongArch64" ?

**Pull request merged**
