### PR TITLE
Detect power saving mode on Android

### PR DESCRIPTION
**Pull request by unknownbrackets**
This doesn't affect games (although, it could), but instead most importantly notifies users.

I'm sure that low battery may notify users anyway, but power saving is more likely not to: I remember on my Galaxy S3 (which I no longer have), it was easy not to notice it was even on.  This shows a message on startup when it is on.

Potentially we could send a low battery level to games which might in some rare cases influence how they render or something.

Anyway, this also disables sending reporting CRCs when power is low / in saving mode.

-[Unknown]

### CODE REVIEW

**Comment by Anuskuss** [comment]
I know you and iOS ain't best friends, but could the Low Power Mode get detected on iOS? When LPM is on it actually underclocks the processor so it might be important to detect on iOS too.

**Comment by unknownbrackets** [comment]
It sure could.  Someone would just need to write the iOS-specific code to call this API and notify the PPSSPP core about low-power mode.  It's intentionally been written so that other platforms can integrate easily.

Pull requests accepted.

-[Unknown]

**Comment by VIRGINKLM** [comment]
Nice one, to me little details like this one make PPSSPP look like a very serious app/project.

**Comment by sum2012** [comment]
@hrydgard how about this one ?

**Comment by hrydgard** [comment]
Oh, was meaning to read it through but forgot about it. Looking at it now.

**Pull request merged**
