### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**
P.S. Found some untranslatable strings.

### CODE REVIEW

**Comment by hrydgard** [comment]
I'll fix the strings, thanks!

**Comment by hrydgard** [comment]
I've fixed the strings in #16548 . Let me know if you find any more.

**Comment by TotalCaesar659** [comment]
Thanks, [updated](https://github.com/hrydgard/ppsspp/pull/16552). Found one more string:

**Comment by hrydgard** [comment]
Fixed that one, reused the text from the main menu, in #16553

**Comment by TotalCaesar659** [comment]
Thank you very much, it works. [Updated](https://github.com/hrydgard/ppsspp/pull/16560) again (I hope it's the last one before 1.14).

**Comment by hrydgard** [comment]
Hopefully yes :)

**Pull request merged**
