### PR TITLE
An attempt to add BlockTransferAllowCreateFB for Naruto Shippuden: Ultimate Ninja Impact

### PR DESCRIPTION
**Pull request by Panderner**
This is attempt for adding BlockTransferAllowCreateFB for Naruto Shippuden: Ultimate Ninja Impact. This helps #12544 and Low-end Devices. If successful I'll ready to merge

Anyone tried to test this PR for improves performance for Low-end Devices?

### CODE REVIEW

**Comment by Panderner** [comment]
If there's a graphical glitches for this PR send me the screenshots.

**Comment by hrydgard** [comment]
The change itself looks right. If someone plays the game a lot and notices no problems with this change, I'm happy to merge.

**Comment by Panderner** [comment]
> The change itself looks right. If someone plays the game a lot and notices no problems with this change, I'm happy to merge.

Got it i'm ready to review

**Comment by Panderner** [comment]
I've tested PPSSPP on retroarch using POCO M3
it greatly increases performance for Low-end Devices when I using modified compat.ini here's a results:

Unmodified compat.ini
Screenshot_2020-12-30-16-27-14-612_com retroarch

Modified compat.ini:
Screenshot_2020-12-30-16-25-17-574_com retroarch

**Comment by Panderner** [comment]
@hrydgard are you ready to merge?

**Comment by hrydgard** [comment]
I assume you didn't find any bad effects, like some missing images or save icons or something?

If so I'm ready to merge.

**Comment by Panderner** [comment]
> I assume you didn't find any bad effects, like some missing images or save icons or something?
> 
> If so I'm ready to merge.

Save icons works fine
Screenshot_2020-12-30-20-33-12-895_com retroarch

**Pull request merged**
