### PR TITLE
Update readme for v1.10

### PR DESCRIPTION
**Pull request by sum2012**

### CODE REVIEW

**Comment by hrydgard** [comment]
Mislinked that one - #13057 should have been linked in that commit.

**Comment by sum2012** [comment]
very sorry

在 2020年6月29日週一 03:40，Henrik Rydgård <notifications@github.com> 寫道：

**Comment by hrydgard** [comment]
Why are you sorry? I mislinked.

**Comment by sum2012** [comment]
Oh i see

**Pull request merged**
