### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**
P.S. ["Scope Storage Enabled"](https://github.com/hrydgard/ppsspp/pull/16605#issuecomment-1364669599) is not fixed yet.
P.P.S. Theme names are untranslatable too:

### CODE REVIEW

**Comment by hrydgard** [comment]
Thanks for the reminders, I'll take care of it.

**Comment by TotalCaesar659** [comment]
@hrydgard Hi, do you have a plan for fixing these bugs before 1.15.0 release? It would be great cause I can continue to work on translation after.

**Comment by hrydgard** [comment]
Yes I do, soon, thanks for the reminder, hehe.

**Comment by hrydgard** [comment]
That should do it.

**Pull request merged**
