### PR TITLE
Cpu features

### PR DESCRIPTION
**Pull request by hsoftxl**

### CODE REVIEW

**Comment by hsoftxl** [comment]
android need flag -DHAVE_DLFCN_H, linux need flag -DHAVE_STRONG_GETAUXVAL
how can i fix build script.

**Comment by ANR2ME** [comment]
I think you need to put those definitions in `ppsspp/libretro/Makefile` when not using `./b.sh`, while the one you set in b.sh seems to be okay.

Btw, why did you remove `-DHAVE_STRONG_GETAUXVAL` from Makefile.common ? does it cause an issue?

**Comment by hsoftxl** [comment]
cpu_features/src/hwcaps.c
code like this
```
#if defined(HAVE_STRONG_GETAUXVAL)
#include <sys/auxv.h>
static unsigned long GetElfHwcapFromGetauxval(uint32_t hwcap_type) {
  return getauxval(hwcap_type);
}
#elif defined(HAVE_DLFCN_H)
// On Android we probe the system's C library for a 'getauxval' function and
// call it if it exits, or return 0 for failure. This function is available
// since API level 18.
//
// Note that getauxval() can't really be re-implemented here, because its
// implementation does not parse /proc/self/auxv. Instead it depends on values
// that are passed by the kernel at process-init time to the C runtime
// initialization layer.

#include <dlfcn.h>

typedef unsigned long getauxval_func_t(unsigned long);

static uint32_t GetElfHwcapFromGetauxval(uint32_t hwcap_type) 
```
it need HAVE_DLFCN_H flag in android, but now set HAVE_STRONG_GETAUXVAL,
i want add these flag in build script. so  i remove HAVE_STRONG_GETAUXVAL in Makefile.common 
@ANR2ME

**Comment by ANR2ME** [comment]
Yeah, i've checked that `#ifdef` yesterday when i commented before.

Anyway, the failing builds on your PR are the one that doesn't use `./b.sh`, so i think those flags/definitions supposed to be in `ppsspp/libretro/Makefile` for those failing builds.

**Comment by unknownbrackets** [comment]
CMake args won't pass through to cflags.  Does #16969 help?

-[Unknown]

**Comment by hrydgard** [comment]
If it's fine now after #16969, feel free to go ahead and close this.

**Comment by hsoftxl** [comment]
it is work.

**Pull request closed without merging**
