### PR TITLE
Move texture decode/hash to after vertex decode

### PR DESCRIPTION
**Pull request by unknownbrackets**
~~If nothing else, this will probably help #8012.~~ Hmm, not sure, maybe it won't.

Doesn't seem to have any performance impact currently, but if a texture is detected as only 272 tall, this will never hash the entire 512x512.  Before, it was, but only the first time.  So this will load some textures slightly faster.

Additionally, the code is better broken up and probably cleaner.  I think some of the methods can be more easily shared too, though they currently have small differences.

This also allows for optimizations, such as uploading a subset of a texture, based on the vertex decode data.  None are implemented yet, but an example would be a 480x272 background image that is depal'd, or even video frames that have to be unswizzled.  With this change, we can now limit those operations to only the first 272 rows (or less, as the case may be.)

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
Looks better in https://github.com/hrydgard/ppsspp/issues/8012

**Comment by unknownbrackets** [comment]
How does this look @hrydgard?  Largely just a refactor.

-[Unknown]

**Comment by hrydgard** [comment]
Oh, sorry, forgot to merge. I did look through it..

**Comment by hrydgard** [comment]
Seems there are cases where this causes us to upscale movie textures, see #9125. Will try to find time to look into it soon..

**Pull request merged**
