### PR TITLE
Improve atrac streaming positions from tests

### PR DESCRIPTION
**Pull request by unknownbrackets**
I think this will take care of #8261.

Now I have some passing tests showing a bunch of these things, although there may be more little sample offset issues.

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
Sol Trigger got this log
```
at3 bgm thre W[ME]: HLE\sceAtrac.cpp:1099 80630018=sceAtracAddStreamData(0, 0001df88): too many bytes
```

Gran Turismo looks fine

**Comment by unknownbrackets** [comment]
Hmm.  Does it log sceAtracGetStreamDataInfo() sending `0001df88` before that warning?

-[Unknown]

**Comment by daniel229** [comment]
Sound like yes.000025c8 for example
```
04:28:623 at3 bgm thre N[ME]: HLE\sceAtrac.cpp:1644 0=sceAtracGetStreamDataInfo(0, 09fe5990[08ac22a8], 09fe5994[000025c8], 09fe5998[0007a1a4])
04:28:628 at3 bgm thre N[ME]: HLE\sceAtrac.cpp:1298 00000000=sceAtracDecodeData(0, 08a9d764, 09fe59e0[000004f9], 08ac6a84[00000000], 08ac6a80[0])
04:28:628 at3 bgm thre N[ME]: HLE\sceAtrac.cpp:1644 0=sceAtracGetStreamDataInfo(0, 09fe5990[08ac2878], 09fe5994[00001ff8], 09fe5998[0007a1a4])
04:28:637 at3 bgm thre N[ME]: HLE\sceAtrac.cpp:1298 00000000=sceAtracDecodeData(0, 08a98b48, 09fe59e0[00000800], 08ac6a84[00000000], 08ac6a80[0])
04:28:637 at3 bgm thre N[ME]: HLE\sceAtrac.cpp:1644 0=sceAtracGetStreamDataInfo(0, 09fe5990[08ac2b60], 09fe5994[00001d10], 09fe5998[0007a1a4])
04:28:642 at3 bgm thre N[ME]: HLE\sceAtrac.cpp:1298 00000000=sceAtracDecodeData(0, 08a9ab48, 09fe59e0[00000800], 08ac6a84[00000000], 08ac6a80[0])
04:28:642 at3 bgm thre N[ME]: HLE\sceAtrac.cpp:1644 0=sceAtracGetStreamDataInfo(0, 09fe5990[08ac2e48], 09fe5994[00001a28], 09fe5998[0007a1a4])
04:28:650 at3 bgm thre N[ME]: HLE\sceAtrac.cpp:1298 00000000=sceAtracDecodeData(0, 08a9cb48, 09fe59e0[00000800], 08ac6a84[00000000], 08ac6a80[0])
04:28:650 at3 bgm thre N[ME]: HLE\sceAtrac.cpp:1644 0=sceAtracGetStreamDataInfo(0, 09fe5990[08ac3130], 09fe5994[00001740], 09fe5998[0007a1a4])
04:28:650 at3 bgm thre W[ME]: HLE\sceAtrac.cpp:1099 80630018=sceAtracAddStreamData(0, 000025c8): too many bytes
```

**Comment by unknownbrackets** [comment]
Hah, okay, that's weird.  Seems like this is still a problem with RemainingFrames.  Something about -3 is not correct.  I'll have to debug more later...

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, that seems a lot better.

-[Unknown]

**Comment by daniel229** [comment]
Still get that error

**Comment by unknownbrackets** [comment]
Hmm, any way to reproduce?  I was getting it on the title screen and while walking around, if I waited long enough, but now it doesn't happen either place no matter how long I wait.

-[Unknown]

**Comment by daniel229** [comment]
Still the same way,after loading savedata and waiting.

**Comment by daniel229** [comment]
Wait,looks like git getting confusing and I have not update to the latest one.

**Comment by daniel229** [comment]
Sol Trigger and Gran Turismo look fine with the latest commit.

**Pull request merged**
