### PR TITLE
Functions replace in games

### PR DESCRIPTION
**Pull request by daniel229**
Just follow the alpha order.
between memmove and strcat,be seen in Toukiden games and its demo other 20 games.
memset
https://cloud.githubusercontent.com/assets/3481559/5810613/4ec72fb4-a084-11e4-8801-89dbe82abc43.png

these two functions always be seen togather, in PoPoLoCrois (JPN) and other 5 games,between memcmp and memset
memcpy
https://cloud.githubusercontent.com/assets/3481559/5810641/b8a192b2-a084-11e4-99d1-7f61aeb372ee.png

memmove
https://cloud.githubusercontent.com/assets/3481559/5810642/b8a6b940-a084-11e4-89f2-d11b75d4faaf.png

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Those look correct to me.

-[Unknown]

**Comment by daniel229** [comment]
there is a interesting game ,all functions own its name.
Are the memcpy2 and memcpyalpha need to be replace with memcpy?
https://cloud.githubusercontent.com/assets/3481559/5810701/9c52cc7e-a085-11e4-827a-95ab15de0ded.png
https://cloud.githubusercontent.com/assets/3481559/5810702/9c57779c-a085-11e4-8dc8-506997cbe16b.png

over 2000 knownfuncs in this game
(rename jpg to 7z)
https://cloud.githubusercontent.com/assets/3481559/5810710/aa1eb3c2-a085-11e4-99e1-5cc01b39939d.jpg

**Comment by unknownbrackets** [comment]
That's cool.  It means they left symbols in the binary.

The fact that they have alternate names scares me.  O would not replace them unless it fixes something.  I don't look hard maybe memcpy2 is in 2 byte units or something.

-[Unknown]

**Comment by daniel229** [comment]
I found a interesting function FPS_SetFPSID can adjust max FPS,
the address 0x088CB9B8 set 0 60FPS,set 1 30 FPS, set 2 15FPS

**Comment by unknownbrackets** [comment]
That's probably game specific, but a lot of games use functios like that.  It might be interesting if it's a common function found in other games, but it's kinda short so it might be a little dangerous (short functions that write to static addresses are the most likely to incorrectly match another function via hash and not do the same thing.)

Though, for that specific game, this definitely looks super useful for forcing it to 60 fps.

-[Unknown]

**Comment by daniel229** [comment]
not seeing it in other games yet,FPS_GetFPS is seen in Gachitora,the value is 0x09090980 at 30FPS,don't know how to change this.

**Comment by unknownbrackets** [comment]
Arg a0 to that fund should be 0, 1, 2, or 3.  Any other value is treated as 0.

Forcing the arg to a different number may make it 60 fps.

-[Unknown]

**Comment by daniel229** [comment]
That function does not break.

**Pull request merged**
