### PR TITLE
Enable EXT_blend_func_extended

### PR DESCRIPTION
**Pull request by unknownbrackets**
Not really tested.  The IOS define is because I don't expect iOS headers to be updated yet.

https://www.khronos.org/registry/gles/extensions/EXT/EXT_blend_func_extended.txt

Also, used an `inout` qualifier for `EXT_shader_framebuffer_fetch`.  This was definitely breaking it on PowerVR Rogue (have no information on if it would work with this change or not), per some logs - shader compile errors.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
It sounds like this causes an issue on (some?) SHIELD K1 devices running Marshmallow:

http://forums.ppsspp.org/showthread.php?tid=1552&pid=118331#pid118331

Not confirmed, but I assume those devices should support EXT_blend_func_extended.  The weird thing is, not seeing any reports for that extension - either no one using such a device has felt like enabling reporting, or there's an issue in reporting.

-[Unknown]

**Comment by hrydgard** [comment]
Decided to disable this feature on Android nVidias for now.

**Comment by gannon345** [comment]
v1.2.2-649-g8294a54 build fixed the issue with Nvidia Shield K1 tablet.

**Comment by unknownbrackets** [comment]
I wonder if that means a driver bug, or us using it wrong.  Definitely wasn't using the src1 alpha, then.

-[Unknown]

**Comment by hrydgard** [comment]
Since pretty much the same code works on desktop, I would guess driver bug. If there isn't some GLSL ES technicality about #enabling extensions etc...

**Comment by unknownbrackets** [comment]
We do send `#extension GL_EXT_blend_func_extended : require`... not seeing anything else required by the spec.

-[Unknown]

**Comment by gannon345** [comment]
Just out of curiosity, have you attempted to use the desktop version on the Shield tablet and X1? They support the full OpenGL 4.3 (and I think 4.4), not just GLES 3.x.

**Pull request merged**
