### PR TITLE
Enabled some code on proAdhoc by @lightfirst

### LINKED ISSUE #7962: [Feature Request] Enabled some code on proAdhoc.cpp
I don't know why disable it, but if it does n't breach something, I suggest enable it
what's more enable those code fixed "back loddy but can't plays” 

just remove /*  and  */
----------------
			// Multithreading Lock
			/*peerlock.lock();
			// Unlink Left (Beginning)
			if(prev == NULL)friends = peer->next;
			// Unlink Left (Other)
			else prev->next = peer->next;
			// Multithreading Unlock
			peerlock.unlock();
			// Free Memory
			free(peer);
			peer = NULL;*/

--------------

					// Should only add non-existing group (or replace an existing group) to prevent Ford Street Racing from showing a strange game session list
					/*SceNetAdhocctlScanInfo * group = findGroup(&packet->mac);

					if (group != NULL) {
					// Copy Group Name
					group->group_name = packet->group;

					// Set Group Host
					group->bssid.mac_addr = packet->mac;
					}
					else*/

-----------------

### PR DESCRIPTION
**Pull request by sum2012**
Fix #7962

### CODE REVIEW

**Comment by hrydgard** [comment]
Change looks fine to me, but does it work? Any idea why the code was disabled? It must have caused someone trouble at some point....

**Comment by sum2012** [comment]
@ANR2ME Do you remember these old code ?

**Comment by lightfirst** [comment]
@hrydgard  you don't remember why disable it? 1c7152d

**Comment by unknownbrackets** [comment]
That's AdamN's commit, not @hrydgard's.  And it even says in the commits that there are a bunch of bug fixes that the author doesn't really remember / didn't keep detailed notes on.  I think this serves as an object lesson to commit more frequently.

So naturally @hrydgard does not know what it broke.  But an assertion was made that it broke things.

To be fair, most of the code in sceNet* looks [dangeresque] (https://www.youtube.com/watch?v=KA9Zy2zHoJk) to me.  I assume the important thing to people is if Monster Hunter isn't harmed by this change.

-[Unknown]

**Comment by hrydgard** [comment]
Why close? This might be OK, still. @unknownbrackets is just saying that we don't know much about this change, and it needs to be tested appropriately if we are to merge it.

**Comment by lightfirst** [comment]
For Monster Hunter enable those code fixed "back loddy but can't plays”
I mean:
2 Players(A, B) on lobby, player A left lobby then join the same lobby again but not found player B, player B also can't found player A.
only both player A and player B left lobby then join lobby they can see each other

**Comment by LunaMoo** [comment]
MH is probably the only way with active adhoc community around here, but people play many other adhoc games locally with friends/family, maybe linking a build with that change in the adhoc compatibility thread on forums would make some lurkers active to test it if AdamN doesn't remember why he commented it out.

 While at adhoc disabled code, does https://github.com/hrydgard/ppsspp/blob/1c67de0c215db0b5e0b9525fac6e199794217f1b/Core/HLE/sceNetAdhoc.cpp#L1809 and https://github.com/hrydgard/ppsspp/blob/1c67de0c215db0b5e0b9525fac6e199794217f1b/Core/HLE/sceNetAdhoc.cpp#L1967 have any sense? Looks like this code currently does nothing, possibly it was changed as a lazy way to comment it out as well:], following the comments it should check if nbio == 1. Might be the thing which is causing socket error 10035(WSAEWOULDBLOCK) in some games, not sure.

**Comment by hrydgard** [comment]
It would be great if someone who actually does use adhoc (I don't) would test through these changes with their favorite games..

**Comment by sum2012** [comment]
omg,press wrong button or wrong command in github software

**Comment by sum2012** [comment]
I redo pull request in 7968

**Comment by hrydgard** [comment]
@sum2012 OK

**Comment by ANR2ME** [comment]
Hmm.. i think those commented code was related to a possibility of some players could get lost connection when all players ready and the multiplayer game/mission started (when moving group), i don't remember which games, and also gibberish additional session name on Ford Street Racing due to left-over session name didn't get cleared.

As i remember those codes didn't have any issue with MH games (and many other games) at the time i commit it. Since what version did MH became broken? and was there any adhoc changes at that time?

**Comment by lightfirst** [comment]
@LunaMoo 
Gundam VS Gundam Next Plus get  socket error 10035 #7444  Do you have any idea about that?

**Comment by LunaMoo** [comment]
@lightfirst nope, also I now see I was wrong about it being disabled, I'm just blind. What I didn't saw yesterday that it sets nbio only once and checks it twice both for 0, so it does have sense and just ensures that the portion of the code between the two checks is set to nonblocking.

 10035 could be caused by setting nonblocking flag for what should be set to blocking, but it might as well be broken somewhere else where it should have an opposite code and ensure something that has to, is set to blocking.

**Comment by lightfirst** [comment]
@LunaMoo I try disable other code, I am not sure it's rignt or not, but it help Gundam VS Gundam Next Plus 
http://forums.ppsspp.org/attachment.php?aid=14459

http://forums.ppsspp.org/attachment.php?aid=14460

**Comment by LunaMoo** [comment]
Cool, just saw that a minute ago in the forums, what code did you changed?

**Pull request closed without merging**
