### PR TITLE
Implement vertex range culling

### LINKED ISSUE #5001: DTM Race Driver 3; Toca 2 Graphic Problems
in DTM Race Driver 3 and Toca 2 there are massive Graphic Problems ingame

(some kind of scan lines over the game-graphics)

### LINKED ISSUE #8251: Brave Story a black triangle
Also happen in 0.9.9.1-54-gdfbb0bd and 0.9.6

Ge debugger

other tabs

### LINKED ISSUE #10928: Project Diva Extend - Graphical issue
What happens?
In song *Hello Planet there's a scene near the 2 minute mark where Miku cries and the camera focuses on the ground and there's supposed to be teardrops on the floor but there's nothing!
screenshot_2018-04-17-08-30-16-740_org ppsspp ppsspp

What *should* happen?
Watch this video from an actual PSP (it's not mine). Skip to ~2:00. You can see the teardrops.
https://m.youtube.com/watch?v=F1RDRohjGxA

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 7.0
Snapdragon 821
Vulkan and OpenGL tested.
Block transfer on or off makes no difference either.

### LINKED ISSUE #11260: Dissidia 012: Bad camera transitions during cutscenes
Recording showing the problem:  
https://my.mixtape.moe/ukrpbu.flv

What it should look like:  
https://www.youtube.com/watch?v=vm04EHjKEao&feature=youtu.be&t=229

Confirmed reproducible at native resolution with default ini. Tested with OpenGL and Vulkan backends; Vulkan appears to trigger the issue in more scenes than OpenGL.

OS: Linux/ArchLinux x86-64
GPU: Radeon RX 480
GPU Driver: Mesa radeonsi/radv [5ba3e5c](https://cgit.freedesktop.org/mesa/mesa/commit/?id=5ba3e5c3588abd6db0b737b53f3aeb4093136094)

### PR DESCRIPTION
**Pull request by unknownbrackets**
Based on tests, skips triangles with any point outside the 4096x4096 box, except when depth clamping would engage.  Does not actually implement depth clamp, just implements the culling rules related to it.

Alternative to (and heavily inspired by) #9527 and currently GLES only seeking feedback and tests in more games.  This at least fixes the Brave Story triangle (#8251) so far, but I don't have all the affected racing games to confirm.

If this seems right, can port it to the other backends for merge.

Fixes #9527, fixes #8251, fixes #5001, fixes #10928, fixes #11260, may help #2159, #5507, #7026, and #7294.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
I guess we could maybe use this on some devices?
https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_clip_cull_distance.txt

Also wonder if I should add a hidden ini-only setting in case this causes issues or performance problems...

-[Unknown]

**Comment by hrydgard** [comment]
Tagged this for 1.8.0, depending on how it goes might bump to 1.7.0.

**Comment by marosis** [comment]
@hrydgard😥

**Comment by hrydgard** [comment]
What? It's not finished. No need for the sadface.

**Comment by unknownbrackets** [comment]
I tried setting `gl_ClipDistance[0]` to a very negative number, and `glEnable(GL_CLIP_DISTANCE0);`, but doesn't clip anything.  Not sure what I'm missing... no errors.

Well, maybe we stick with the w approach.  Anyway, I went ahead and ported this to the other backends.

-[Unknown]

**Comment by hrydgard** [comment]
Looking very good so far, though I don't have all the affected games either. Unlike my old change it doesn't break Wipeout subtly in the corners. 

It doesn't seem to have any bad effect that I can see, but I haven't tested on many devices yet. If there are issues, as mentioned we can just whitelist it per game...

**Comment by unknownbrackets** [comment]
Vulkan depth clamp is interacting poorly with this on #11260 - of the two examples, one isn't fixed still, and it's only not fixed when Vulkan's depthClampEnable is true.  On all other backends, it's fixed by this pull.

I'm not sure why - presumably depth clamping happens right before depth testing, after the vertex shader?  I didn't find any obvious definition of this for Vulkan.  In that case, it would imply depth clamping is sometimes breaking the `w = NAN` thing.

-[Unknown]

**Comment by unknownbrackets** [comment]
Added a depth clamping improvement, see #11399 for more details (there's still a less common scenario that is wrong.)  Now #11260 is fixed.

-[Unknown]

**Comment by hrydgard** [comment]
Thanks. I'll run through a whole bunch of games soon and then probably merge. Seems safe enough nw (and easy enough to disable in case of problems).

The Vulkan clamping behavior is a bit unfortunate, yeah..

**Comment by marosis** [comment]
I will testing

**Comment by marosis** [comment]
Btw please can you answer me why are android builds minimaly? I see only for Windows platform on PPSSPP builds website

**Comment by Emulatorer** [comment]
screenshot_2018-09-19-12-57-04
Hellboy The Science Of Evil
screenshot_2018-09-19-12-56-32
YuGiOh Arc V tag force special

**Comment by Emulatorer** [comment]
screenshot_2018-09-19-12-55-54

screenshot_2018-09-19-12-56-21
Tekke  6

**Comment by Emulatorer** [comment]
Phone Specs:
Mali-450 MP
Octacore
2GB ram
PPSSPP use Build 1.6 3-483g1f881d790

**Comment by unknownbrackets** [comment]
Maybe we ran out of vertex shader registers... ugh.  Might have to blacklist cullrange on Mali-4xx.

-[Unknown]

**Comment by marosis** [comment]
Ohhhh. Aaaaaand problems are starting😂😂😂

**Comment by unknownbrackets** [comment]
Maybe we could use `gl_extensions.gpuVendor == GPU_VENDOR_ARM && strstr(gl_extensions.model, "Mali-4") && !gl_extensions.VersionGEThan(3, 0)` to set a bug flag, and blacklist on Mali 4xx, but I don't have enough devices to validate that it fixes it...

-[Unknown]

**Comment by unknownbrackets** [comment]
Or maybe those games are using large viewports, should try after #11407.

-[Unknown]

**Comment by unknownbrackets** [comment]
Hmm, I wonder if we should try running a glsl->spirv->opt->glsl pass on the shaders...

-[Unknown]

**Comment by hrydgard** [comment]
Hm. They have so little confidence in the driver optimizer that they hide it behind an option? 

But yeah, that would be interesting to try.

**Comment by Emulatorer** [comment]
PPSSPP Build v1.6.3-492-g9fddfff66 didn't fixed the issue :(

**Comment by marosis** [comment]
DTM race driver-still same issue
screenshot_20180921-191444

**Pull request merged**
