### PR TITLE
Update zh_CN.ini

### PR DESCRIPTION
**Pull request by leoxxx**

### CODE REVIEW

**Comment by leoxxx** [comment]
I feel confused.“Logging Channels = 日志通道”,”Logging Channels = 记录通道“ or “Logging Channels = 日志记录通道”, which one is the best?
Now I use the “Logging Channels = 日志通道”.

**Comment by unknownbrackets** [comment]
Logging channels means, in other words, categories to include in the log output.  For example, you could enable audio-related logging, or filesystem-related logging.  It's to choose which categories you want enabled or disabled, and at what level (only errors, include warnings, etc.)

-[Unknown]

**Comment by leoxxx** [comment]
> Logging channels means, in other words, categories to include in the log output. For example, you could enable audio-related logging, or filesystem-related logging. It's to choose which categories you want enabled or disabled, and at what level (only errors, include warnings, etc.)
> 
> -[Unknown]

So,"channel"="categories",is it right?  I confuse the "logging" should be translated which one.

**Comment by unknownbrackets** [comment]
Basically, yes.  Also similar to a "TV channel" or "radio channel".  It's that kind of channel in English.  But category is basically the same in this context.

-[Unknown]

**Comment by leoxxx** [comment]
> Basically, yes. Also similar to a "TV channel" or "radio channel". It's that kind of channel in English. But category is basically the same in this context.
> 
> -[Unknown]

The logging means: record or save a log, is it right?
what about "记录日志分类" ?

**Comment by unknownbrackets** [comment]
Yeah, to choose what will be saved in the log.

-[Unknown]

**Review by leoxxx — COMMENTED** [review]
Logging Channels = 记录日志分类

**Comment by leoxxx** [comment]
I pull a new commit. https://github.com/hrydgard/ppsspp/pull/16541/commits/095e234999a141dda9dc7c6c27d6539c32ae9e54

**Pull request merged**
