### PR TITLE
Combo key

### PR DESCRIPTION
**Pull request by xiushudongfang**
With Combo keys, you can map multiple keys to one touch button.   when you press the touch button, equivalent to press multiple keys, it has reached the purpose of simplifying the operation.
screenshot_2015-10-14-18-53-46
screenshot_2015-10-14-18-53-57
screenshot_2015-10-14-18-54-12
screenshot_2015-10-14-18-55-57

### CODE REVIEW

**Comment by hrydgard** [comment]
The concept is really good. Not sure about the symbols on the new buttons though, but I'll think about what would look nice :)

I haven't looked at the code in detail yet, but it needs a rebase and some styling cleanup. I can do that for you but not right now, maybe later this week.

**Comment by unknownbrackets** [comment]
Is there enough need for quick button combinations to warrant 5 extra buttons?  I can think of L/R mainly, and sometimes L or R plus one other button.

Personally, to reduce confusion, I would mark them (1), (2), (3), (4), etc.  Some gamers might be confused by e.g. A/B being present, or by upside-down triangle buttons.  I think numbers are the best way to represent they are custom (or potentially a slightly different button style.)

-[Unknown]

**Comment by xiushudongfang** [comment]
@hrydgard Thanks .

**Comment by xiushudongfang** [comment]
@unknownbrackets Yeah,you are right .It is not necessary,but someone tell me PspKvm may need these keys.I think it is not difficult to  meet this need,so I add all buttons.
qq 20151015150031

**Comment by hrydgard** [comment]
If we just use numbers, we can simply have 1-6 for example without confusing users too much, I think.

**Comment by xiushudongfang** [comment]
How about this?
qq 20151015155817
qq 20151015155833
qq 20151015155906

**Comment by hrydgard** [comment]
The "5" looks a bit thin/dark. Maybe you can use a slightly bolder font for the five numbers? "Roboto" which we use for the rest of the UI?

**Comment by xiushudongfang** [comment]
@hrydgard  It is .png,not font.I do it by Phone Shop .

**Comment by hrydgard** [comment]
OK. I will replace the number pngs when I merge later.

**Comment by hrydgard** [comment]
Merged this as #8096, so closing this one.

**Pull request closed without merging**
