### PR TITLE
Android: Update deps; Cannot reproduce #11420

### PR DESCRIPTION
**Pull request by Florin9doi**
Cannot reproduce #11420
The only problem is that the build process took way too much time.
Is it really required to build every file for 4 architectures multiplied with 2 flavors multiplied with 3 buildTypes ?

### CODE REVIEW

**Comment by hrydgard** [comment]
I'm gonna try it with these changes later and see if it still repros for me, maybe also updating the build tools helps.

Yeah well, if you find a way to get the configurations down, let me know. But if you plug in a device and press Run, it will only build a single configuration (first time it will run all the 24 "configures" though).

**Comment by Florin9doi** [comment]
Updating build tools is also required: https://developer.android.com/studio/releases/gradle-plugin#3-2-0

**Comment by hrydgard** [comment]
Don't know what I'm doing wrong but with this branch I'm getting the same thing that I saw before, which is that the output is the following:


> Configure project :android
    Overriding Android Version Name, Code: 1.6.3-501-Florin9doi-ANDROID_DEPS 16030501
    C:\dev\ppsspp\assets

    CONFIGURE SUCCESSFUL in 1s

And then it just says Gradle Sync Failed.

All I see in idea.log is:

    2018-09-29 00:23:28,743 [d thread 1]   INFO - e.project.sync.GradleSyncState - Gradle sync failed (2 s 434 ms)

**Comment by hrydgard** [comment]
I did upgrade Android Studio to 3.2, maybe related...

**Comment by unknownbrackets** [comment]
Working here.  Android Studio 3.2, ndk r18, had to update sdk for 28.0.3.  Appears successful.

-[Unknown]

**Comment by hrydgard** [comment]
Alright. I'm just gonna merge this and troubleshoot my environment then...

**Pull request merged**
