### PR TITLE
GPU: Account for w properly in lines, fixing width

### LINKED ISSUE #15756: Tekken 6 Bonus Stage Nancy laser beam is invisible (lines)
### Game or games this happens in

ULES01376

### What area of the game

ppsspp v1.13.1 Nancy laser beam is invisible.
Screenshot_2022-07-30-09-02-59-333_org ppsspp ppsspp

ppsspp v1.12.3 Nancy laser beam is visible
Screenshot_2022-07-30-09-03-23-299_org ppsspp ppssppgold

### What happens

Nancy laser beam is invisible.

### What should happen

Nancy laser beam should be visible.

### GE frame capture

[ULES01376.ppdmp.zip](https://github.com/hrydgard/ppsspp/files/9226171/ULES01376.ppdmp.zip)

### Platform

Android

### Mobile phone model or graphics card

Redmi Note 9 Android 12 Helio G85 Mali-G52 GPU

### PPSSPP version affected

v1.13.1

### Last working version

v1.12.3

### Graphics backend (3D API)

Vulkan/OpenGL

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try changing graphics settings to determine if one causes the glitch (especially speed hacks or enhancements/replacements.)
- [X] Include logs or screenshots of issue.

### PR DESCRIPTION
**Pull request by unknownbrackets**
See #15756.  It seems so obvious now, I was obviously mainly thinking about throughmode/2D before, and Persona/etc. working lulled me...

Fixes #15756 (rRootage too.)  Might be worth checking lines in Test Drive Unlimited's maps (though I'm not sure they aren't just thin on a PSP...)

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Let's merge and check after :) This should be correct.

**Comment by unknownbrackets** [comment]
Still needs a green checkmark.

-[Unknown]

**Review by hrydgard — APPROVED** [review]
Eh, right :)

**Comment by hrydgard** [comment]
Wish that auto-merge + approved could be done in one step.

**Pull request merged**
