### PR TITLE
Remove duplicates from ThreadManForKernel

### PR DESCRIPTION
**Pull request by Florin9doi**

### CODE REVIEW

**Comment by sum2012** [comment]
The game I test maybe give 2 difficult of upper case and lower of 0X28B6489C ?

**Comment by sum2012** [comment]
The log is from
https://github.com/hrydgard/ppsspp/issues/13205
18:22:889 hle\scekernelmodule.cpp:751 W[LOADER]: Unknown syscall in known module 'ThreadManForKernel': 0x28b6489c

**Comment by sum2012** [comment]
I will test again when new build produce

**Comment by Florin9doi** [comment]
#13205 was closed by #13217

**Comment by hrydgard** [comment]
hex numbers don't have upper and lower case, only their representation in c++ source code :P  still the same number.

**Comment by sum2012** [comment]
I test again that game.No more that log now.

**Pull request merged**
