### PR TITLE
Add dpiawareness to manifest

### PR DESCRIPTION
**Pull request by Bigpet**
instead of doing it at runtime, still works in WinXP according to @StepS- in the IRC,
should probably be tested there to be sure

Also don't include 2 manifest files
So we apparently included 2 manifest files.
One from the *.rc file and one generated by the IDEs manifest tools
- added the contents of rt_manif.bin to PPSSPP.manifest
- made ppsspp.rc include PPSSPP.manifest
- set the *.vcxproj to not generate an additional manifest

### CODE REVIEW

**Comment by Bigpet** [comment]
Btw. we currently include 2 manifest files, even without these dpiaware changes

We can decide to either just include it in the *.rc file or just add a *.manifest files and enable the "EmbedManifest" option

I just did the first one but if the second one is preferable I can change it to that

**Comment by hrydgard** [comment]
This seems fine, thanks.

**Comment by thedax** [comment]
Did you test with NVidia users to make sure their TVs and stuff aren't flickering still? I'm pretty sure I tried this back before I first added that code and the manifest trick did not work.

**Comment by Bigpet** [comment]
Wasn't that just with fullscreen?

I have an Nvidia card on a SamsungTV and I haven't had any issue. It may have been an issue with having 2 manifests, how did you add it, in the VS options, a seperate manifest or in the r_manif.bin?

**Comment by thedax** [comment]
As I recall, I messed with it only through VS options, and it had no effect. Yeah, it was only fullscreen that was affected; I'll try it out on my TV soon-ish since I was one of the affected people.

**Comment by Bigpet** [comment]
The reason why I didn't set it through the options is twofold, for one I now disabled VS generating a manifest (since it was generating a second one). The other reason is that the option "true/pm" is not selectable through the Visual Studio GUI.

If you just changed that btw. then it would not have ended up in the main manifest, but in the weird second one.

**Comment by huahuutoan** [comment]
Rat vui

**Pull request merged**
