### PR TITLE
Implement CW cheat refresh rate.

### PR DESCRIPTION
**Pull request by LunaMoo**
See #7375
refresh rate

### CODE REVIEW

**Comment by sum2012** [comment]
I think that need independent setting of each cheat

**Comment by AizerMortenort** [comment]
Where is the updated version?

**Comment by Bigpet** [comment]
@AizerMortenort this is an open pull request. It has not been merged. If you want this version you need to checkout https://github.com/LunaMoo/ppsspp/tree/CWcheatStuff yourself and compile it or wait.

**Comment by AizerMortenort** [comment]
is 77 the default one?

**Comment by hrydgard** [comment]
It's quite a weird feature but apparently standard in cheat engines for the PSP, so alright.

**Comment by LunaMoo** [comment]
@AizerMortenort yes 77ms is currently used value. If you can't build it on your own, here: https://www.mediafire.com/?3a5bdsv2g33vsqm
 Check if setting it very low helps with your cheat that requires it, it can go as low as 1ms, althrough I'm not sure if long cheat list would be executed in that time which might(?) be limiting real lowest frequency.

 As for making it for each cheat, feels to complex for what it's worth, don't even know if it would work without rewriting the whole thing.

**Comment by LunaMoo** [comment]
Hmm anyone have an idea how to fix saving for per-game settings without breaking android? I don't really get why it broke;p, was it random like sometimes with symbian?.

**Comment by AizerMortenort** [comment]
I must praise your work Lona Moo!
The code does work now and doesn't cause any freeze!
The camera doesn't move itself! 
Great Work my friend.

Henrik , please implement this in the next releases of the emulator.
This is a good addition.
Thank you both. 

Expect a donation soon. :)

**Pull request merged**
