### PR TITLE
yugioh save fix tool

### PR DESCRIPTION
**Pull request by sum2012**
#7914 
It is impossible to maintain this tool by myself forever.
Use this tool can recover game save by themselves.
The cause of bad save (cannot save) are load "save status" and use cwcheat,
but the real cause still unknown.

### CODE REVIEW

**Comment by hrydgard** [comment]
Does this hurt anything for new saves for this game? If not, and this is needed to rescue old saves or something, I would be fine with turning this into a compat setting (so it's only enabled for this game ID, and eliminates the need to add yet another INI option)

**Comment by sum2012** [comment]
This is not  hurt anything for new saves for this game.
This is apply to yugioh series game.
Yu-Gi-Oh_GX 1-5 jpn,us,eur
Yu-Gi-Oh_ARC-V_Tag_Force_Special
I need to find out these game id after I back home .

**Comment by Emulatorer** [comment]
Since Im a big fan of this Duel Trading Card Games I find the game ID using cheat.db :)

@Sum2012 This is the game ID of all Yu-Gi-Oh! in PSP or did I miss some of theme?

_S ULJM-05151
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force [JP]
_S ULES-00600
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force [EU]
_S ULUS-10136
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force [US]
_S ULUS-10302
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force 2 [US]
_S ULJM-05260
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force 2 [JP]
_S ULES-00925
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force 2 [EU]
_S ULES-00926
_G Yu-Gi-Oh! GX Tag Force 2 [EU]
_S ULJM-05373
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force 3 [JP]
_S ULES-01183
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force 3 [EU]
_S ULUS-10481
_G Yu-Gi-Oh! 5D's Tag Force 4 [US]
_S ULJM-05479
_G Yu-Gi-Oh! 5D's Tag Force 4 [JP]
_S ULES-01362
_G Yu-Gi-Oh! 5D's Tag Force 4 [EU]
_S ULUS-10555
_G Yu-Gi-Oh! 5D's Tag Force 5 [US]
_S ULJM-05734
_G Yu-Gi-Oh! 5D's Tag Force 5 [JP]
_S ULJM-05940
_G Yu-Gi-Oh! 5D's Tag Force 6 [JP]

**Comment by Emulatorer** [comment]
Since Im a big fan of this Duel Trading Card Games I find the game ID using cheat.db :)

@Sum2012 This is the game ID of all Yu-Gi-Oh! in PSP or did I miss some of theme?

_S ULJM-05151
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force [JP]
_S ULES-00600
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force [EU]
_S ULUS-10136
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force [US]
_S ULUS-10302
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force 2 [US]
_S ULJM-05260
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force 2 [JP]
_S ULES-00925
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force 2 [EU]
_S ULES-00926
_G Yu-Gi-Oh! GX Tag Force 2 [EU]
_S ULJM-05373
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force 3 [JP]
_S ULES-01183
_G Yu-Gi-Oh! Duel Monsters GX: Tag Force 3 [EU]
_S ULUS-10481
_G Yu-Gi-Oh! 5D's Tag Force 4 [US]
_S ULJM-05479
_G Yu-Gi-Oh! 5D's Tag Force 4 [JP]
_S ULES-01362
_G Yu-Gi-Oh! 5D's Tag Force 4 [EU]
_S ULUS-10555
_G Yu-Gi-Oh! 5D's Tag Force 5 [US]
_S ULJM-05734
_G Yu-Gi-Oh! 5D's Tag Force 5 [JP]
_S ULJM-05940
_G Yu-Gi-Oh! 5D's Tag Force [JP]
_S NPJH-00142
_G Yu-Gi-Oh! ARC-V Tag Force Special [JP]

**Comment by sum2012** [comment]
@Emulatorer A big thanks.
@hrydgard Done

**Comment by hrydgard** [comment]
Before I merge, I would just like to clarify - is it old saves (from old PPSSPP versions) or PSP saves (from a real PSP) that PPSSPP fails to open without this?

**Comment by sum2012** [comment]
No,it only affect abuse "save status" and "load status".
Normal open without this is okay.

**Comment by hrydgard** [comment]
Ah right, okay. Well, that's annoying enough... especially since it works okay with most other games so people get used to mixing save states and real saves.

**Comment by unknownbrackets** [comment]
Well, I think this is probably a bug in the networking dialog code or something?

-[Unknown]

**Pull request merged**
