### PR TITLE
Link fail on case sensitive filesystem SDL2_ttf

### PR DESCRIPTION
**Pull request by noabody**
Case sensitive identifier for package is `SDL2_ttf` not `SDL2_TTF`.  Will cause linker failure on all case sensitive filesystems that use the standard case as defined in sources.

### CODE REVIEW

**Comment by noabody** [comment]
I'm reading that MACOSX target is case insensitive which is not really relevant.  The standard naming is `SDL2_ttf` which will only affect case sensitive filesystems.

**Comment by hch12907** [comment]
This is weird... I am using Linux (case-sensitive) and SDL2_TTF works fine here. But changing it to SDL2_ttf doesn't seem to hurt either.

**Review by unknownbrackets — APPROVED** [review]

**Comment by unknownbrackets** [comment]
If it doesn't hurt and it helps someone, seems reasonable to merge.

-[Unknown]

**Comment by unknownbrackets** [comment]
Thanks for the fix.

-[Unknown]

**Pull request merged**
