### PR TITLE
UI: Consistently set bgaudio on game start

### LINKED ISSUE #8944: Games intro music is played on the pause screen
I don't know if this is a feature or a bug but:

1.Right click on a game that have music in the game info screen
2.Click on the Play button
3.Press Esc to go to the Pause screen
The game intro music will continue playing from the position you stop it when you click on the play button

If you directly start the game(without entering the game info screen),then going to the pause screen will not play the music

And there is something else too(not related to this but I don't know if it wort making another issue)

In the Display Layout Editor the text in the middle is divided like this
S
tr
et
in
g

### LINKED ISSUE #8953: Strange increase in the cpu usage
When I just start ppsspp,my cpu core usage is barely moving above 2% and the cores speed is 800Mhz(meaning idle)
If I go to "Controls Mapping" the cpu usage goes up and the cores speed is increased twice(1.6Ghz)
And if I go there while a game is running,it will increase the cpu usage even more and it will make the cpu to go in turbo mode which is 3.7-3.9Ghz

i7 4771

### PR DESCRIPTION
**Pull request by unknownbrackets**
Before we were doing it only in certain cases.  This now means that background audio will always play on the pause screen.

The alternative would be never playing it on the pause screen.  I'm not really sure which is best, so figured we might as well play music.

Fixes #8944, fixes #8953.

-[Unknown]

### CODE REVIEW

**Comment by vsub** [comment]
High volume background music is not really nice while you are taking your time configuring per the settings or looking through the cheats.

I prefer the music to only run in the game info screen and not in the pause screen.
On some games the music sounds weird for 1-2 seconds when you pause the game.

**Comment by unknownbrackets** [comment]
I've added some performance improvements to text wrapping - a huge chunk was `SplitString`, unexpectedly.  The stringstream implementation was quite slow.

Hm.  Well, I'm okay with making it only play music on the main screen (when selecting via keyboard/controller) and info screen.  Anyone else have opinions?

-[Unknown]

**Comment by unknownbrackets** [comment]
By the way, I can imagine it making sense to lower the volume on secondary pages (like pause or settings) or on repeats of the audio, alternatively.  For example, if I'm browsing with my controller, and linger on an item, maybe when the music repeats it could fade down to 50%.

Not sure if that makes sense, I'm not really an audio person.

-[Unknown]

**Comment by vsub** [comment]
Lowering the volume is good but some songs are just annoying(10 seconds cut repeating from the beginning over and over)

**Comment by hrydgard** [comment]
I agree with only playing music on the main menu and info screen, that's the most consistent with how the real PSP behaves, if I remember correctly...

**Comment by unknownbrackets** [comment]
Okay, done.

-[Unknown]

**Comment by hrydgard** [comment]
Thanks!

**Pull request merged**
