### PR TITLE
SDL: really try lower GL profiles & add GLES context support

### PR DESCRIPTION
**Pull request by psyke83**
* When compiled with USING_GLES2, attempt to use only valid ES context
  versions.
* Ensure that lower profiles are attempted correctly rather than
  prematurely returning from the function after the first failure.

Needed for Raspberry Pi to successfully launch.

### CODE REVIEW

**Comment by psyke83** [comment]
I tried leaving the attemptVersions array untouched - ppsspp would launch successfully, but the emulated content would not actually boot, staying on a black screen, but the menu works when pressing ESC.

The Pi should only support ES 2.0 at maximum, and I suppose it makes sense not to try higher versions when building against USING_GLES2...

**Comment by unknownbrackets** [comment]
Hmm, `USING_GLES2` actually means GLES 2.0+ for us.  Does this happen even if it has `{3, 2}, {3, 1}, {3, 0}, {2, 0}` in it?

Perhaps we should just let it autodetect as before for ES contexts, and put the entire core section in an `#ifndef USING_GLES2`...

-[Unknown]

**Comment by psyke83** [comment]
Ok, I tried changing the array to ```{3, 2}, {3, 1}, {3, 0}, {2, 0},``` and the content still does play correctly. I'll try to ifndef the whole part next, will let you know in just a few minutes.

**Comment by psyke83** [comment]
OK, I tried the following tests separately:
1: Isolating the whole ```for (size_t i = 0; i < ARRAY_SIZE(attemptVersions); ++i) {``` loop with an ```#ifndef USING_GLES2``` so that it would only attempt the fallback context creation.
2: From this PR, instead of this:
```
#ifdef USING_GLES2
                SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
                SetGLCoreContext(false);
#else
                SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
                SetGLCoreContext(true);
#endif
```
Change to this:
```
#ifndef USING_GLES2
                SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
                SetGLCoreContext(true);
#endif
```

3: Isolating this part only:
```
#ifndef USING_GLES2
                // Make sure to request a somewhat modern GL context at least - the
                // latest supported by MacOS X (really, really sad...)
                SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, ver.major);
                SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, ver.minor);
                SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
                SetGLCoreContext(true);
#endif
```

1 & 2 failed, but 3 works. Would you like me to update the PR to match #3, or should I just update the array to check the latest ES version?

**Comment by psyke83** [comment]
I won't be available to test for a few hours, so I've updated the PR to include the higher ES profile levels and amended the commit message.

I wasn't completely clear on what you meant re the "entire core section", but this change (no. 3 that I was alluding to) also works:
```
diff --git a/ext/native/base/PCMain.cpp b/ext/native/base/PCMain.cpp
index 128e045d4..f6713ed96 100644
--- a/ext/native/base/PCMain.cpp
+++ b/ext/native/base/PCMain.cpp
@@ -596,19 +596,19 @@ int main(int argc, char *argv[]) {
 	SDL_GLContext glContext = nullptr;
 	for (size_t i = 0; i < ARRAY_SIZE(attemptVersions); ++i) {
 		const auto &ver = attemptVersions[i];
+#ifndef USING_GLES2
 		// Make sure to request a somewhat modern GL context at least - the
 		// latest supported by MacOS X (really, really sad...)
 		SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE);
 		SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, ver.major);
 		SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, ver.minor);
 		SetGLCoreContext(true);
+#endif
 
 		g_Screen = SDL_CreateWindow(app_name_nice.c_str(), x,y, pixel_xres, pixel_yres, mode);
 		if (g_Screen == nullptr) {
-			NativeShutdown();
 			fprintf(stderr, "SDL_CreateWindow failed: %s\n", SDL_GetError());
-			SDL_Quit();
-			return 2;
+			continue;
 		}
 
 		glContext = SDL_GL_CreateContext(g_Screen);
```

It's simpler than adding the GLES context support, but if context creation fails for any reason, it will retry the exact same process 11 times unnecessarily.

**Comment by hrydgard** [comment]
Oops, you're gonna need to rebase this - I moved PCMain.cpp to the SDL subdirectory and renamed it SDLMain.cpp.

git should take care of the rename and reapplying your changes automatically though.

**Review by unknownbrackets — APPROVED** [review]
This approach looks good to me.

-[Unknown]

**Comment by psyke83** [comment]
Rebased the commit & retested a build against latest master - still working OK. Thanks.

**Comment by hrydgard** [comment]
Seems fine for now. Ideally at some point later we'll transition to not using #ifdef for the GL/GLES distinction.

**Pull request merged**
