### PR TITLE
Turn off TextureSecondaryCache while psmf video is playing

### PR DESCRIPTION
**Pull request by sum2012**
Fix opening video not show up in #6903

### CODE REVIEW

**Comment by hrydgard** [comment]
Good find. However I don't think this should be a config setting, as it's set by the program itself. Also, I think there may be a better way to fix this, will look into it.

**Comment by unknownbrackets** [comment]
If I'm reading this right, this prevents deleting from the secondary cache while a video is playing: that is, it actually uses the secondary cache MORE while a video is playing?

-[Unknown]

**Comment by hrydgard** [comment]
Doesn't make much sense indeed, but since this apparently works, there has to be some strange interaction. Maybe an empty frame is kept longer than it should?

**Comment by sum2012** [comment]
Yes,the strange that directx 9 can see the video without this change

**Comment by sum2012** [comment]
Now no need this,closing

**Pull request closed without merging**
