### PR TITLE
Merge lang submodule into the main git repo

### LINKED ISSUE #14612: Merge assets/lang back into the main repo?
The volume of commits to assets/lang is very small these days, it no longer makes much sense to keep them separate. If there are no objections, I'll merge it next week.

### PR DESCRIPTION
**Pull request by hrydgard**
Simple PR that just replaces the submodule with the files directly. There's no longer any real reason to keep the translations separate.

Fixes #14612

### CODE REVIEW

**Comment by unknownbrackets** [comment]
I'd recommend marking the lang repo as archived afterward.

-[Unknown]

**Comment by hrydgard** [comment]
Will do after verifying that the buildbot is still happy.

**Comment by W-MS** [comment]
ae8e3468863833b53b0988ae039da8d
lang settings no longer available

**Comment by Gamemulatorer** [comment]
> ae8e3468863833b53b0988ae039da8d
> lang settings no longer available
Are you using the latest development version of PPSSPP from buildbot?
Screenshot_2021-07-20-11-23-43-453_org ppsspp ppsspp

**Comment by W-MS** [comment]
I'm currently maintaining the iOS buildbot. For this build, it did removed all the working folder and git clone recursive again. So I can make sure it's all the latest.

**Pull request merged**
