### PR TITLE
Improve atrac parsing and differentiate streaming from data

### LINKED ISSUE #7282: Prince of Persia The Forgotten Sands JPN lockup problem
Since https://github.com/unknownbrackets/ppsspp/commit/0aa7247feaaec564a4233ff502189a97a229d731

Just lockup with Janpanese sound ,English sound is fine in the beginning scene.

### LINKED ISSUE #8093: Ys Seven music suddenly stops!
Using the latest dev version on Android, the background music in the game YS Seven suddenly stops after playing a few minutes and you can just hear the sound effects and they all have a weird echo.  I am using the default settings with skip buffer effects option enabled.

### PR DESCRIPTION
**Pull request by unknownbrackets**
Need to create more and better tests, but I've run through a bunch of data and then verified against some games, and this is working.

Much of this is based on the values that are stored in the sceAtrac context buffers.  I'm trying to more or less match them.  It seems they CAN be modified by games as well, so it might be ideal to actually store and maintain state there only...

Anyway, this does a few things:
1. Populates the context data a bit more correctly.
2. Determines streaming vs. non-streaming, which allows "infinite looping" via adding data, as games expect in streaming mode.
3. Doesn't pad failed packets when we're at file end.
4. Calculates sample end more correctly when there's no fact chunk.
5. Buffers first few frames from 0 when seeking, to warm up ffmpeg with data for the decoder.
6. Attempts to get the remaining frame value more correct.  It's still off though, but was off before.
7. Parses fact/smpl chunks more correctly and handles riff size more like firmware.

Still a lot more to do to get it correct.  Gotta start figuring out exactly how looping cuts between samples and in what way the second buffer is used - I'm suspecting that it's used to handle a decode that would need some data from near the end and some near the start?

Also, should fix #8093.  Fixes #7282.

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
Fixes https://github.com/hrydgard/ppsspp/issues/7282

**Comment by sum2012** [comment]
Code Lyoko still stuck in "no problem" screen
modify log:
https://gist.github.com/sum2012/9e9ae0bae0a1059aa8a4

**Comment by sum2012** [comment]
fyi, some atrac infomation find from jpcsp
https://github.com/jpcsp/jpcsp/commit/b27d47ef364a8baf34677893fffe2a6268fbeedf#diff-6da48760382b8f38f381417b75f7dcbcR428

**Comment by sum2012** [comment]
and this https://github.com/jpcsp/jpcsp/commit/b48ff1a1ec4bed64ab84c284188b8932746e90f0

**Comment by unknownbrackets** [comment]
Some of those changes look like they are already in PPSSPP.  Anyway, I plan to build tests to make sure things work rather than try to port over the code from JPCSP.

-[Unknown]

**Comment by hrydgard** [comment]
Tried a bunch of games, seems fine. #6663 still remains.

**Pull request merged**
