### PR TITLE
Update the README for 1.2.0

### PR DESCRIPTION
**Pull request by hrydgard**
I'm sure I missed something as usual, please comment :)

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Some others, not sure if they really need to be in though: #8096, #8225, #8330

I'm a bit short on time right now, here are some other that are maybe:
#8219, #8216, #8178, #8130, #8117, #8043, #8019, #8285, #8284, #8296, #8286, #8308, #8316, #8314, #8451

-[Unknown]

**Comment by sum2012** [comment]
Yes,missing "Combo Key"

**Comment by sum2012** [comment]
Fix video sound which has mono audio

**Comment by daniel229** [comment]
Support Eiyuu Densetsu: Sora no Kiseki Kai HD Remasters.https://github.com/hrydgard/ppsspp/pull/8314

**Comment by sum2012** [comment]
Support adhoc port offset

**Comment by vnctdj** [comment]
@hrydgard What about shrinking the file a bit ? I'm not sure we should keep all these very old versions...

**Comment by sum2012** [comment]
Yes,should move to history.txt

**Pull request merged**
