### PR TITLE
Scoped storage translation

### PR DESCRIPTION
**Pull request by iota97**
Add the keys in en_US for reference, fix ja_JP from #14706 and make progress string translatable

### CODE REVIEW

**Comment by nassau-tk** [comment]
Is it means that if merged this PR then translate Japanese automatically?

**Comment by hrydgard** [comment]
I think it's slightly early to translate these maybe? I expect to polish this stuff up a bit more, which might include changing the text and order of it quite a bit..

**Comment by iota97** [comment]
I agree is too early, but since nassau-tk translated some already I see value in having them in (mostly because I think is better to make as clear as possible what can happen to your data). 

Maybe should just not update the en_US one for now tho'.

**Comment by hrydgard** [comment]
Yeah, fair enough.

**Comment by nassau-tk** [comment]
When Japanese translation wasn't indicated, Japanese would feel weak at the knees in fear.
lmao
It means...
The Japanese who don't try to understand English. I think they give up operating.

**Comment by hrydgard** [comment]
Let's get it in, but be ready that there might be some changes to these.

**Comment by nassau-tk** [comment]
Of course sir.
Then I will try translate quicklly.

**Comment by nassau-tk** [comment]
OKey.
Translate is working.
But, A part is over character.(2 characters.)
Probably, 99.9% Japanaese can understanding it.
We'll assume that it's OK for now.

**Comment by hrydgard** [comment]
Oh, hehe. I'll leave as much space as possible, maybe make the text shrink or wrap if it's not enough space. Gotta be ready for long translatations here I think ...

**Pull request merged**
