### PR TITLE
Handle breakpoints within replacements better

### PR DESCRIPTION
**Pull request by unknownbrackets**
This way you can trivially set a breakpoint on (or inside) a replaced function to see if it's being run.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
@Kingcom, I think you requested this a while ago, finally implemented.

-[Unknown]

**Comment by daniel229** [comment]
The same memmove() in star ocean (JP).

**Comment by unknownbrackets** [comment]
Interesting.  Added the US version of `memmove()` in Star Ocean, which is different.

-[Unknown]

**Comment by daniel229** [comment]
That memmove() is also in Chuumon Shiyouze! Oretachi no Sekai and many other games

**Pull request merged**
