### PR TITLE
More translation fixes

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes issues reported in #18773

### CODE REVIEW

**Comment by Saramagrean** [comment]
Duplicate. 😅

2024-01-28 23_21_42-More translation fixes by hrydgard · Pull Request #18776 · hrydgard_ppsspp

**Comment by hrydgard** [comment]
oh no, oops. fixing

**Comment by TotalCaesar659** [comment]
Thanks, please fix "Screen notch insets" too before I pull out the update.

**Comment by hrydgard** [comment]
done.

**Pull request merged**
