### PR TITLE
Cleanup display and touch control layout editors a bit more

### LINKED ISSUE #12797: Display layout editor bugs in manual scaling
When I select manual scaling in display layout editor and it happens similar to #12781 

Here's a YouTube video:
https://youtu.be/O19BgISVquM

### PR DESCRIPTION
**Pull request by unknownbrackets**
Fixes #12797 in the same way as before, not converting back and forth between center coords.  Gets rid of the local_dp_* hacks and simplifies some code.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Code looks good, not gonna check all the fiddly math though, let's try it :)

**Comment by unknownbrackets** [comment]
Well, I mostly just changed `const auto &prevParams = displayRepresentation_->GetLayoutParams()->As<AnchorLayoutParams>();` to grab the prev anchor position (rather than `bounds.center()`) to fix the drift.  I haven't dug into why a centered anchor pos deviates from the center of its bounds, but I assume it's a rounding issue.

-[Unknown]

**Comment by LunaMoo** [comment]
There's a weird thing after this merge, pressing "Center" moves the screen a bit left if it was sticking to one of the sides already. If it wasn't stuck to any side, it will center most of the time, but sometimes moves a bit in random(?) directions which can be seen even after it's centered initially.

 Also there seems to be a problem with the bottom part of the visualized border being a bit too low so the "screen" doesn't look like it's filling it when it does, but that had to be broken earlier I guess as previous build also has that.

**Comment by unknownbrackets** [comment]
The random movement was happening before these changes though.  But I realized the root of these problems (I think this cleanup is still good.)

-[Unknown]

**Pull request merged**
