### PR TITLE
Link PR and issues in README

### PR DESCRIPTION
**Pull request by iota97**
This will make them clickable for now, not sure if is worth the trouble tho'.

### CODE REVIEW

**Comment by hrydgard** [comment]
Readme becomes slightly more annoying to edit, but no big deal probably. I'll consider it.

**Comment by iota97** [comment]
If needed this script can convert the README automatically (it check for the # to not have a [ before so it won't change already changed one), if you want I can just commit it.

```
#!/bin/python

import re
f = open("README.md", "r+")
cont = f.read()
updated = re.sub(r"([^[])#(\d+)", r"\1[#\2](https://github.com/hrydgard/ppsspp/issues/\2)", cont)
f.seek(0)
f.write(updated)
f.truncate()
f.close()
```

**Comment by hrydgard** [comment]
Yeah, throw in the script, that's nice.

**Comment by hrydgard** [comment]
Though I just thought of something else, the .md is also used as the README.txt kind of equivalent, and it got a lot harder to read in raw text form with this unfortunately. Not that big of a deal though...

**Comment by Anuskuss** [comment]
Thanks for implementing this @iota97. I'm late to the party but I've also written a python script but never submitted it, but after seeing your script I would like to nit-pick a little and recommend the use `#!/usr/bin/env python` instead of `#!/bin/python`.

I'm kinda disappointed that hovering over the urls doesn't reveal that issue/pr sneak peak with the title and description (like it does when referencing in comments) since that was be very useful when skimming through the changes. Well, maybe that would be a feature request for [dear-github](https://github.com/dear-github/dear-github).

> Though I just thought of something else, the .md is also used as the README.txt kind of equivalent, and it got a lot harder to read in raw text form with this unfortunately. Not that big of a deal though...

I already thought about that and have a solution for you. This solves two problems but could be considered hacky:
- README becomes unreadable as text
- Repo changes name breaking the links
```py
#!/usr/bin/env python
import re

with open('README.md', 'r+') as f:
  md = re.sub('(?<!\[)#(\d+)', '[#\\1](/../../issues/\\1)', f.read())
  f.seek(0)
  f.write(md)
  f.truncate()
```

So this
```md
What's new in 1.10.0
--------------------
* Graphics and compatibility fixes ([#12800](https://github.com/hrydgard/ppsspp/issues/12800), [#12670](https://github.com/hrydgard/ppsspp/issues/12670), [#12635](https://github.com/hrydgard/ppsspp/issues/12635), [#12857](https://github.com/hrydgard/ppsspp/issues/12857), [#12941](https://github.com/hrydgard/ppsspp/issues/12941), [#11898](https://github.com/hrydgard/ppsspp/issues/11898), [#12695](https://github.com/hrydgard/ppsspp/issues/12695), more)
```
becomes this
```md
What's new in 1.10.0
--------------------
* Graphics and compatibility fixes ([#12800](/../../issues/12800), [#12670](/../../issues/12670), [#12635](/../../issues/12635), [#12857](/../../issues/12857), [#12941](/../../issues/12941), [#11898](/../../issues/11898), [#12695](/../../issues/12695), more)
```

**Comment by unknownbrackets** [comment]
FYI - the way to keep it readable in markdown, and also to add title previews, is this:

```
 * Graphics and compatibility fixes ([#12800][])

[#12800]: https://github.com/hrydgard/ppsspp/issues/12800 "x86jit: Force INF * 0 to +NAN #12800"
```

Which looks like this:

 * Graphics and compatibility fixes ([#12800][])

[#12800]: https://github.com/hrydgard/ppsspp/issues/12800 "x86jit: Force INF * 0 to +NAN #12800"

-[Unknown]

**Comment by Anuskuss** [comment]
Wow, that's even cleaner (minus the repo changing the name though). Needs a more advanced script to fetch all the titles but should be easy enough. I can create one if you want to do it that way :)

**Comment by unknownbrackets** [comment]
Well, the only trouble with relative links is I don't think there's a way to specify a base path (`<base href="https://www.google.com" />` doesn't work.)  So if you're trying to keep it readable as a document outside github.com, the links won't work.

-[Unknown]

**Comment by iota97** [comment]
Updated in #13014 

About relative link I prefer to have it accessible from everywhere (it would broke it outside of github and on fork as well).

As URL are at the end of the file how long they are should not be a concern anymore, and if repo changes name a regex will fix it in no time anyway.

**Pull request merged**
