### PR TITLE
Oops, rebuild FBOs when buffered changes

### PR DESCRIPTION
**Pull request by unknownbrackets**
I'd thought about moving where `useBufferedRendering_` was updated, but then evidently forgot.  This is simpler, and takes care of the part of #9637 that easily reproduces.

-[Unknown]

### CODE REVIEW

**Comment by LunaMoo** [comment]
GPU part doesn't seem to help, still reproduces black screen with buffered->skip buffers->buffered.

Core part for the icon works fine:3.

**Comment by unknownbrackets** [comment]
Well, I'm not able to reproduce.  But I guess you must be switching during the time between EndFrame and BeginFrame, so changed to just handle that setting with the others.

I've added a fallback which will attempt to recreate FBOs that fail to create.

-[Unknown]

**Comment by LunaMoo** [comment]
Oh, I see it does work when going to settings, still fails when changing mode using drop down menu on windows.

(and loading savestates:P, but as mentioned in the issue, that's affecting only some games and only with d3d11 backend)

**Comment by unknownbrackets** [comment]
Hmm - to be clear, these D3D11 / Windows UI issues predate #9617.  It probably has nothing to do with FBOs.

-[Unknown]

**Comment by unknownbrackets** [comment]
Fixed that, it was the skip draw flag.  Has been a bug since forever.

-[Unknown]

**Comment by hrydgard** [comment]
Good fixes. I'm fine with all this - merge ready?

**Comment by unknownbrackets** [comment]
Yes.  There's a couple of unrelated leaks I found running in debug mode but I'll look at those later.

-[Unknown]

**Pull request merged**
