### PR TITLE
GPU: Hook US version of Marvel Alliance upload

### PR DESCRIPTION
**Pull request by unknownbrackets**
See #9852.  Appears to be the same basic func, but something resulted in a different hash.  Register use for from/to seems the same.  Not tested.

-[Unknown]

### CODE REVIEW

**Comment by Panderner** [comment]
Unfortunately PPSSPP crashes before Activision logo for both US versions, I'm using artifact build

**Comment by unknownbrackets** [comment]
And it doesn't crash without this change, right?  Hmm, there's probably somewhere a register is different that I missed then, maybe size.

-[Unknown]

**Comment by Panderner** [comment]
> Does the EU version crash?

Yep it crashes for EU version even i'm using Latest build not artifact build.

**Comment by sum2012** [comment]
Crash trace

**Comment by sum2012** [comment]
Current master merge this pr, no crash and no help

**Comment by unknownbrackets** [comment]
Okay, the func is the same as EU with just one small register usage different (t7 vs s7), but I must've misread the assembly before or something and got the size wrong in #9915.  This is still not tested, but maybe fixes the bug.

Might even fix something in the EU version too.

-[Unknown]

**Comment by hrydgard** [comment]
Cool, let's give it a try.

**Pull request merged**
