### PR TITLE
jit: Discard unused regs before a syscall

### PR DESCRIPTION
**Pull request by unknownbrackets**
This is a pretty minor optimization, though.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Seems fine, but I'm worried about even more of these issues where games rely on the contents of registers (or stack, but that's separate), violating the calling convention. Discarding these would seem to reduce the likelyhood of getting the "right" values in the registers by a bit...

**Comment by unknownbrackets** [comment]
Well, right after the syscall we will fill the values with 0xDEADBEEF anyway.  The only reg this is not true for is V1, but that's only if the syscall doesn't use it.  I can remove V1.  I guess V0 also if there are any void funcs.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, drop V0 and V1 and I'll merge.

**Comment by unknownbrackets** [comment]
Okay, done.  Also added HI/LO.

-[Unknown]

**Pull request merged**
