### PR TITLE
Fix flickering in SD Gundam G Generation Portrble

### PR DESCRIPTION
**Pull request by daniel229**

### CODE REVIEW

**Comment by hrydgard** [comment]
"Portrble" should be "Portable" everywhere, right?

**Comment by daniel229** [comment]
Sorry,still there is a typo

**Comment by daniel229** [comment]
just close this

**Comment by hrydgard** [comment]
you can just commit --amend and then push -f to your branch to fix the typos instead of making a new pull :)  but either is fine

**Comment by daniel229** [comment]
Seems to has to learn some git commands.

**Comment by unknownbrackets** [comment]
Yeah some nice ones are:

1. `git stash` (great command) and `git stash pop` (saves changes you don't want to commit yet.)
2. `git comment --amend` (changes the last commit.)
3. `git rebase -i upstream/master` (allows you to change other commits not merged yet.)
4. `git bisect good` and `git bisect bad` (for automated bisecting.)

-[Unknown]

**Comment by daniel229** [comment]
Thanks,I will try it out.

**Pull request closed without merging**
