### PR TITLE
Fix-ja_jp.ini

### PR DESCRIPTION
**Pull request by nassau-tk**
Fixed some UI text.

But, I couldn't change some text below.
image

### CODE REVIEW

**Comment by hrydgard** [comment]
That's weird, it should have worked to change those. I'll look into it soon.

**Comment by hrydgard** [comment]
It does seem to work for me, at least in recent builds.

**Comment by nassau-tk** [comment]
And!! 
Show Memory Stick folder
too. Thanks!

**Comment by nassau-tk** [comment]
> It does seem to work for me, at least in recent builds.
> 
> image

OK!!

**Comment by hrydgard** [comment]
Hm, show memory stick folder doesn't seem to have been added to the ini files, but should work to translate if you do.

**Comment by nassau-tk** [comment]
Oh.... I miss take it about MS folder text.
Ok. I will fix later.

And, Color Tint & Saturation is not change on my 1.12.3-1215.
I will check next merged build.

**Comment by hrydgard** [comment]
Try 1.12.3-1264...

**Pull request merged**
