### PR TITLE
Import SPIRV-Cross. This will be used later to translate post-processing shaders...

### PR DESCRIPTION
**Pull request by hrydgard**
…to the various shader languages we use.

Eventually, this will make it possible to use post-processing with Vulkan and D3D11. Probably not DX9, though maybe.

### CODE REVIEW

**Comment by hrydgard** [comment]
Can't get it to build on Android right now (silly issue with std::to_string), but merging anyway, as the main goal is D3D11. Will eventually need it on Android too to run post processing shaders on vulkan but that can wait.

**Comment by mrcmunir** [comment]
@hrydgard  Broken linux build? 
CMake Error at ext/SPIRV-Cross/CMakeLists.txt:23 (message):
  Build out of tree to avoid overwriting Makefile

**Comment by hrydgard** [comment]
Hm, travis should've caught that.. I'll look into it.

**Comment by hrydgard** [comment]
After a `git submodule update --init --recursive`, things seem to build alright on my mac using CMake.

**Comment by hrydgard** [comment]
Oh yeah, make sure to not just do "cmake .".  It's better to use ./b.sh.

**Comment by mrcmunir** [comment]
@hrydgard  Ah I see working fine with ./b.sh  or mkdir build folder thanks

**Comment by iOS4all** [comment]
@hrydgard nice job. You're an active person and always helps people who have issues.
Keep going man.

**Pull request merged**
