### PR TITLE
Create vital directories on Android storage permission grant. 

### PR DESCRIPTION
**Pull request by hrydgard**
Should help #11020

### CODE REVIEW

**Review by Leopard20 — CHANGES_REQUESTED** [review]
Perhaps you should add another line to your function `CreateDirectoriesAndroid`:

```File::CreateDir((g_Config.memStickDirectory + "PSP/SYSTEM").c_str());```

**Comment by leopard20** [comment]
Also, creating directories after permission is granted doesn't clear the whole directory, does it?

**Comment by hrydgard** [comment]
Oops, yeah definitely. And no, CreateDir only creates a directory if it doesn't exist, it does nothing beyond that.

**Comment by leopard20** [comment]
Ok good! :)

**Comment by hrydgard** [comment]
Tested it myself by renaming the PSP directory on my device, and it looks like it works fine.

**Pull request merged**
