### PR TITLE
IR: centralize common parts of native backend

### PR DESCRIPTION
**Pull request by unknownbrackets**
This splits some things out of RiscVJit and makes them common for less repeated code between backends.

There's more that can be moved.  I actually think that it'd make sense to do this for the regcaches too (vector isn't thought out yet, but I suspect it'll end up pretty similar ultimately between the backends.)

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Yeah, I think vectors-after-the-IR-transform will also end up very similar between the backends, just like the normal GPR/FPR regcaches and soon. Though the current more complicated x64 vector regcache, maybe not so much?

**Review by hrydgard — APPROVED** [review]
Looks good, a nice step towards more native IR backends.

**Comment by unknownbrackets** [comment]
I'm planning to leave those.  Currently, the existing regcaches are better for debugging if a memory access failure occurs, so I'm not wanting to replace them with IR.  I'm imagining an additional option in dev options.  But could be faster than the existing jit.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, that plan makes sense.

**Comment by unknownbrackets** [comment]
I'm thinking of making register mapping in the common IR regcache code slightly "magical".  For most ops the registers to map are "obvious" based on IRMeta, so I'm thinking of having either like `gpr.Map(inst);` or even a kinda magical `gpr.Dest()` (since it actually already knows the current `inst` and could auto-call `Map(inst)` for you when using those helpers, if not yet called.)  I'd keep the more manual way for more complex ops, HI/LO, etc.  I don't like overly magical things but I kinda feel like the code will just behave obviously and do what you want and expect.

I'm also thinking of combining the GPR and FPR to one cache, although IR does refer to them with an offset.  So it might be i.e. `regs.R(inst.dest)` / `regs.F(inst.dest)` / `regs.V(inst.dest)` or `regs.DestR()` / `regs.DestF()` / `regs.DestV()` or something.  I think a lot can be centralized and we can just split loc out to REG/FREG/VREG, and the IRReg has a natural type.  And for example, I think the same "multilane" support used for vecs can naturally handle LO/HI, so sharing code makes sense for the regcache state.

What do you think - crazy?

-[Unknown]

**Pull request merged**
