### PR TITLE
Add right analog for touch controls.

### PR DESCRIPTION
**Pull request by LunaMoo**
Not to be confused with #9859 which this doesn't fulfill despite that issue name as it's a request for mapping other controls for the analog which this doesn't.

 It only add's a right analog to be used as a proper right analog. This is useful for HD remasters and even more for games patched(ie through CWCheat) to get real right analog controls for example Metal Gear Solid Peace Walker or Ghost in the Shell Stand Alone Complex.

 If set to visible, resetting touch location to defaults will move face keys up and place right analog under reflecting dpad and left analog stick.

Screenshot_2019-07-18-04-05-42-596_org ppsspp ppssppluna

### CODE REVIEW

**Comment by unknownbrackets** [comment]
I think this is a good thing, but I'm slightly concerned that it'll lead to confused users when it doesn't work in 99% of games unless there's some way to tell them it needs cheats or there's mapping or something...

-[Unknown]

**Comment by LunaMoo** [comment]
Made it clear on the visibility screen. Right analog touch is disabled by default, so anyone who will want to activate it will see that it doesn't do anything in PSP games.

**Comment by hrydgard** [comment]
Still a little concerned by the wording, as it implies that PPSSPP plays things other than PSP games (which strictly is true, but for most normal purposes isn't). Maybe it should only appear at all when playing remasters and patched game?

**Comment by marosis** [comment]
So what just use right analog stick as, triangle= Y Up, cross= Y down, square= X left and circle= X right. This is really good for FPS games

**Comment by LunaMoo** [comment]
Ok, changed to "(not used by most games)".
 Can't really make it to "only patched games" since patches can be applied by different ways some not detectable in any easy way and maintaining some kind of list would be a chore. At most I could hide touch right analog completely through ini-only setting since remasters only use it as d-pad alternative and patches are even less popular than fps patches and I don't see people even willing to learn how to make them.

 As for requests about mapping digital controls to touch analog as stated on the start this PR has nothing to do with that. I'm also not intrested in doing it at all since for me the benefit of touch analog stick exists only when it's used at much larger size than my thumb which is really useful to gain better control over sensitivity with true analog control, but that's actually something that most PSP games doesn't really support even for left stick. There might be people for which this is positive improvement, but to me personally it would at most be the opposite and would rather replace "digital analog stick" into 4 digital touch buttons since analog used digitally typically has to use some high threeshold and requires bigger and more tiresome movement for exactly same digital actions.

**Comment by Emulatorer** [comment]
Right Analog doesn't work in Monster Hunter 3rd HD 🤔
Screenshot_2019-07-25-06-36-47
Screenshot_2019-07-25-06-36-56
Im using ppsspp luna edition 😅
@LunaMoo Do I need to use cwcheat for MH3rd HD?

**Comment by Saramagrean** [comment]
It work for me without cheat. :)

**Comment by Saramagrean** [comment]
It work for me without cheat. :)

In the village can not rotate the camera angle, will only be used when playing in quests.

**Comment by Emulatorer** [comment]
@Saramagrean thanks for feedback now I can really enjoy playing Monster Hunter 3rd HD via PPSSPP :3

**Comment by hrydgard** [comment]
Decided I can accept the new wording. Merging.

**Pull request merged**
