### PR TITLE
jit-ir: Correct downcount handling

### PR DESCRIPTION
**Pull request by unknownbrackets**
Oops, was wrong - already accounted for delay slots.  Clear so we don't double count when emitting a syscall.

Fixes FF4 utility msg flickering.  Also, I guess since `Syscall` exits, it'll never `ApplyRoundingMode()` (and also any accounting for downcount afterward, so I just removed it.)  Maybe we need Syscall to restore/apply rounding itself?  Hmm.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Right, yeah, need to think more about rounding.

**Comment by hrydgard** [comment]
Maybe Syscall shouldn't exit? We could just as well emit an ExitToConst directly afterwards..

**Comment by unknownbrackets** [comment]
Yeah, that makes sense.

-[Unknown]

**Comment by hrydgard** [comment]
Oh, right. Yeah, it does need to exit :)

**Pull request merged**
