### PR TITLE
Rename GLES files to match the convention the other backends use.

### PR DESCRIPTION
**Pull request by hrydgard**
This is just minor cleanup - in the other backends files are called things like TextureCacheVulkan, but GLES files had no suffix. Fixing that.

### CODE REVIEW

**Comment by xebra** [comment]
Seems good changes, I was bothering them.

**Comment by hrydgard** [comment]
@xebra Yeah :) I might hold off on this until your tesselation branch is complete to avoid conflict though.

**Comment by xebra** [comment]
@hrydgard Thank you for waiting.

**Comment by moura464** [comment]
https://pandorawiki.org/Porting_to_GLES_from_GL

**Comment by hrydgard** [comment]
@xebra I'm merging this when the CI passes, so please make sure to rebase your new work on master once this is in :)

**Comment by xebra** [comment]
@hrydgard I tried rebase with command line but something weird, so I recreate remote repo, delete and forked again :p

**Pull request merged**
