### PR TITLE
Add some ThreadManForKernel nids

### PR DESCRIPTION
**Pull request by sum2012**
Find in #13797

### CODE REVIEW

**Comment by hrydgard** [comment]
Did you link to the right issue? That one's about flicker on Vulkan in WWE.

**Comment by sum2012** [comment]
Just find in that game use that functions.
No help.

**Comment by hrydgard** [comment]
Oh, ok. Well, this should be fine I guess.

**Comment by unknownbrackets** [comment]
Is it a hacked version of the game or something?  No regular game should be using kernel-mode funcs.

-[Unknown]

**Comment by sum2012** [comment]
Maybe the game want to use sceUsbBus_driver to do unusual thing ?
Original log:
https://gist.github.com/sum2012/832b157a9b0797fec3abce2040b74487

**Comment by hrydgard** [comment]
Yeah these imports can come from PRXes that games load, apparently...

**Comment by unknownbrackets** [comment]
Looks to me like we would be best off emulating sceUSB_PSPComm_Driver (usbpspcm, also in kd) in that case, presumably it's a module with kernel mode access to pull in those drivers, etc.

Does that game use USB for something?

-[Unknown]

**Comment by sum2012** [comment]
I don't know

**Pull request merged**
