### PR TITLE
Identify remasters based on UMD_DATA hash

### LINKED ISSUE #8268: HD Remasters with more than 64MB RAM crash instantly
There is two HD Remasters, that use more than 64MB RAM:
-Eiyuu Densetsu: Sora no Kiseki SC Kai HD Edition
-Eiyuu Densetsu: Sora no Kiseki 3rd Kai HD Edition
To make them work you need to slightly modify the code. The modifications were posted by B1ackDaemon in Issue #1494:

1. Uncomment game strings in Core\HDRemaster.h
2. Place decrypted exdata0 contents to memstick folder and add following code in Core\HLE\sceIo.cpp
pspFileSystem.Mount("exdata0:", memstickSystem);
pspFileSystem.Unmount("exdata0:", memstickSystem);

The problem occurs the moment you try to start the game.

### PR DESCRIPTION
**Pull request by unknownbrackets**
I don't actually have any remasters, so this has not been tested with an actual remaster.  But it ought to work.

Fixes #8268.

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
blackscreen Eiyuu Densetsu Sora no Kiseki FC Kai HD Edition
```
25:17:106 root         I[KERNEL]: HLE\sceKernelThread.cpp:1943 276=sceKernelCreateThread(user_main, 08804228, 00000020, 327680, 80000000, 00000000)
25:17:106 root         I[KERNEL]: HLE\sceKernelThread.cpp:2014 0=sceKernelStartThread(276, 33, 09fffed0)
25:17:106 root         I[KERNEL]: HLE\sceKernelThread.cpp:2053 __KernelReturnFromThread: 0
25:17:106 user_main    E[HLE]: Util\BlockAllocator.cpp:61 Clearly bogus size: 024a3000 - failing allocation
25:17:106 user_main    E[KERNEL]: HLE\sceKernelMemory.cpp:1020 sceKernelAllocPartitionMemory(partition = 2, UserSbrk, type= 3, size= 38416384, addr= 00001000): allocation failed
25:17:107 user_main    E[HLE]: Util\BlockAllocator.cpp:61 Clearly bogus size: 024a3000 - failing allocation
25:17:107 user_main    E[KERNEL]: HLE\sceKernelMemory.cpp:1020 sceKernelAllocPartitionMemory(partition = 2, UserSbrk, type= 3, size= 38416384, addr= 00001000): allocation failed
25:17:107 user_main    I[IO]: HLE\sceIo.cpp:937 stdout: //----------------------------------------------//
25:17:107 user_main    I[IO]: HLE\sceIo.cpp:937 stdout: 
25:17:107 user_main    I[IO]: HLE\sceIo.cpp:937 stdout: //                                              //
25:17:107 user_main    I[IO]: HLE\sceIo.cpp:937 stdout: 
25:17:107 user_main    I[IO]: HLE\sceIo.cpp:937 stdout: // YamanekoCoreSystem Init                      //
25:17:107 user_main    I[IO]: HLE\sceIo.cpp:937 stdout: 
25:17:107 user_main    E[HLE]: Util\BlockAllocator.cpp:61 Clearly bogus size: 024a3000 - failing allocation
25:17:107 user_main    E[KERNEL]: HLE\sceKernelMemory.cpp:1020 sceKernelAllocPartitionMemory(partition = 2, UserSbrk, type= 3, size= 38416384, addr= 00001000): allocation failed
25:17:107 user_main    W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 00000000
25:17:107 user_main    W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 00000004
25:17:107 user_main    W[MM]: MemmapFunctions.cpp:130 WriteToHardware: Invalid address 00000008
```

**Comment by daniel229** [comment]
Debugger log
https://gist.github.com/daniel229/2ecbf0505dfa37436500

**Comment by unknownbrackets** [comment]
It did not detect that as a remaster.  Does your UMD_DATA.BIN contain `ULJM-05170|55C069C631B22685|0001|G` (it can have other things as well, as long as it has that)?

If so, I must've done something wrong.  In that case, can you try just "55C069C631B22685" for the value in HDRemaster.cpp or something?

-[Unknown]

**Comment by daniel229** [comment]
It has that

**Comment by daniel229** [comment]
"55C069C631B22685" instead of "ULJM-05170|55C069C631B22685|0001|G" is still blackscreen

**Comment by daniel229** [comment]
It seems broke by https://github.com/unknownbrackets/ppsspp/commit/d273deedeb28356c0028b759fcf48d7f5d8d8296 ,it can load to title before taht change.

**Comment by MIuIddy** [comment]
There is a small error in line 125 of Core/PSPLoaders.cpp.
´´´
if (entry.umdDataValue && umdData.find(entry.umdDataValue) != umdData.npos) {
```
should be
´´´
if (entry.umdDataValue && umdData.find(entry.umdDataValue) == umdData.npos) {
```
otherwise the original game gets detected as remaster and the remaster gets detected as the original.

**Comment by daniel229** [comment]
@MIuIddy the game going to the title now,still hangs on new game or after loading save.

**Comment by unknownbrackets** [comment]
@daniel229 did you put the exdata files inside memstick/exdata/ULJM05170/?

-[Unknown]

**Comment by daniel229** [comment]
Is it like this?Still not help.

**Comment by MIuIddy** [comment]
What is the filename extension of the files in the folders?
If it's .EDAT, you need to decrypt the files.
If it's .DAT, you need to remove the extension, for example "c_stchr0.itp.DAT" becomes "c_stchr0.itp".
If the files in etc end with .itp and the files in mpa3 with .map everything should work fine.

Also there should be one of this lines in the logfile:
´´´
HLE\sceIo.cpp:521 I[IO]: Did not find exdata/ULJM05170/ under memstick for exdata0:/
´´´
´´´
HLE\sceIo.cpp:519 I[IO]: Mounted exdata/ULJM05170/ under memstick for exdata0:/
´´´

**Comment by daniel229** [comment]
Thanks,decrypting files now,it seems need an hour.

**Comment by unknownbrackets** [comment]
Hmm.  Maybe PSP/exdata/ is better, if people want this on Android devices.  Opinions?

-[Unknown]

**Comment by daniel229** [comment]
Are MUSIC,PICTURE,VIDEO,PAUTH,PAUTH also in PSP folder for Android?

**Comment by unknownbrackets** [comment]
No, they aren't.

-[Unknown]

**Comment by daniel229** [comment]
Looks good,but the saving dialog is broken.



broken


before

**Comment by unknownbrackets** [comment]
Oh, right.  That's probably the case in all remasters.  I've just pushed something to this branch which may fix that.

-[Unknown]

**Comment by daniel229** [comment]
fixed.

**Comment by daniel229** [comment]
Someone play the FC HD ver on PPSSPP one year ago,MP4 also play fine.
https://www.youtube.com/watch?v=0eB3bJURSmo

**Comment by unknownbrackets** [comment]
@hrydgard I think this is all good now, although the PPGe change is a bit less than beautiful.  It seemed the simplest solution by far, though.

-[Unknown]

**Comment by hrydgard** [comment]
That should be alright, yeah.

**Pull request merged**
