### PR TITLE
Change jpn0 font

### PR DESCRIPTION
**Pull request by nassau-tk**
I finished fix the jpn0.pgf.
JIS Kanji-Lv1(Kanji = 2946characters).
All chekced & modified manually.

### CODE REVIEW

**Comment by hrydgard** [comment]
Great, thank you so much!

**Comment by hrydgard** [comment]
Oh wait, something went wrong there - I merged into another branch? Your PR target was not master.

I'll fix it up manually.

**Comment by nassau-tk** [comment]
Oops!!
My wrote "Description" appear to "Download Commit log"!!
I'm embarrassed!!

And,Did I make a mistake? 
It's so Sorry...
It's so difficult to use Github system for me.:tired_face:

**Comment by hrydgard** [comment]
Don't worry about it :)

**Pull request merged**
