### PR TITLE
Use software transform for flat shading and fix colors

### LINKED ISSUE #10969: dust effect displays green triangular shapes issue
im playing this Brave story new traveler game using vulkan backend when i notice that the dust effects displays wrong images (green triangular shapes) 

OS android 7.0 , Octa-core, 2360 MHz, ARM Cortex-A53, 64-bit, 16 nm , Mali-T830 MP2 , 4 GB RAM

### PR DESCRIPTION
**Pull request by unknownbrackets**
This fixes #10969 in the way described there.  This makes it work properly on all backends.

Rectangles were already fine because we always use the BR vertex to generate the triangles.  In theory, we should use flat always in clear mode, but I'm not aware of any games using triangle clears currently anyway.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Very nice!

**Comment by xebra** [comment]
Hm, I got an issue on flat shading with HW tessellation only on D3D11 and Vulkan, it will cause tessellation is turned off(it just drawing a plane refinement mesh).
But, maybe we had no choice anyway, I think.
I will put it on hold for now because I'm not sure what is the problem in detail.

**Comment by hrydgard** [comment]
Oh, right. I think we should only fall back to software like this for draw calls that aren't tesselation, I find it unlikely that the provoking vertex would be very important for tesselated geometry (and if it is, we can just change around the order of our emitted vertices)...

**Comment by unknownbrackets** [comment]
Oops - sorry, didn't even think about that.

-[Unknown]

**Pull request merged**
