### PR TITLE
softgpu: Track dirty vs really dirty per buffer

### PR DESCRIPTION
**Pull request by unknownbrackets**
When games draw and display with a frame lag, it becomes important that we indicate really dirty for the correct buffer.  Since some triple buffer, this attempts to track at the buffer level using 1024 byte granularity.

May help #15062.  Fixes black screens, at the very least, in some games such as Brave Story.

-[Unknown]

### CODE REVIEW

**Comment by Gamemulatorer** [comment]
Buildbot is not updated. I cannot test this commit.

**Comment by hrydgard** [comment]
I pinged orphis about the buildbot.

**Comment by Gamemulatorer** [comment]
Unfortunately there's still no android build.
Screenshot_2022-02-14-11-55-28-573_com android chrome

**Comment by Gamemulatorer** [comment]
I can confirm this fixes my issue #15062

But question is why the fps is become 15/30 fps if I use frameskipping x1 and got 50/60 fps if no frameskipping?

**Comment by unknownbrackets** [comment]
Currently, the software renderer (unless you have frameskip enabled) ignores the game FPS and pushes 59.97 frames each second.  Whatever game you play, you will always see 60 as the FPS because of this.  This is really what the PSP did as well, essentially it always renders duplicate frames to 60 FPS.

When you turn on frameskip, it stops doing this.  Thus, 50/60 immediately becomes 25/30 and then goes down to 15/30.

-[Unknown]

**Pull request merged**
