### PR TITLE
Fix OpenGL on Windows XP

### PR DESCRIPTION
**Pull request by unknownbrackets**
Can't forget about memory alignment.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Oh! Great catch! I suspect this will fix several crashes that we've been seeing, not necessarily only on Windows XP...

**Comment by unknownbrackets** [comment]
Yeah, presumably would affect arm32 as well, right?  I think arm64 allocates aligned, though.

-[Unknown]

**Comment by hrydgard** [comment]
NEON just tends to run slow rather than crash on misalignment, but there are exceptions to that, so possibly.

**Comment by hrydgard** [comment]
Strange, in my XP VM, things still crash...

**Comment by ShadowLady** [comment]
This seems to be crashing opengl on my windows 10 at least.

**Comment by unknownbrackets** [comment]
Oops, yes, there's a bug with upscaling.

-[Unknown]

**Pull request merged**
