### PR TITLE
Switch to XXH3

### PR DESCRIPTION
**Pull request by unknownbrackets**
XXH3 seems to be better than XXH64 or XXH32 across 32 bit and 64 bit on Android and Windows.  I assume it's the same on macOS/Linux/iOS.

For those wondering, this isn't likely to get you from 5 FPS to 20 FPS or anything, expect much smaller gains.

This does keep the [ARM prefetch patch](https://github.com/hrydgard/ppsspp/blob/3ec61274fabd3a50060b707b6f09b0e809cafb18/ext/xxhash.c#L226-L228) for XXH32, which is now only used by texture replacement.

My benchmarks:

&nbsp; | x86_32 | x86_64 | armv7a | armv8a
-- | -- | -- | -- | --
XXH32 | 0.012706 | 0.012276 | 0.021979 | 0.027757
XXH64 | 0.071030 | 0.007636 | 0.066026 | 0.016456
City64 | 0.051656 | 0.007598 | 0.050303 | 0.013116
XXH3_64 | 0.009174 | 0.006052 | 0.019761 | 0.013228
QuickTex | 0.001712 | 0.002569 | 0.005600 | 0.005710

Above numbers are representative of typical runs on 1024 bytes of data, but I only tested a few devices (only Kryo for ARM.)  Because XXH3_64 is always faster than XXH32, I moved everything to use it (outside texture replacement.)  I also removed seeds because the default seed function is measurably faster on ARM64 (~14% improvement), though it's basically the same elsewhere which seemed weird.

Supposedly, XXH3 (at least the 128 bit variant) is very close to crc32c hardware hashing speeds on some hardware, although I didn't verify.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
I'm a little confused by the use of "Reliable" in the hashing code. That means one that never changes right, and identical to our current texture replacement hash? But in that case, why did it have two different return types depending on architecture?

**Comment by unknownbrackets** [comment]
Well, previously it meant more like "strong" hash instead of the weak quick hash.

-[Unknown]

**Comment by hrydgard** [comment]
Maybe we should just call it StableHash or TextureReplacementHash instead now. "Reliable" is too fuzzy...

**Comment by unknownbrackets** [comment]
I'll just do XXH directly, it's only texture replacement now.  Makes the header simpler.

-[Unknown]

**Comment by hrydgard** [comment]
Alright, I'm fine with that.

**Comment by unknownbrackets** [comment]
Cool, that's what I pushed earlier.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, was just waiting for CI.

**Comment by Gamemulatorer** [comment]
#Justasking this is only improve texture replacement performance? 🤔😅

**Comment by hrydgard** [comment]
It's actually exactly the opposite, performance won't be improved when you use texture replacement - because we can't change that hash function.

**Pull request merged**
