### PR TITLE
Update the README for 1.1

### PR DESCRIPTION
**Pull request by hrydgard**
I'm sure I forgot some important stuff, so please remind me :)

### CODE REVIEW

**Comment by sum2012** [comment]
Add support of regression of "correct depth rounding"
Fix Tenchu San "walk through walls" bug in mobile by temporarily disable optimization

**Comment by sum2012** [comment]
minor improve adhoc

**Comment by sum2012** [comment]
Switch to VS2015 for compile windows build

**Comment by unknownbrackets** [comment]
#6976, while it broke GTA, also fixed audio garbage that would happen whenever music looped (aside from improved some minor compatibility.)  Many people reported this issue and complained about it.    Might be worth mentioning.

Maybe we call out texture scaling perf improvements (#7449)?  It contained perf improvements + we added extra.  Plus, the texsplit changes will have also improved this further for some games (depends on game.)

More improvements to Direct3D, like #6920.  Might be worth mentioning that D3D9 got improved to be more inline with OpenGL.

I still see reports of #7548 every now and again, but probably not worth mentioning...

UV rotation (#7736) was a semi-common report, not sure if it's worth the readme though.

Non-mobile screen rotation (#7739) might be worth mentioning for some?  Not sure either how big this is.

Improve BSD support (#7772)?

Savedata management UI (#7808)?  Can probably merge into the savestate for homebrew line.

It's a shame arm64 static registers isn't user-visible enough to mention, that was a fun one.

Should we mention Windows 10 is supported?  We did have to make some changes, I thought, not sure if they were necessary changes.

-[Unknown]

**Comment by hrydgard** [comment]
#7739 (screen rotation) is already mentioned, I'll add a bunch of the others though.

There's limited space for "What's new" on Android apps, but I guess in the README we can add however much we want so quite a few will make it. Thanks for the reminders!

**Comment by unknownbrackets** [comment]
Ah, missed rotation.  Yeah, sounds fair - especially can remove BSD/Windows/etc. from the Android app display.

-[Unknown]

**Pull request merged**
