### PR TITLE
HTTP user agent fix for DownloadManager

### PR DESCRIPTION
**Pull request by hrydgard**
Our HTTP user agent was `NATIVEAPP 1.0` for these which isn't very good, RetroAchievements want clear user agents.

Now uses PPSSPP/{git-version}.

Also a quick fix for recognized games with no achievements.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Minor pedantry: "NATIVEAPP 1.0" is actually a perfectly valid (but not ideal) user agent.  In that case, "1.0" is a comment, not a version, but it's not supposed to be required for products to specify versions in user-agents.

Might be better to do this even beyond downloader, but not very important.

-[Unknown]

**Comment by hrydgard** [comment]
Turns out we already do it a lot beyond DOWNLOADER.

Though hm, maybe we should use a space instead of / then between PPSSPP and the git version?

**Comment by unknownbrackets** [comment]
Well, it's correct to use:

 * PRODUCT
 * PRODUCT/VERSION
 * PRODUCT/VERSION SUBPRODUCT/VERSION OTHER/VER
 * PRODUCT COMMENT

And the like.  The syntax is basically `(PRODUCT[/VERSION])* COMMENT`.  But it is correct to use `/` to separate the version, just saying that it shouldn't have crashed or anything with the old way.

-[Unknown]

**Comment by hrydgard** [comment]
Ah OK. Well, I didn't get reports of crashing, just that the retroachievement folks didn't want strange names that don't correspond to an emulator name, preferably.

**Pull request merged**
