### PR TITLE
Minor fixes to SDL + resolution display

### LINKED ISSUE #8070: Shortcut actions bug
Hi ppl, this start when start using the state slots to test things in the game, the the game start auto-loading slots, i'm very bad explaning this so here a video:

http://www.mediafire.com/watch/n1nnnb2mqqz6emf/video.mp4

ppsspp config: http://www.mediafire.com/download/0gnqq33wtinmlrc/PSP.tar.gz

how you can see moving the cursor or alt+tab load the state.
i'm usings gentoo 64 and the sdl version

Log: https://gist.github.com/latot/58bdd8e113b3bd78f911

Thx.

### PR DESCRIPTION
**Pull request by unknownbrackets**
This fixes [key event issues in SDL](https://github.com/hrydgard/ppsspp/issues/8070#issuecomment-167438606) and also shows "(upscaling)" when changing resolutions and pegged at 1x due to an upscaling shader.

-[Unknown]

### CODE REVIEW

**Comment by latot** [comment]
little question its normal this log?

https://gist.github.com/latot/ad216de79a708869a056

now are new messages from blockallocator (in start and end)

**Comment by unknownbrackets** [comment]
Yes, we log allocations and such so we can see why memory is full if allocations fail.

-[Unknown]

**Comment by latot** [comment]
okis, so we don't need open any issue for that messages?

**Comment by unknownbrackets** [comment]
I also included a scratchpad range check.  Most of our checks were treating it as if it was 4x as large as it really is.  This seems related to the crash in #8104, but obviously not the ultimate cause since it's only happening on Android.

-[Unknown]

**Comment by unknownbrackets** [comment]
@latot well, I'm leaving it off for now, since we don't do that on Windows or any other platform really, either.  Maybe it would be best to log, I'm just worried that some system might trigger frequent keypress events (such as a touch based system) and that could cause a lot of log statements and a perf issue.

Maybe the concern is unfounded, though.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets Well done fix #8104

**Comment by latot** [comment]
@unknownbrackets i was worried of that too, when i try use it before i found a lot of messages, but was for this and because don't are set the unknow keys in sdl, with this fix and with include unknow keys the log is normal now, and only show unmapped keys. Can be good idea some one test it.

Cya.

**Pull request merged**
