### PR TITLE
Update Russian translation

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by TotalCaesar659** [comment]
@hrydgard I want to ask more about translation. Sorry fo doing it here, the issue template requires to fill a lot of data (a game for fixing, OS etc.), I'm afraid not to fit in it.
Some strings are untranslatable. I try to add them to ru_RU.ini file with translation, but they remain English. Here they are:




Could you look into this?

**Comment by hrydgard** [comment]
Thanks, I'll take a look tomorrow.

**Comment by TotalCaesar659** [comment]
Alright, thanks.

**Comment by hrydgard** [comment]
I think #16460 will fix all of these once it's in. Let me know if there are further issues later.

**Comment by TotalCaesar659** [comment]
Just one string left: "Stereo display shader".

**Comment by TotalCaesar659** [comment]
@hrydgard Could you check this? I'd wanted to update the translation before 1.14.0 release.

**Comment by hrydgard** [comment]
I'll fix it shortly!

**Comment by hrydgard** [comment]
Should be all good now

**Comment by TotalCaesar659** [comment]
Thank you very much! Russian translation is [updated](https://github.com/hrydgard/ppsspp/pull/16474).
There are some more strings:

**Comment by hrydgard** [comment]
Aspect Ratio I thought was working, let me fix that.

The others are really extremely debugging-specific and not something regular users will touch, not sure if worth translating.

**Comment by TotalCaesar659** [comment]
Alright, just check "Aspect Ratio" then, it's already added to the translation.

**Comment by hrydgard** [comment]
Fix is in.

**Comment by hrydgard** [comment]
Thanks for reporting!

**Pull request merged**
