### PR TITLE
[Build] Generate iOS IPA

### PR DESCRIPTION
**Pull request by anr2me**
This is moved from https://github.com/hrydgard/ppsspp/pull/15446 since i need to test another action on my master branch

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm, couple of tests still showing yellow, not sure what's up with that. Otherwise, is this ready to go?

**Comment by ANR2ME** [comment]
As mentioned by @unknownbrackets before:
```
Changing the matrix on the test changes the required check names. If we merge this, we need to change the configuration of the branch protection.

-[Unknown]
```

The test stuck probably because this PR changed the artifact naming to include the id (ie. macos, clang) thus no longer recognized

**Comment by hrydgard** [comment]
Hm, do we still need this? There's some conflict.

**Comment by anr2me** [comment]
We already have the manual generate IPA, so this is not needed anymore.

This PR only used to automatically packed and released the IPA build to https://github.com/hrydgard/ppsspp/releases since the files used to generate the IPA already existed all this time (seems to be built together with the MacOS build) but not exposed to artifacts/release.

**Pull request closed without merging**
