### PR TITLE
Sas: Add option to control reverb volume

### LINKED ISSUE #14328: Audio Reverb Level Adjustment for Users
https://github.com/hrydgard/ppsspp/issues/10246

Reverb in some games drives a lot of people insane if there's a lot of it, making it unplayable for some including myself. 
I understand that it's basically impossible for you guys to adjust it perfectly for every game, which is why I'd like to propose a reverb level adjustment feature in the settings menu (maybe in audio or developer tools) to let users choose how much reverb there is/other parameters related to reverb. That way it's possible to let the devs work on the major problems and the users can spend the time fine tuning reverb levels/parameters per game.

### PR DESCRIPTION
**Pull request by unknownbrackets**
This also allows you to turn it off.  Some don't like the reverb effects (which are probably inaccurate still), so while not a fix, this does provide another option.  See for example #8645 or #10246.

It's another option but it is a preference some people want to adjust, and audio settings aren't too crowded.

Fixes #14328.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Yeah, since the emulation is so inaccurate, this makes sense.

**Comment by OCRBonk** [comment]
This is a neat setting. I was hoping this would allow me to turn up the Reverb volume in Final Fantasy Tactics since even on real hardware it's nothing even close to the PS1 version. But turning it up amplifies a lot of the problems with the reverb and causes the already audible aliasing to become even worse.

Turning it to 0 is nice but no reverb then. That had me thinking though. How hard would it be to add support for VST 2/3 plugins so we can turn the reverb emulation off. And at least use  ;While not accurate; nice sounding reverb. There are a lot of great paid and free Reverb VST plugins and they are always low latency on the CPU at least in a DAW setting.

I know someone else mentioned about potentially trying to design tests to model the behavior of the reverb on real hardware.
Is it the testing part of that equation the more time consuming and larger part of the work? Or just designing the tests?

**Comment by unknownbrackets** [comment]
I created some samples of the reverb based on a simple tone and our results are pretty far off currently.  But it's an equation with a lot of variables, so modeling it to get it right is hard... ideally I'd like to make them exactly accurate.

Some mode to have higher quality reverb doesn't sound bad at all.  Ideally paired with accurate reverb...

-[Unknown]

**Comment by OCRBonk** [comment]
I'm not sure how accurate it would end up because I assume the PSP's reverb hardware is configurable(?), but there is the possibility of captured impulses played back through an audio plugin (Say a 1khz sine wave at xdB volume) like what is done to model things like the frequency response of a space in real life or the response of a particular loudspeaker. 
Impulses are usually very small in size, while not ideal perhaps it would be possible to build a per game database where the parameters a game uses are logged and plugged into a homebrew program on real hardware and then an impulse response is recorded based on how those parameters change the behavior of the reverb unit.
Of course this is assuming games only use one setting because i'm not a programmer by any means. But i'm sure there are probably games that adjust and use different settings? 

The other inaccurate idea is just VST plugins built into the audio mixing chain and simply processing whatever audio is sent before final output. (IE: Turn reverb volume to zero, use TAL-Reverb-4  as your plugin and dial settings to taste). The reverb wouldn't sound anything like real hardware but at least the reverb would sound pleasant.

**Comment by unknownbrackets** [comment]
There are 10 presets (like echo, room, studio, pipe, etc.) games can use, and that's it.  The game can't tune the parameters individually, just choose a preset and turn on/off.

-[Unknown]

**Comment by OCRBonk** [comment]
That would make getting impulse responses a lot simpler if there is just 10 presets. 
I don't know how much work it would be to code everything necessary. (Program on real hardware to do nothing but play sweeps or a tone for each of the 10 presets from here for example https://www.audioease.com/altiverb/sampling.php , programming in VST support to use with a convolution reverb or your own system to use the impulses with ,etc)

But perhaps it is a worthwhile alternative since reverse engineering the asic itself is not viable. 
Food for thought.

**Comment by unknownbrackets** [comment]
Yeah, here are the samples I already pulled (from a simple tone):
[reverb_tone_samples.zip](https://github.com/hrydgard/ppsspp/files/7923644/reverb_tone_samples.zip)

-[Unknown]

**Comment by OCRBonk** [comment]
I'll try plugging these into a convolution reverb and see how they sound when I have a chance.

**Comment by OCRBonk** [comment]
So I gave these a shot and didn't quite work out right.
Perhaps how the impulse is generated needs some adjustment? (Maybe doing a sine wave sweep will produce a better result?)
Here's what one of the impulses sounded like full on wet.
https://drive.google.com/file/d/1r9OcyiUgkCexNzDwhuuLsZkqs2-d4C78/view?usp=sharing
Vs an impulse of a reverb unit
https://drive.google.com/file/d/17eWFVi8rNAYRIhEEnuELf2yNNUWlr2XD/view?usp=sharing
And for fun a Guitar Amp Cab
https://drive.google.com/file/d/1Dyiwx0RlKAKGuccm0zRvq_5dYYdJ1R5g/view?usp=sharing

**Pull request merged**
