### PR TITLE
Fix mouse scroll for key mapping

### LINKED ISSUE #11043: Mouse scroll doesn't work when mapped via mouse control
Mouse scroll doesn't work when mapped via mouse control on windows as reported in [here](https://forums.ppsspp.org/showthread.php?tid=24311), would take a look myself, but affraid I'm not going to have much time this week and was invited to a party in the weekend;p, might forget later without issue.

### PR DESCRIPTION
**Pull request by LunaMoo**
Fixes #11043 (which I totally forgot about;p ~ sorries)

### CODE REVIEW

**Comment by LunaMoo** [comment]
Please don't merge yet, it causes some weird wheel interaction in UI;c, I guess it needs that fix has to be limited to in-game similar to how mouse movement is.

**Comment by LunaMoo** [comment]
Heh, I think it's still bad overall, going to have to think about it more as it can get stuck.
 Does WM_MOUSEWHEEL is only called when a wheel event is passed? Or maybe something related to #11226

**Comment by LunaMoo** [comment]
As far as I tested this works fine now althrough may be a bit hacky. I set a variable in WM_MOUSEWHEEL event when wheel is "key_down" and check for that variable under default case to send "key_up".

 Moved WM_MOUSEWHEEL to DisplayProc as well, dunno what "some reason" was forcing it in WndProc, but works fine nowadays in DisplayProc.

 If this solution is acceptable I can squash the commits later.

**Comment by LunaMoo** [comment]
Heh I squashed, but it still sucks I need to release it elsewhere, default case in DisplayProc still requires some event to trigger I guess.

**Comment by LunaMoo** [comment]
Ended up using a timer using 16ms delay to ensure wheel is released on next frame even in 60 fps games. I think it's ready now.:]

**Comment by hrydgard** [comment]
Yeah, I suppose that'll be alright...

**Pull request merged**
