### PR TITLE
Added new Natural Colors PP shader (removed blur) 

### PR DESCRIPTION
**Pull request by Leopard20**
Fixes https://github.com/hrydgard/ppsspp/issues/10766.
Here's a couple of photos for comparison:

**Original Natural Color PP Shader**:
screenshot_2018-03-24-00-39-05-223_org ppsspp ppsspp

**Modified Version (called Natural Colors (No Blur) )**:
screenshot_2018-03-24-00-38-52-281_org ppsspp ppsspp

### CODE REVIEW

**Comment by leopard20** [comment]
Please let me know if I failed to alter some files in the process.

**Comment by LunaMoo** [comment]
Preferably you should not change existing natural colors at all to avoid messing people's configs and confusing them, including it's name. The blur was part of the original effect, so you should rather mention the new variant is blurless than changing old one to nc+blur :P

**Comment by leopard20** [comment]
Right! Let me change em again! 😩

**Comment by leopard20** [comment]
@hrydgard 
If you don't mind me asking, why do you use both Travis CI and App Veyor? Don't they both do the same thing?!

**Comment by LunaMoo** [comment]
Appveyor is for visual studio / windows builds while travis for everything else, it's common to break windows while developing for example on linux and the opposite, so it helps.
Neither appveyor or travis does anything for pr with no changes affecting build, so if you finished making changes I could merge this... BUT if that's not too much to ask would be nice if you squashed all your commits into a single one(if you're new with git, that's a good thing to learn anyway:P), since all of those commits are unnecessary clutter which just add more to git history for no reason.

**Comment by leopard20** [comment]
If things look good then sure you can merge it.

> would be nice if you squashed all your commits into a single one

Sorry I don't know how to do this!

**Comment by TheComputerGuy96** [comment]
@leopard20 https://stackoverflow.com/a/5201642

**Comment by leopard20** [comment]
Unfortunately I don't use Git. Any other solution?

**Comment by hrydgard** [comment]
Oh, are you doing this using the github text editor? :)  You better learn real git...  but I can squash it for you when I merge.

**Comment by leopard20** [comment]
Yeah. Thanks.

**Comment by marosis** [comment]
Thank you leopard20!@Hrydgard this is it what i wanted!:D

**Comment by marosis** [comment]
Now it is looks like Real PSP screen

**Comment by leopard20** [comment]
@marosis Glad you like it!

@LunaMoo @hrydgard @unknownbrackets 
It looks like the name is not correct though. It says NaturalA but it should be Natural Colors (No Blur). I won't make another pull request just one of you guys fix it. Thanks.

**Comment by vnctdj** [comment]
I really like it too, thanks @leopard20 :)

**Comment by leopard20** [comment]
@vnctdj 
You're welcom!

**Pull request merged**
