### PR TITLE
Backport some code from my UWP branch to keep it small

### PR DESCRIPTION
**Pull request by hrydgard**
Might as well get this in and tested.

This might help #9369  .

### CODE REVIEW

**Comment by hrydgard** [comment]
Actually this doesn't solve the whole problem for 9369, working on it.

**Comment by xebra** [comment]
This can't compile HW tess.

```
error X4016: SV_InstanceID semantic cannot be used with 10Level9 targets
error X3548: in vs_4_0_level_9_1 uints can only be used with known-positive values, use int if possible
```
Also "featureLevel_" is not initialized.

**Comment by moura464** [comment]
build working YES 1f609

**Comment by xebra** [comment]
Ah, my issues was caused by uninitialized "featureLevel_" and "vs_4_0_level_9_1" .
I confirmed it can compile with vs_4_0.

**Comment by hrydgard** [comment]
That's also what's causing trouble in #9361, working on a fix.

**Comment by xebra** [comment]
Fixed 👍

**Pull request merged**
