### PR TITLE
SaveState:Don't register the event during Dostate.

### PR DESCRIPTION
**Pull request by shenweip**
Fixes https://github.com/hrydgard/ppsspp/pull/13585#discussion_r512414877.

### CODE REVIEW

**Comment by hrydgard** [comment]
I'm a little confused here really. Why don't we just register the event once during init?

**Comment by shenweip** [comment]
Old savestates don't do state for the event, I want to make the old savestates work correctly.

**Comment by unknownbrackets** [comment]
This change makes sense to me.

@hrydgard to explain, imagine the following simple scenario:

I have two modules, each with one event:

sceCtrl: event 1 = ctrl publish event
sceDisplay: event 2 = vblank event

The IDs are included in the CoreTiming linked lists which are saved to RAM as numbers.  Now, I realize that there's more functionality in sceCtrl and I need another event.  So now Init runs:

 * __CtrlInit() runs:
     * event 1 = ctrl publish event
     * event 2 = new ctrl feature bugfix event
 * __DisplayInit() runs:
     * event 3 = vblank event

Next, I load my save state,  Now these steps:

 * SaveStart::Do() runs
 * CoreTiming::DoState runs
     * Event registry is wiped (because the IDs need to match the new world.)
     * A pending vblank (event ID 2) loads into the pending events linked list
 * __CtrlDoState() runs:
     * RESTORE event 1 = ctrl publish event
     * REGISTER NEW event 2 = new ctrl feature bugfix event
 * __DisplayInit() runs:
     * RESTORE event 2 = vblank event

So if we stop restoring, and just rely on Init, then the pending vblank will trigger my new ctrl event, and no more vblanks will ever happen.  Save state broken.

If we register a new event during DoState, then it'll get overwritten by the vblank event.  Good news: vblanks work and maybe my save state can limp along.  Bad news: my new ctrl event secretly triggers vblanks and weird bugs ensue.

Yes, we probably need some checks to make sure no one accidentally registers an event during DoState.  And maybe we could change the formatting for the future to use names or something in the CoreTiming objects (which names would have to be included in the registration), and then we could rely on the Init list.

-[Unknown]

**Comment by hrydgard** [comment]
Ahhh now I get it. Thanks unknown! 

Yes those steps would prevent some mistakes indeed.

**Comment by aliaspider** [comment]
do the event ids need to be part of the savestate in the first place ? ie. can't the event list be completely recreated in Dostate? unless the old event order is important somehow ...

**Comment by aliaspider** [comment]
ok, I see that the event list is referencing the registered ids which makes saving them necessary. but then again, if `event_types.size()` is saved in the state, doesn't that make `event_types.resize()` unnecessary in `RestoreRegisterEvent` ? because that seems to be the reason why calling `RegisterEvent` is currently unsafe for new events that are not present in the old state.

**Comment by unknownbrackets** [comment]
It just registers in order.  I don't think it'd be smart to get into some world where you have to type a random number and hardcode it.  And deleting types is of course possible (and has happened iirc), so relying on size won't work.

There's a list of pending events.  We need to know which events those are - it's important.  But unless we change all event types to be registered in a separate file and make sure to add the new ones last (which would be a pain itself and just generate this same sort of conversation and problem), the ids are essentially not deterministic from adds/removals.

-[Unknown]

**Comment by aliaspider** [comment]
ok deleted types would be a real problem. I assumed the stored size in a savestate version was always >= than previous versions.
too bad, otherwise the solution to all this would have been pretty simple ...

**Pull request merged**
