### PR TITLE
Update PixelDepthRounding list avoid flickering in Phantasy Star games

### PR DESCRIPTION
**Pull request by daniel229**
Affect Phantasy Star Portable 1 and Phantasy Star Portable 2 JP version and their demo.

### CODE REVIEW

**Comment by daniel229** [comment]
Don't know if we should remove Phantasy Star games from [VertexDepthRounding] list,it works fine without [VertexDepthRounding].

**Comment by hrydgard** [comment]
We'll probably remove VertexDepthRounding anyway in favor of our new type of pixel depth rounding.

**Comment by daniel229** [comment]
But other games not working well with pixel depth rounding,such as Puyo Puyo Fever 2,Power Stone Collection,Taiko no Tatsujin Portable DX,PhotoKano

**Comment by unknownbrackets** [comment]
Hmm, ULUS10410 can't be in both places, right?  And the text still needs either vertex or pixel rounding, otherwise it won't show up.

In GLES_GPU.cpp, try replacing this:

```c++
	if (fbo_standard_z_depth() > 16) {
		if (!g_Config.bHighQualityDepth) {
			features |= GPU_SCALE_DEPTH_FROM_24BIT_TO_16BIT;
		} else if (PSP_CoreParameter().compat.flags().PixelDepthRounding) {
			if (!gl_extensions.IsGLES || gl_extensions.GLES3) {
				// Use fragment rounding on desktop and GLES3, most accurate.
				features |= GPU_ROUND_FRAGMENT_DEPTH_TO_16BIT;
			} else if (fbo_standard_z_depth() == 24) {
				// Here we can simulate a 16 bit depth buffer by scaling.
				// Note that the depth buffer is fixed point, not floating, so dividing by 256 is pretty good.
				features |= GPU_SCALE_DEPTH_FROM_24BIT_TO_16BIT;
			} else {
				// At least do vertex rounding if nothing else.
				features |= GPU_ROUND_DEPTH_TO_16BIT;
			}
		} else if (PSP_CoreParameter().compat.flags().VertexDepthRounding) {
			features |= GPU_ROUND_DEPTH_TO_16BIT;
		}
	}
```

With:

```c++
	if (fbo_standard_z_depth() > 16) {
		const CompatFlags &flags = PSP_CoreParameter().compat.flags();
		if (!g_Config.bHighQualityDepth || flags.PixelDepthRounding || flags.VertexDepthRounding) {
			features |= GPU_SCALE_DEPTH_FROM_24BIT_TO_16BIT;
		}
	}
```

That will make it use the decreased range in all cases.  How well does that work for those games?

-[Unknown]

**Comment by daniel229** [comment]
Phantasy Star Portable 2 JP version still work fine with being in both place.ULUS10410 is maybe the same.
With the modified code,it's worse when only pixel rounding,Don'tshow up the text PhotoKano .

**Pull request merged**
