### PR TITLE
Refactor VRAM download, optimize rendered CLUTs

### LINKED ISSUE #8252: Brave Story crashed in boss fight
Since https://github.com/hrydgard/ppsspp/pull/8240 ,fixed in https://github.com/hrydgard/ppsspp/pull/8246

master build crash and color is wrong

with https://github.com/hrydgard/ppsspp/pull/8246 ,color is correct.

Stack trace

### PR DESCRIPTION
**Pull request by unknownbrackets**
This fixes #8252.  I set out to fix that and I ended up greatly improving the performance of Brave Story in battles with the CLUT download.

Turns out, we were downloading too much, and doing it over and over.  This optimization is huge for Brave Story, pretty much as good as #8246... but note that one without a bunch more work, that won't work with texture scaling.

Anyway, the only real downside of this is that it adds another flag that needs to be reset on every render.  I think the driver overhead is larger and this is fairly cheap, hopefully.

Improvement:
Boss battle (fairy complicated enemies): 192% -> 696%
Rabbit battle: 469% -> 745%

These changes don't prevent #8246, but for reference, the same numbers with that branch:

Boss battle: 640%
Rabbit battle: 800%

Based on the way the game renders (using a few different CLUTs for a set of textures that draw the enemy), we end up re-rendering several textures many times.  In the boss battle especially.  This is why the changes in this pull are actually faster for that example.

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
Great, but broken in kurohyo 2.
Start menu

**Comment by unknownbrackets** [comment]
Hmm, something wrong in 28a07c70c6786765bb12dae0658c2c76f5f2b2a3.

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, so this probably explains my troubles with this game in the other pull.  I assumed it would start the CLUT at x=0.  This one is using several CLUTs on the same row.

I already tried adjusting it to load using an offset, but I have a bug somewhere.  It only works if I download the full 384 bytes the first time... hmm.

-[Unknown]

**Comment by unknownbrackets** [comment]
D'oh, and right after I posted that I saw the typo.

-[Unknown]

**Comment by daniel229** [comment]
Broke brave story

**Comment by unknownbrackets** [comment]
Sorry, I'm doing a terrible job testing.  I just forgot to make sure it took the closest one, should be good now in both.

-[Unknown]

**Comment by hrydgard** [comment]
Hm, I'm sure I'm missing something, but why not look for an exact match?

**Comment by unknownbrackets** [comment]
Kurohyo loads from an offset X, so an exact match doesn't work.  It loads 64 pixels of bytes or something at the same interval from a framebuffer that is 1px tall.

In contrast, Brave Story uses multiple framebuffers right next to each other, at 0x400 bytes apart.

-[Unknown]

**Comment by unknownbrackets** [comment]
By the way, that's the same reason my on GPU stuff doesn't work for the game; since it never downloads the CLUT for the offsets, and doesn't match the framebuffer for them, those all render with a garbage CLUT.  I'm pretty sure applying this offset will help there, but have not done it yet.

-[Unknown]

**Comment by daniel229** [comment]
Look good now.

**Comment by hrydgard** [comment]
Ah I see, right.

**Comment by hrydgard** [comment]
@unknownbrackets Strangely, this badly breaks Ridge Racer on my S6 - lots of blackness and missing road. (To bisect back here I had to retroactively fix a bug where we would generate different shader versions for VS and FS).

**Comment by unknownbrackets** [comment]
What caused that was that `CheckGLFeatures()` was not called, so all the `gstate_c.Supports()` flags were wrong, because they assumed you have no gl extensions.  I don't think the stuff this touches even happens during Ridge Racer, at least not for me?

-[Unknown]

**Comment by hrydgard** [comment]
Well, reverting this merge fixes Ridge Racer, so somehow it does. But I agree, I don't think it downloads at all...

**Pull request merged**
