### PR TITLE
Update Roboto font

### PR DESCRIPTION
**Pull request by TacoTheDank**
Hey, I saw you hadn't updated your font in a while, so I decided to go and do that. This provides actually noticeable improvements on the typeface, and will subsequently make for a better UI e x p e r i e n c e.

You can use https://fontdrop.info/ to compare the old and new files and their data to see how they look. If you use Windows, you can also double click both of them, center the windows on each other, and ALT+TAB between them to compare (which is more easily noticeable compared to the fontdrop option).

The site where the font was obtained is here: https://fonts.google.com/specimen/Roboto+Condensed
The source code of Roboto is here: https://github.com/googlefonts/roboto

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Personally I like the old font better.  I didn't like the 2.x change.

But I guess it doesn't matter that much either way.

-[Unknown]

**Comment by TacoTheDank** [comment]
@hrydgard Any updates on this?

**Comment by LunaMoo** [comment]
Fonts should probably be renamed instead of versioned as this is basically a slightly different font with no real benefits for normal people and one major disadvantage of changing what people got used to.

 This is an open source project, nobody stops you from changing fonts, colors, icons towards what you like more, but why do you feel any need of applying your subjectivity over other users?

**Comment by hrydgard** [comment]
Personally I think the current font is just fine for the current look, updating it indeed has little benefit. 

If we  one day give the look of the emulator a big makeover, then we'll also change the font to match, probably.

**Comment by TacoTheDank** [comment]
Alright

**Comment by TacoTheDank** [comment]
> This is an open source project, nobody stops you from changing fonts, colors, icons towards what you like more, but why do you feel any need of applying your subjectivity over other users?

@LunaMoo 

This comes off as pretty rude and accusatory. Please watch the tone...

**Pull request closed without merging**
