### PR TITLE
An attempt at cleaning up the checks in ThreadUtil

### PR DESCRIPTION
**Pull request by hrydgard**
Had reported issues on some platforms.

### CODE REVIEW

**Comment by Sanaki** [comment]
No change on x86_64 Linux, but changing `return (int)gettid();` on line 152 to `return (int)syscall(__NR_gettid);` did resolve it for me. That said, I harvested that solution from elsewhere, I don't know enough about the implications of it to feel comfortable submitting a PR myself in this case.

**Comment by hrydgard** [comment]
Baffling to me, as far as I understand, defining _GNU_SOURCE should make gettid() available.

I'll change it to the syscall.

**Comment by FridgeRacer** [comment]
> No change on x86_64 Linux, but changing `return (int)gettid();` on line 152 to `return (int)syscall(__NR_gettid);` did resolve it for me. That said, I harvested that solution from elsewhere, I don't know enough about the implications of it to feel comfortable submitting a PR myself in this case.

Thanks! Cloned and tried to build PPSSPPSDL on my Nintendo Switch (Ubuntu 18.04) today but had the same error, this allowed me to progress past it.

**Comment by hrydgard** [comment]
I've merged the fix. Though it's still weird.

**Comment by Sanaki** [comment]
No argument there. Thanks.

**Pull request merged**
