### PR TITLE
 SaveState: Show warning on old / long use state

### PR DESCRIPTION
**Pull request by unknownbrackets**
This does a few things:

1. Starts tracking the *initial* PPSSPP version used for a save state (not just the latest to save it.)  May be useful for debugging too.
2. Shows a warning message if the initial PPSSPP version is less than the current PPSSPP version.
3. Shows a warning message if a save state has been cycled (loaded, saved, loaded, saved) for >= 10 times, every 5th time.  The goal is to detect using save states instead of save games for long term.
4. Shows save state related errors and warnings for longer than 2s.
5. Adds an ini-only config setting in case these warnings cause people to [freeze during winter](https://xkcd.com/1172/).

This is common guidance on the forum when users report issues, but might as well tell everyone - not just the special few who ask for help.  Used the same message after some consideration, to make translations easier and keep it terse.

Also, in case of features like #8661, it might become even more common to replace in game saves with save states.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm. I like the version tracking, but I can see this getting annoying when people use states repeatedly to get through tricky levels, instead of saving progress. Also, doing a regular save should maybe reset the counter?

In addition, I'm not sure how much I like the "for less bugs" wording, it kind of implies that bugs are inevitable. There are many games (most?) in which using save states is actually pretty much rock solid, barring accidental overwriting of states... Sure there are games that have bugs where you can't actually complete the game if you don't save properly and reload the game few times, but those are rare.

**Comment by leopard20** [comment]
I agree with Henrik. It is annoying to some people. And not everyone knows how to change config settings! (particularly phone users)
Probably you should make the option more accessible if you finally decide to add it.

**Comment by unknownbrackets** [comment]
10 cycles is a lot, though.  Just to make sure we're speaking the same language:

1. I start up a game, and load an in-game save.  In the past, I've used save states a lot, but I don't load one now.  LEVEL: 0

2. I get to a tricky jump or level, so I save state.  LEVEL: 1

3. After messing up, I load state.  I'm bad at this jump, so I keep trying, loading state over and over.  It ends up taking me no less than 12 tries to get it right, each time loading state again.  LEVEL: 1

4. Satisfied that I finally got past this, I save state again.  LEVEL: 2

5. I finish the level, and save in game.  LEVEL: 2

6. I quit the game and come back to it tomorrow, loading my in game save.  LEVEL: 0

I'm sure any message can be annoying, but bugs can be annoying too.  And we're not going to go out and fix the bugs in games that crash after a super long play session (I'm pretty sure Persona 3 has such a bug, for example.)

I would argue that bugs are *definitely* inevitable if you use, and only use, save states.  Perhaps I'm less inclined to believe that there's a PSP game that's perfect and has no bugs or leaks in its code than you are.

Perhaps it would settle the concerns to use time instead?  If a play session using save state cycles lasts > 3 hours, for example?  Originally avoided time because of fast forward and other things.

-[Unknown]

**Comment by unknownbrackets** [comment]
No one reads TLDR warning messages, though.  If they're not gonna care about the short message, a longer message won't help either.

-[Unknown]

**Comment by unknownbrackets** [comment]
I made it check based on time now - 4 hours of continuous virtual runtime, and at least 2 save/load cycles.  Just to say reiterate:

 * The message is intentionally short.  People who don't care will easily ignore it, which is fine.  People who care will read it and benefit.  I'd rather keep it simple and unobtrusive than build an AI algorithm and game ID list to guess when exactly is the most ideal time to show a complicated, hard to digest message.

 * While there's nuance, I don't think it's worth making it paragraphs of hard-to-translate text to explain the situation in detail.  People will Google if they want to know, that's the world we live in.

 * We are talking about a short line of text that displays for 5 seconds at the top of the screen.  If it's a big problem, I would argue that the "internal resolution" message is at least as, if not more, annoying - and often not as useful.  Does it need a checkbox to prevent it from showing more than once?

-[Unknown]

**Comment by hrydgard** [comment]
Alright, seems unobtrusive enough. Let's merge.

**Pull request merged**
