### PR TITLE
Use MEMSIZE SFO param to detect 64MB homebrew

### LINKED ISSUE #2183: Killzone Liberation crash on intro (PSP-2000 allows too much memory)
The game crash on intro

OS:Windows 7 32 Bits
Emu : ppsspp-v0.7.6-1249-gdd41d4a-windows-x86
log : http://pastebin.com/rW2EqunA

### PR DESCRIPTION
**Pull request by unknownbrackets**
Now, use 32MB for normal games even in PSP-2000 mode, which is how real firmware behaves.

Warning: this may impact cheats with default settings.  But it only moves closer to accurate with real firmware.

Fixes #2183.

-[Unknown]

### CODE REVIEW

**Comment by VIRGINKLM** [comment]
I'm pretty sure in Ad-Hoc mode Final Fantasy Type-0 uses the whole 64MB range, it was the reason it doesn't work on PSP-1000.

**Comment by unknownbrackets** [comment]
A simple JpcspTrace would likely prove that it starts up with 32MB like any game, and probably uses the other 32MB for UMD cache like any other game.

It may simply be that for performant network play, it needs this UMD cache to exist (otherwise there would be huge UMD delays when it tries to load certain things, which might desync the network play.)

That being said, there may be ways to request memory from other partitions or access the other memory somehow.  That being said, even the aliased partitions are normally < 32MB on the PSP-2000.

-[Unknown]

**Comment by LunaMoo** [comment]
Cheats aside - would be nice to leave an option(ini only would be ok) to restore previous functionality as it's usefull for some other things, like certain mods or jp->en translations that couldn't be done on real hardware without plugins if at all.
 Can't give any existing/popular example, but found that feature pretty usefull in the past myself when importing english translation to japanese game from pc port to psp game where the english script just couldn't fit in 32mb.

**Comment by unknownbrackets** [comment]
If you want it to work on a real PSP's CFW, you'd need to include the MEMSIZE flag anyway.  I don't see a reason to motivate translators to require users to fumble around in options, rather than specify it the correct way anyway.

Perhaps we could even provide PPSSPP-specific SFO params to request a specific amount of memory, if it's common.  But I don't think it's useful as a user option - it's not a user option even in CFW.

-[Unknown]

**Comment by LunaMoo** [comment]
How to add that flag to a commercial game then? Just add "MEMSIZE" to the end of PARAM.SFO or something alike?
 Editing param.sfo just for 64mb would be fine for my needs just don't know how it should be done. I don't really think it's that common as most people care about psp support when starting to do anything for psp games, I just don't as I mess around with a lot of things that will never see a sunlight;p.

**Comment by unknownbrackets** [comment]
The PSPSDK generally does this by defining `PSP_LARGE_MEMORY=1`, which results in `mksfo -d MEMSIZE=1` or something.

But yes, an SFO is just a key/value table, so MEMSIZE just needs to be added to it, and it must have the value exactly 1 (CFW also shares this requirement.)  This was only supported for PBPs (I'm not sure how/if it works for ISOs on CFW...)

I've just added that, though.

-[Unknown]

**Comment by LunaMoo** [comment]
Thanks for the extra support:), in the meantime downloaded leecherman's param.sfo editor which has a template for it so doesn't even have to type it in.:]

**Comment by unknownbrackets** [comment]
Also added a fix for #5030, it's kinda relatedish to some of these changes.

-[Unknown]

**Pull request merged**
