### PR TITLE
Ad hoc: Band-aid fix for clear peer list. Should fix #7331

### LINKED ISSUE #7331: [Ad Hoc] Player leave detection
It seems that PPSSPP doesn't detect correctly when another player leave ad hoc / close his PPSSPP.
Here is an example :
There is 2 players in the Gathering Hall.
Player 1 close his PPSSPP.
The screen of player 2 still shows that player 1 is here, even if its debug log is showing that player 1 has disconnected.

When I enter the Gathering Hall :
enter
When I leave the Gathering Hall :
leave
And even this one that has appeared when I closed PPSSPP :
leave2

### PR DESCRIPTION
**Pull request by tywald**
This is a temporary solution.

### CODE REVIEW

**Comment by hrydgard** [comment]
I haven't done much with the peer code, but there must be a reason someone commented those lines out. Is this well tested with multiple games? If so I'm fine with merging.

**Comment by LunaMoo** [comment]
This was commented out with https://github.com/hrydgard/ppsspp/commit/1c7152db3ac254a5f8739419c82be42c1319532d 
which was part of #7264

 Hate the fact that soo much things in this code are commented out without actual comment on reason... Just a guess, but maybe some games are disconnecting too early hence it was disabled to make it playable as improved compatibility was primary reason behind people wanting that pr to be merged.

 Feels risky to merge right before release.

**Comment by tywald** [comment]
Unfortunately I have only tested with Monster Hunter games, they work at least. During a multiplayer session it should be working normally as before because they are only called when you disconnect, sceNetAdhocctlDisconnect(). So it shouldn't remove any peer prior to that.

I checked if deleteFriendByIP() could cause an exception if friends == NULL but luckily the for-loop only runs when it's != NULL.

Code wise it doesn't seem to be a problem but who knows what the games can do.

**Comment by adenovan** [comment]
Game that not affected by this pull request 
- Monster Hunter Freedom Unite
- Monster Hunter Portable 3RD
- God Eater Burst
- God Eater 2
- Yu-Gi-Oh! 5D's Tag Force 6

**Comment by hrydgard** [comment]
@adenovan  How do you feel about this pull request? I don't do much network gaming but if you've tested it with a lot of games, I'm fine with merging this. Code-wise, it seems correct.

**Comment by adenovan** [comment]
@hrydgard i feel this PR is safe to merge because almost all of my games work without problem but it still a few list of game if compared with adhoc compability list on forums. i will ask facebook openvpn comunity to do more test on game that i didn't have. so i can list what game call this cleared peer list function and break the networking that works before. this pull request is really needed for Monster Hunter game because #7331 is really an annoying bug specially for playing online with random people. the list on my previous comment will be updated for the info what game work and what game broken by this PR.

**Comment by tywald** [comment]
@adenovan Just poking to check if there has been more tests recently. 

What kind of games that many people play which are not on the list above are left to be tested? I assume Tekken 6 should be checked before concluding. It seems good so far, no broken games yet.

**Comment by hrydgard** [comment]
Let's go for it and see if there are complaints instead, at this point.

**Pull request merged**
