### PR TITLE
CMakeLists: relocate EGL library name detection

### PR DESCRIPTION
**Pull request by psyke83**
Raspberry Pi targets require a custom EGL library name (configured in cmake/Toolchains/raspberry.armv*.cmake). Move configuration of EGL_LIBRARIES for generic targets out of SDL2 target to ensure correct library name is used everywhere (including QT builds).

Fixes build on Raspberry Pi.

### CODE REVIEW

**Comment by psyke83** [comment]
FYI, with this PR, ppsspp builds successfully, but it won't launch on my Raspberry Pi 3:

```
Parameters:
Executing: /opt/retropie/emulators/ppsspp/PPSSPPSDL "/home/pi/RetroPie/roms/psp/Castlevania Dracula X Chronicles [U].iso"
39:43:469 Core/Config.cpp:1051 I[LOADER]: Loading controller config: /home/pi/.config/ppsspp/PSP/SYSTEM/controls.ini
39:43:943 Core/Config.cpp:1137 I[LOADER]: Config saved: /home/pi/.config/ppsspp/PSP/SYSTEM/ppsspp.ini
39:43:945 Core/Config.cpp:1150 I[LOADER]: Controller config saved: /home/pi/.config/ppsspp/PSP/SYSTEM/controls.ini
I: Config.cpp:440: Longest display side: -1 pixels. Choosing scale 1
I: NativeApp.cpp:445: Boot filename found in args: '/home/pi/RetroPie/roms/psp/Castlevania Dracula X Chronicles [U].iso'
SDL_CreateWindow failed: Could not initialize OpenGL / GLES library
I: NativeApp.cpp:1140: NativeShutdown called
```

I haven't compiled a ppsspp build in some time, so I'm not sure when this problem started happening. Will try to investigate the issue.

**Comment by psyke83** [comment]
Update: this commit is the cause of the launch failure: https://github.com/hrydgard/ppsspp/commit/66832d2180e3c299da9722c0efde473bf5304785

**Comment by unknownbrackets** [comment]
Ah, so on Raspberry Bi is failing on SDL_CreateWindow.

Does it work to replace this?

```c++
			NativeShutdown();
			fprintf(stderr, "SDL_CreateWindow failed: %s\n", SDL_GetError());
			SDL_Quit();
			return 2;
```

With `continue;`?  So that `if (g_Screen == nullptr) {` just continues?

-[Unknown]

**Comment by psyke83** [comment]
No, it doesn't work, because the fallback profile creation also doesn't work on Pi. I've got a patch that I've tested against the faulty commit; I'm just retesting it against to master to be 100% sure before submitting the PR.

**Comment by psyke83** [comment]
OK, confirmed to be working fine, so... https://github.com/hrydgard/ppsspp/pull/10423

**Review by unknownbrackets — APPROVED** [review]

**Pull request merged**
