### PR TITLE
Change hyphen to dash

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by hrydgard** [comment]
Not sure I see the point for such an obscure error message.

**Comment by TotalCaesar659** [comment]
I wanted to get all these hyphens in translations to uniformity. As for perfectionist, it hurts my eyes)) But OK, you're the boss, you can close it then.

**Comment by unknownbrackets** [comment]
If we're changing the translation key anyway, I'd just as soon remove the hyphen/dash entirely...

-[Unknown]

**Comment by Chriszxz** [comment]
> I wanted to get all these hyphens in translations to uniformity. As for perfectionist, it hurts my eyes)) But OK, you're the boss, you can close it then.

*I wanted to get all these hyphens in uniform to translations. As a perfectionist, it hurts my eyes. But OK, you're the boss, you can close it then.

If you are a perfectionist why don't you study grammar first? Lmao.

**Pull request closed without merging**
