### PR TITLE
Add option to slow down mouse wheel to closer resemble button presses

### LINKED ISSUE #18564: Speed up the mouse wheel
### What should happen

 I noticed that the buttons are faster compared to the mouse wheel

### Who would this benefit

PPSSPP

### Platform (if relevant)

Windows

### Games this would be useful in

PPSSPP

### Other emulators or software with a similar feature

_No response_

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

### PR DESCRIPTION
**Pull request by LunaMoo**
Should fix #18564
Default is unchanged, add's an option to delay it.

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm, this will only work on Windows. 

Maybe we can rework this to a more cross-platform solutions by doing some simple state tracking in NativeKey ?

**Comment by LunaMoo** [comment]
Hah, sorry just followed wheelUp and forgot MainWindow is for windows, have to look how wheel is handled outside of platform specific code. Anyway the person requesting it might at least test if that's what he wants, because there's a bit of confusion there about mouse wheel being slow when it's imo more about the opposite.

**Comment by hrydgard** [comment]
Yeah, good point about testing first.

**Comment by LunaMoo** [comment]
Hmmm... not sure how to make it the way you said, I tried delaying it in NativeKey, but then if I just stop controlling the game it'll freeze in the state it was in since it stops updating.^_^; Anyway I'm going to family birthday soon, so will keep this on hold.

**Comment by hrydgard** [comment]
You're gonna need to put one part of it in NativeFrame as well.

I can take care of it.

By the way, how meaningful do you think it is to have a setting? Maybe it would be alright to just do 0.1ms, most games should catch that. And if a second event comes in during that time, we'll just send a KEY_UP directly followed by a new KEY_DOWN.

**Comment by hrydgard** [comment]
I made https://github.com/hrydgard/ppsspp/pull/18568 to replace this, have a look @LunaMoo .

**Comment by hrydgard** [comment]
Because I've merged #18568, I'm closing this.

If a setting for the timer delay is still required, we can just copy it over from there.

**Pull request closed without merging**
