### PR TITLE
UI: Implement a glowing border touch control style

### PR DESCRIPTION
**Pull request by unknownbrackets**
Sorta like #5624, but not really the same because it barely glows.  Just brighter and with a background.  Didn't want to implement complicated bloom or color effects...

I kinda prefer this though, as I like it not covering up even more than my fingers already cover.  When they double in size, sometimes I slip off them because I don't realize where their edges are, too.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Nice, I'm gonna check what this looks like and probably merge later.

**Comment by hrydgard** [comment]
Yeah as you say the glow is pretty small and mostly invisible when touching the buttons on an actual touchscreen. But seems fine to me, some people may prefer it.

Maybe I'll later add a version with a larger glow - but I won't do it using glow effects, just a larger semitransparent blob underneath.

**Comment by marosis** [comment]
It is cool.

**Comment by Emulatorer** [comment]
Can you add this color theme in the button style because it's refreshing in eyes ☺
screenshot_2018-10-19-17-46-56
it's a bug happen when I installed ppsspp 1.6.3 from playstore after uninstalling the beta build.

**Pull request merged**
