### PR TITLE
Swap depth range to use minz/maxz

### LINKED ISSUE #8424: MotoGP graphical artifact
Since https://github.com/hrydgard/ppsspp/pull/8376

before

### LINKED ISSUE #8456: Crash Mind over Mutant does not show anything except the videos.
When booting the game, nothing but the movies showing the companies that made the game will show. The game still seems to play fine, as you can here things like Crash's footsteps and the menu noises, but the screen will be completely black
[ppsspplog.txt](https://github.com/hrydgard/ppsspp/files/94922/ppsspplog.txt)
Using Version - ppsspp-v1.1.1-736-g14fb4f2-windows-amd64
Video - https://youtu.be/e1joKQIzhcU

### PR DESCRIPTION
**Pull request by unknownbrackets**
This does a few things:
1. Properly supports minz/maxz by using them as the depth range.
2. Flushes when clipEnable changes.
3. Sacrifices some bits of precision to allow for "fake clamping" of the depth range when clip is enabled.  Currently, I've sacrificed 2 bits allowing depth between [-2.5, 2.5].

This actually fixes MotoGP for me (would be nice to confirm), since it is using clipEnable, and therefore clamping the depth.

Some flaws (not sure if important):
- Still does not handle rounding per my tests; e.g. without clip enabled, cuts off at precisely [0, 65535].  Not worse than before.
- Per-vertex depth rounding comes out with slightly offset values.  I'm not sure if this is just a precision issue, or if I've made an error.  But they are close and Phantasy Star Portable 1 works.
- Per-pixel depth rounding is potentially wrong now; but I couldn't get it to come out right (tried applying offset and scale.)  Phantasy Star Portable 1 still works as-is if per-pixel is forced.

Could use help on the per-pixel rounding.  This is what I tried:

``` c++
    if (gstate_c.Supports(GPU_ROUND_FRAGMENT_DEPTH_TO_16BIT)) {
        const float offset = 0.5f * (DepthSliceFactor() - 1.0f) * (1.0f / DepthSliceFactor());
        const double scale = DepthSliceFactor() * 65535.0;
        WRITE(p, "  highp float z = gl_FragCoord.z;\n");
        WRITE(p, "  z = floor((z - %f) * %f) * %f + %f;\n", offset, scale, 1.0 / scale, offset);
        WRITE(p, "  gl_FragDepth = z;\n");
    }
```

Anyway, this seems like an improvement otherwise.

Fixes #8456 and fixes #8424.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Cool. Getting this tested with Heroes Phantasia might be a good idea if pixel depth rounding has changed..

**Comment by hrydgard** [comment]
Seems to work well in all the games I tried.

**Comment by daniel229** [comment]
Heroes Phantasia missing menu.


disable pixel depth rounding,menu appearing, but it will flicker badly.

**Comment by daniel229** [comment]
Where is DepthSliceFactor()

**Comment by unknownbrackets** [comment]
Sorry, add this to GPUStateUtils.cpp:

```c++
float DepthSliceFactor() {
    return depthSliceFactor;
}
```

And then GPUStateUtils.h:

```c++
float DepthSliceFactor();
```

-[Unknown]

**Comment by daniel229** [comment]
Pixel depth rounding works with that code,and even flicker less than before.

**Comment by daniel229** [comment]
That modified per-pixel rounding code make Phantasy Star Portable 2 JP missing text.

**Comment by unknownbrackets** [comment]
Turns out the issue was precision.  I've changed it to something simpler.

Also, how does Heroes Phantasia fair with `static const float depthSliceFactor = 256.0f;` instead of 4.0f?

-[Unknown]

**Comment by daniel229** [comment]
Phantasy Star Portable 2 JP now flicker even with PixelDepthRounding.
For Heroes Phantasia 256.0f seems not better or worse than 4.0f

**Comment by unknownbrackets** [comment]
If you change `depthSliceFactor` to `1.0f` does Phantasy Star Portable 2 JP stop flickering?  Or does it still flicker?  Does 256 help it, either?

-[Unknown]

**Comment by daniel229** [comment]
Never mind,just forgot  add game id to the list,it works fine.

**Comment by unknownbrackets** [comment]
Ah, great.  So then sounds like pixel rounding is working fine now, and this fixes a few bugs otherwise.  Yay.

-[Unknown]

**Comment by hrydgard** [comment]
@daniel229 please send pull requests with any missing game ids :)

**Comment by daniel229** [comment]
Fixed a minor issue in Danball Senki W.

**Comment by unknownbrackets** [comment]
That's probably the minz/maxz clipping.  Cool.

-[Unknown]

**Pull request merged**
