### PR TITLE
Vulkan: Skip flips, not draw, for vsync fast-forward

### PR DESCRIPTION
**Pull request by unknownbrackets**
When you have vsync enabled on Vulkan, it's harder to temporarily disable it.  Because of this, we previously forced frameskip during fast-forward.

Of course, this has the problems described in #13546.  We should actually use the same flip skipping we now use by default for all other fast-forwarding, which works just as well.  This has fixed bugs in other games, so I don't want people using vsync + Vulkan to confusingly report those bugs are not fixed for them.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Small risk here: a device with a normal refresh rate below 60 would potentially also start using the skip flip mode.  That's not exactly a bad thing.

-[Unknown]

**Comment by hrydgard** [comment]
The old comment that Vulkan doesn't support it is inaccurate, it's possible with some careful swapchain management. 

However, this is definitely still the way to go.

**Comment by unknownbrackets** [comment]
The vsync flag is off by default, and cannot be enabled in the UI on Android.  We use VULKAN_FLAG_PRESENT_MAILBOX or VULKAN_FLAG_PRESENT_FIFO_RELAXED on Android.  That said, vsync can be enabled in the ini on Android.

So this should mainly only affect desktop Vulkan.

-[Unknown]

**Comment by hrydgard** [comment]
One of the issues with switching from skips to no-flip is that if the game was close to being GPU-limited before, there simply will be not much of a speedup. But maybe that's OK, and certainly better than errors...

Eh, I'll just merge.

**Pull request merged**
