### PR TITLE
(Libretro) Add optimal input read codepath - bitmasks

### PR DESCRIPTION
**Pull request by inactive123**
This is an optimal codepath for libretro that allows us to grab the entire button state (sans analogs) in one function call instead of having to query a function callback for each individual button. It also has a fallback path for libretro frontends that don't implement this environment  callback.

### CODE REVIEW

**Comment by hrydgard** [comment]
I don't mind this at all, but if you check the diff here on github, you see that there's something quite wrong with the tabs and spaces here. Fix it up and I'll merge :)

**Comment by twinaphex** [comment]
We follow different code formatting conventions for libretro - 3 spaces for tabs et all. I have this setup in Vim and all.

Would you mind if I just change everything in libretro.cpp to follow this same convention then?

**Comment by hrydgard** [comment]
I'm ok with a separate convention as long as it stays in the retro folder. But I'd suggest maybe converting on a function by function basis as you touch them, to not make huge diffs. Every other line in a different convention makes the diffs too hard to read.

**Comment by twinaphex** [comment]
Fair point. I'll follow the style conventions of PPSSPP in all files outside of the libretro/ dir.

**Comment by twinaphex** [comment]
I'll change the other files in libretro/ on an as-per needed basis, i.e. when I need to make edits to them.

Hopefully this is sufficient for now.

**Comment by hrydgard** [comment]
I'm ok with that.

Though honestly it's not that hard in vim to setup to have different conventions in different folders...

**Comment by twinaphex** [comment]
We'll definitely do that for the files outside the libretro folder.

**Comment by twinaphex** [comment]
So to confirm, this is ready to go or does something still need to be done on my end?

**Pull request merged**
