### PR TITLE
Add define hleLogNOTICE and hleReportNOTICE

### PR DESCRIPTION
**Pull request by sum2012**
fix compile on scemp3

### CODE REVIEW

**Comment by sum2012** [comment]
oop,still have more error

**Comment by sum2012** [comment]
done

**Comment by unknownbrackets** [comment]
Can we use Notice for consistency with the others?  I know it's NOTICE_LOG, but these behave more like functions (returning values) which is why I gave them camelCase names.

Is this for an upcoming update to sceMp3?

-[Unknown]

**Comment by sum2012** [comment]
I know what 's wrong with me now.
I replaced Debug to NOTICE this file.
So that hleLogDebug become hleLogNOTICE 
Closing

**Comment by sum2012** [comment]
I just want to debug crazy taxi with scemp3.
No finding

**Pull request closed without merging**
