### PR TITLE
Add second alternate speed and buttons for alt speed

### PR DESCRIPTION
**Pull request by unknownbrackets**
This refactors a bunch of things along the way.  The more user facing things are:

1. There are now two alternate speed settings.  Each can be disabled.
2. Speed toggle cycles through alt speed settings (normal -> alt speed 1 -> alt speed 2 -> normal.)
3. There are two new buttons for "alt speed 1" and "alt speed 2".  These function like "unthrottle" in that the speed is applied while they are pressed.
4. The "speed 1" and "speed 2" buttons are also available as touch buttons.

I think this should satisfy the needs in #7981, at least generally.  Rather than change unthrottle (which does what it says and is simple), to me it makes more sense to make the alt speed option more versatile as the above.

There's also some more behind the scenes changes:
1. Moved some config values into ConfigValues.h - a lot of places didn't use enums, or have hidden away enums, and I feel like this will encourage us to write cleaner code (since ConfigValues.h is included far less places.)

2. All the touch control related settings are now grouped in structs, which makes the code simpler and repeat less.  There's still parts that could be better, but at least it's much easier to add a new button now.

3. Made the touch control visibility page use more consistent UI with touch control layout and fixed a leaked class per checkbox.

4. Sorts the touch control visibility list as it was probably intended to be sorted (otherwise "Alt speed 1" would be first.)

5. Removed old pre-0.9.8 or so touch control layout config migration code.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Oh, the buttons are kinda uninspired right now, just 10 degree upward arrow and 10 degree downward arrow.  I'm no artist.  Showing a 1 and 2 in them sounded worse...

-[Unknown]

**Comment by hrydgard** [comment]
Cool, will read the code soon. My only immediate objection is that buttons/controls that cycle through more than two settings often feel awkward and confusing to use, and if one of the speeds is super fast can easily skip forward much more than intended by accident trying to toggle back to normal speed for example.

**Comment by unknownbrackets** [comment]
There's no cycle touch button - there's only two buttons for activating each speed.

You can however map a gamepad / keyboard button to toggle between the speeds (same toggle button as before.)  If the second speed is disabled (as is true by default), it continues working as before: toggling on and off the first alternative speed.

That has never had a touch button, though.

-[Unknown]

**Comment by hrydgard** [comment]
Ah, I missed that disabling the speeds would remove them from the cycle. That should be alright then as it's easy to set it up with a single alternate speed too.

**Comment by unknownbrackets** [comment]
What do you think?  I'd like to recommend that #11202 add an enum to ConfigValues for the magic numbers, but it doesn't exist yet.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, sorry for the delay, I'm fine with this. Will just read through it again then merge.

**Pull request merged**
