### PR TITLE
Update ja_JP.ini

### PR DESCRIPTION
**Pull request by nishinji**
image
In Japanese, the order of the contents of %d is reversed
ex.
A of B
BのA
Please solve this issue.

### CODE REVIEW

**Comment by hrydgard** [comment]
Oh, silly mistake. I'll make a fix so you can use %1 and %2.

**Comment by hrydgard** [comment]
I'm gonna get https://github.com/hrydgard/ppsspp/pull/18308 in first, then you can update this to match.

**Comment by nishinji** [comment]
@hrydgard done.
If you don't like the fix commit, i can discard it.

**Comment by hrydgard** [comment]
It's alright.

**Pull request merged**
