### PR TITLE
Some function replacements in some games

### PR DESCRIPTION
**Pull request by daniel229**
Fixes background and saveicons in some games.

 "Rewrite Portable"
https://cloud.githubusercontent.com/assets/3481559/5625548/31f7291a-95b8-11e4-92eb-b604faf67008.png

Kud Wafter
https://cloud.githubusercontent.com/assets/3481559/5625551/5681d1ea-95b8-11e4-93ce-f71a1f178106.png

Amatsumi Sora ni Kumo no Hatate ni
https://cloud.githubusercontent.com/assets/3481559/5625552/5ceee2e8-95b8-11e4-88a5-b4f86e8d684f.png

Sangoku Koi Senki Otome no Heihou
https://cloud.githubusercontent.com/assets/3481559/5625556/7042ddae-95b8-11e4-9598-2da30a49bc7e.png

Grisaia no Kajitsu La Fruit de la Grisaia
https://cloud.githubusercontent.com/assets/3481559/5625561/7d363ccc-95b8-11e4-8758-9e8a2238a38d.png

Kokoro Connect Yochi Random
https://cloud.githubusercontent.com/assets/3481559/5625563/82cbdc00-95b8-11e4-9fb1-a2d5c7f86e3c.png

To Heart 2 Portable
https://cloud.githubusercontent.com/assets/3481559/5625567/8d2bc3b8-95b8-11e4-82d8-27c7d7bb0c96.png

### CODE REVIEW

**Comment by unknownbrackets** [comment]
I think you could hook Rewrite higher and just use A0 (before li a0, 0x50.)  Doesn't really matter, just reading from sp makes me worry it's an unrelated function.  Kud Wafter also, in fact it's also an 0x50.

For Amatsumi Sora ni Kumo no Hatate ni, it's also a0 at the top of the function I think.

To Heart 2 could also be A1.  Doesn't really matter but that's the arg the caller is passing in, so a tiny bit clearer imho.

None of those really matter, it's probably fine as is.

-[Unknown]

**Comment by daniel229** [comment]
Rewrite, Kud Wafter and Amatsumi Sora ni Kumo no Hatate ni won't work,if change that,Maybe need find another functions?

**Comment by unknownbrackets** [comment]
Hmm, really?  Is the value it stores to 0(sp) from a0 not the same one you read in later from sp?  It doesn't seem to be passing a pointer into the function it calls.

But, well, I have not looked hard at all these funcs but they all generally look like they are the ones reading the vram.

-[Unknown]

**Comment by daniel229** [comment]
Yes,They are the same value.

**Comment by daniel229** [comment]
Did a misktaken sorry.

**Comment by sum2012** [comment]
Thanks @daniel229 
Anyay,is there are guide for make function replacement ?  (write in wiki better)

**Comment by daniel229** [comment]
@sum2012 I usually set a breakpoint address 0x04088000 size 88000 or  adress 0x04000000 size:200000 before where the game has problem,and then go to there,it hit an instruction in a function,remember that reg in the instruction,if the reg is in a loop,just trace back to outside a loop find another reg which pass the value to it.Usually just need to fill the reg and the buffered size in the function something like the following in ReplaceTables.cpp,

```
static int Hook_rewrite_download_frame() {
 const u32 fb_address = currentMIPS->r[MIPS_REG_A0];
 if (Memory::IsVRAMAddress(fb_address)) {
 gpu->PerformMemoryDownload(fb_address, 0x00088000);
 CBreakPoints::ExecMemCheck(fb_address, true, 0x00088000, currentMIPS->pc);
 }
 return 0;
}
```
and add one to ReplacementTableEntry entries[],the offset is the distance from head of the function to the address that you replace.1 instrution is 4 bytes.
```
{ "rewrite_download_frame", &Hook_rewrite_download_frame, 0, REPFLAG_HOOKENTER, 0x5C },
```

In PPSSPP.ini,set FuncHashMap = True
Right click the function in the disambly,and then rename the function, quit PPSSPP,a function hash would find in \MemStick\PSP\SYSTEM\knownfuncs.ini ,add someting like the following to MIPSAnalyst.cpp
```
{ 0xd1db467a23ebe00d, 724, "rewrite_download_frame", }, // Rewrite Portable
```

**Pull request merged**
