### PR TITLE
Update Simplified Chinese

### PR DESCRIPTION
**Pull request by Narugakuruga**
Use 🛆☐◯╳ to replace words. Not sure if this can display on phones 

I will test on my 7 year old Redmi 4 after merged

### CODE REVIEW

**Comment by hrydgard** [comment]
"Use 🛆☐◯╳ to replace words" << what does this mean?

**Comment by Narugakuruga** [comment]
> "Use 🛆☐◯╳ to replace words" << what does this mean?

Triangle Square Circle Cross. 
Apparently 🛆 is not available on old phones. I will change to △

**Comment by hrydgard** [comment]
Heh. On Mac that looks like 

image

**Comment by Narugakuruga** [comment]
Okay. so switch back to words now. Maybe it's some system font coding issue....

**Comment by hrydgard** [comment]
I think those characters are just not very commonly supported ones.. Oh well.

**Comment by unknownbrackets** [comment]
Yeah, those symbols are not widely supported.  🔺 is a triangle that's pretty widely supported but its color may be confusing.

You can search for them online, i.e. here: https://emojipedia.org/triangle-with-rounded-corners/ (which shows how limited the support is for that one.)

-[Unknown]

**Pull request merged**
