### PR TITLE
Improves depth clamping simulation

### PR DESCRIPTION
**Pull request by shenweip**
Some differences after this change:
- Reverse Z acts as an independent feature instead of being included in accurate depth.(Makes opengl enable depth clamping simulation)
- Depth silce factor is setted to 1.0 if depth clamp disabled.
- Not rescale Z when clearing Z-buffer(Not sure this).

Helps #7932, in opengl and dx9 backend, if do rescale Z when clearing Z-buffer, the "black screen" will always be front, and start menu(out of depth range) doesn't pass depth test even if be clamped to depth range.

### CODE REVIEW

**Review by unknownbrackets — COMMENTED** [review]
Depth is complicated on the PSP and if we want to add another path, I'm fine with that.  That said, I don't think we should be breaking accurate depth or moving farther from correct behavior with it.

The current problems with "accurate depth" are, as far as I know:

1. When depth clamping is not natively supported, the 37.5% buffer on each side only goes so far in masking the problem, and also makes certain tests fail.  Non-accurate depth "accidentally" makes this work by incorrectly scaling depth values.

2. When depth clamping is natively supported, it clamps to the clip range instead of the full range.  A draw with negative Z, depth clamp, and minz=1 should still be clipped.  That's not how modern hardware does depth clamping, though.  See #11399.

3. Range culling, a separate feature, has more complex interactions with depth clamping that don't always behave right.  This is really an issue with or without accurate depth, though.

4. The 16-bit path really doesn't work on many devices because clears and draws may round differently (frustratingly), so you can't even use the 1/256th subset properly to emulate a 16-bit depth buffer.

With that said, accurate depth is in general better and more accurate IMHO.  I can trivially come up with drawing that works on a PSP and fails poorly in the non accurate depth path.  For better or worse, games usually either do simple things with depth, or complicated things.

I would've expected the 37.5% buffer in Direct3D 9 to have made #7932 work, though.

-[Unknown]

**Comment by shenweip** [comment]
Thanks @unknownbrackets 's detailed explanation, When depth clamping is not natively supported, how about just simply clamping the Z of vextex to the depth range min/max instead of 37.5% buffer? Just like this:
```javascript
ShaderManagerDX9.cpp
VSSetBool(CONST_VS_ISDEPTHCLAMPENABLE, gstate.isDepthClampEnabled());
VSSetFloat(CONST_VS_DEPTHRANGRMIN, ToScaledDepthFromIntegerScale(getDepthRangeMax()));
VSSetFloat(CONST_VS_DEPTHRANGRMAX, ToScaledDepthFromIntegerScale(getDepthRangeMin()));
```
```javascript
VertexShaderGeneratorDX9.cpp
if (!gstate_c.Supports(GPU_SUPPORTS_DEPTH_CLAMP)) {
		WRITE(p, "  if(u_isDepthClampEnabled) {\n");
		WRITE(p, "    if(outPos.z/outPos.w > u_depthRangeMax) {\n");
		WRITE(p, "      outPos.z = u_depthRangeMax * outPos.w;\n");
		WRITE(p, "    }\n");
		WRITE(p, "    if(outPos.z/outPos.w < u_depthRangeMin) {\n");
		WRITE(p, "      outPos.z = u_depthRangeMin * outPos.w;\n");
		WRITE(p, "    }\n");
		WRITE(p, "  }\n");
}
WRITE(p, "  Out.gl_Position = outPos;\n");
```

**Comment by unknownbrackets** [comment]
That would deform objects.  Imagine a typical clipping situation:

Clipped triangle on top and bottom

Essentially, that's what happens with depth clamping, except that the edge of the object is flattened (deformed) against the near or far Z edge.

What you propose would mean stretching the depth coordinates, and would result in a smaller triangle (the triangle would not get clipped at the top and bottom like that, but would become fully within the depth viewport.)  This would break perspective and make everything look wrong.

In theory, it may be possible (in a geometry shader or something?) to "clip" the triangle and generate triangles to correctly flatten against the edge.

Explaining another way: if you imagine a typical perspective triangle of a street:

One point perspective street

Let's say that the game tries to draw the triangle of the street with the far red X at 100% past the valid depth screenspace.  What that ultimately means is that 1/3 (or something) of the street triangle (the farthest portion) would all have the same depth values in the depthbuffer.  It would visually draw the same with depth clamping, because only the pixel values are clamped.

If we adjusted the Z values on the vertices, that means that the end of the street would move CLOSER, and the street would render 2/3 as far out.  It would look weird, especially if it didn't draw the entire scene with depth clamping.

If we were to "clip" this, we would create multiple triangles: two triangles on each side going to the far plane, two more triangles for the space between those edges to reach the far plane, and then another triangle flattened against the far plane.  UVs etc. would all be adjusted just like with clipping.

-[Unknown]

**Comment by shenweip** [comment]
Seems need more works for this, closing for now.

**Comment by Gamemulatorer** [comment]
@shenweip any possible update about this one?

**Pull request closed without merging**
