### PR TITLE
Hardcode the cheats that work around the Tony Hawk's Underground jit issues.

### PR DESCRIPTION
**Pull request by hrydgard**
Temporary, horrible hack working around #3854 and also #6544 affecting MTX MotoTrax (US version only)

Not proud of this but it will have to do for 1.8.0. Really want to finally have this game playable by default. Promise I will find a real or at least a better fix in the future....

### CODE REVIEW

**Comment by LunaMoo** [comment]
Why compat.ini? Not going to do anything for other gameID's anyway, kind of useless unless it's just there as a reminder.

**Comment by hrydgard** [comment]
You're right, but I like to collect all the hacks there heh.

**Comment by unknownbrackets** [comment]
Hmm... not a huge fan, but okay.  How does this do in IR?  I remember I'd added that precompile / hash check iirc.  Are the variants here super diverse, or are there just a few options, and it churns through them?

If there's only a set number of options, maybe the trick is (like IR iirc) keeping around the old versions of the jit and swapping between them as it changes.

-[Unknown]

**Comment by hrydgard** [comment]
I'm really also not a huge fan, I just wasn't able to come up with something better for 1.8.0.

Really, we need to get rid of the overwriting, and I think we have the RAM budget for it now, just too big a project to squeeze in.

I think there's around 4 or 8 different option, but it's been a long time since I looked into what the code actually did so that might be off.

**Pull request merged**
