### PR TITLE
Update <Share> dialog on Android 10; Fixes #12846

### LINKED ISSUE #12846: Update "Share" dialog on Android 10
PPSSPP uses old "Share" dialog on Android 10, that supports new one (https://developer.android.com/training/sharing/send).

### PR DESCRIPTION
**Pull request by Florin9doi**
Fixes #12846 

Screenshot_1587762653

### CODE REVIEW

**Comment by Florin9doi** [comment]
Should we change http to https?

**Comment by hrydgard** [comment]
Yes. Also, Intent.createChooser only exists from API 22 and forwards. Please add a fall back path for older API versions.

**Comment by Florin9doi** [comment]
There are 2 methods; 
- public static Intent createChooser (Intent target, CharSequence title) - Added in API level 1
- public static Intent createChooser (Intent target, CharSequence title, IntentSender sender) - Added in API level 22

Should be ok

**Comment by hrydgard** [comment]
Oh sorry, I missed that. Should be OK then.

**Pull request merged**
