### PR TITLE
Support different image format for atlas

### PR DESCRIPTION
**Pull request by iota97**
Provide the PNG as well in the assets to make it easier to use.

Make the default logic less messy, I don't have a UWP machine to test tho' :/

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm, what's the purpose of this? The atlas needs to be generated by the atlas generator anyway, you're not supposed to manually edit it...

**Comment by iota97** [comment]
The idea was to make it easier to edit the atlas without having to compile or use the atlas tools.

Many people are able to edit a PNG, but having to mess with compilers and scripts might turn off someone.

If you think it's better to always regenerate the atlas feel free to close this ofc :)

**Comment by hrydgard** [comment]
The issue is that such direct edits will become a maintenance nightmare when the atlases change... things can get shuffled around quite a bit. 

Have been previously leaning towards building the atlas at runtime from small pngs for non-font atlases, although the reduced I/O performance on modern Android kind of probably made that a bad idea :(

**Comment by iota97** [comment]
I see :/

**Pull request closed without merging**
