### PR TITLE
Disable Depth Rounding for Summon Night 5 (JP)

### PR DESCRIPTION
**Pull request by daniel229**
Fixes https://github.com/hrydgard/ppsspp/issues/8181

### CODE REVIEW

**Comment by daniel229** [comment]
Disable Depth Rounding for MotorStorm Arctic Edge and Saigo no Yakusoku no Monogatari.I think there are more.

**Comment by daniel229** [comment]
Is EnableDepthRounding better than NoDepthRounding?

**Comment by hrydgard** [comment]
Yeah, I'm starting to think we should flip it around, too...

**Comment by unknownbrackets** [comment]
IMHO, if this many games get z fighting with it, then either (a) there's a bug or (b) this is an unexpectedly common consequence of doing it at the vertex level.  I think we should make sure we understand which.

-[Unknown]

**Pull request merged**
