### PR TITLE
Implement a few x86 vertexjit optimizations

### PR DESCRIPTION
**Pull request by unknownbrackets**
Micro-benchmarking results from unittest in commit messages - one only for SSE 4.1.

-[Unknown]

### CODE REVIEW

**Comment by zminhquanz** [comment]
Does it perf improvement on SSSE 3 and SSE 3

**Comment by unknownbrackets** [comment]
Yes, but not the s16 pos throughmode change (which only works for SSE 4.1.)  The rest are SSE2+.

Note that these improvements are only measured for vertex decoding.  This is only a percentage of the overall rendering process, so don't expect a huge impact in most games.

-[Unknown]

**Comment by hrydgard** [comment]
If you have Haswell or better (BMI2 extensions), it's possible to do an even faster 4444->8888 through PDEP:

    (color in eax)
    pdep ebx, eax, 0xF0F0F0F0
    pdep ecx, eax, 0x0F0F0F0F
    or ebx, ecx

**Comment by unknownbrackets** [comment]
I'm still rocking my ivy, will probably upgrade at some point but it's been serving me quite well (aside from lacking AVX2 and BMI2.)  Definitely some cool things can be done there.

-[Unknown]

**Comment by hrydgard** [comment]
Still rocking an Ivy as a main machine as well, but I've got a more modern CPU in the laptop. It's fast enough though, so not a very important optimization. PDEP/PEXT are really cool instructions though, I'm sure they have more interesting uses.

**Comment by iOS4all** [comment]
Is this fix related to iOS micro stutter or not?
Thanks.

**Comment by unknownbrackets** [comment]
No.  This only applies to x86 (Intel) CPUs, which are not used in any iOS devices.

-[Unknown]

**Comment by iOS4all** [comment]
Oh.... ok thanks

**Pull request merged**
