### PR TITLE
Support for notched phones

### PR DESCRIPTION
**Pull request by Florin9doi**
Needs testing, some settings may became inaccessible

### CODE REVIEW

**Comment by hrydgard** [comment]
Thanks! I've tried similar stuff but had issues on my notched phone, I'll test it later before I merge.

**Comment by hrydgard** [comment]
Yeah, this is gonna need additional work. With fullscreen off, I get that white edge I could never get rid of:
fullscreen_off

And with fullscreen on, the UI is clipped and needs fixing: 
fullscreen_on

Right now I don't see how it's worth it - PSP games at approximately 16:9 just aren't wide enough for this to matter at all.

**Comment by unknownbrackets** [comment]
It seems like the ideal thing would be to make the notch area black.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, which is what currently happens without this pull request..

**Comment by unknownbrackets** [comment]
I guess I might want to put buttons near the notch, at most... then again, I'm planning to avoid notch phones for as long as I can.

-[Unknown]

**Comment by Florin9doi** [comment]
>Right now I don't see how it's worth it - PSP games at approximately 16:9 just aren't wide enough for this to matter at all.

You're right

**Comment by hrydgard** [comment]
Well, I do want to extend the UI out into the notched area later - but I'm gonna postpone it to 1.10.

**Comment by Halo-Michael** [comment]
And Please add FullScreen Button for iOS.

**Pull request closed without merging**
