### PR TITLE
softgpu: Use SIMD more for dot products

### PR DESCRIPTION
**Pull request by unknownbrackets**
Had this in a stash from before v1.15.x were released.  It's a small gain but it helps when there's a lot of vertex processing.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Small gains add up!

**Comment by hrydgard** [comment]
Given that we probably don't match the hardware dot products to the bit level here, we might even be able to use `dpps` (`_mm_dp_ps`).

**Comment by fp64** [comment]
Hm, `_mm_dp_ps(a, b, 0x71)` seems neither faster nor slower, but shorter and more straightforward.

**Comment by unknownbrackets** [comment]
Mostly I avoid dpps because I've found it to be slow in the past.  Just checked on godbolt and I'm seeing it much slower (just casually replacing Dot33SSE4 with it and trying clang 16 as well.)  Maybe depends on what runner it hits, because one time I did see it about the same speed.  This latest runner seems to prefer the SSE2 code:

dpps     2.555 2.587 2.506 2.563 2.465 
SSE4, v2 1.594 1.538 1.577 1.536 1.610 
SSE2     1.325 1.336 1.352 1.372 1.335 

Was mostly trying to avoid the awful codegen in Dot().  Feel free to PR one of the other versions.

The template stuff was more to convince MSVC to inline and use SSE regs more consistently.  There aren't processors without SSE4.1 that will be able to run softgpu at decent performance for most games AFAIK, so I mostly just want to keep it running there and am not worrying about perf on SSE2.  But if we can avoid the annoying hoops, all the better.

-[Unknown]

**Comment by fp64** [comment]
Yes, I also seen `dpps` being mentioned as slow on some archs.

I also don't understand the reason for `&& !PPSSPP_ARCH(X86)` (e.g. `Dot33SSE4` has it, but `LightCeil` doesn't).

> There aren't processors without SSE4.1 that will be able to run softgpu at decent performance for most games AFAIK

Well, Valkyria Chronicles II runs at about 8 FPS on my SSE4-less machine in SW mode, so yeah, sounds about right (somewhat usable for debug purposes, but not for normal play). Dithering has its charm though.

**Comment by hrydgard** [comment]
Oh right, forgot that that's why we haven't used dpps so far.

**Comment by fp64** [comment]
My understanding is that `dpps` basically isn't  ever [*faster*](https://fgiesen.wordpress.com/2016/04/03/sse-mind-the-gap/) than doing it by hand, so the only wins are codesize, convenience, and, maybe, register pressure.

**Pull request merged**
