### PR TITLE
d3d9: Support blitting depth on frame switch

### PR DESCRIPTION
**Pull request by unknownbrackets**
Can be optimized more, but this makes Jeanne d'Arc work in D3D9 now.  Not sure why it didn't work before.  Will probably help #6497 for d3d9 as well.

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
Still broken.

**Comment by unknownbrackets** [comment]
Is it the same before and after, or different?  Hmm, in any case, this pull request definitely fixes Jeanne d'Arc.  Maybe there are other issues affecting that game too...

-[Unknown]

**Comment by unknownbrackets** [comment]
Oh wait, I committed with a test to make sure I had the wrong bits.  D'oh.  Sorry, try now.

-[Unknown]

**Comment by daniel229** [comment]
still broken.

This is the master build.

**Comment by hrydgard** [comment]
This is a very slow method - I would be afraid of performance regressions in games that happen to trigger depth copies even though they don't need it - though I'm not sure how common that is...

**Comment by sum2012** [comment]
I suggest merge this change first.

**Comment by hrydgard** [comment]
Well, alright. D3D9 is only a backup solution anyway, OpenGL is recommended where possible.

**Comment by unknownbrackets** [comment]
A user has reported that on their (probably old) hardware, this caused significantly bad performance:
http://forums.ppsspp.org/showthread.php?tid=1272&pid=114983#pid114983

Probably going to lump this into "slow buffer effects".

-[Unknown]

**Pull request merged**
