### PR TITLE
Disable lazy texture caching while mpeg video playing

### LINKED ISSUE #14090: Musou Orochi: Maou Sairin Enhanced Version video
(Only reporter phone have problem
v1.10.3 no problem ,a problem from #14047  )

https://youtu.be/yGaOnJVnTdA

### PR DESCRIPTION
**Pull request by sum2012**
Fix #14090

### CODE REVIEW

**Comment by hrydgard** [comment]
I understand the issue (it's texturing all four pieces from the same address, one after the other, and it doesn't change enough for the "lazy" texture hash to actually detect a change) but I think there are better ways than this. I'll think of something...

**Comment by unknownbrackets** [comment]
We should be doing a "safe" invalidation of the data Mpeg/Psmf decodes to, but I guess it's copying it somewhere else to texture from it, or something?  What a silly thing to do.  Do we know how it copies?

-[Unknown]

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets 
[recording.zip](https://github.com/hrydgard/ppsspp/files/5956251/recording.zip)

**Comment by unknownbrackets** [comment]
There's no memcpy logged in the dump, but I do see it texturing in that dump from the same VRAM address.  I guess it must be copying it, though.

Also the dump has the texture repeated, which I didn't expect..

-[Unknown]

**Comment by hrydgard** [comment]
This reproduces in the Euro version of Warriors Orochi. 

Tried a few minor tweaks in the texture cache like marking textures numFrames = 0 if minihash fails, and stuff like that, with little success - the texture state machine has gotten way too complicated, heh. Due for a rewrite I think to make it more understandable what's going on.

There's no obviously good hack here, disabling lazy texture caching for a frame on mpeg decode is of course one possibility...

Easy workaround right now is, as has been mentioned, to just turn off the lazy texture caching option.

I'm going to leave this for a better fix later.

**Pull request closed without merging**
