### PR TITLE
Add "Disable culling" as a speedhack for experimentation

### PR DESCRIPTION
**Pull request by hrydgard**
Range culling (which we'll just call culling in the setting name) still is problematic enough that it can be useful to have this way to turn it off as an escape route, until we really get it right. Since disabling it can break some games like famously TOCA, it needs to be under speedhacks, technically it can also be a small speedup though generally the performance difference is not detectable.

See for example #17061 or #18561 . In the first one, we are off by a small epsilon, that needs further testing to fix.

We will still try to avoid adding back a compat setting, since we know most of the details now.

### CODE REVIEW

**Review by JustAWhiteBloodCell — APPROVED** [review]

**Comment by IrfanH495** [comment]
this fixes tenchu ​​san too
I've experienced it for a long time.
Finally, without creating issues, the problem can be resolved.
Thanks!
disable culling off
Screenshot_20231219-064651_PPSSPP

disable culling on
Screenshot_20231219-064704_PPSSPP

**Comment by hrydgard** [comment]
Oh, I don't remember or didn't know that issue. That's another benefit of adding options like this - reports come in about more instances of the problem.

**Comment by unknownbrackets** [comment]
I think any remaining range culling issues are down to rounding, fiddly nan/inf issues, or similar.  Overall, I'm pretty confident range culling widely happens.

I think that game might've been in the software renderer issues issue, and iirc it just barely ends up rounding Z slightly wrong.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, I don't doubt that it happens consistently - as you say, it's more about the fiddly stuff.

#17061 for example needs a really slight amount of padding.

**Comment by Kethen** [comment]
Interesting, was working on a fov patch for gran turismo and was scratching my head over some popping culling on the sides of the screen pretty close to the camera when fov is roughly above 50 (also applies to unmodified cockpit view, which has a fov of 52.xxxx, while follow/bumper has 33, roof has 35 so there wasn't much visible screen side popping for those)

No idea if that was intended by the game, but with this option enabled, it seems to have removed all of those popping culling

**Comment by Kethen** [comment]
sceIoDevctl extension would indeed be handy for plugin development, tho currently the fov patches are done in cwcheat to leverage the built-in ui

eg. https://github.com/Kethen/RemasteredControls_GTpsp/blob/8b1178c30c65462c720ed7d08543dced8f0e5e3d/multiplayer_tweaks/UCES01245.ini#L19

**Pull request merged**
