### PR TITLE
Modified "ltn0/1/2/3/4/5/6/7 .pgf"

### PR DESCRIPTION
**Pull request by nassau-tk**
I tried made "ltn1.pgf/ltn3.pgf/ltn5.pgf/ltn7.pgf" files.

### CODE REVIEW

**Comment by nassau-tk** [comment]
See #13589

**Comment by nassau-tk** [comment]
I tried made "ltn0.pgf/ltn2.pgf/ltn4.pgf/ltn6.pgf" files too.

**Comment by hrydgard** [comment]
Cool! Got any pictures of what these look like?

**Comment by nassau-tk** [comment]
OK.
Please, See below.
**[EXIT]**
image
image
image

**[Jeanne d'Arc]**
image
image
image
image
image
image
image
image
image
image
image
image
image
image

**Comment by nassau-tk** [comment]
Offcourse, It's not perfectly match with "Original PSP pgf".
But, It became more good to size.
I'm convinced that the width of the character and the space became quite good.
Please understand that it was made by handwork to depend on the sense judged from my eye thoroughly.
And,I can't test all of English games.

**Comment by hrydgard** [comment]
Looks like a great improvement! I think in pretty much every game, it will be better than the current font. 

Thank you for your work! Let's merge and see if people report any issues :)

**Comment by nassau-tk** [comment]
Yes!
If happend some issue then I will try hard to soleved it. 😅 

And, Don't forget this things.
Some,English Games need "jpn0.pgf".
Like a Assassin's Creed:Blood Lines.

**Comment by hrydgard** [comment]
Yes, thanks for the info!

**Pull request merged**
