### PR TITLE
Change the armips submodule to a git subtree.

### PR DESCRIPTION
**Pull request by orbea**
I know my previous subtree PR was closed, but after talking about this in #ppsspp @ freenode I was given a 'Maybe' at the suggestion of changing armips into a git subtree so here is the proposal.

The main reason to do this is never have this compile issue again and help any noobs who try compiling ppsspp and may not understand that they need the submodule.
```
../Core/Debugger/SymbolMap.cpp:41:39: fatal
error: ext/armips/Core/Assembler.h: No such file or directory
```
Additional reasons include inherent issues with submodules which have been explained before and the goal of reducing the number of submodules that will be cloned with `git submodule update --init --recursive`.

Additionally the recursive `tinyformat` submodule in `armips` is now a git subtree after this PR and will pose no problems here. https://github.com/Kingcom/armips/pull/125
```
This subtree was made with.
```
git remote add armips https://github.com/Kingcom/armips
git subtree add --prefix ext/armips armips master --squash

It can be updated at any time with.
```
git subtree pull --prefix ext/armips armips master --squash
```
Some documentation on git subtree.
https://www.atlassian.com/blog/git/alternatives-to-git-submodule-git-subtree

### CODE REVIEW

**Comment by hrydgard** [comment]
I'm gonna read up a bit on git subtree, seems like a feature that might be worth learning. Armips seems like a much better candidate for a potential first use of subtree than our monstrous FFMPEG repo, that's for sure.

**Comment by orbea** [comment]
Yea, that is a great point about FFMPEG. :)

**Comment by unknownbrackets** [comment]
If we're using one submodule, what's the benefit of this?  We don't get blame or anything else, so it just makes this repo larger, mainly:

https://github.com/orbea/libretro-ppsspp/blame/2f0cd65236ef79ae2fabd9611c6bf77c0d951e91/ext/armips/Archs/ARM/ArmRelocator.cpp

-[Unknown]

**Comment by orbea** [comment]
I'm not really sure I understand what you are asking? The commits do not have to be squashed, but that would make the commit history rather messy and would inflate the size of `.git/`. Either way the commit range between merges is documented in the commit messages automatically and it is easy to bisect using the upstream repo as a result.

The benefits have been discussed before, but here they are again.
1. Entirely avoids the build error for the missing `ext/armips/Core/Assembler.h` include.
2. Submodules do not work well with shallow clones because the referenced commit could be at any depth.
3. Github has a horrible habit of throttling some users to around 10 kb/s or less during some clones. This is extremely frustrating in projects with many submodules where every other submodule clones at ridiculously slow speeds and requires the user to ctrl+c and start over many times over.

This does not solve the 2nd or 3rd issue entirely, but it does help mitigate it a little, but you are right that this does inflate the size of the ppsspp repo. However users have to clone armips either way so in the end its actually smaller since armips commit history does not have to be cloned.

**Comment by hrydgard** [comment]
OK, I understand what subtree is now but I don't see many major advantages for us.

Since we are not going to do this to FFMPEG anyway, we will still have submodules, so people will still have to use ```git clone --recursive``` or ```git submodule update --init --recursive``` after cloning.

There will therefore be no user experience benefit - closing.

**Comment by orbea** [comment]
Sorry to hear that. Even without ffmpeg there is user benefit for every submodule they do not have to clone separately from the main repo, but its your choice. Would you mind updated the armips submodule so that at least tinyformat does not have to be cloned as a submodule?

**Comment by hrydgard** [comment]
Yeah, I'll do that.

**Comment by orbea** [comment]
Cheers!

**Pull request closed without merging**
