### PR TITLE
Fix logic error: assign EGLSurface to EGLConfig

### PR DESCRIPTION
**Pull request by muxiaozi**

### CODE REVIEW

**Comment by muxiaozi** [comment]
@lvonasek Can you help me confirm its correctness, thanks!

**Comment by lvonasek** [comment]
Thanks, it makes sense to me. However I would like to test it on all supported headsets before merging it. I am currently on a vacation, so I will test it afterwards.

**Comment by muxiaozi** [comment]
Okay, I have successfully tested on quest2. Besides, wish you a good time!

**Review by lvonasek — APPROVED** [review]
LGTM. Tested on Pico Neo 3 Link, Pico 4 and Oculus Quest 2

**Review by lvonasek — APPROVED** [review]
@hrydgard, could you merge it?

**Pull request merged**
