### PR TITLE
Workaround for graphics glitch in Phantasy Star Portable 2

### PR DESCRIPTION
**Pull request by level99procrastinator**
In Phantasy Star Portable 2, depth range sometimes goes negative and is clamped by `glDepthRange` to 0, causing graphics clipping glitch (issue #1788). This hack modifies the projection matrix to work around it.

A checkbox is added under Hack setting to toggle this.

Hack off
a0

Hack on
a1

### CODE REVIEW

**Comment by hrydgard** [comment]
Bouncy cars?

**Comment by issuer** [comment]
http://youtu.be/EVzM_MWneq8

The cars do strange movements and bounce all over the place when played with and without high ping (obviously more noticeable with high ping). Enabling this hack helps with the "bouncing".

Tested with PPSSPP to PPSSPP and JPCSP to PPSSPP. On JPCSP's screen, the PPSSPP car was bouncing like a low-rider when doing donuts. This was in a LAn environment, so ping was not the issue here. After enabling the PSP2 hack, the issue was gone, the car behaved as expected, like on JPCSP did on PPSSPP screen side.

**Comment by hrydgard** [comment]
But, this hack just affects drawing. It should have no impact on game physics... That doesn't even seem to be possible. Sure it wasn't just coincidence?

**Comment by issuer** [comment]
Strange... just did a retesting and it seems fine, but i'm sure in old versions (like the one in the video) the cars bounced like crazy even at low ping. I guess this was fixed somehow and i didn't even notice, it's been a while since i played Burnout online/multiplayer.

About the FFt0 i'm not sure since i was using the infinite invading time on missions hack and when using the PSP2 hack it didn't work at the time, but i've only tested it 2 times, so i assumed it would've been caused by it. I guess it isn't related then... still, i'll leave the PSP2 hack enabled at all times and see what happens.

**Pull request merged**
