### PR TITLE
ppsspp 1.3 stops when I start Metal Gear Solid Peace Walker

### PR DESCRIPTION
**Pull request by AXprime**
Hello.. I'm using ppsspp new . I finished Metal Gear Solid portable ops in ppsspp and it worked fine . But when I tried playing Metal Gear Solid Peace Walker in ppsspp 1.3 .. it stopped.. Do u have any idea how to get it work? Thanks in advance..

### CODE REVIEW

**Comment by moura464** [comment]
e5e75f1ff82c6abced1200ce64bcc9ea

**Comment by hrydgard** [comment]
What? Why did you make a pull request with a bunch of random stuff?

Please make a proper issue instead.

**Comment by AXprime** [comment]
Can any any one help me I'm in github too.. I'm not having the solve for my problem...

**Comment by moura464** [comment]
Code Compare !!!

**Pull request closed without merging**
