### PR TITLE
Landscape Auto for Android

### PR DESCRIPTION
**Pull request by Florin9doi**

### CODE REVIEW

**Comment by hrydgard** [comment]
Oh, I see. I didn't know that was a thing :)

**Comment by hrydgard** [comment]
I think you're gonna want to extend this line:

    if (badOrientationCount < 3 && requestedPortrait != detectedPortrait && requestedOr != ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED) {

to also check for SCREEN_ORIENTATION_SENSOR_LANDSCAPE.

**Comment by unknownbrackets** [comment]
Makes sense.  Auto-landscape-only makes more sense to me than auto-including-portrait.  Sometimes I have my phone upside down and it's annoying to have to rotate my phone for PPSSPP to be upright, unlike most any other app, so I'm a fan.

-[Unknown]

**Comment by hrydgard** [comment]
Actually never mind my comment, it's not needed. Merging!

**Pull request merged**
