### PR TITLE
HLE: sceKernelAllocPartitionMemory volatile memory support (partition 5)

### PR DESCRIPTION
**Pull request by Crow-bar**
The real psp, when requesting memory from the 5th partition, allocates it in the range 0x08400000 - 0x08800000.
This should fix some homebrew issue.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
This needs to think about save states, at least.  I think there were other restrictions though - might only be kernel mode or when volatile memory is locked?

-[Unknown]

**Comment by Crow-bar** [comment]
> This needs to think about save states, at least. I think there were other restrictions though - might only be kernel mode or when volatile memory is locked?
> 
> -[Unknown]

Yes
This works in user mode, requires a prior call to sceKernelVolatileMemLock.
When saving or hibernating, psp waits for volatile memory to be unlocked (sceKernelVolatileMemUnlock).

Maybe something is missing in my code.

**Comment by hrydgard** [comment]
Yeah, this looks like something we should support. Unknown is right that it'll need versioning checks in the state save code.

For testing purposes and so forth, could you link to or name some homebrew that uses this?

**Comment by unknownbrackets** [comment]
I added the save state handling in #16058 (merging that will merge this as well.)

-[Unknown]

**Comment by Crow-bar** [comment]
> Yeah, this looks like something we should support. Unknown is right that it'll need versioning checks in the state save code.
> 
> For testing purposes and so forth, could you link to or name some homebrew that uses this?

https://github.com/DaedalusX64  but this is a bad example.

and i found it here 
https://github.com/adventuregamestudio/ags/blob/master/PSP/malloc/malloc.c 



> Yeah, this looks like something we should support. Unknown is right that it'll need versioning checks in the state save code.
> 
> For testing purposes and so forth, could you link to or name some homebrew that uses this?


DaedalusX64 (maybe a bad example)
https://github.com/DaedalusX64/daedalus/blob/master/Source/SysPSP/Utility/VolatileMemPSP.cpp

AGS
https://github.com/adventuregamestudio/ags/blob/master/PSP/malloc/malloc.c

Xash3d will use this):
https://github.com/Crow-bar/xash3d-fwgs

I wrote a small test:
https://github.com/Crow-bar/p5test

**Comment by unknownbrackets** [comment]
It seems like it allows allocating even if you don't lock volatile memory first (of course you'll get a fault if you access it.)  I haven't thoroughly tested, but it also seems like locking/unlocking volatile won't reset allocations.

-[Unknown]

**Pull request merged**
