### PR TITLE
Add a small assert and some warning fixes

### PR DESCRIPTION
**Pull request by unknownbrackets**
Just in case the file gets truncated, let's try to avoid confusing ourselves.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
We already have a "smart C file" called IOFile (which could use some cleanup, by the way).

**Comment by unknownbrackets** [comment]
Well, alright, although it seems less than KISS.  It seems to work.... it's used a grand total of one other place.

I think my best evidence that it's not very KISS is that you didn't use it, heh.

-[Unknown]

**Comment by hrydgard** [comment]
I had actually completely forgotten it existed until I saw some Dolphin code that started using it recently (yeah, it's in Dolphin's Common too)

**Comment by hrydgard** [comment]
I like the operator std::FILE *() you had in yours by the way.

**Pull request merged**
