### PR TITLE
Some minor cleanups and optimizations

### PR DESCRIPTION
**Pull request by chinhodado**

### CODE REVIEW

**Comment by chinhodado** [comment]
Can this be merged?

**Comment by hrydgard** [comment]
Currently it conflicts, and the pre-increment thing i don't see much point with, it's not actually faster. But if you rebase it, sure.

**Comment by chinhodado** [comment]
Done

**Comment by hrydgard** [comment]
I cleaned this up a little and merged. Didn't see the point of swapping all those x++ to ++x.

**Pull request closed without merging**
