### PR TITLE
Microphone:Improves the support of microphone.

### PR DESCRIPTION
**Pull request by shenweip**
The main changes are as follows:

- Adds support for non blocking mode.
- Changs the way to write sound recording data, now write in multiple times.
- Implements some related funcs.(experimental).

The microphone in Invizimals is supported now. At least the first mission I have tested(using microphone), I was able to clear it on Windows and Android.

### CODE REVIEW

**Comment by Panderner** [comment]
How do you get the Invizimals trap card @shenweip?

**Comment by shenweip** [comment]
Draw one myself.

**Comment by hrydgard** [comment]
Really nice work! Will look at it in detail later today.

**Comment by Panderner** [comment]
> Draw one myself.

How do you draw the trap card @shenweip?

**Comment by shenweip** [comment]
A sample like this.

**Comment by Panderner** [comment]
> 
> A sample like this.

How do you get this?

**Comment by Florin9doi** [comment]
You can find a better quality photo on Google Images and print it or you can point your camera to the Google Images page for a quick test

**Comment by shenweip** [comment]
Yes, it's a easier way to get the trap card.

**Comment by hrydgard** [comment]
Looks good to me! I merged.

**Pull request merged**
