### PR TITLE
TexCache: Optimize DXT3/DXT5 decode to single pass

### LINKED ISSUE #10795: Medal of honor Heroes 2 crashing after mission
What happens?
after first mission game crashing when loading statistics what you did and what not
MoH Heroes 1 is fine

What *should* happen?

What hardware and operating system are you running PPSSPP on? GPU might matter if it's a graphical issue.
Android 6.0 OpenGL Lenovo K10A40. Used default settings. CPU clocks=Auto

### PR DESCRIPTION
**Pull request by unknownbrackets**
I expect this to fix #10795, although I haven't tested that particular game.

Basically, because we previously decoded DXT1 first, then read that back and applied alpha data to it.  On Vulkan we should only write to memory, and the read was killing performance.

This refactors and writes out colors with alpha data just once.  To test, I made it rebuild the texture each frame, and decode 10 times in a loop - this made that take 1% as long.

Most games don't use DXT, but those that do should get better load times.

-[Unknown]

### CODE REVIEW

**Comment by marosis** [comment]
Cool!! Iam So happy when i see fixed issues. You write here how DXT1? Killing performance? So this can improve it in this game?

**Comment by hrydgard** [comment]
Wow, good catch! Just goes to show how important it is to never read from our pushbuffers....

**Comment by marosis** [comment]
Not helped! Same status!!!

**Comment by marosis** [comment]
OpenGL

**Comment by hrydgard** [comment]
This should definitely have fixed the Vulkan perf issue, but if you had a crash in GL, I guess that might remain @marosis  . I'll reopen the issue #10795 .

**Comment by marosis** [comment]
Yeah it fixed Vulkan but not OGL

**Comment by hrydgard** [comment]
You mean OGL still crashes, or OGL is still slow?

**Comment by marosis** [comment]
I have tested on Xiaomi redmi note 5. OPENGL no crashes. Vulkan No crashes.
Lenovo K10a40 OpenGL crashing. Vulkan not supported

**Pull request merged**
