### PR TITLE
pgf modified jpn0/kr0/ltn0,2,4,6

### PR DESCRIPTION
**Pull request by nassau-tk**

### CODE REVIEW

**Comment by hrydgard** [comment]
What are the changes here?

**Comment by nassau-tk** [comment]
WAo!!  I'm surprised quick response!

Those PGF will solved Issue #13767 .

And, I decide now that I throw "The Github Desktopto" to garbage box.
This is so useless and Annoying to the master.

**Comment by nassau-tk** [comment]
I will try PR other way.:sweat:

**Comment by Panderner** [comment]
@nassau-tk I don't think that you merged to issue https://github.com/hrydgard/ppsspp/pull/1.

**Comment by nassau-tk** [comment]
@Panderner 
Oh! Sorry!
I can't PullRequest correctly by Github Desktop(GUI).
So,Many times tried but NG.😓

**Comment by unknownbrackets** [comment]
It seems like it'd be harder, but I think it's simpler to use the command line.  It might seem scary at first, but it's just like a recipe.

Get Git here:
https://gitforwindows.org/

Next, go to your PPSSPP folder (which I assume you already have) and right click.  You should see an option "Git bash here".  Use that:
https://www.ajonit.com/wp-content/uploads/2018/07/git-bash-gui.jpg
(don't use the GUI, it's a trap.)

Now you should see a black window like this:
https://gitforwindows.org/img/gw1.png

Looking at this screenshot, you can see the colored line - that's your "prompt" as it's called.  The computer is asking you what you want to do.  Only specific commands work - but don't worry, I'll give them to you, like a cheat sheet.

To start, a few things to paste for setup:
```sh
git remote add upstream https://github.com/hrydgard/ppsspp.git
git remote add origin https://github.com/nassau-tk/ppsspp.git
```

MAKE SURE to do the above first, before the below.  You won't have to do it again.

Now, let's start a brand new "branch".  Conceptually, this is like starting a new email or a new document.  As part of this, we're going to update the latest info.
```sh
git fetch upstream
git checkout -b pgf-fix-i upstream/master
```

In the above, you can change "pgd-fix-i".  This is like the document name.  I recommend keeping it to letters, numbers, and dashes only.

REMEMBER: you should start a new branch whenever a PR is merged.  Using an old branch will complicate things and you'll run into problems.

Okay, now make the changes you want to make.  Have fun and change any file you need to.

Once ready, the next command allows you to see what files are different.  This lists everything you COULD commit:
```sh
git status
```

You might see something like this:

```
On branch free-space
Your branch and 'upstream/master' have diverged,
and have 2 and 14 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   android/AndroidManifest.xml
```

The above means I have modified the "AndroidManifest.xml" file in the android folder, but it's not "committed" yet.  That's like an unsaved change in a document.  It's not ready to go to the PR, I'm still working on it.

If you want to add a file's current changes just run:
```sh
git add assets/flash0/font
```

The above will add any changes in the font folder to your commit.  You could be more specific, like `git add assets/flash0/font/ltn0.pgf`.  Note this only adds the CURRENT version of that file.  If you change it some more, you'll need to run `git add` again.

That only picks what you WANT to "commit" or send for a change, but it doesn't actually commit it.  For that, use:
```sh
git commit
```

This should open a Notepad window, which might seem a bit weird.  You have to put some sort of message like you have been, i.e. `Fixed " i " jpn0/kr0/ltn0,2,4,6`.  Then save the file and close Notepad.  This saves the changes to your branch.

We're now ready to push the changes up so you can open a PR:
```sh
git push origin pgf-fix-i
```
(the last part has to be the same name as when you started the new change.)

You can then go here: https://github.com/hrydgard/ppsspp
And you'll see a prompt to open a PR.

To add more changes (perhaps based on feedback), just follow the above steps.  Use `git add`, then `git commit`, and finally `git push` just like above.  You'll keep using the same document name.

Another trick: the way I make it look like I'm so smart and don't make tons mistakes (even though I actually do) is by "rewriting history".  Every time you add a commit, it's a separate change that shows up for all to see.  Even after it's merged, every change you make it shown separately.

When I notice I've made a typo, instead of adding a separate commit I want to trick people into thinking I'm smart.  This only works when I've just made a commit with some files and want to change it.  If I made another commit since, it's not so easy.

All I do is first, use git add on the fixed version of the file:
```
git add assets/flash0/font
```

And then, I use a different command for the commit part:
```
git commit --amend
```

This will still open Notepad, but now it'll let me modify the message I put before (so I can fix typos in it too.)  After I save, it modifies that commit instead of creating a new one.

If I had already used `git push` before, it won't work now.  It'll say something about my branch being "out of date".  It's wrong, it's just confused because I rewrote history.  So I have to use a different command to push as well:
```sh
git push origin -f pgf-fix-i
```

And then it will modify my PR so people see my modified commit now.


I know that might sound complex, but if you want to give git bash a try, I find it the clearest way to use git.  GUIs are great for a lot of things (for example... emulation), but git is just not one of them, IMHO.  The terminal seems scary at first, but once you see it just works when you paste the magic words in, it gets a lot easier.

-[Unknown]

**Comment by nassau-tk** [comment]
@unknownbrackets
 I remove all.
And re-clone PPSSPP.

Sorry,Is this wrong?

xxxxx@ADMIN-PC MINGW64 /g/Github/ppsspp (pgf-fix-i)
$ git add assets/flash0/font
The following paths are ignored by one of your .gitignore files:
assets/flash0
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"

**Comment by nassau-tk** [comment]
xxxxx@ADMIN-PC MINGW64 /g/Github/ppsspp (pgf-fix-i)
$ git add .

xxxxx@ADMIN-PC MINGW64 /g/Github/ppsspp (pgf-fix-i)
$ git status
On branch pgf-fix-i
Your branch is up to date with 'upstream/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        modified:   assets/flash0/font/jpn0.pgf
        modified:   assets/flash0/font/kr0.pgf
        modified:   assets/flash0/font/ltn0.pgf
        modified:   assets/flash0/font/ltn2.pgf
        modified:   assets/flash0/font/ltn4.pgf
        modified:   assets/flash0/font/ltn6.pgf


Is it Ok???

**Comment by nassau-tk** [comment]
xxxx@ADMIN-PC MINGW64 /g/Github/ppsspp (pgf-fix-i)
$ git commit
[pgf-fix-i b4847976d] Fixed "jpn0/kr0/ltn0,2,4,6
 6 files changed, 0 insertions(+), 0 deletions(-)
 rewrite assets/flash0/font/kr0.pgf (64%)
 rewrite assets/flash0/font/ltn0.pgf (77%)
 rewrite assets/flash0/font/ltn2.pgf (91%)
 rewrite assets/flash0/font/ltn4.pgf (90%)
 rewrite assets/flash0/font/ltn6.pgf (90%)

xxxxx@ADMIN-PC MINGW64 /g/Github/ppsspp (pgf-fix-i)
$ git push origin pgf-fix-i
remote: Permission to hrydgard/ppsspp.git denied to nassau-tk.
fatal: unable to access 'https://github.com/hrydgard/ppsspp.git/': The requested URL returned error: 403

Hahaha...

**Comment by unknownbrackets** [comment]
Hm, your "origin" is hrydgard.  Try running these:

```sh
git remote rm upstream
git remote rm origin
git remote add upstream https://github.com/hrydgard/ppsspp.git
git remote add origin https://github.com/nassau-tk/ppsspp.git
```

Then try the `git push origin pgf-fix-i` again.  Although you may want to use:

```sh
git push origin -f pgf-fix-i:nassau-tk:my-new-pgf
```

That will update your PR.

-[Unknown]

**Comment by nassau-tk** [comment]
@unknownbrackets 
Thank you!
Maybe I did it!
PR #13780 .

(When the next occurred, can it be processed?):sweat:

**Pull request closed without merging**
