### PR TITLE
Just in time for v1.11.1 ;)

### PR DESCRIPTION
**Pull request by Anuskuss**

### CODE REVIEW

**Comment by Panderner** [comment]
@Anuskuss what 3 games that cause issues for 32gb memory stick on real hardware?

**Comment by hrydgard** [comment]
I didn't know these games had issues with large storage space - has this been reported before?

I am still open to merging this, it's not really likely to break much.

**Comment by sum2012** [comment]
@Panderner 

LEGO Star Wars II: The Original Trilogy
Tony Hawk's Underground 2 Remix
Virtua Tennis: World Tour

**Comment by Panderner** [comment]
> @Panderner
> 
> LEGO Star Wars II: The Original Trilogy
> Tony Hawk's Underground 2 Remix
> Virtua Tennis: World Tour

Umm yes but can we check the real hardware that cause issues for larger storage space first?

**Comment by hrydgard** [comment]
I just haven't seen reports that these games had this problem before, so I'm a little surprised by this PR.

**Comment by Panderner** [comment]
Feel free to close this if there are no issues for these games on larger storage space.

**Comment by hrydgard** [comment]
I want an answer from @Anuskuss  :)

**Comment by Anuskuss** [comment]
> Feel free to close this if there are no issues for these games on larger storage space.

Lol

So anyway, here are reports of other people:
https://www.reddit.com/r/PSP/comments/6xfrq1/lego_star_wars_the_original_trilogy_cant_save/
https://www.reddit.com/r/PSP/comments/aef3h3/psa_tony_hawks_underground_2_remix_if_you_have_a/
https://www.reddit.com/r/PSP/comments/8p4zc1/virtua_tennis_world_tour_wont_save/

**Comment by hrydgard** [comment]
Thanks @Anuskuss !  That's enough proof :) 

This is highly unlikely to break anything anyway, so in it goes.

**Comment by Panderner** [comment]
> > Feel free to close this if there are no issues for these games on larger storage space.
> 
> Lol
> 
> So anyway, here are reports of other people:
> https://www.reddit.com/r/PSP/comments/6xfrq1/lego_star_wars_the_original_trilogy_cant_save/
> https://www.reddit.com/r/PSP/comments/aef3h3/psa_tony_hawks_underground_2_remix_if_you_have_a/
> https://www.reddit.com/r/PSP/comments/8p4zc1/virtua_tennis_world_tour_wont_save/

Thanks @Anuskuss

**Pull request merged**
