### PR TITLE
Add glInvalidateFramebuffer on clobber

### PR DESCRIPTION
**Pull request by unknownbrackets**
This adds an INVALIDATE command in GLES to the end of render passes where that aspect is going to be clobbered anyway.

Currently assumes the data needs to live across frames, but it'd probably be an okay smallish speedhack to invalidate at the end of frames for any/all depth.

Kingdom Hearts, for example, does trigger this ingame, but it's only for the stencil buffer.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Have you seen any performance change from this? I seem to recall that some early mobile drivers had bad issues with glInvalidateFramebuffer but maybe it's no longer a concern.

Otherwise seems fine, but now we're getting into the kind of things that are dangerous enough to push to the next version, as we're slowly approaching 1.10. Although, maybe this one isn't that bad...

**Comment by hrydgard** [comment]
Actually the first and third commit I think I want to merge now. But anything that changes how GL is used feels iffy at this stage...

**Comment by unknownbrackets** [comment]
I'll split it out - I didn't see a good boost or anything, was just hoping it'd help some mobile.  Didn't know it sometimes made things worse.

I did know it could cause badness to do it at the beginning of drawing, which is why I put it at the end of each pass.

-[Unknown]

**Comment by hrydgard** [comment]
Gonna need a tiny little rebase here.

**Pull request merged**
