### PR TITLE
[Build] Manual generate Android APK

### PR DESCRIPTION
**Pull request by anr2me**
Creates Android APK artifact on demand.

The target Branch and Build Variant can be selected from Workflow UI
image

It can takes more than 30 minutes to assemble the APK
https://github.com/ANR2ME/ppsspp/actions/runs/2010682140

PS: i'm not sure why it didn't ask for Android SDK nor NDK, so i'll just commented the script in case it will be needed later.

### CODE REVIEW

**Comment by hrydgard** [comment]
Cool, good to have.

**Comment by unknownbrackets** [comment]
I guess this would be signed with even another key from the release or git builds?

As far as the SDK, I think they updated the base Actions runner image to include the SDK (although not sure about versions...) at some point.

-[Unknown]

**Comment by ANR2ME** [comment]
i exclude the `Release` build variant because i'm worried it will need a key, while the `Debug`/'Optimized` variant doesn't seems to need a key (as i remembered when i build PPSSPP using Android Studio)

Ah, that make sense why it didn't ask for SDK, but PPSSPP need NDK isn't? or was it optional?

**Comment by unknownbrackets** [comment]
Well, PPSSPP definitely requires the NDK, but maybe that's baked into the image now too.  We have at many times not successfully compiled with the latest (or with older) NDKs, though, so we usually want to be specific about which version is installed.

-[Unknown]

**Comment by ANR2ME** [comment]
Based on this comment https://github.com/actions/virtual-environments/issues/2689#issuecomment-778112138
it seems the image have both the latest NDK (22) and LTS NDK (21) versions side by side, and `ndk-bundle` is the symlink for LTS (21.x) version.

So we're good for now, but may be we'll need to Setup NDK (in the future if it _still_ need a specific version)

**Pull request merged**
