### PR TITLE
Add OSM progress display for GamedataInstall

### LINKED ISSUE #14688: Everybody's tennis(Europe). Stuck on 'checking storage media'
It's just stuck on this screen forever. This happens after the first tennis game you play.

### PR DESCRIPTION
**Pull request by sum2012**
fix #14688

### CODE REVIEW

**Comment by sum2012** [comment]
I do not know that how to solve ubuntu-latest build fail
PSPGamedataInstallDialog.cpp:(.text+0x13f0): undefined reference to `osm'

**Comment by unknownbrackets** [comment]
Most games show progress bars during install.  Is this to workaround some specific game that doesn't?  Or a bug in PPSSPP that's preventing the progress bar in that game?

-[Unknown]

**Comment by sum2012** [comment]
workaround for Everybody's tennis and Hot Shots Tennis: Get a Grip

**Comment by hrydgard** [comment]
Hm, I think we can do better with some PPGe graphics. What's shown on the real PSP during install?

**Comment by sum2012** [comment]
@hrydgard 
https://ibb.co/1GwbRm9
https://ibb.co/FKzJpkc
https://ibb.co/dW0qDSR
https://ibb.co/pbpJTYn

**Comment by sum2012** [comment]
@hrydgard  this picture change to english,better
pic_0000
pic_0003
pic_0004

**Comment by hrydgard** [comment]
Thanks, yeah, I think we should try to approximate that instead. Should be fairly easy, I might take a look in a while.

**Comment by unknownbrackets** [comment]
There must be a flag, some games show their own UI.  I think Valkyria Chronicles 2, for example.

-[Unknown]

**Comment by sum2012** [comment]
> There must be a flag, some games show their own UI. I think Valkyria Chronicles 2, for example.
> 
> -[Unknown]

 Valkyria Chronicles 2  use SceUtilitySavedata instead of sceUtilityGamedataInstall

**Comment by unknownbrackets** [comment]
Hm, maybe it does.  At least its sequel uses it:

Valkyria Chronicles 3 progress

It's been a while but I don't think it shows any PSP OS UI.

-[Unknown]

**Comment by hrydgard** [comment]
It wouldn't be a complete disaster if we drew an extra progress bar on top though, in case we can't find the flag...

**Comment by sum2012** [comment]
@unknownbrackets I don't know that my game of Valkyria Chronicles 2  don't have gameinstall log:


full log:
https://gist.github.com/sum2012/9e9f8dc8bb56583a576faccdafafd53f

**Comment by unknownbrackets** [comment]
Sorry I meant its sequel, Valkyria Chronicles 3 / Senjou no Valkyria 3.

-[Unknown]

**Comment by sum2012** [comment]
A small note:
jpcsp imp game install screen (missing Install completed.)
in https://github.com/jpcsp/jpcsp/commit/7227a2df1f9c1e487576369e57a48d8aeb4d7eda

**Comment by sum2012** [comment]
Install completed. added in https://github.com/jpcsp/jpcsp/commit/09c9374b9e12109689120795c859a94828a14a91

**Comment by hrydgard** [comment]
So the flag about whether to show the dialog or not seems to be SceUtilityGamedataInstallParam.mode == PSP_UTILITY_GAMEDATA_MODE_SHOW_PROGRESS, and the constant is just 1. Easy enough.

I think a first version of this could just check that flag and draw a progress bar, and skip the confirmation and stuff.

**Comment by hrydgard** [comment]
Closing this because I merged #17919

**Pull request closed without merging**
