### PR TITLE
Config: Add game name to game-specific inis

### LINKED ISSUE #11373: [Feature Request] Include game name inside ini
It would make detecting games a lot easier for those who manually edit game configs if you added the game name at the start of the ini file, even though it serves no purpose for the emulator itself!

### PR DESCRIPTION
**Pull request by unknownbrackets**
Fixes #11373.

-[Unknown]

### CODE REVIEW

**Comment by leopard20** [comment]
Thanks. Just one tiny issue. For some reason, only the. game ID, not title, is added to the config. For example, this is the start of the config file for Silent Hill Origins:
```
﻿# Game config for ULUS10285 - 
[General]
.
.
.
```

**Comment by unknownbrackets** [comment]
That's strange.  What steps are you using to create the ini (just to make sure it's not an issue with a certain path only)?

-[Unknown]

**Comment by unknownbrackets** [comment]
Maybe it also matters the type of game - it won't work for virtual disc (i.e. extracted iso) games or direct ELFs.

-[Unknown]

**Comment by leopard20** [comment]
The game title is detected correctly when I tap and hold on the game icon. 

I simply launched the game, then checked the config file. Also tried changing some settings to make sure the config is being written to but the title is still not appearing.

However, if I delete the config completely and let it be recreated again, the title appears.

**Pull request merged**
