### PR TITLE
Game info screen: Add checks against the Redump database

### LINKED ISSUE #12469: Add option to verify ISOs against redump.org?
redump.org provides metadata for most of the PSP discs, but of course don't host any downloads. 

I didn't actually know that redump.org had a PSP database because it's not visible from the main website's list of platforms, but it's really there:

http://redump.org/discs/system/psp

So if we can get our hands on the actual database, or find an easy way to query it, it should be easy to add a way to check that an ISO has not been modified from its original form.

### PR DESCRIPTION
**Pull request by hrydgard**
The ReDump project keeps a database of title names, IDs and hashes of nearly all PSP games (and games for a lot of other platforms).

This adds a way to check your ISO against it, to make sure you managed to dump your UMD to ISO correctly through your PSP. By default, it just checks the ID and size, and if those are OK it'll show a notice to click Calculate CRC to verify. If not, it immediately shows a warning.

Needs a bit more polish before it goes in, both UI and code-wise.

We may consider doing a size check and warning users for bad ISOs on boot too, not just in the game info screen.

Fixes #12469

### CODE REVIEW

**Comment by fp64** [comment]
Super-minor, but other overloads of `startsWith` can probably just call `std::string_view` version now?

**Comment by fp64** [comment]
Also, unused parameter `delim` in `SplitCSVLine`.

**Comment by Felipefpl** [comment]
> Fixes #12469

It's GREAT to see the oldest issues being fixed.

**Comment by hrydgard** [comment]
Let's get this in and see how it works for people.

**Pull request merged**
