### PR TITLE
[libretro] Replace `std::clamp()` with local `clamp()`

### PR DESCRIPTION
**Pull request by RobLoach**
This replaces libretro's use of `std::clamp()` with a local implementation of `clamp()`.

### CODE REVIEW

**Comment by hrydgard** [comment]
Why?

**Comment by RobLoach** [comment]
When building with LibreELEC, even when we had the `-std=c++17` flag set, `clamp` was still being reported as not a member of `std`. @ToKe79 would know which platform this was an issue on, but it was likely some older target like busybox or something.

While we could define a small macro or something to replicate `std::clamp`, thought it would be good to leverage an existing implementation. If you'd rather we take that direction, I'd be happy to make a follow up commit. Thanks!

**Comment by hrydgard** [comment]
Make a local static one instead. Reaching into the color conv code from there is more awkward than duplicating.

**Comment by RobLoach** [comment]
@hrydgard Updated to a local implementation. Thanks for the review :+1:

**Comment by ToKe79** [comment]
works for me - thanks @RobLoach & @hrydgard

**Review by hrydgard — APPROVED** [review]

**Pull request merged**
