### PR TITLE
Move texture coords, mipmapping, and blending func into linear jit

### PR DESCRIPTION
**Pull request by unknownbrackets**
This mostly leaves nearest alone, as linear tends to be the most demanding.  Probably makes sense to do some of this there too, though.

This expands the sampler functions to be more specialized, which also means we have more of them.  Currently, I have W and H as part of the ID, which might be a mistake - but it does allow using some shifting for multiply.  Didn't seem to help all that much though, so maybe not worth it...

Moving coord calculation and blending into jit was definitely worth it.  For example, at full multithreading and fast-forward, my i7-8700 was getting ~78 FPS in the logo of Valkyria Chronicles 3 (after the animation completes.)  These changes bring that to ~88 FPS (+12%.)  Improvements vary, though - in game only went from 36 FPS to 38 FPS (+5%.)

This was about as good as I could've hoped from this change.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Cool!

Multiplication has simply become very fast in the last few generations of Intel CPUs, probably why the benefit of shifts instead was small.

**Review by hrydgard — APPROVED** [review]

**Comment by Gamemulatorer** [comment]
I want to this on my phone but unfortunately there's still no android build in ppsspp buildbot.

**Comment by hrydgard** [comment]
Most of the new speedups in the software renderer are x86-only anyway, so you won't see much difference.

Buildbot should hopefully catch up soon..

**Comment by unknownbrackets** [comment]
Just the usual terribleness of the Android build tools:

```
AAPT2 aapt2-7.0.4-7396180-linux Daemon #3: Idle daemon unexpectedly exit. This should not happen.
```

-[Unknown]

**Pull request merged**
