### PR TITLE
Adrenotools followup

### PR DESCRIPTION
**Pull request by hrydgard**
This fixes most of the issues I commented on in #18532 . Most importantly, moves it to developer tools until we've gained more confidence in it - but it's looking good.

Remaining issues for future commits:

- [ ] Add PPSSPP doc here: https://github.com/K11MCH1/AdrenoToolsDrivers/tree/main/docs
- [ ] Fix driver bug "detection" to not detect bugs from the proprietary driver when using these
- [ ] Add Adreno drivers to PPSSPP Store? 
- [ ] Move back to Graphics settings?

### CODE REVIEW

**Comment by Crytonics** [comment]
PPSSPP doc are added in https://github.com/K11MCH1/AdrenoToolsDrivers

**Comment by Crytonics** [comment]
> @Crytonics https://github.com/K11MCH1/AdrenoToolsDrivers/blob/main/docs/ppsspp.md still has the headline "Citra Usage" :)

Fixed

**Comment by hrydgard** [comment]
I think I do want it to not be too easy to find. The reason is that there's a substantial amount of crash reports coming in from people loading bad adreno drivers.

**Comment by Crytonics** [comment]
> I think I do want it to not be too easy to find. The reason is that there's a substantial amount of crash reports coming in from people loading bad (or not matching their device) adreno drivers.

Yea that is problem on all emulators, people just need to read desc for drivers. When drivers get released there is says what gpu can run that specific driver.

**Comment by hrydgard** [comment]
people will never read the description :)

**Pull request merged**
