### PR TITLE
Right mouse button as back in menu navigation

### LINKED ISSUE #12648: [Feature Request] Right Mouse Button to Cancel Current Menu
Just a quick thought that came across my mind while navigating the settings. I think it would be super comfy to be able to cancel a menu (or a setting pop-up) by simply clicking the right mouse button. Serious Sam games had this as a navigation method and you could return from submenus really fast.

### PR DESCRIPTION
**Pull request by iota97**
Add support to navigate back using mouse 2. Fixes #12648.

NOTE: Couldn't test on Windows sadly as I don't have a build environment for that (tested on Linux SDL and Qt).

### CODE REVIEW

**Comment by unknownbrackets** [comment]
I'm not a huge fan of right click being hardcoded as back...

-[Unknown]

**Comment by iota97** [comment]
Added a setting to toggle it, disabled by default. It is in system settings ATM as it seem control is more for the PSP ones, not sure tho'.

**Comment by hrydgard** [comment]
I think this is just odd, nothing else that I use on a regular basis works like this.

**Comment by iota97** [comment]
I find it pretty comfortable, but It's really unusual indeed... Up to you I guess.

**Comment by hrydgard** [comment]
Come to think of it some more, the main problem with this is that it prevents us from using right-click for anything else on screens other than the main screen (which can't be backed out from). It just so happens that currently our only use of right-click that I can think of is accessing the game info screens from the main screen, but doing this would make it impossible for us to use right-click on other screens.

So I'm inclined to not merge this. I'll think some more.

**Comment by unknownbrackets** [comment]
One way or another the Qt fix looks good.

I think I saw this also in Retroarch maybe when I messed with it?  To me it feels awkward.  I may be biased though - my mice have always had back buttons built in, but I always remap them because I don't want a quick back button.

If we did map back automatically from the mouse, I'd rather do it from NKCODE_EXT_MOUSEBUTTON_4, since that is by default back for many apps afaik.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, that we can do.

**Comment by iota97** [comment]
Is that yeah about the Qt or mouse 4?
Let me know what you prefer me to do: should I open a separate PR with the Qt part, change this with mouse4 (hardcoded I guess rather than a option for that?), or anything else :)

**Comment by hrydgard** [comment]
Mouse4 :)

**Pull request merged**
