### PR TITLE
Simplify Vulkan initialization a little, don't recreate surface on resize

### PR DESCRIPTION
**Pull request by hrydgard**
Except on Android, where we still do since the surface is lost on defocus/resize.

Might help #13009.

Not yet tested with SDL, will do shortly.

### CODE REVIEW

**Comment by hrydgard** [comment]
Tried this on Ubuntu 20.04. Resizing the window works great, however toggling the fullscreen option on and then off crashes with:

```
W: VulkanRenderManager.cpp:1031: VK_SUBOPTIMAL_KHR returned - ignoring
INTEL-MESA: error: ../src/intel/vulkan/anv_batch_chain.c:1697: execbuf2 failed: Invalid argument (VK_ERROR_DEVICE_LOST)
46:24:310 Common/MsgHandler.cpp:45 E[SYSTEM]: Critical: Lost the Vulkan device! If this happens again, switch Graphics Backend from Vulkan to OpenGL
E: MsgHandler.cpp:72: Lost the Vulkan device! If this happens again, switch Graphics Backend from Vulkan to OpenGL
```

Not sure whether I'm doing things wrong there..

**Comment by hrydgard** [comment]
Just realized there's a pretty bad race condition though, since we don't acquire/present on the thread that gets the resize message. Will fix.

**Comment by hrydgard** [comment]
Well actually we do handle that by joining the thread. hm.

**Comment by hrydgard** [comment]
The crash here might be related to the one from #13009  ?  Very odd.

Doesn't happen on master.

**Comment by iota97** [comment]
FWIW this PR is working fine on Manjaro with NVIDIA.

**Comment by hrydgard** [comment]
It works fine on my ubuntu laptop too except when coming back from full screen, which is odd.

**Comment by hrydgard** [comment]
Closed in favor of #13164.

**Pull request closed without merging**
