### PR TITLE
Revert "Display: Avoid limiting FPS without a clear"

### LINKED ISSUE #11177: F1 2006 eur ( UCES00238 )  cannot in-game since v1.5.4-189-gc1a23658d
@unknownbrackets 
In the past (at least v1.3-276-gad04f97) ,It need simulate UMD delay to in-game #9193 
But in v1.6.3 cannot in-game.

Fast test 
last good: v1.5.4-187-g6b6487afc
last bad: v1.5.4-189-gc1a23658d
Compare: https://github.com/hrydgard/ppsspp/compare/v1.5.4-187-g6b6487afc...v1.5.4-189-gc1a23658d
That mean #10456
v1.5.4-187-g6b6487afc debug log: https://drive.google.com/file/d/1gRP5GHTvJNZcfslVXZyNmw3lWtBHGd5T/view?usp=sharing
v1.5.4-189-gc1a23658d debug log:
https://drive.google.com/file/d/1whMo0oNZCzas2E3jL3WAMoCBO08jFZEC/view?usp=sharing
v1.6.3-173-g0fd4ea882 debug log:
https://drive.google.com/file/d/1AE_croUJq8VCiObW2x4wcWKQu5NTno-i/view?usp=sharing

The screen is unlimited loading,then show full white screen,

### PR DESCRIPTION
**Pull request by sum2012**
This revert f9750dd13723c6b1b2837235e9f98e7d8fe3485a

Fix #11177 might help  , #10763 and possibly #11272

### CODE REVIEW

**Comment by unknownbrackets** [comment]
It'll break FF4 and Tales of Phantasia again, though, right?

Where does it get stuck when "force max fps" is disabled?  Maybe we have some other function that isn't delaying and should.

-[Unknown]

**Comment by unknownbrackets** [comment]
I will say, to be clear: if this improves God of War and F1, it's probably a good trade.  Would be good to know if Transformers used to work / works with this reverted.

-[Unknown]

**Comment by marosis** [comment]
Can't wait😄

**Comment by hrydgard** [comment]
Replaced this with the lighter #11770.  (I want to keep the clear counting, just not act on it).

**Pull request closed without merging**
