### PR TITLE
Switch Android build to using clang (needs buildbot update)

### PR DESCRIPTION
**Pull request by unknownbrackets**
I'm least certain about the VAO func changes (aapcs-vfp), but I think it should be safe.

Did not fix all the clang warnings, just some as I was trying to get it to compile.  Have not really tested on a device yet.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Hmm, it seems not to work on my device properly...

-[Unknown]

**Comment by maximu** [comment]
For this warning: unknown warning option '-Wno-psabi' [-Wunknown-warning-option]

You need delete -Wno-psabi in Local.mk for switch to clang because clang don't like this flag :Fixed this warning

**Comment by sum2012** [comment]
I compile error with  r11b ndk

**Comment by maximu** [comment]
Yes it's broken because we needs recompile switch ffmpeg  too with clang .

I'm investigate this how compile with clang ffmpeg library.

**Comment by maximu** [comment]
I'm miss for arm64 they don't like asm code with clang

./libavutil/aarch64/bswap.h:31:13: error: invalid instruction mnemonic 'rev16'
    __asm__("rev16 %w0, %w0" : "+r"(x));
            ^
<inline asm>:1:2: note: instantiated into assembly here
        rev16 %di, %di
        ^~~~~
In file included from libavformat/aacdec.c:23:
In file included from ./libavutil/intreadwrite.h:25:
In file included from ./libavutil/bswap.h:38:
./libavutil/aarch64/bswap.h:38:13: error: invalid instruction mnemonic 'rev'
    __asm__("rev %w0, %w0" : "+r"(x));

How fix it? 

This problem is related with Arm64 only others architecture compile ffmpeg ok with clang in my internal test

**Comment by unknownbrackets** [comment]
This works fine now (with r11c), but there's still the ffmpeg problem.  Ideally, ffmpeg needs to be rebuilt with android-9 and with --disable-asm in x86.

-[Unknown]

**Comment by hrydgard** [comment]
ok, I'll take care of rebuilding ffmpeg soon.

**Comment by unknownbrackets** [comment]
See https://github.com/hrydgard/ppsspp/issues/8677#issuecomment-220856973 for notes about switching FFmpeg to clang.  Looks doable.

With that we'd only need the NDK updated on the buildbot (#8677 must be fixed first.)

One odd thing, in my tests I'm using everything the same - but I don't get the pic errors on x86_64, even without rebuilding ffmpeg for x86_64... unlike https://travis-ci.org/hrydgard/ppsspp/jobs/131943336.  But, it builds also with clang.

Apparently FFmpeg is at 3.0 now and includes "asm optimizations": http://ffmpeg.org/#pr3.0

-[Unknown]

**Comment by unknownbrackets** [comment]
I tried 3.0, and it's probably worth updating to given we'd need to recompile a bunch of things anyway, but it doesn't help the x86 issue.

Anyway, on my local, all Android platforms link fine, but on Travis (even with the same binaries), they don't.  I'm not sure why.  I've tried cleaning my objs and also cleaning the ccache in Travis without improvement.  I definitely did recompile it with `--enable-pic`.

Not sure what I might've done wrong.

-[Unknown]

**Comment by maximu** [comment]
I Have too with linked problem with Clang compiler  
NOTE : Android-x64 ffmpeg script  missing --enable-pic Maybe we needs recompile x86_64 with clang compiler.

**Comment by maximu** [comment]
Well for some part  good wews disable asm ffmpeg code in x86-32bits load fine under marshamllow-x86

I tested in my notebook with latest android-x86 changes Kernel 4.4.10 + mesa driver 11.2.2 + android 6.0.1 r43 version patched security may 1.

tmp_3969-screenshot_20160523-132224-183916702

tmp_3969-screenshot_20160523-132922-150526160

tmp_3969-screenshot_20160523-1332091405673383

FF7 crisis core test 5x resolution and HW 2x scaler full speed without problem in x86 lib.

tmp_3969-screenshot_20160523-125844-1669866591

For other bad part x86_64 won't linked fine with clang for some reason this problem no exist with GCC 4.9.

**Comment by unknownbrackets** [comment]
Hmm I had rebuilt with `--enable-pic` in x64 in the branch I linked to and this PR:
https://github.com/unknownbrackets/ppsspp-ffmpeg/blob/update3/android-x64-build.sh#L12

-[Unknown]

**Comment by maximu** [comment]
@unknownbrackets   Ah Ops sorry I miss this line in you script also i use the same binary in you ffmpeg repository and not helped here same problem when linked with clang compiler but working fine with GCC 4.9 linked  in both x86 architectures .

**Comment by unknownbrackets** [comment]
Strange.  The only real difference is I did the linking on a CentOS 7 box, but I'm not sure how that could matter since it should be using the toolchain from inside the NDK.

We can try again with r12 or keep gcc 4.9 for x86_64.  But AFAIU, we'll eventually need to switch to clang, so I'm glad to know about the problems ahead of time.

-[Unknown]

**Comment by unknownbrackets** [comment]
@maximu Dumb mistake, I forgot I had tried ec491ef as an alternative to `--disable-asm` and never removed it.  That was what made x86_64 build correctly (although it doesn't allow asm on x86.)

It seems FFmpeg wants to be linked with `-Wl,-Bsymbolic`, not sure if that has any dangerous side effects for us.

-[Unknown]

**Comment by maximu** [comment]
@unknownbrackets Ah I see good find with this https://github.com/hrydgard/ppsspp/pull/8651/commits/ec491ef16b2ec374d55090cf7c0d5ce0673a2cff change compile fine  with clang compiler :+1:

**Comment by unknownbrackets** [comment]
@hrydgard only things remaining for this are:

- [ ] Buildbot update to latest NDK (in perfect world, might wait for r12)
- [ ] Ideally update FFmpeg on all platforms (this updates most, but not Windows/Mac/iOS)
- [ ] Linux sound issue (or could rollback to old FFmpeg libs there)

-[Unknown]

**Comment by mrcmunir** [comment]
NDK r12 released out.
Clang has been updated to 3.8
Now they use by default : -Wl,--warn-shared-textrel and -Wl,--fatal-warnings for 32bit architectures

**Comment by hrydgard** [comment]
Cool, guess it's time .. I won't have time to do the work until next week unfortunately.

@Orphis , feel like getting the buildbot ready for NDK 12 in the meantime?   Watch out - Google has managed to swap their windows 32-bit and 64-bit downloads on their NDK download page...

**Comment by unknownbrackets** [comment]
I'll rebase this after hrydgard/ppsspp-ffmpeg#39 is merged, and pull out the Travis/Linux experiment.  I'll also update it to use r12b.

I think we might have to keep the unused exports thing, at least for x64.  I can experiment with making that x64 only.

I think we still need the buildbot update...

-[Unknown]

**Comment by hrydgard** [comment]
Thanks for updating the branch. Hopefully we will run fine on Nexus Player now :)

**Comment by unknownbrackets** [comment]
@Orphis not seeing r12 or r12b on the buildbot - no env var, and trying to build with the dir fails.

-[Unknown]

**Comment by unknownbrackets** [comment]
Just an update: buildbot is all working now.

-[Unknown]

**Comment by unknownbrackets** [comment]
Someone reported worse performance in FIFA 14 (and unnamed other games) after this commit (not sure if Clang or FFmpeg):

http://forums.ppsspp.org/showthread.php?tid=20315

We could try switching back from clang - although I haven't yet reproduced the performance difference.

-[Unknown]

**Comment by hrydgard** [comment]
We're not gonna switch back. GCC is deprecated for Android now so we'll just have to live with it. If we can figure out a specific part that got slower, we might be able to optimize it back up.

**Pull request merged**
