### PR TITLE
State optimizations 2

### PR DESCRIPTION
**Pull request by hrydgard**
This is just #9255 reorganized and rebased, some parts in a different order since we now do it in all backends and it makes more sense that way. Also it's shorter since I merged parts of #9255 into master.

Still has some of the same bugs (but not all of them), so copying over the checklist.

Performance improvements range from middling to very good. It seems to be especially beneficial for D3D11, probably because it lets us avoid a bunch of state change calls. For example, in a GTA:LCS scene on my machine, we go from to 560fps to 740fps, though that's an extreme case.

Not ready for merge yet.

- [x] Need to change vertexFullAlpha logic
- [ ] Validate allowShaderBlend dirties
- [x] Brave Story missing octopus (related to DIRTY_BLEND_STATE somehow)
- [ ] MAX_REASONABLE_BLITS_PER_FRAME?
- [ ] SetDepthUpdated?

### CODE REVIEW

**Comment by hrydgard** [comment]
@unknownbrackets  Fixed a few more issues, all my usual suspects work now. Can you explain the three unfilled checkboxes a little more? :)

**Comment by unknownbrackets** [comment]
Validate allowShaderBlend dirties / MAX_REASONABLE_BLITS_PER_FRAME:

We track [# of blits per frame](https://github.com/hrydgard/ppsspp/blob/17a250df7a9d791c6d9135d6e337726596d6d31f/GPU/Common/DrawEngineCommon.cpp#L500), and just need to make sure a situation with blits renders right -
 * If two draws in a row both need blitting, does `ApplyDrawStateLate` re-blit as needed?
 * Do the max blits per frame account for this?  Should probably just move to where it actually blits.
 * Do changes to the render target cause it to re-evaluate if a blit is needed (probably yes)?

SetDepthUpdated:
We track this [while building state](https://github.com/hrydgard/ppsspp/blob/0ca16c29ae37a1a11c3809b5abc429cc2e256cfa/GPU/GLES/StateMappingGLES.cpp#L310) and probably should just move it somewhere else.  But maybe it doesn't matter, as long as it's re-evaluated whenever render target changes (since it's cleared then and used to track if depth needs blitting.)

-[Unknown]

**Comment by hrydgard** [comment]
Rebased, reordered and squashed a few things. For some reason github is showing some of the commits out of order above?? Very weird.

**Comment by hrydgard** [comment]
Anyway, I don't think SetDepthUpdated is an issue, and I'm thinking of just merging this to see the fallout. Would like to merge in good time before 1.5, whenever that will be...

**Comment by hrydgard** [comment]
Rebased again with more reordering work - now the commits are mostly cleanly ordered by which dirty-flag they relate to, which should aid bisection.

Going to merge this once the build passes.

**Pull request merged**
