### PR TITLE
Update langregion.ini

### PR DESCRIPTION
**Pull request by Endarko**
Upadate jv_ID= "Jawa (Indonesia)"

### CODE REVIEW

**Comment by unknownbrackets** [comment]
I think this is the same as #8510.  Will speakers of Javanese / Jawa recognize "Jawa" or will "(Indonesia)" help them know for sure it's the right dialect / language?

-[Unknown]

**Comment by Endarko** [comment]
Jawa

**Comment by unknownbrackets** [comment]
Okay, thanks.  I'll close this then, since "Jawa" is already in.

-[Unknown]

**Comment by Endarko** [comment]
oke..

**Pull request closed without merging**
