### PR TITLE
Mpeg:Only allow firmware >= 6 for warmup

### PR DESCRIPTION
**Pull request by sum2012**
Fix blue screen in #13146

### CODE REVIEW

**Comment by hrydgard** [comment]
Wasn't there some 3.x game that required warmup too? Or not?

**Comment by sum2012** [comment]
Final Fantasy tactics Firmware 3.0.3 the game work warm up and  don't have problem.
JPCSPTrace log: https://gist.github.com/sum2012/0ad2108cbe6ada8bc86e996dcf779670
In the JPCSPtace log: https://gist.github.com/sum2012/0ad2108cbe6ada8bc86e996dcf779670
sceMpegGetAtracAu and sceMpegGetAvcAu don't return ERROR_MPEG_NO_DATA

**Comment by hrydgard** [comment]
I guess let's try it...

**Comment by sum2012** [comment]
I test urgently rather than god eater firmware 6.xx

**Comment by sum2012** [comment]
Zettai Meikyuu Grimm: Nanatsu no Kagi to Rakuen no Otome  which firmware 6.20
Only return ERROR_MPEG_NO_DATA from in the video's middle
https://gist.github.com/sum2012/08f4eef7c5a032d8a10e9850a84221c5

**Comment by unknownbrackets** [comment]
Mid stream, ERROR_MPEG_NO_DATA is returned when there's not enough data to produce a stream.  This may be true even for "warm up", I'm not sure the exact semantics.  I think I've still gotten no data when calling it with a lot of packets.  I've wondered if the ME is decoding packets in the background after add.

-[Unknown]

**Comment by sum2012** [comment]
Beginning warm up maybe only required in God Eater Series's game

**Pull request merged**
