### PR TITLE
Trying to improve sceMpegAvcDecodeYCbCr

### LINKED ISSUE #11060: Sunday Vs Magazine Shuuketsu! Choujou Daikessen (Japan) crashes out after the intro
PPSSPP v1.5.4-995-g373366911 Windows 64 bit
choose arcade mode and after you choose your character  and opponent the intro plays and after that it goes to play music but then static and nothing but a black screen
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2021031/ppsspplog.zip)

### PR DESCRIPTION
**Pull request by sum2012**
Fix #11060

original log: https://github.com/hrydgard/ppsspp/files/9640801/ppsspplogv1.13.2-1209-ga26a353c2.zip
modify log (attached) 
[ppssppmodifylog.zip](https://github.com/hrydgard/ppsspp/files/9641060/ppssppmodifylog.zip)

edit:credit to @shenweip

### CODE REVIEW

**Comment by hrydgard** [comment]
I think it's becoming clear that there are multiple versions of the mpeg.prx module with different behavior, so something like this probably needs to be done. But I wonder if we can't do this in a better way, like, when the mpeg module is first loaded, we can check where from, and maybe its CRC?

**Comment by unknownbrackets** [comment]
Either way, I suspect this `initAddr` thing is really `frameWrittenAddr` and needs to be aligned with whether it wrote a frame, though I'm not sure.  The mpeg code is still pretty inaccurate.

-[Unknown]

**Comment by sum2012** [comment]
mpegLibVersion = 0x010A
This mpeg.prx is loaded from flash0 from sceUtilityLoadModule
(this game's firmware is 5.03 ,I don't think that need CRC check)
19:54:905 sxm_main     I[SCEUTIL]: HLE\sceUtility.cpp:523 0=sceUtilityLoadModule(00000100)
19:54:922 sxm_main     I[SCEUTIL]: HLE\sceUtility.cpp:523 0=sceUtilityLoadModule(00000101)
19:54:956 sxm_main     I[SCEUTIL]: HLE\sceUtility.cpp:523 0=sceUtilityLoadModule(00000300)
19:54:972 sxm_main     I[SCEUTIL]: HLE\sceUtility.cpp:523 0=sceUtilityLoadModule(00000301)
19:55:006 sxm_main     I[SCEUTIL]: HLE\sceUtility.cpp:523 0=sceUtilityLoadModule(00000302)
19:55:022 sxm_main     I[SCEUTIL]: HLE\sceUtility.cpp:523 0=sceUtilityLoadModule(00000303)
19:55:056 sxm_main     I[SCEUTIL]: HLE\sceUtility.cpp:523 0=sceUtilityLoadModule(00000304)
19:55:073 sxm_main     I[SCEUTIL]: HLE\sceUtility.cpp:523 0=sceUtilityLoadModule(00000305)
19:55:106 sxm_main     I[SCEUTIL]: HLE\sceUtility.cpp:523 0=sceUtilityLoadModule(00000306)
19:55:123 sxm_main     I[SCEUTIL]: HLE\sceUtility.cpp:523 0=sceUtilityLoadModule(00000307)

My change change to if (mpegLibVersion == 0x010A) {
or if (mpegLibVersion >= 0x010A) {
better ?

**Comment by sum2012** [comment]
Parappa_The_Rapper EUR version
mpeg.prx is in
\PSP_GAME\USRDIR\modules.psp\mpeg.prx

**Comment by hrydgard** [comment]
@sum2012  I'd go for `mpegLibVersion >= 0x010A`. Gonna have to do a lot of testing to make sure nothing breaks though - as Unknown says, things are inaccurate, we're not 100% sure this is a versioning issue, could just be an accuracy problem.

**Comment by sum2012** [comment]
@hrydgard done

**Comment by unknownbrackets** [comment]
Quickly checked a few games using this func:
 * Jeanne d'Arc
 * Kingdom Hearts
 * Persona 2: Innocent Sin
 * Persona
 * Sol Trigger
 * Hexyz Force
 * Final Fantasy
 * Patapon 2
 * Motorstorm: Raging Ice Demo

There's a longer list of games that could be tested, but at least these seem fine with this change.

-[Unknown]

**Comment by sum2012** [comment]
Real PSP log of the log:
https://gist.github.com/sum2012/935762f26936ec544b63dbdb6b41bd4c 
 `initAddr`  always 1

**Comment by unknownbrackets** [comment]
Well, there may be more to do with how it calls sceMpegGetAvcAu as well, or timing.

-[Unknown]

**Comment by hrydgard** [comment]
Let's try this and see how it goes. Thanks for reworking it!

**Comment by sum2012** [comment]
@hrydgard I don't mean it,you haven't approve it.

**Review by hrydgard — APPROVED** [review]

**Comment by hrydgard** [comment]
oops, sorry about that.

**Comment by sum2012** [comment]
Lucky this patch fixed other mpeg game: Saru Getchu PipoSaruRacer (UCJS10032)
#12768

**Pull request merged**
