### PR TITLE
Replace memset in Final FantasyTactics (jpn)

### PR DESCRIPTION
**Pull request by daniel229**
Thanks @unknownbrackets 
https://github.com/hrydgard/ppsspp/issues/7353

### CODE REVIEW

**Comment by daniel229** [comment]
Test Drive Unlimited also uses this one.

**Comment by daniel229** [comment]
The function is popular, also found in Bakumatsu Rock Ultra Soul.

**Comment by unknownbrackets** [comment]
That's great, I like it when we find popular implementations of memset and memcpy.

Is the memcpy() also recognized?  It should be near the memset.  In the US tactics, it's the second function above memset.

Actually, the one in between is probably a memmove(), and is not currently recognized... hmm, definitely looks like one.

-[Unknown]

**Comment by daniel229** [comment]
Yes,it's recognized when this patch.many other games use it.

This one between memcpy() and memset,probably a memmove() and it's also popular in many games. found in Chuumon Shiyouze! Oretachi no Sekai

**Comment by unknownbrackets** [comment]
Okay, #7355 tracks the US version of `memmove()` here.  If the JP version is different (screenshot looks different, US version uses padding...), want to add it here too?  Just in case some game uses it in a way that fixes something.

Does look like a memmove().  It also helps that they are in alpha order.  This really helped me be sure when I initially marked a bunch of implementations, since they are often in order by name (sometimes there are nids that verify them as well.)

-[Unknown]

**Comment by daniel229** [comment]
JP version already has an memcpy() and memmove().

**Comment by unknownbrackets** [comment]
Oh, but it's not recognized in your Chuumon Shiyouze! Oretachi no Sekai screenshot?

-[Unknown]

**Comment by daniel229** [comment]
That "memmove()" in Chuumon Shiyouze! Oretachi no Sekai is not recognized.I haven't hook it
I can find more these functions in games.

**Comment by unknownbrackets** [comment]
Well, the way it does a backwards and forwards copy in there makes me think it's a memmove().  Might as well hook it.

-[Unknown]

**Comment by daniel229** [comment]
That is https://github.com/unknownbrackets/ppsspp/commit/daf3448591a2de98b0e662f92d4cdb596f1fe95e

**Pull request merged**
