### PR TITLE
Work on MIPS JIT.

### PR DESCRIPTION
**Pull request by xsacha**
Jit still doesn't work (crashes in enter code). Need work on MipsAsm.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Well, I think we should eventually merge this, although still no idea what makes it break.  I've been recently trying to get the IR closer to merging.

-[Unknown]

**Comment by xsacha** [comment]
Do you have a copy of this branch? I accidently it.

**Comment by unknownbrackets** [comment]
It was at 5004a60 before.

-[Unknown]

**Comment by xsacha** [comment]
I switched my MIPS machine to Android temporarily and didn't save the branch anywhere :|

some commits on 19 Nov 2014
	@xsacha 	xsacha 	MIPS: Add MipsAsm file. 	4348344
	@xsacha 	xsacha 	MIPS: Fix delay slots. Use NOPs for now.  6de5e86
	@xsacha 	xsacha 	MIPS: Set -march to mips32r2 for 32-bit MIPS. …	06e3b73
	@xsacha 	xsacha 	MIPS: Fix a few issues. Save regs. 	5b8061e
	@xsacha 	xsacha 	MIPS: Remove NOPs for delay slots (now automatic) 	a8baf27
	@xsacha 	xsacha 	MIPS: Implement JIT block cache. 	8fc2185
	@xsacha 	xsacha 	MIPS: Add CompBranch JIT and BGEZ inst. 	fb6db47
	@xsacha 	xsacha 	MIPS: Add Jump calls and Syscall 	2e1f9d7
	@xsacha 	xsacha 	MIPS: Fix some mistakes. Emitter was using wrong shifts. LW was tryin… 826dcfd
	@xsacha 	xsacha 	MIPS: Fix up which files should be built. 	3d3b0e1
	@xsacha 	xsacha 	MIPS: Fix call function bug, jit now works. Thanks @unknown. Add stub… 1030cdc
	@xsacha 	xsacha 	MIPS: Implement Replacement, VBranch and FPUBranch. 	38d88c2
	@xsacha 	xsacha 	MIPS: Fix ABI (o32). 	93f2adb
	@xsacha 	xsacha 	Use different temporaries for WriteDownCount and Comp_Generic to prev…	297395e
	@xsacha 	xsacha 	MIPS: Implement a Regcache. 	5004a60

**Comment by MoochMcGee** [comment]
@xsacha Did you accidentally 93 MB of RAR files too? Is it bad?

**Comment by unknownbrackets** [comment]
Put it here:
https://github.com/unknownbrackets/ppsspp/tree/mips-jit

Will probably rebase it soon.

-[Unknown]

**Pull request closed without merging**
