### PR TITLE
Assets reorg

### PR DESCRIPTION
**Pull request by hrydgard**
ppsspp/assets should only (or at least mostly) contain files we have a use for on all platforms, so that including the whole directory as-is (excluding .git in the lang submodule) makes sense. This will simplify the new Android build a little, and also various scripts we may use to package things up now or in the future.

This also moves the lang directory into assets.

### CODE REVIEW

**Comment by sum2012** [comment]
Please fix windows and Android build lang.Now they doesn't include lang file in the "Automated PPSSPP builds"

**Comment by hrydgard** [comment]
Thanks for the reminder, will fix soon. @Orphis are we missing the new lang folder in the buildbot script? I think we might be...

**Comment by Orphis** [comment]
I'm on it!

**Comment by Orphis** [comment]
Can you try downloading the Windows 32 bit build and tell me if it works for you now?

**Comment by sum2012** [comment]
@Orphis Worse than before, no lang folder

**Comment by sum2012** [comment]
assets/lang/ still missing

**Comment by Orphis** [comment]
What build did you download? It's there for me in v1.3-123-g4a977d8

**Comment by sum2012** [comment]
@Orphis I re-try again,now okay,thanks

**Comment by sum2012** [comment]
@Orphis I test v1.3-127-gdba95bd of Android build,
Lang still missing,Please help ,thanks

**Comment by Orphis** [comment]
Please, can you confirm that the Windows builds are fine?!

**Comment by sum2012** [comment]
Yes,Windows builds are fine

**Comment by sum2012** [comment]
This is Android build screenshot - no lang
screenshot_20161025-010644

**Comment by sum2012** [comment]
Someone in baidu forum said that assets folder missing lang folder in Android build so that no lang

**Pull request merged**
