### PR TITLE
Atrac addStream:SeekToSample when RemainingFrames > 2

### LINKED ISSUE #7601: Gripshift freeze in-game
There is work around for USA version
http://forums.ppsspp.org/showthread.php?tid=1040&pid=104256#pid104256
@unknownbrackets 
v1.0.1-177-g0b7ae3d 
Music volume zero (good) log:
https://drive.google.com/file/d/0B3OaSdeV0L8kNXFlcEZXbXZIOFU/view?usp=sharing
Music volume full (bad) log:
https://drive.google.com/file/d/0B3OaSdeV0L8kYkd2VGIwcmdPLW8/view?usp=sharing

### LINKED ISSUE #10139: Shrek smash and crash racing freezes, can be unfrozen by going into menu
The game start normally but when i press start to go to game main menu fps drop to 0/0 to pass this i have to go to dev menu freeze image and unfreeze then the menu appear also i have this issue when start race. My phone is galaxy s7 edge exynos, mali gpu opencl 1.2 v1.r12p and also i am using vulkan backend.

### LINKED ISSUE #11586: Jackass - The Game (USA) music and reset problems
choose any game then when you start it the music just keeps on repeating one note and then when you choose to exit out of the game and back to the main menu it freezes up on the loading screen
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/2612770/ppsspplog.zip)

### LINKED ISSUE #12083: Save State -> Load state changes in-game mechanics in "Jackass: the Game"
related (though different region, and issue is not necessarily game-specific): #11586 

I want to clarify that while the problem is rare, the emulator behaviour (which is what I want to concentrate the issue on) is still very weird (as confirmed by @hrydgard himself)

# ROM

Jackass the Game (Europe).iso
> Size:	1,812,494,336 bytes
> CRC32:    FB133420
> MD5:	3A714CB9A2BCF79DB7203273DC5EECC0
> SHA1:	d03293698b7b112d7c6e010190f97043e32912b0
> SHA384:	9c09d296db959ca53b75e8dc70a3155685d7e6514a1bbff1130d27d886a60877a6aeeb49f652dfaf58df0302d3775303

# PPSSPP
## PPSSPP 1.7.4; settings changed
*Seemingly the most stable version for this game:*

* (changed controls, shouldn't affect anything)
* Rendering backend:
	Direct3D 9:		colour glitches, texture glitches, image upside down. Unplayable
	Direct3D 11:	no buffered parts rendered. Unplayable
	**OpenGL**:		best rendering backend in avail
	Vulnano: (unable to test out)
	
* Rendering mode (required): Buffered rendering (unbuffered fails on minigames)

## PPSSPP 1.8.0;
* The first time tried, for whatever reason the framerate wasn't capped. Not sure why.
* Tried running again, the problem disappeared; not sure why
* Changed the same settings as for 1.7.4 -> seemingly the same in-game behaviour

# Now to the game itself.

* The set-up I test, if I go to Minigames -> Golf Rally. Play it for 10 seconds (whether doing the moves or not), and notice the game's in-game timer looping incorrectly breaking the gameplay. All the music, gameplay, and moves begin looping incorrectly

* Another side effect is, if you now "exit stunt", the game crashes entirely. If you try exiting before the timers break, you should be able to do so.

# "Weird workaround"

As I described,
>  if you PAUSE the emulation and then resume it, the game kinda rolls out its wheels and stops glitching (including that it allows to exit minigames). How is it even possible?

Turns out I slightly misremembered it. What you really need to do, is go to is,

1. Get the game to the specific "bypassable" state (explained below)
2. Save state
3. Load state
4. If did not work out
    * Possibly wait ~5 seconds keeping the game running 
    * Go to 2

## Bypassable state

Bypassable state is the state in which the workaround may work out. Found bypassable and non-Bypassable states are:

Non-bypassable
* Pause menu

Bypassable
* "Action", i.e. while the stunt running
__________
* "Injury report" - i.e. score obtained
* "Video footage obtained", i.e. achievements
* End stunt menu

____
____

### TL:DR
it seems there is a pattern, which is that,
* Music plays -> Bypassable
* Music does not play -> Non-bypassable

## Strategy 

1. Best strategy is,
    * Begin stunt, wait until the timers break 
    * Fail it
    * In the after-stunt menu, perform the workaround

2. The second-best strategy, is not as stable, but useful where early stunt exiting is impossible is
    * Begin stunt, wait until the timers break 
    * (Recommended) set the emulation speed to, say, 20%
    * While the stunt running, perform workaround

## real time clock sync
*aka Game Settings -> More settings -> System -> Emulation -> Force real clock sync (slower, less lag)*

> make sure you're not using "real time clock sync"

While testing, the parameter is **Disabled** (unchecked).

Try with it on (just to test out):
Tick, then reset: Nothing changes

## Unsolved issues

1. Party boy is still unplayable.
**Reason** is simple: The music, and timers accordingly, reset entirely upon stunt restarting
**Workaround**:
    1. Begin stunt, wait until the timers break
    2. With a RAM hacking software, set the score to >750 to pass it
    3. While the stunt running, Wait another 10 seconds, perform workaround
    4. If failed, goto 3
    5. After finishing stunt, save game and forget about stunt thereafter

(Possibly) other stunts of the similar nature may make use of this workaround as well if need be

### LINKED ISSUE #13773: Coded Arms Contagion music stops playing in few seconds
There's a bug where Coded Arms contagion music stops playing immediately in few seconds:

Here's a Log:
```
FMOD Streame E[ME]: HLE/sceAtrac.cpp:571 avcodec_decode_audio4: Error decoding audio -1094995529 / bebbb1b7
```

After Stopped playing music. The music will start playing again.

### PR DESCRIPTION
**Pull request by sum2012**
Test with Code Lyoko #2539 still work 
Fix #13773 fix #7601 Fix #11586 Fix #10139
Fix #12083 the Golf Rally fixed

Coded Arms Contagion
v1.10.3-1330-g73da378ef log:
https://gist.github.com/sum2012/2261ff5a3b769a17d9864cd98d6bcff9

modify log: 2  (no "orignal FF: Frame decoding error!")
https://gist.github.com/sum2012/8213cb6351656b7e3138bf0089caa3b6

real psp log:
https://gist.github.com/sum2012/05ae453e97050a77497d132a676582fb

Hope other people give me feed back by Atrac 
This is windows 64 bit  test build 2
https://drive.google.com/file/d/1kKVEwousMWlkHlMbN2X3B13tOxsR4VbZ/view?usp=sharing

edit: Loco roco 2  also remain frame < 2 at the beginning ,not test much

### CODE REVIEW

**Comment by hrydgard** [comment]
Interesting! It does feel weird to do a seek in AddStreamData though, I wonder what the reason is that those games get fixed by that...

**Comment by sum2012** [comment]
There is no reason that don't add data into "stream" form of  Atrac .
They don't call sceAtracGetBufferInfoForResetting for seek

**Comment by hrydgard** [comment]
Oh, so this is really all about looping?

**Comment by sum2012** [comment]
90% same sound,10% time difficult.
But I already tested out  Castlevania X Chronicles [ULUS10277] break this,
It don't require seek.Don't error but sound become bad.
I need more games to test

**Comment by hrydgard** [comment]
Well either way it's an interesting find that may give us clues for how to really fix this ... hm.

**Comment by sum2012** [comment]
Regression list: (Sound bad)
Castlevania X Chronicles ULUS10277
Brothers Conflict Passion Pink ULJM06066
Saru Getchu PipoSaruRacer  UCJS10032

**Comment by sum2012** [comment]
atrac->bufferState_ == ATRAC_STATUS_STREAMED_LOOP_FROM_END
RemainFrame,GameID

Good,don't seek
1-2 ULUS10351
18-22  ULJM06066
42 UCJSJS10038
40-84 ULJM05841
114-115 ULUS10277
511-512 NPJH50789
526 ULUS10273
681-682 UCJS10032

Bad,Need seek
14-17 ULUS10194
218-219 ULUS10040
218-219 ULUS10303
351 ULUS10184

Don't know whether we need these data to hack to fix

**Comment by Panderner** [comment]
Update: K-On! Houkago Live! breaks this PR.

**Comment by Gamemulatorer** [comment]
> Any current state of this PR?
> > I do not find any improve

Can you make this as compatibility tweaks?

**Comment by Catarax** [comment]
Played Jackass (Europe) with the windows build linked ("This is windows 64 bit test build 2"), the game doesn't crash anymore, making it playable.

However all mini games music is looped every 2/3 seconds, making all songs annoying.

**Comment by sum2012** [comment]
use #15838 instead

**Pull request closed without merging**
