### PR TITLE
Remove the assembly implementation of 4x4 matrix mul, in favor of intrinsics.

### PR DESCRIPTION
**Pull request by hrydgard**
This function is only ever called by the bbox culling stuff, which is used by very few games, and this won't even be slower in practice. Gets rid of an .asm file that seem to be causing build problems for people occasionally (#15964 for example).

### CODE REVIEW

**Review by unknownbrackets — APPROVED** [review]

**Comment by hrydgard** [comment]
Hm, looks like it'll need some tweaks for 32-bit. Will do soon.

**Comment by hrydgard** [comment]
yup, that'd be the easiest solution.

**Comment by unknownbrackets** [comment]
I think you bumped ffmpeg by mistake.

-[Unknown]

**Comment by LibretroAdmin** [comment]
Hi, this PR broke several libretro builds -
https://git.libretro.com/libretro/ppsspp/-/pipelines/134052

**Comment by unknownbrackets** [comment]
I guess this: https://github.com/hrydgard/ppsspp/blob/6b6271a53e815a5b3abc16be309a1ad35bbc18bd/libretro/Makefile.common#L697

-[Unknown]

**Comment by hrydgard** [comment]
@LibretroAdmin I'll fix

**Comment by LibretroAdmin** [comment]
Thanks.

**Comment by LibretroAdmin** [comment]
Hmm, seems like some files are still not being compiled in since it fails at the linking stage -
https://git.libretro.com/libretro/ppsspp/-/pipelines/134060

**Comment by hrydgard** [comment]
Oh, I think I understand what went wrong. Fix upcoming.

**Comment by hrydgard** [comment]
Alright, new attempt committed

**Comment by LibretroAdmin** [comment]
What is the new attempt?

I checked the latest commit on master - this one still exhibits the same issues -

https://git.libretro.com/libretro/ppsspp/-/pipelines/134092

**Comment by unknownbrackets** [comment]
I suppose that's from updating zstd.  Maybe #15975 may help.

-[Unknown]

**Comment by LibretroAdmin** [comment]
Hi, thanks for the effort so far.

So Windows builds now build, the only one still failing to build is OSX -

https://git.libretro.com/libretro/ppsspp/-/jobs/2463909

**Comment by hrydgard** [comment]
Looks like it has something to do with whether it should use bmi2 instructions or not, and presumably some sort of detection mismatch or maybe a missing file again. Nothing to do with this PR, but should of course be fixed.

**Comment by hrydgard** [comment]
Oh, no, I think we're just missing lib/decompress/huf_decompress_amd64.S in the makefile.

**Pull request merged**
