### PR TITLE
 Android: Allow using a custom Memory Stick storage path

### LINKED ISSUE #9573: Not changeable PSP save directory (Android)
Since my phone has low built in free storage space could anyone implement saving on external sd card?

### PR DESCRIPTION
**Pull request by unknownbrackets**
This allows a user to keep their save data on an insertable card, or otherwise.

Fixes #9573, possibly also #11115 (actually merging seems dangerous and tricky), possibly #6307.  Possibly #11731 too, although the UI isn't ideal for that laser-specific case.

Makes #10199 worse, since it just asks the user to type a path.  I briefly looked at opening a "browse for folder" dialog on Android... but then just backed away slowly.  But some folder browser would be ideal, and much more useful than just an option to store with the app (since that's not necessarily so great if you have an SD card slot.)

Errors are also a bit easy to miss.  It uses the tips to tell you if the path you entered isn't writable.  Maybe it should show a proper error screen...

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Hm, I realized there might be one issue.  If a user puts storage onto an exFAT or FAT card, we should really activate the case sensitivity stuff I suppose...

-[Unknown]

**Comment by hrydgard** [comment]
UI isn't exactly optimal but it's a good setting to have. Let's do it.

**Comment by unknownbrackets** [comment]
Someone reported this not working on a Huawei P9+ with Android 8.0, only when putting it on the micro SD card.  Other paths working, and a Huawei Y3 with Android 5.0 worked fine.

Hmm.  Will see if I can test more.  Don't have many devices, especially not with micro SD slots...

-[Unknown]

**Comment by Saramagrean** [comment]
Same problem in Galaxy J7 too. 
Spec: Android 6.0.1, SD Card 32 GB. (VFAT FAT32)

**Comment by hrydgard** [comment]
Thinking of hiding the feature temporarily for the 1.8.0 release to avoid endless support email, until we can figure this out...

**Comment by Saramagrean** [comment]
Test again with Huawei P9+, PPSSPP can change Memory stick folder to SD Card, if set default location to. SD Card. :)
screenshot_20190228-115618
screenshot_20190228-115638

**Comment by unknownbrackets** [comment]
Basically, depending on the device/ROM and whether permissions were customized, you can't write to external SD cards so easily.

However, if you add: "/Android/data/org.ppsspp.ppsspp/" to the path, it will work.  Example: "/storage/1234-5678/Android/data/org.ppsspp.ppsspp/".

We could make a selection for this based on the return values of `getExternalFilesDirs(null)`.  I don't know how to detect if the device manufacturer has allowed write outside of this based on the normal external storage write permission.

Interestingly, on a device I reproduced this with - both /storage/emulated/0/ and /storage/1234-5678/ were owned by root:sdcard_rw and had the same permissions and selinux context.  Sigh.

-[Unknown]

**Comment by Saramagrean** [comment]
Change to "mnt/media_rw/1098-BF03" It's work!!
Screenshot_PPSSPP_20190330-185041

**Comment by Saramagrean** [comment]
Set path to "/storage/SD Card name/Android/data/org.ppsspp.ppsspp/" is work too, but use the File explorer app create folder "org.ppsspp.ppsspp" folder before adjust settings. If folder is not created, PPSSPP will not be able to use this path. 
Screenshot_PPSSPP_20190410-073045

**Comment by unknownbrackets** [comment]
Huh, PPSSPP on my device could create the path.  Annoying that there's so much difference between devices here.

From what I understand of changes planned in the next Android version, this is only going to get more problematic...

-[Unknown]

**Pull request merged**
