### PR TITLE
PostShaders translation

### PR DESCRIPTION
**Pull request by vnctdj**
To translate shaders we get strings from https://github.com/hrydgard/ppsspp/blob/master/assets/shaders/defaultshaders.ini.
The problem is that we use the string between square brackets to display the shader name when it's in the main screen, and we use the string at the "Name=" line to display the shader name when it's in the corresponding popup.
Therefore, each of these strings requires its proper translation.
But it's useless to have 2 different strings for 1 shader name, we should always use the string at the "Name=" line.

This is what I have done in this pull request.
It seems to work well... But I'm not sure, should we change more things in the code ?

### CODE REVIEW

**Comment by hrydgard** [comment]
Makes sense. I'll merge after 1.0.1 though, which will be later this week.

**Comment by vnctdj** [comment]
Thanks, I will wait then :)
What about my (minor) other pull request ?

**Comment by vnctdj** [comment]
Oops sorry, this merge was useless :/

**Comment by vnctdj** [comment]
I have just noticed that my changes broke the shaders themselves...
I'm working on a fix.

**Comment by vnctdj** [comment]
Too bad I can't reopen this pull request, I have opened another here : https://github.com/hrydgard/ppsspp/pull/7467
Sorry about this, I'm still a beginner in Git :/

**Pull request closed without merging**
