### PR TITLE
(UWP) Update Manifest Files

### PR DESCRIPTION
**Pull request by ghost**
Updates version string to 1.16.5.

### CODE REVIEW

**Comment by hrydgard** [comment]
I'm not sure we should add all these file extensions.. I noticed that on my Windows PC, the UWP build had somehow registered itself for them, but double clicking a game to launch didn't actually work for some reason.

**Comment by GABO1423** [comment]
> I'm not sure we should add all these file extensions.. I noticed that on my Windows PC, the UWP build had somehow registered itself for them, but double clicking a game to launch didn't actually work for some reason.

Hmmm, alright then. I'll just make this a version string update then.

**Review by hrydgard — APPROVED** [review]

**Comment by hrydgard** [comment]
I'll add updating this version number to my checklist so I don't forget next time. Or maybe we can find a way to automate it from the git tag...

**Comment by ANR2ME** [comment]
> I'm not sure we should add all these file extensions.. I noticed that on my Windows PC, the UWP build had somehow registered itself for them, but double clicking a game to launch didn't actually work for some reason.

May be we're missing the "Handle the activated event"? https://superuser.com/questions/1599952/associate-file-extension-to-uwp-windows-10-app-not-in-open-with-list
But it only have C# and VB example, unlike the URI activation event that have C++ example too.

**Comment by GABO1423** [comment]
> Or maybe we can find a way to automate it from the git tag...

I don't think that really can be done as-is, but I do know that if we generate the UWP vcxproj and sln files with CMake, it's possible to define the string based on the git tag via a CMake command. Of course that means adding CMake support for the UWP builds in the first place, but other than that it just has to be done manually sadly.

**Comment by ANR2ME** [comment]
> > Or maybe we can find a way to automate it from the git tag...
> 
> I don't think that really can be done as-is, but I do know that if we generate the UWP vcxproj and sln files with CMake, it's possible to define the string based on the git tag via a CMake command. Of course that means adding CMake support for the UWP builds in the first place, but other than that it just has to be done manually sadly.

We can use powershell script to update the version isn't? https://www.codeproject.com/Articles/1023041/Automatically-Incrementing-the-Package-appxmanifes

**Comment by GABO1423** [comment]
> > > Or maybe we can find a way to automate it from the git tag...
> > 
> > 
> > I don't think that really can be done as-is, but I do know that if we generate the UWP vcxproj and sln files with CMake, it's possible to define the string based on the git tag via a CMake command. Of course that means adding CMake support for the UWP builds in the first place, but other than that it just has to be done manually sadly.
> 
> We can use powershell script to update the version isn't? https://www.codeproject.com/Articles/1023041/Automatically-Incrementing-the-Package-appxmanifes

There's an inherent issue with that, when do we run it? We don't want to run it when using the workflow/making a build locally since this should only be increased when a new version of PPSSPP is released. And if we make a script at all, it would have to be run manually whenever a PPSSPP update is released, and at that point you might as well just manually update the string in the files anyway.

**Comment by ANR2ME** [comment]
Yes, what i meant was updating the version string instead of incrementing it, just using the link as reference for the poweshell script to access the property.

**Pull request merged**
