### PR TITLE
GPU: Remove clear framebuf on first use speedhack

### LINKED ISSUE #13295: Figure out what to do with the framebuffer-clear optimization hack
We've long unintentionally (through forgetfulness) had a hack enabled that clears framebuffers on the first use - but only in OpenGL on mobile devices. After some cleanup, it's currently set like this in the FramebufferManagerCommon constructor:

```
clearFramebufferOnFirstUseHack_ = gl_extensions.IsGLES;
```

Basically, it forces a clear the first time we use a framebuffer during a frame. This is incorrect but seems to have few bad effects.

Clearing the framebuffer before drawing can be hugely beneficial on mobile chips (tiled renderers), since they can avoid loading the old framebuffer contents from main memory into tile memory. Some modern desktop chips can benefit too but not nearly as much. 

Since this is only enabled with OpenGL ES, it's possible that this could account for some reports of Vulkan being slower than GL on some devices (could of course also be driver issues or us doing something suboptimally, but...).

This could also be the cause of rendering bugs (effects that rely on previous frame data getting lost), though I don't know any that this is suspected of being the cause of.

Anyway, I see a few options:

* Also force-enable it on Vulkan for known "tiled" GPUs. Could introduce bugs.
* Enable it for everything (since the benefit it so tiny on non-tiled GPUs, probably not a good idea)
* Get rid of it entirely, slowing down GL ES
* Create a setting, default to true on tiled GPUs / mobile

Any other ideas?

### PR DESCRIPTION
**Pull request by unknownbrackets**
Wasn't helping much.  Fixes #13295.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Agreed, it's not worth it.

**Comment by kage2051** [comment]
I recently made some tests on a relatively recent Adreno device and didn't notice any regressions. However, my concern here is that this change might slow down some GLES 2.0 devices, such as the Mi Box S which uses an old Mali-450 GPU.

**Comment by unknownbrackets** [comment]
Well, that's the reason for disabling after a stable release - hopefully someone will use a git build and come along and tell us if we're wrong.  But I will say, a challenge is that no one is testing with this - it's another setting with questionable (if any) benefit on most devices that people can use to get new and exciting bugs that no one else sees.

If there's any device that really benefited we should bring it back but we already disabled by default in 1.11.0, so I'm hoping someone will complain about PPSSPP getting slower already if it's a problem.

-[Unknown]

**Comment by kage2051** [comment]
> If there's any device that really benefited we should bring it back but we already disabled by default in 1.11.0, so I'm hoping someone will complain about PPSSPP getting slower already if it's a problem.

That is why I'm planning on doing tests on slower devices, the Mi Box S is a perfect sandbox for that since it's the only GLES 2.0 device that's still being sold surprisingly.

**Pull request merged**
