### PR TITLE
Make compilable under VS2015

### PR DESCRIPTION
**Pull request by Bigpet**
the reason for the std::bind removal is that it threw an error about not being able to keep VertexData aligned

### CODE REVIEW

**Comment by hrydgard** [comment]
Right. Not really sure what the timezone stuff is about though? Did something change with _MSC_VER?

**Comment by Bigpet** [comment]
goes with https://github.com/Kingcom/armips/pull/29 and https://github.com/hrydgard/native/pull/264 but does not depend on them.

Additionally to actually compile it on VS 2015 you need to enable this option on the include and library paths (to make it find the new universal C library): 

image


the timezone thing is already deprecated and was now finally actually removed

**Comment by Bigpet** [comment]
the timezone thing is already deprecated and was now finally actually removed

the current headers say 
    
    /*
    daylight, timezone, and tzname are not available under /clr:pure.
    Please use _daylight, _timezone, and _tzname or
    _get_daylight, _get_timezone, and _get_tzname instead.
    */

and the docs on https://msdn.microsoft.com/en-us/library/htb3tdkc.aspx
even say `These global variables have been deprecated for the more secure functional versions, which should be used in place of the global variables.`

So maybe it should be the function `_get_timezone` instead.

Also, I forgot about non __GLIBC__ platforms like BSDs, etc, so I probably need to change that a little

**Comment by unknownbrackets** [comment]
The `#else` wasn't meant to be Visual Studio specific, it was meant for non-glibc.  Maybe a new `#elif` is needed instead.

-[Unknown]

**Comment by Bigpet** [comment]
Alright, that should be better

**Pull request merged**
