### PR TITLE
Fix Pangya(KS).

### LINKED ISSUE #12492: Pangya - Infinite loading. (Android/Windows)
### What happens?
Game infinite loading in every mode. since v1.9.3-91-ge09296b9b.
Pangya1
Pangya2

### What *should* happen?
Game can loading and play normally in every mode. :)

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
- Huawei P9 Plus (Android 8.1/Kirin 955/Mali T-880)
- Windows 10 64 bit (i5 6200U/Gefore 940M)
and Use PPSSPP v1.9.3-140-ga8d2e513b with default settings.

### PR DESCRIPTION
**Pull request by shenweip**
Pangya(KS) seems want to check something base on a delay(over 15ms) and system time.Anyhow, the game work now.

Also fix #12492 ,the issue occur since commit e09296b9b10d6ee9997dcd86bc10d172a48a4b1b,re-grab SCE_KERNEL_ERROR_NOCWD now.

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm, the delay is fine, maybe even don't need the REALISTIC check, but the NOCWD thing... needs thinking about.

Were you able to determine which in particular of the many  "|| error == SCE_KERNEL_ERROR_NOCWD" changes that fixed it?  Because I think that in many or most of the cases, it's not correct to ignore the error. Some hardware testing may be needed here.

**Comment by hrydgard** [comment]
Cool, that puts a little more light on what might be going on here. @unknownbrackets it seems that a NOCWD error can linger around and prevent a successful open? Or something like that? I don't have time right now to dig deep but will look again in the weekend.

**Comment by shenweip** [comment]
Yeah, I think i misunderstand someting.@hrydgard The game actually need a SCE_KERNEL_ERROR_NOCWD to return to sceIoOpen if the file not found.But SCE_KERNEL_ERROR_NOCWD was missed since commit e09296b and overwritten by ERROR_ERRNO_FILE_NOT_FOUND because file path mapping is successful.

**Comment by unknownbrackets** [comment]
Hmm, if anything I'd prefer returning `-SCE_KERNEL_ERROR_NOCWD` to get a positive value, and then just return `-error` if `error != 0` and `error > 0`.  Though, I think ignoring that error in some calls is just papering over other bugs.

-[Unknown]

**Comment by shenweip** [comment]
> Though, I think ignoring that error in some calls is just papering over other bugs.

@unknownbrackets Do you mean not ignoring the positive value from `MapFilePath()` would be better?It seems to be likely to break somethings?

**Comment by unknownbrackets** [comment]
I mean that `SCE_KERNEL_ERROR_NOCWD` should probably be returned by all calls as an error, not just sceIoOpen.  That is, it should just be `return SCE_KERNEL_ERROR_NOCWD;` not `return 1;`.

If that breaks anything, in theory it just means we've got an issue with cwd management.  IIRC doing that before broke Final Fantasy 3 or something, but decent chance we've fixed that bug by now...

-[Unknown]

**Comment by shenweip** [comment]
Alright,thanks @unknownbrackets ,done now.

**Review by unknownbrackets — APPROVED** [review]

**Comment by hrydgard** [comment]
Cool, looks good.

**Pull request merged**
