### PR TITLE
Add Dream Club PixelDepthRounding

### LINKED ISSUE #6497: Dream Club portable graphic issue
v0.9.8-1000-ga675c30 no problem

v0.9.8-1018-g318f641 human some problem
v0.9.8-1020-gcda9833 cannot see human
v0.9.8-1061-gcda9833 cannot see human
v0.9.8-1142-g1415532-windows-amd64\ bg full black
v0.9.8-1206-g9503603 cannot see human
v0.9.8-1219-gf664979 cannot see human
v0.9.8-1235-gd1357e5 semi problem on human
v0.9.8-1282-g935f1cb semi problem on human
v0.9.8-1538-gbe0340b semi problem on human

v0.9.8-1018-g318f641 log:
https://gist.github.com/sum2012/13c11126d5b9add2ef81
v0.9.8-1538-gbe0340b log:
https://gist.github.com/sum2012/b8d15983366d98e19a7e

### PR DESCRIPTION
**Pull request by sum2012**
Fix #6497

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Well, I'm not sure if this is "the fix".  It makes me think something else is wrong...

-[Unknown]

**Comment by daniel229** [comment]
Will cause flickering in Jeanne d'Arc.

**Comment by sum2012** [comment]
@daniel229 Thanks,
I haven't tested Jeanne d'Arc.

**Comment by daniel229** [comment]
Still not fixed Dream Clud in D3D.
OpenGL


D3D9

**Comment by sum2012** [comment]
I will check again when back home

**Comment by sum2012** [comment]
Strange,I don't have that problem

**Comment by daniel229** [comment]
It happens with 4x resolution.

**Comment by sum2012** [comment]
Yes....

**Comment by hrydgard** [comment]
Not sure what to do with this ... at a minimum it needs a rebase.

**Pull request closed without merging**
