### PR TITLE
Update and rename PPSSPP.desktop as well as add PPSSPPSDL.desktop for Linux AppImages

### PR DESCRIPTION
**Pull request by ghost**
I am proposing to change the name and contents of "PPSSPP.desktop" in the "Qt" folder as well as add "PPSSPPSDL.desktop" to the "SDL" folder for the creation of AppImages.

Please note that I do not know if the "PPSSPP.desktop" file is being used for other reasons.

### CODE REVIEW

**Comment by hrydgard** [comment]
I would suggest that you stick to the SDL build and don't even try to package the Qt build. The latter is unmaintained, lacks major features and is really not recommended.

Unless you want to volunteer for maintaining the Qt build, that is...

**Comment by sandboxgamedev123** [comment]
Okay. I plan on making an SDL build. If there is a reason for me to use Qt instead, I might volunteer to be the maintainer of the Qt build.

**Comment by Miguel-hrvs** [comment]
If you want some appimage reference here you have mine: https://gitlab.com/Miguel-hrvs/ppsspp-appimage

**Comment by Samueru-sama** [comment]
Btw please if you are going to make an appimage, use [this](https://github.com/probonopd/go-appimage) appimagetool as it makes the appimage `fuse3` compatible.

That appimagetool can also do the job of linuxdeploy, but I haven't had much luck with it, so I stick to using linuxdeploy + that appimagetool.

**Comment by sandboxgamedev123** [comment]
I changed from Qt to SDL for the 32-bit and 64-bit AppImage builds.

However, if anyone has questions regarding a Qt build I can try to help.

**Review by hrydgard — APPROVED** [review]

**Pull request merged**
