### PR TITLE
Add flags to turn off parts of jit

### PR DESCRIPTION
**Pull request by unknownbrackets**
Related to #11753, but doesn't actually add any UI yet.  The flags work, but are at this point ini-only.

Felt like the simplest way was to reuse CONDITIONAL_DISABLE.  Tried to create a few useful categories for a basic level of "bisecting."

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Oh, I just started hacking on this - let's use yours :) 

I was thinking about having one bitfield per category and thus room to disable most instructions individually, but maybe that'd be overkill. This is a good start, anyway.

**Comment by hrydgard** [comment]
Oh yeah, we should probably disable reporting when any of these disabling flags are set, as behavior could diverge if there are bugs.

**Comment by unknownbrackets** [comment]
Ah, sorry.  It seemed like a quick thing I could do while doing something else at the same time, heh.

Hmm, we could always move to separate bitfields per category later.

-[Unknown]

**Comment by hrydgard** [comment]
Yup.

**Comment by hrydgard** [comment]
There's a compile error in ArmCompVFPUNEON.cpp , FYI

**Comment by hrydgard** [comment]
I'll build the UI.

**Pull request merged**
