### PR TITLE
Serve local web debugger from assets

### PR DESCRIPTION
**Pull request by unknownbrackets**
This packages the debugger at https://github.com/unknownbrackets/ppsspp-debugger into assets, and serves it from PPSSPP itself when remote debugger is enabled.

Web browsers are going to be restricting public web URLs from accessing anything determined as internal, which would include PPSSPP's API.  Serving from PPSSPP should avoid this restriction for now, although currently there's no automatic way to know the URL.

Of course, updates to the web debugger will require the submodule to be updated.  Importantly, this is tracking an orphan branch that has the built files output (rather than the source files, since there's a compilation process.)  The build process is in the README and also in GitHub Actions, which adds a commit to the `bundled` branch on every merge to master for ppsspp-debugger.

Only tested this on Windows for now.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Ah yeah, this should work fine.

Always slightly scared of pointing submodules to branches of github repos, since in my experience they have a bad habit of disappearing, but shouldn't be an issue here.

**Comment by unknownbrackets** [comment]
I think it doesn't work unless you have the `branch` value set on the .gitmodules config - I think it only fetches the specified branch when doing a submodule update.

-[Unknown]

**Comment by hrydgard** [comment]
Well I think it's more that actual commit hashes can disappear from github repos when you delete branches. (I've only had these issues in completely unrelated projects, btw, so may have been configured suboptimally)

**Comment by unknownbrackets** [comment]
Oh ok, yes that would happen on gc so might happen unpredictably.  I don't plan to ever delete this branch, though, and I think it'd be recreated by the action anyway.

-[Unknown]

**Comment by hrydgard** [comment]
But if it's recreated by the action, the old commit hash will fall out of date immediately?

**Comment by unknownbrackets** [comment]
Ah, sorry you're right.  But I won't delete it anyway.  To be sure, I just enabled branch protection so GitHub will reject deletions or force pushes.

-[Unknown]

**Comment by hrydgard** [comment]
Okay, so subsequent releases will end up in new commits on that branch, and will not replace the branch entirely with a new one with the same name then. That should be safe.

**Pull request merged**
