### PR TITLE
Fixed new shader name not displaying correctly

### PR DESCRIPTION
**Pull request by Leopard20**
Sorry. I don't know why the name wasn't correct. This should fix it.

### CODE REVIEW

**Comment by hrydgard** [comment]
That's weird? We should be displaying the name...

**Comment by leopard20** [comment]
I know. But just displayed the tag [ ], NaturalA!

**Comment by hrydgard** [comment]
Got it, it's a bug. I'm fixing it.

**Comment by hrydgard** [comment]
Fixed in the upcoming build, this isn't needed.

**Pull request closed without merging**
