### PR TITLE
Android: Show some Java exceptions as they happen

### PR DESCRIPTION
**Pull request by hrydgard**
These are very bad and we want to know about them, so pop them up in angry red.

Will probably later hook up to our reporting system too.

### CODE REVIEW

**Comment by IrfanH495** [comment]
sorry i want to ask, all these permissions have been allowed, but nothing happens.
Screenshot_20230707-022901_PPSSPP
Screenshot_20230707-023347_Permission controller

**Comment by hrydgard** [comment]
Fixed

**Comment by IrfanH495** [comment]
because I don't understand, all my save data,DLC is lost, lol 😅😆😆😆😆🤣
Screenshot_20230707-031523_PPSSPP
Screenshot_20230707-031706_ZArchiver
Goodbye Save data Zettai zetsumei toshi 3 multiplayer & final fantasy type-0 multiplayer

**Comment by IrfanH495** [comment]
it's ok, i've searched there is no new psp folder in my storage.
after all it's just save data and Dlc not the game.

**Comment by hrydgard** [comment]
Well there is no way your data got deleted. It's there.

**Comment by IrfanH495** [comment]
I've searched with the name cheat/save data/uljm******, nothing comes up, just like the picture above that appears 133kb in size on the psp.and my storage is bigger as I remember it is 1.6*gb.
this is my own fault, maybe my device is the problem.

**Comment by hrydgard** [comment]
check in /Android/data/org.ppsspp.ppsspp ?

**Comment by IrfanH495** [comment]
there is nothing in it, my android 10 permissions still easy.
Screenshot_20230707-041359_ZArchiver

**Pull request merged**
