### PR TITLE
Add ant build script for Android in windows

### PR DESCRIPTION
**Pull request by sum2012**

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm, I think it's better to build all the ABIs by default. Otherwise you'll produce binaries that only work on ARMv7 devices (and suboptimally on ARMv8). Of course, you can add a few commented out lines that only build specific ABIs to this script if you like, as it's only an example that is meant to be modified.

**Comment by sum2012** [comment]
What is the command for build all  ABIs by default ?

**Comment by hrydgard** [comment]
Very simple:

    ant release -Dndkbuildopt="-j6"

**Comment by sum2012** [comment]
done

**Comment by unknownbrackets** [comment]
I'm personally against tracking files that are useless without modifications.  So basically guaranteed dirty tree.

-[Unknown]

**Comment by hrydgard** [comment]
Well, it's kind of documentation, not unlike a readme, just named .bat  :P   You do have a point though - should probably simply be in the build guide in the wiki or actually in the README or similar. It is, kind of, in the wiki - though it recommends "android update" to be run first which is no longer needed?

**Comment by unknownbrackets** [comment]
I think that triggers the SDK to update itself, so probably not a bad idea, I suppose.

-[Unknown]

**Pull request merged**
