### PR TITLE
Add UI Tint/Saturation settings

### PR DESCRIPTION
**Pull request by hrydgard**
Does the color tinting in the vertex shader.

Makes the background grayscale, and sets a color, so it'll follow the tint properly.

Lighter alternative to full custom themes as in #15394, although I'm kinda torn which way to go.

iota97 started work on the same too at my suggestion. This uses a simpler hsv conversion, not sure which one looks best though. Adds support for all the backends too.

### CODE REVIEW

**Comment by iota97** [comment]
Just a few thing to improve the UI:
- Remove darkening background (kinda off with live update)
- Allow to increase saturation as well

Pushed it here: https://github.com/iota97/ppsspp/tree/vertex-hue-ui

Time to make a RGB animation now ;)

**Comment by hrydgard** [comment]
Pulled your change, nice, makes sense.

**Comment by hrydgard** [comment]
Still a bug left with uniform bufer sizes, fixing.

**Comment by iota97** [comment]
Pushed at the [same branch as before](https://github.com/iota97/ppsspp/tree/vertex-hue-ui) a fix for the live update that wasn't quite complete :P

**Comment by Gamemulatorer** [comment]
how about this now?

**Comment by hrydgard** [comment]
Confirmed that this does indeed work just fine on Mali-400.

**Pull request merged**
