### PR TITLE
OpenXR - Modify camera parameters in realtime

### PR DESCRIPTION
**Pull request by lvonasek**
To modify the VR camera, map "VR camera adjust" button on any button.

When you hold the "VR camera adjust" button you can modify:
* the side move or the camera height using left joystick.
* the fov or the camera distance using right joystick.
* reset to default by pressing the joystick

https://user-images.githubusercontent.com/6472545/198678067-64756b2a-6bcc-4e9b-88ec-57312d7565d5.mp4

### CODE REVIEW

**Comment by hrydgard** [comment]
That's cool. However, the mapping to CTRL_HOLD is a little odd, we should probably just define a new virtual key.

Though to be honest, I've forgotten what CTRL_HOLD is anyway...

**Comment by lvonasek** [comment]
I somehow hoped CTRL_HOLD holds the scene without moving, however it seems it does currently nothing.

**Comment by hrydgard** [comment]
Well, games can listen to it, if they feel like it. I just don't know which actual input it is :)

**Comment by hrydgard** [comment]
Anyway, even if it's unused, CTRL_HOLD isn't the right semantic, though it kinda sounds like it :)

Do feel free to create a new virtual binding for this, search for say "VIRTKEY_OPENCHAT" in the code, the rest should be easy to figure out.

**Comment by unknownbrackets** [comment]
On the PSP, the power switch had three positions: you pulled it upward to turn the device on or put it to sleep, and otherwise it sat in the middle.  You could pull it downward to activate "hold" (it would stay in this position until moved out of hold.)

From memory, during "hold" it would continue to display the screen but other inputs were typically non-responsive (I assume at the OS level because I think this worked in all games I know of.)  You could, for example, turn off the screen and switch to "hold" mode, then put it in your pocket to listen to music.

I'm not aware of any games that actually use "hold", but sometimes it was used to activate cheats.

-[Unknown]

**Review by hrydgard — APPROVED** [review]

**Pull request merged**
