### PR TITLE
Avoid discard when we can blend

### PR DESCRIPTION
**Pull request by unknownbrackets**
In this situation:
 * No depth/stencil write.
 * No logic op.
 * Alpha blending enabled with src based on alpha and dest not.

We can replace `discard` with `alpha = 0.0`.  Because alpha, stencil, and depth won't be written in this situation, color is the only thing affected and that will blend based on output alpha.

The details of #11227 seem strange, but this may help that scenario.  More generally, it may improve performance in some games on PowerVR.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
I like the idea! Yet another cause of more shader permutations though :)  Not sure if that's an issue or not. The slowdown mentioned by #11227 is probably not just a shader compile stutter, right, btw.. It's very odd.

Anyway, are all these conditions fulfilled often? Got any examples of games other than 11227?

**Comment by unknownbrackets** [comment]
Some games that trigger this shader:
 * Yggdra Union
 * Legend of Heroes 3
 * Ridge Racer
 * Kingdom Hearts
 * Crisis Core
 * 3rd Birthday
 * Lunar Silver Star Harmony
 * MotorStorm Arctic Edge
 * Jeanne d'Arc
 * Final Fantasy 3

I didn't check exactly where, but some did it early on, and some only in a few parts.  That said, it does appear to be fairly commonly found in games, at least.

-[Unknown]

**Comment by unknownbrackets** [comment]
Oh, and presumably it is not just stutter for that issue, because my understanding is that it's reproducible.  We should be precompiling the second time around.

-[Unknown]

**Comment by hrydgard** [comment]
OK cool. Let's go for it, easy to turn off anyway in case of issues.

**Comment by marosis** [comment]
Can this improve performance on OpenGL too or only on Vulkan?

**Comment by marosis** [comment]
Thank you @unknown

**Pull request merged**
