### PR TITLE
Update to xBRZ 1.2, with its perf improvements

### LINKED ISSUE #7443: Support for xBRZ 1.2 ?
PPSSPP seems to have xBRZ 1.1 but xBRZ 1.2 come out recently with over 30% performance boost.
http://sourceforge.net/projects/xbrz/files/xBRZ/

### PR DESCRIPTION
**Pull request by unknownbrackets**
Performance improvements in PPSSPP not measured, but xBRZ expects 30% improvement.  Fixes #7443.

I did nerf a few whitespace-only changes.

All I did to test was run a few games with 5x scaling.  It seemed possibly faster but I didn't bench anything.  Didn't notice any differences in how it looked (which is expected.)

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
Looks less stutterings in Dai-2-Ji Super Robot Taisen Z.

**Comment by hrydgard** [comment]
I know it's not your implementation, but this seems rather wasteful with RAM. I'm convinced you can get the same benefit by optimizing the code a bit instead of adding a giant 64MB lookup table...

**Comment by unknownbrackets** [comment]
Well, I agree, was just updating it.  I guess another 64MB of usage might be bad on mobile...

-[Unknown]

**Comment by VIRGINKLM** [comment]
Want to do a real benchmark on it? Grab Kingdom Hearts Birth By Sleep and go to Mirage Arena.

**Comment by ThePhoenixRises** [comment]
xBRZ 1.2 could be made into an extra option in the xBRZ / xBRZ 1.2 / Hybrid / Bicubic / Hybrid + Bicubic
And by default put it to the xBRZ thus allowing more devices to work still.

**Comment by unknownbrackets** [comment]
I've updated it to at least only allocate the 64MB upon use.  Performance impact seems nil.

@Zenju are there more plans with this code?  I assume it's been tried, but I wonder if there are opportunities to calculate the `dist()` in parallel via SIMD (not as a lookup.)

By the way, it seems to me `luminanceWeight` is no longer used/supported, but I didn't take a very deep look.  We don't use it anyway so it's not a problem for us.

By the way, how much does the quality degrade when using floats throughout rather than doubles?  It seems to me the range of the distances is e.g. [0, 512) or so, with some values adding 8 of those together.  Still only [0, 4096) so singles might give okay results?

I also found that this:
```c++
		double d = distYCbCrBuffer->dist(pix1, pix2);
		if (a1 > a2)
			return a2 * d + 255.0 * (a1 - a2);
		else
			return a1 * d + 255.0 * (a2 - a1);
```

Gave a better profile than:
```c++
		return std::min(a1, a2) * distYCbCrBuffer->dist(pix1, pix2) + 255 * abs(a1 - a2);
```

But I couldn't consistently tell any improvement in overall perf.  Obviously a good compiler should make these equal anyway.

-[Unknown]

**Comment by Zenju** [comment]
>@hrydgard: I know it's not your implementation, but this seems rather wasteful with RAM. I'm convinced you can get the same benefit by optimizing the code a bit instead of adding a giant 64MB lookup table...

Hehe, go for it. I wasn't able to squeeze a dime out of the old code, but then adding buffering with xBRZ 1.2 improved perf by 30% in my tests just like that. The multi-layered CPU-caches will be very hard to beat by repeating calculations instead.

>@unknownbrackets: I've updated it to at least only allocate the 64MB upon use. Performance impact seems nil.

Your initialization sequence contains a memory race-condition. This was basically the reason why I did the init at global scope.

> @Zenju are there more plans with this code? I assume it's been tried, but I wonder if there are opportunities to calculate the dist() in parallel via SIMD (not as a lookup.)

I don't see any potential with SIMD, but if you do, then go for it! However perf improvements with portable code are preferred of course and up to until now they also seem sufficient.
At the current stage xBRZ perf is optimized to a level where CPU instruction cache misses matter a lot. Therefore I think it will be very hard to top the current perf much more.

> By the way, it seems to me luminanceWeight is no longer used/supported, but I didn't take a very deep look. We don't use it anyway so it's not a problem for us.

This parameter was only used during intial parameter tuning and was left in for a while because perf measurements showed that leaving it in didn't matter.

> By the way, how much does the quality degrade when using floats throughout rather than doubles?

Quality doesn't degrade, buf performance with floats is worse than with doubles in my tests. Might have to do with CPUs optimizing mainly for double nowadays.

> I also found that this: [...] return std::min(a1, a2) * distYCbCrBuffer->dist(pix1, pix2) + 255 * abs(a1 - a2);

Very nice! In my tests this gives 15% better perf in the ARGB case! Obviously this different layout enables much better code generation in Visual Studio! Applied for the next xBRZ release! :)

At this stage of optimization it's hard to tell what else can be done and how much potential is still left. There really is no substitute to doing tests and measuring perf manually.
For example, with the new xBRZ 1.2 buffering I expected I could divide memory consumption in half by taking advantage of the symmetry of the distance function, i.e. dist(pix1, pix2) == dist(pix2, pix1). However when I added a check like "if (pix1 > pix2) std::swap(pix1, pix2);" perf went down by 30%! Instead I had expected an improvement due to lower CPU cache misses on memory, but other factors are in fact dominating. Therefore: always measure :) Great feedback, BTW!

**Comment by hrydgard** [comment]
Hm. If you make sure to use sqrtf instead of sqrt, etc, there's no way float should be slower than double in MSVC 2012+... There was an issue with older MSVCs in 32-bit mode where it would generate excessive conversion operations but it's fixed, and was never an issue in 64-bit mode.

**Comment by unknownbrackets** [comment]
Oh, right, forgot it's called on multiple threads.  I'll just call it in a separate init beforehand.  Thanks for the catch.

Well, I wonder how the performance profile differs on ARM chips.  They're likely to behave differently as far as caches and could handle single floats better than doubles.  I'm sure some people are using xBRZ on more powerful ARM tablets and etc. now with PPSSPP... hmm.

-[Unknown]

**Comment by unknownbrackets** [comment]
Hmm, I'm seeing roughly equivalent or tiny, tiny bit better performance with all floats.  Not sure I've got a good test for perf though here, since it wasn't giving me good, consistent results for the alpha change.

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets both on ARM and x86? I think I would expect double to be slower on ARM especially. Although maybe that impression comes from the fact that x86 can do SIMD with doubles while ARM cannot until ARM64..

**Comment by unknownbrackets** [comment]
Only tested on x64 really, need to set up something better to test on other platforms (right now my test basically consists of running each texture through scaling 100x and logging the time it took, with threading disabled so I can profile better.)

-[Unknown]

**Comment by ThePhoenixRises** [comment]
Any idea if & when you guys intend to implement this code into PPSSPP as this would be very interesting to test on the game, with & without this activated to see the difference this would make.

**Comment by hrydgard** [comment]
@ThePhoenixRises it's in now.

**Pull request merged**
