### PR TITLE
split SDLJoyButtonMap for MacOSX and linux. 

### PR DESCRIPTION
**Pull request by chrisbrasington**
Mapping in else statement was tested on linux with a X360 and wii-u pro controller. Furthering #8285

hrydgard, I'm not 100% on all your environment variables (WIN32, APPLE, LINUX), but I figured it made more sense to give APPLE its own section and let the else statement catch LINUX.

### CODE REVIEW

**Comment by hrydgard** [comment]
Oh, I didn't know we needed a third mapping, figured most platforms could use the Windows one, from eariler reports? But if you tested this one to work, I guess it's fine...

**Comment by chrisbrasington** [comment]
There's a few quirks where the Windows mapping doesn't work for me. The "L2" and "R2" triggers... well they're not triggers on a wii-u pro controller , but buttons. And then I would still need to add a button. I think it's the extra HOME button that throws it off.

But yeah, in linux this works great for X360 and wiiu-pro. Especially the DPAD usage.

**Comment by hrydgard** [comment]
Just would be annoying to get into a situation where I merge one mapping, then someone else chimes in and says on their linux the mapping has to be different...

BTW if you look at the diff, the indentation is different for some reason. Would be nice to not introduce a difference...

**Comment by chrisbrasington** [comment]
I hear you on that. I think the only important part really is supporting enough buttons, I don't care much what they're called. 

Alright, fix indentation is part of this request.

**Comment by hrydgard** [comment]
Alright, let's see how this works for people...

**Pull request merged**
