### PR TITLE
Update README for 1.4.2

### PR DESCRIPTION
**Pull request by hrydgard**
Release tomorrow - anything else needs adding? Still accepting minor fixes.

### CODE REVIEW

**Comment by iOS4all** [comment]
@hrydgard hi there. isn't there any news on micro stutter on iOS?
You take this issue as a milestone on version 1.4.1.
If you don't have time for this it's ok and take your time.
Thanks.

**Comment by DarkLegend481** [comment]
@hrydgard Any news about the UWP version of PPSSPP? It will be released with some version of 1.4 or on the 1.5.0 release?

**Comment by hrydgard** [comment]
@DarkLegend481  Well, MS banned emulators from the store, apparently, so I haven't worked on it more...

**Comment by DarkLegend481** [comment]
@hrydgard Windows 10 can install applications from outside the store... You could end the UWP version and release the appx... :)

**Comment by hrydgard** [comment]
Well, yeah, but most of the point of an UWP version would be to make it easy to install on various tablet devices and stuff, is it easy to sideload? On a proper Win10 device you'll just use the desktop version, so I haven't prioritized it....

**Comment by DarkLegend481** [comment]
To sideload a app on Windows 10 (Mobile and PC), just open the appx and press install...

img2

**Comment by DarkLegend481** [comment]
I found a compiled version to use on Xbox One... But, I don't have a dev account on it :(

**Comment by hrydgard** [comment]
Alright, I'll try to set up builds soon...

**Comment by DarkLegend481** [comment]
Yay! Thanks!

**Comment by hrydgard** [comment]
No promises for when :)

**Comment by hrydgard** [comment]
Oops, managed to pull the trigger before merging this. oh well.

**Pull request merged**
