### PR TITLE
Update atlastool.cpp (add a bunch of korean characters)

### PR DESCRIPTION
**Pull request by mgaver**
Add more characters in learning routine for Korean font

### CODE REVIEW

**Comment by unknownbrackets** [comment]
I think we normally commit the atlas so it needs to be updated.  I wonder how much larger this makes it?  This adds 350 characters.

-[Unknown]

**Comment by hrydgard** [comment]
The atlas is very close to being completely full already unfortunately (although there is some junk in it, a bunch of "unknown character squares" that we should get rid of) so I doubt this will fit...

I plan to look into this later more, but won't make it for 1.2.0.

**Comment by hrydgard** [comment]
Tried it, and unfortunately this pushes the atlas beyond 2048x2048 which is the max size we can rely on working on Android devices. Pushing this to the future when we have better solutions for font rendering - if we can implement native font rendering on Android this won't be needed.

**Comment by hrydgard** [comment]
Now we have native font rendering for Android. Technically this is still needed for a few platforms (iOS, UWP) but I'm not gonna prioritize this any time soon so I'm closing.

**Comment by unknownbrackets** [comment]
Well, and also Linux/Mac, but sure.  Android and Windows are the biggest.

-[Unknown]

**Pull request closed without merging**
