### PR TITLE
Vulkan: Allow alt speed above 60 with vsync

### PR DESCRIPTION
**Pull request by unknownbrackets**
Enabling frameskip when needed.  Also don't enable frameskip when it's not needed, such as OpenGL on Windows with >100% alt speed.

See #12662.  I can't reproduce any unthrottling issues, though.

-[Unknown]

### CODE REVIEW

**Comment by vsub** [comment]
It's working but there is something strange.

1.If Vsync is enabled,the FPS(just the number)on unthrottling and alt speed don't change but the actual speed and percentage change
2.If Vsync is disabled the number changes according to the current speed

**Comment by unknownbrackets** [comment]
Well, that's correct.  If you unthrottle on Vulkan with vsync enabled, we are rendering 60 FPS, the other frames are being skipped.  It's the same way it displays with frameskip enabled.

So for example, 30/60 (100%) would mean frameskip=1.  It's the same concept, like 60/60 (200%) would be skipping 1 frame to reach 200% speed.

-[Unknown]

**Comment by vsub** [comment]
But the game looks the exact same way(as smooth).
60/60(200%) with vsync on look the exact same way as 120/60(200%) vsync off...all frames are rendered,nothing is skipped(frame skipping and FrameSkipUnthrottle  are not enabled)

If that the correct way then ok

**Comment by unknownbrackets** [comment]
Well, when we show 120/60 we are sending 120 frames to your graphics driver, it's just ignoring 50% of them most likely, since your display is probably 60 Hz.

-[Unknown]

**Pull request merged**
