### PR TITLE
Add range checks in replaced memcpy/memset functions.

### PR DESCRIPTION
**Pull request by hrydgard**
Keep seeing especially Replace_memcpy as a semi-rare crash in the reports. Hopefully this will take care of it, though if games hit this, they're probably on their way to failing somehow anyway.

Question - should we instead use Memory::ValidSize to clamp the ranges?

### CODE REVIEW

**Review by unknownbrackets — COMMENTED** [review]
I'd say we bail rather than clamp, although it'd be nice to actually "crash" when ignoring crashes is off, for debugging.  A `Memory::GetPointer()` would do that, or a Core_Exception.  That way if you're doing a romhack, you can tell you messed up instead of things just silently and frustratingly not working.

-[Unknown]

**Comment by hrydgard** [comment]
Hm. We kinda need Memory::GetPointer then, but for ranges, that will trigger the exception...

**Comment by unknownbrackets** [comment]
I did have a branch once where I made it so GetPointer took a required additional argument: size.  But it spiraled into a lot of changes and I decided to come back to it another time.

-[Unknown]

**Comment by hrydgard** [comment]
I guess that last commit is a mini version of your branch then :)

**Review by unknownbrackets — APPROVED** [review]

**Pull request merged**
