### PR TITLE
Reimplement bicubic upscaling.

### PR DESCRIPTION
**Pull request by fp64**
Integrated code from [#15774](https://github.com/hrydgard/ppsspp/issues/15774).

Only very lightly tested.

### CODE REVIEW

**Comment by fp64** [comment]
Hmm, running `./b.sh --headless && python3 test.py -g --graphics=software` on my machine results in
```
277 tests passed, 2 tests failed.
Failed tests:
  rtc/arithmetic
  rtc/lookup
```

**Comment by hrydgard** [comment]
There's something weirdly flaky about the tests on ubuntu, that we need to look into.

**Comment by fp64** [comment]
There is some mildly suspicious stuff in [Core/HLE/sceRtc.cpp](https://github.com/hrydgard/ppsspp/blob/master/Core/HLE/sceRtc.cpp), like using not fully zero-initialized [tm](https://en.cppreference.com/w/cpp/chrono/c/tm), despite:
> The Standard mandates only the presence of the aforementioned members in either order. The implementations usually add more data-members to this structure.

Though changing that specifically does not fix the tests.

**Comment by unknownbrackets** [comment]
It'd be ideal if you could follow the EditorConfig rules and just use tabs for indentation.  I realize this is code you wrote externally, but best to just stay consistent.

Does `const int MIN_LINES_PER_THREAD = 4;` need to be changed to 8, or is it fine because it will clamp to y0/y1 anyway?

Might be the Rtc tests fail due to some local timezone thing.  The sporadic failure needs to be looked into but is not likely related to Rtc...

-[Unknown]

**Comment by fp64** [comment]
> Does const int MIN_LINES_PER_THREAD = 4; need to be changed to 8, or is it fine because it will clamp to y0/y1 anyway?
I think it refers to the source image's lines, so the number of destination image's lines (what `upscale_cubic` cares about) would be at least 8 for all slices except, possibly, last. Still working on e.g. a 10-line slice would takes same amount of work as 16-line, so this is not optimal.

**Comment by unknownbrackets** [comment]
Okay, got it.  That sounds fine, then.

-[Unknown]

**Comment by fp64** [comment]
> It'd be ideal if you could follow the EditorConfig rules and just use tabs for indentation. I realize this is code you wrote externally, but best to just stay consistent.

Done, I think.

**Comment by fp64** [comment]
I should probably mention, that it upscales with Catmull-Rom ('bicubic', that is; 'hybrid' uses B-spline, because that's apparently what it wants), so it may look a bit sharper than a previous implementation (see [table](https://github.com/hrydgard/ppsspp/issues/15774#issuecomment-1201461940)).

Feel free to adjust B, C coefficients, or even expose them to the user.

**Comment by fp64** [comment]
Did a bit of profiling from the actual emulator, and the results are consistent with the synthetic benchmark before: the speedup for bicubic upscaling is about 10x (unlike the previous benchmark, this also includes multithreading). This only counts the CPU upscaling itself though, not the time it takes to upload the resulting texture to GPU.
Encountered no issues with it so far, so can be merged at your discretion.

**Comment by hrydgard** [comment]
Great, thanks!

**Pull request merged**
