### PR TITLE
GPU:Avoid "decimate" the usageFlags corrupted memory

### LINKED ISSUE #7625: GTA crash in debug build in vs2013
v1.0.1-202-gcac0519

 	ntdll.dll!00000000778bf0c1()	Unknown
 	ntdll.dll!000000007786fcc4()	Unknown
 	ntdll.dll!00000000778634d8()	Unknown
 	ntdll.dll!00000000778e70dd()	Unknown
 	ntdll.dll!00000000778ab5aa()	Unknown
 	ntdll.dll!00000000778634d8()	Unknown
	PPSSPPDebug64.exe!_heap_alloc_base(unsigned __int64 size) Line 58	C
 	PPSSPPDebug64.exe!_heap_alloc_dbg_impl(unsigned __int64 nSize, int nBlockUse, const char * szFileName, int nLine, int * errno_tmp) Line 431	C++
 	PPSSPPDebug64.exe!_nh_malloc_dbg_impl(unsigned __int64 nSize, int nhFlag, int nBlockUse, const char * szFileName, int nLine, int * errno_tmp) Line 239	C++
 	PPSSPPDebug64.exe!_nh_malloc_dbg(unsigned __int64 nSize, int nhFlag, int nBlockUse, const char * szFileName, int nLine) Line 302	C++
 	PPSSPPDebug64.exe!malloc(unsigned __int64 nSize) Line 56	C++
 	PPSSPPDebug64.exe!operator new(unsigned __int64 size) Line 59	C++
 	PPSSPPDebug64.exe!std::_Allocate<std::_Container_proxy>(unsigned __int64 _Count, std::_Container_proxy * __formal) Line 28	C++
 	PPSSPPDebug64.exe!std::allocator<std::_Container_proxy>::allocate(unsigned __int64 _Count) Line 579	C++
 	PPSSPPDebug64.exe!std::_Wrap_alloc<std::allocator<std::_Container_proxy> >::allocate(unsigned __int64 _Count) Line 848	C++
 	PPSSPPDebug64.exe!std::_Vector_alloc<0,std::_Vec_base_types<float,std::allocator<float> > >::_Alloc_proxy() Line 624	C++
 	PPSSPPDebug64.exe!std::_Vector_alloc<0,std::_Vec_base_types<float,std::allocator<float> > >::_Vector_alloc<0,std::_Vec_base_types<float,std::allocator<float> > >(const std::allocator<float> & __formal) Line 603	C++
 	PPSSPPDebug64.exe!std::vector<float,std::allocator<float> >::vector<float,std::allocator<float> >() Line 681	C++
 	PPSSPPDebug64.exe!http::Downloader::GetCurrentProgress() Line 444	C++
 	PPSSPPDebug64.exe!DrawDownloadsOverlay(UIContext & dc) Line 653	C++
 	PPSSPPDebug64.exe!NativeRender() Line 729	C++
 	PPSSPPDebug64.exe!UpdateRunLoop() Line 169	C++
 	PPSSPPDebug64.exe!Core_RunLoop() Line 211	C++
 	PPSSPPDebug64.exe!Core_Run() Line 269	C++
 	PPSSPPDebug64.exe!TheThread(void * __formal) Line 192	C++
 	[External Code]

### PR DESCRIPTION
**Pull request by sum2012**
Fix #7625

### CODE REVIEW

**Comment by Bigpet** [comment]
should the `else` not be for the `if (age > FBO_OLD_AGE) {` since that's the only path that deletes `vfb` (by calling `DestroyFramebuf`)

**Comment by sum2012** [comment]
Ok,I will try that when I get back home

**Comment by unknownbrackets** [comment]
I guess it was just "saved" by the resize generally not deallocating, probably.  Darn, my bad.  I also think it being above the if is simplest.  That, or a `continue;` inside the if.

It's important that the usage flags are updated for displayed framebuffers (which the current change would break.)

-[Unknown]

**Comment by hrydgard** [comment]
ok. so @sum2012 , just move UpdateFramebufUsage(..) to line 1151, instead of putting it in an "else". Thanks for finding the regression :)

**Comment by sum2012** [comment]
@Bigpet yes, move  UpdateFramebufUsage(vfb);  above that if also work
@unknownbrackets It is ok,finally I (and Bigpet) fixed the crash
@hrydgard This pull request is ready

**Pull request merged**
