### PR TITLE
Create as UTF-8 format of new cwcheat file

### LINKED ISSUE #4300: cwcheat font encode issue
Report from tieba
http://tieba.baidu.com/f?ct=335675392&tn=baiduPostBrowser&sc=40104401393&z=2641864230
When use orignal ansi format

When the cheat save as UTF-8 encode ,the issue solved.

Can we have two solution ?
1:When create new cwcheat,default is UTF-8 encode
2:Add "Auto convert cwcheat ansi to UTF-8 encode" function in PPSSPP

### PR DESCRIPTION
**Pull request by sum2012**
Fix #4300

### CODE REVIEW

**Comment by Bigpet** [comment]
pre C++11 fstream classes only take `char *` not `std::string` so just change `myCheatFile.open(activeCheatFile);` to `myCheatFile.open(activeCheatFile.c_str());`instead of that ifdef

**Comment by sum2012** [comment]
Thanks @Bigpet

**Comment by hrydgard** [comment]
Hm, I think this won't work if the PPSSPP directory contains unicode letters? 

I would propose:

    FILE *f = FileUtil::OpenCFile(activeCheatFile, "wb");
    if (f) {
      fwrite("\xEF\xBB\xBF", 1, 3, f);
      fclose(f);
    }

**Comment by sum2012** [comment]
@hrydgard 
It points to error to FileUtil
Error:name followed by "::" must be a class or namespace name

**Comment by Bigpet** [comment]
@sum2012 it's clearly just a typo he meant `FILE *f = File::OpenCFile(activeCheatFile, "wb");`

**Comment by hrydgard** [comment]
Yeah, of course I didn't mean to follow it exactly, I just wrote from memory, wasn't at my main computer :)

**Comment by sum2012** [comment]
I need a little time to do some test

**Comment by sum2012** [comment]
@hrydgard done
@Bigpet Thanks again

**Comment by sum2012** [comment]
@hrydgard you have another idea ?

**Pull request merged**
