### PR TITLE
Fix crash on windows debug build on exit

### PR DESCRIPTION
**Pull request by sum2012**
Not sure will help #13223

### CODE REVIEW

**Comment by hrydgard** [comment]
I think there's a better way - I'm gonna investigate this in the near future. Tagging for 1.11 so I remember to look at it.

**Comment by sum2012** [comment]
I get two difficult crash trace in v1.10.3-1187-g5eea7435d

**Comment by hrydgard** [comment]
I'm gonna take care of this soon.

**Comment by sum2012** [comment]
I get this crash when debugging DX11

**Comment by hrydgard** [comment]
I think 92e648b on master might have taken care of this.

**Comment by sum2012** [comment]
In the main menu,change to DX 11  cause error

**Comment by hrydgard** [comment]
alright, but changing backends without restarting is a debug-only feature that is not that critical. I'll postpone that to 1.12.

**Comment by unknownbrackets** [comment]
Are you still seeing this crash without this change?

-[Unknown]

**Comment by sum2012** [comment]
Seem okay now.Closing

**Pull request closed without merging**
