### PR TITLE
v1.0.1-567-gg123456

### PR DESCRIPTION
**Pull request by DZSourcer**
New in PPSSPP - Replay Video Configurations in Pause Mode
Just click the mouse button or press on your guide controller to create a videofile

### CODE REVIEW

**Comment by Bigpet** [comment]
I'm confused, this seems to just be one isolated file (that doesn't even have a *.cpp extension) that's not in any way connected to the rest of the program and is mostly just copy&paste from ppsspp\UI\PauseScreen.cpp. 

If you are the spammer that has been opening random issues and pull requests, can you please actually tell us what you want?

**Comment by DZSourcer** [comment]
As the typical video capture programs, I re-build the pause game mode for the video capture in standart quality

**Comment by DZSourcer** [comment]
I will re-build the pause game mode for the video capture in windows standart mediafile

**Comment by Bigpet** [comment]
Ok, but maybe you should actually do that before you make a pull request and not just copy&paste code and replace "Texture" with "Video"

**Pull request closed without merging**
