### PR TITLE
Added IO Timing Method option for RetroArch PPSSPP Core.

### PR DESCRIPTION
**Pull request by EATSTEAK**
It fixes many games(djmax etc.) on RetroArch.

### CODE REVIEW

**Comment by hrydgard** [comment]
yeah, this seems reasonable until we've dealt with this properly..

**Comment by hrydgard** [comment]
However, it doesn't build as-is: 

https://travis-ci.org/hrydgard/ppsspp/jobs/519972496

**Comment by itstake** [comment]
It just a typo issue. Fixed.

**Comment by orbea** [comment]
It seems the clang libretro build is still failing.

https://travis-ci.org/hrydgard/ppsspp/jobs/520311576

**Comment by itstake** [comment]
fixed everything.

**Pull request merged**
