### PR TITLE
Split texture application into two phases

### PR DESCRIPTION
**Pull request by unknownbrackets**
~~So, this could use some more cleanup and testing, and probably is not yet ready for merge.~~

However, I think it's a good idea with some trade-offs.  Might even add an option for it (maybe no UI.)

Some pros/cons:
- Negative: slows down vertex decoding, through-mode only now (usually not as hot, but could be.)
- Positive: detects when <= 272 pixels need to be hashed, preventing needless re-uploads and un-xBRZ passes.
- Positive: potentially provides a chance to thread some parts of texture caching (with init/finalize steps.)
- Positive: detects when render-to-self and render-with-clut textures can have a smaller subset copied.

~~Might also need some better interaction with the vertex cache.~~

Currently, it only does u16 through - not float through.  Note that u8 through is not usable on hardware so doesn't matter.

There are cases where this might also help with non-through - as long as UV gen is texcoords, we can still detect what part of the texture is being referenced (possibly with prescale/UV scale&offset involved.)  It turns out some games which would benefit from these optimizations use non-through.

One idea I had to avoid the impact of checking the bounds was to check the number of verts and use a different step/jit func.  This would create even more permutations, but could allow the cost to be minimal even for non-through.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
This looks great! Will look at it in more detail later, but seems quite worthwhile.

**Comment by daniel229** [comment]
background in Danball Senki W looks worse than before.

now



before

**Comment by unknownbrackets** [comment]
Yeah, something is still wrong with the sliced copying...

-[Unknown]

**Comment by unknownbrackets** [comment]
@daniel229 can you bisect quick commit started that just to be sure?

-[Unknown]

**Comment by daniel229** [comment]
Sure,it's https://github.com/unknownbrackets/ppsspp/commit/0d688399db7e9b34d1b202e6e1caac5b4cb0bda3

**Comment by unknownbrackets** [comment]
I think 2e84418 will fix that.  Needs some cleanup, as well as some d3d9 parity still.  Probably need to clean up use of gstate some, not sure.

It'd be great to see testing on whether this causes any other problems.  It should hopefully be faster.

-[Unknown]

**Comment by daniel229** [comment]
No regression from over 30 games testing with the lastest change and I don't see any significant difference in speed.

**Comment by hrydgard** [comment]
This is great. But I wish we could get rid of all these variables in gstate_c and forward them between the different stages of texture application with a struct on the stack instead (we'd send a pointer to it to the vertex decoder so it can write to it). gstate_c is really becoming a bit of a monster, and it's hard to tell whether data in there is "old" or needs to be updated... 

Can be deferred to after merge though.

**Comment by unknownbrackets** [comment]
Well, for now I've just made sure it applies to Direct3D 9 as well.  I think redoing the way vertex decode stuff is tracked should be a separate merge, since it will change stuff outside just these changes.  It may also have a separate performance impact.

Also, still have not added anything for non-through in this pull, but again I think it can be done separately and might have a larger performance concern as well.

-[Unknown]

**Comment by hrydgard** [comment]
Now that the other one has been merged, can you rebase this for slightly easier review?

**Comment by unknownbrackets** [comment]
Wait a minute, I think I did something wrong on arm... one sec.

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, added fixed regs on arm64.  Maybe can improve this, but let's see what this does for now.

-[Unknown]

**Pull request merged**
