### PR TITLE
Adhoc Socket - An attempt to improve connection stability that was broken recently.

### PR DESCRIPTION
**Pull request by anr2me**
It's seems my previous PR to fix performance on Warriors Orochi 2 was causing connection instability due to high rate of dropped packets.

### CODE REVIEW

**Comment by Lemoncak3** [comment]
So will this fix make warrior orochi lag again? I haven't tried it before though.

**Comment by MojoJojoDojo** [comment]
I guess you should just stay on that specific version if you want orochi to have no lag.

**Comment by kage2051** [comment]
Or better yet, upgrading to a PC or device with higher end specs might be your solution.

**Comment by hrydgard** [comment]
What kind of a silly comment is that? In networking code, performance problems are rarely due to CPU...

**Comment by ANR2ME** [comment]
> So will this fix make warrior orochi lag again? I haven't tried it before though.

This should also fix the issue where Warriors Orochi often failed to Join. 
On localhost Warriors Orochi should be running in full speed, but on LAN there might be some slowdowns sometimes (especially if there are too many movements), but not as bad as a slide show.

**Comment by kage2051** [comment]
For some reason I misread when I posted my original reply.

But yeah, network lag can also be produced by other protocols using 2.4GHz channel if WLAN is used on that same channel as well. This on Android multiplayer.

**Pull request merged**
