### PR TITLE
Updated links to HTTPS

### PR DESCRIPTION
**Pull request by TotalCaesar659**
Updated links to HTTPS.
P.S. Please fix the link in repo description "A PSP emulator for Android, Windows, Mac and Linux, written in C++. Want to contribute? Join us in #ppsspp on freenode (IRC) or just send pull requests / issues. For discussion use the forums on ppsspp.org. http://www.ppsspp.org".
P.P.S. Please, fix the images in https://ppsspp.org/downloads.html

### CODE REVIEW

**Comment by hrydgard** [comment]
Oh thanks. Fixed the project description.

For me, those images work?

**Comment by TotalCaesar659** [comment]
Yeah, they do, thanks!

**Comment by hrydgard** [comment]
I self-hosted instead of hotlinking the images, maybe some kind of http/https issue. Anyway, thanks for testing and suggesting these changes.

**Comment by TotalCaesar659** [comment]
Sorry, I forgot to ask: could you make automatic re-route from HTTP to HTTPS for ppsspp.org?

**Comment by unknownbrackets** [comment]
Unfortunately, PPSSPP makes some requests to the server (for example to check for version updates), and doesn't yet support SSL.  That means we can't mandate SSL for the entire domain yet.

We might be able to do it just for the homepage, or pages ending in .html only, though.

-[Unknown]

**Comment by TotalCaesar659** [comment]
OK, thanks for the explanation.

**Pull request merged**
