### PR TITLE
Update README.md for 1.8.0

### PR DESCRIPTION
**Pull request by hrydgard**
I'm sure there are plenty of good changes missing here, remind me please :)

Plus I should add some pull request references.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Some notes without regard to whether they're worth putting in the readme (unorganized):

 * Avoid AMD crash on startup due to bad Vulkan drivers (#11802)
 * Fixes to various lighting bugs (#11567, #11574, #11577)
 * Significant performance improvement in Earth Defense Force 2 (#11172)
 * More speed in FF4 effects and other generated curves (#11425)
 * Support for resizing Vulkan on Linux (#11451)
 * Improved support for GLES on Linux/IoT (#11507, #11537, #11541, #11632, #11746, #11806, #11845)
 * Percentage based frameskipping (#11523)
 * Fix for thick white line in Gran Turismo (#11530)
 * Fix to Motorstorm freeze on non-Windows (#11618)
 * Faster block transfer in some games (#11531, #11553, #11776)
 * Blending optimizations and improvements (#11543, #11620)
 * Improve D3D11 rendering issues (#11584)
 * Change default graphics backend to D3D11 or OpenGL (#11621, #11658)
 * Remove some outdated settings (#11665, #11666, #11667)
 * Fix remote disc streaming with ipv6 (#11689, #11700)
 * Vulkan: Workarounds for some driver bugs for 5xx series Qualcomm GPUs (#11691, #11694)
 * Workaround lack of support for vertex range culling on older GPUs (#11712, #11773, #11787)
 * Fix some Qt port issues with recent performance improvements (#11720, #11807, #11808)
 * UWP Xbox One: fix X/Back button confusion (#11740)
 * PowerVR Vulkan display corruption fixed (#11744, #11747)
 * Fix Formula 1 2006 timing issue (#11767)
 * Fixes and workarounds for some vertex range culling bugs that broke a few games (#11785, #11859)
 * Naruto Shippuden 3 hang fixed (#11780)
 * Fix trackpad capture on macOS trackpads (#11804)
 * Android: Allow putting PSP storage on custom paths like SD cards (#11812)
 * Corrected vocp instruction, fixing models in Artdink games (#11822, #11835)
 * Bundle SDL in binary for macOS builds (#11831)
 * Prevent keeping games open on Windows (#11842)
 * Fix "real clock sync" setting (helps with latency for music games - #11813)

-[Unknown]

**Comment by hrydgard** [comment]
Thanks Unknown! I'll sort them a little bit and include most.

**Comment by Emulatorer** [comment]
@hrydgard possible release of v1.8.0 in buildbot or ppsspp.org is March 12 😅

**Comment by hrydgard** [comment]
Is that a question? Yeah that's the plan, I'm not gonna be able to work much on it next week so just getting everything ready.

**Comment by Narugakuruga** [comment]
@hrydgard Do you recommend stick with D3D11 instead of Vulkan for Nvidia users? I wonder which are better...

**Comment by Emulatorer** [comment]
@hrydgard thanks for answering :3

**Comment by hrydgard** [comment]
@Narugakuruga  I'd recommend Vulkan since that's where the most future improvements are going to be. But if D3D11 works better for you, well, go for that.

**Comment by Narugakuruga** [comment]
Ok, I will wait till vulkan vsync be fixed.

**Comment by unknownbrackets** [comment]
People are noticing that https://www.ppsspp.org/version.json hasn't been updated.

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets fixed.

**Pull request merged**
