### PR TITLE
Framebuffer code cleanups, log changes, enable BlockTransferAllowCreateFB for Burnout Legends

### LINKED ISSUE #12345: Burnout Legends: Find a way to enable BlockTransferAllowCreateFB cleanly
This eliminates the readbacks needed for the sun effect. 

Enabling the flag works fine and results in no graphical artefacts, and does not (as I initially feared due to the inconsistent copy sizes used by the game) result in excessive framebuffer creation, but we do cause some unnecessary reporting, since it currently confuses the texture cache system a bit. Here's a log from a few minutes of play:
```
46:50:457 idle0        I[G3D]: Common\TextureCacheCommon.cpp:1580 Texture cached cleared from 97 textures
46:59:714 idle0        I[G3D]: Common\FramebufferCommon.cpp:1384 Creating RAM framebuffer at 04170000 (19x50, stride 64, format 3)
47:02:284 idle0        I[G3D]: Common\FramebufferCommon.cpp:1384 Creating RAM framebuffer at 04170000 (17x50, stride 64, format 3)
47:04:052 idle0        I[G3D]: Common\FramebufferCommon.cpp:1384 Creating RAM framebuffer at 04170000 (16x50, stride 64, format 3)
47:16:197 idle0        I[G3D]: Common\FramebufferCommon.cpp:1384 Creating RAM framebuffer at 04170000 (50x50, stride 64, format 3)
48:09:716 idle0        I[G3D]: Common\FramebufferCommon.cpp:1384 Creating RAM framebuffer at 04176000 (16x64, stride 16, format 3)
48:09:716 idle0        W[G3D]: Common\TextureCacheCommon.cpp:805 Render to texture using CLUT with different strides 64 != 16
48:09:716 idle0        E[G3D]: Common\TextureCacheCommon.cpp:844 4 and 8-bit CLUT format not supported for framebuffers
48:09:716 idle0        W[G3D]: Common\TextureCacheCommon.cpp:860 Render to texture with incompatible formats 5 != 3 at 04176000
48:09:720 idle0        W[G3D]: Common\FramebufferCommon.cpp:1681 Block transfer upload 09522010 -> 04176000
48:09:720 idle0        I[G3D]: Common\FramebufferCommon.cpp:1384 Creating RAM framebuffer at 04177000 (8x32, stride 8, format 3)
48:16:657 idle0        I[G3D]: Common\FramebufferCommon.cpp:1384 Creating RAM framebuffer at 04170000 (26x50, stride 64, format 3)
48:27:801 idle0        I[G3D]: Common\FramebufferCommon.cpp:1384 Creating RAM framebuffer at 04170000 (50x50, stride 64, format 3)
51:20:941 idle0        I[G3D]: Common\FramebufferCommon.cpp:1384 Creating RAM framebuffer at 04176000 (16x64, stride 16, format 3)
51:20:943 idle0        I[G3D]: Common\FramebufferCommon.cpp:1384 Creating RAM framebuffer at 04177000 (8x32, stride 8, format 3)
51:31:152 idle0        I[G3D]: Common\FramebufferCommon.cpp:1384 Creating RAM framebuffer at 04170000 (17x50, stride 64, format 3)
51:32:023 idle0        I[G3D]: Common\FramebufferCommon.cpp:1384 Creating RAM framebuffer at 04170000 (21x50, stride 64, format 3)

### PR DESCRIPTION
**Pull request by hrydgard**
Changes to the logging. I'm now comfortable enabling BlockTransferAllowCreateFB for Burnout Legends, eliminating the slow readback. Thus, fixes #12345 .

### CODE REVIEW

**Comment by Gamemulatorer** [comment]
Burnout Legends performance still the same :(
still lag @2X resolution with simulate block transfer effects enable.

**Comment by hrydgard** [comment]
@Gamemulatorer can you check the game ID of your ISO? Maybe I missed one in the compat.ini setting.

**Comment by Gamemulatorer** [comment]
It's ULES00125 and its already added to compat.ini

**Comment by Panderner** [comment]
I'm using Realme C2 and performance of this game running smoothly in 2x resolution on latest build:

We compared the Lastest build and older versions:
v1.10.3-319-g9f147e870 and newer:
Screenshot_2020-08-06-01-32-56-40_2f85358b2198d26f8aca533d68bee793
v1.10.3-315-gb5cc3a0ba and older:
Screenshot_2020-08-06-01-38-42-27_2f85358b2198d26f8aca533d68bee793

**Comment by hrydgard** [comment]
Yeah this should be a noticeable improvement on many devices, but some devices still might not have enough power to run this game at 2x, of course. Wouldn't expect much additional improvement from here unfortunately.

**Comment by Gamemulatorer** [comment]
Im using android lollipop with mali450 gpu octacore cpu
Here's my log hope it can help improve the performance of this game on my phone :)
[ULES00125.zip](https://github.com/hrydgard/ppsspp/files/5031639/ULES00125.zip)

**Comment by Gamemulatorer** [comment]
This is ok now on my phone I just set the build prop "viewroot.profile_rendering=false"
> Set this system property to true to force the view hierarchy to render at 60 Hz. This can be used to measure the potential framerate.
Why is lag when is set it to true?

Screenshot of the game running 27/30fps @ 2x resolution
Screenshot_2020-08-07-08-06-32

**Comment by Panderner** [comment]
> This is ok now on my phone I just set the build prop "viewroot.profile_rendering=false"
> 
> > Set this system property to true to force the view hierarchy to render at 60 Hz. This can be used to measure the potential framerate.
> 
> Why is ppsspp lag when is set it to true? other emulator like mame4droid, epsxe and reicast still running smooth when this prop is set to true.
> 
> Screenshot of the game running 27/30fps @ 2x resolution
> Screenshot_2020-08-07-08-06-32
> But still got a framedrops when too may opponents

Maybe your phone refresh rate issue. any android displays below 60hz might be unsuitable for all NTSC console games even Game Boy and NES Emulators

**Comment by hrydgard** [comment]
@Gamemulatorer If viewroot.profile_rendering=false makes a difference, you should go into developer settings on your phone and turn off GPU profiling. Having it enabled is probably losing you a lot of performance across many games.

**Comment by Gamemulatorer** [comment]
@hrydgard there's a possibility that will you add soon Naruto Shippuden Ultimate Ninja Impact to BlockTransferAllowCreateFB compat.ini?

**Comment by Gamemulatorer** [comment]
burnout legends sun black box issue is not fixed on old adreno gpu see #13332

**Pull request merged**
