### PR TITLE
HLE: Replace Motorstorm pixel read func

### PR DESCRIPTION
**Pull request by unknownbrackets**
Helps with some lighting, see #12363.  Note: because of our caching, this shouldn't read the same framebuf multiple times per frame.

Probably doesn't fix that, because there's also a blending case that doesn't work, which makes PPSSPP too dark.  But, it's harder to fix generically, might have to detect a fixed src color + double blending and do special tricks...

-[Unknown]

### CODE REVIEW

**Comment by Panderner** [comment]
How about abnormal shadows in the USA version of the game?

**Comment by hrydgard** [comment]
@Panderner  Please don't post about other issues in pull requests like this. Open a new one and provide a screenshot of the error (and preferably a correct one too).

**Comment by unknownbrackets** [comment]
I think we should still merge this, though.

-[Unknown]

**Comment by hrydgard** [comment]
yeah, I was afraid of a perf impact and was going to test it a bit, sorry for not getting around to it. I'm gonna merge and deal with it later.

**Comment by hrydgard** [comment]
oops, misclick.

**Comment by Panderner** [comment]
@hrydgard oh ok

**Pull request merged**
