### PR TITLE
Implement sceAdler32

### PR DESCRIPTION
**Pull request by daniel229**
Fixes hangs in StreetKix Freestyle
jpcsptrace
https://gist.github.com/daniel229/b82ba54a8dda3309d72c

add <code>NOTICE_LOG(HLE, "sceAdler32(adler=%08x, data=%08x, datalen=%08x,ret=%08x)", adler, data, datalen,ret);</code> under <code>u32 ret = adler32(adler, buf, datalen);</code>
https://gist.github.com/daniel229/7be20dc5fe5c0049969a

debug log with previous build
https://gist.github.com/daniel229/7fdd5ca1e4fbba41a163

previous build

fixed build

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Looks pretty good, definitely a kernel module.  Nice job.

-[Unknown]

**Comment by daniel229** [comment]
Is this wrong <code> || !Memory::IsValidAddress(data + datalen)</code>?

**Comment by unknownbrackets** [comment]
Hmm, right, technically `data + datalen` doesn't need to be a valid address.  `data + datalen - 1` does.

We probably ought to have a `IsValidRange` or something, technically it could start in VRAM or scratchpad or something and end at a valid address, and include invalid addresses, but this is unlikely.

So probably just change it to `data + datalen - 1` and it's fine.

-[Unknown]

**Comment by daniel229** [comment]
If the datalen would mean sizeof(u8) or sizeof(u32)?

**Comment by unknownbrackets** [comment]
I'd be very surprised if it was u32, hard to tell without testing.  If you `* 4` it when sending it to `adler32()`, does the game still work?  That would answer the question.

But, I think it's correct as is, most likely.

-[Unknown]

**Comment by daniel229** [comment]
*4 won't work.

**Comment by hrydgard** [comment]
Adler32 is the name of an algorithm, and 32 is simply the output size. So it makes sense as is.

http://en.wikipedia.org/wiki/Adler-32

**Pull request merged**
