### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by TotalCaesar659**

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Well, I always put two spaces after a period, not a typo but I suppose not common convention.

Some people hate it now, though.  As best I can work out, these people think it's better for a paragraph to look like a huge block of text.  They complain about "rivers" or "pigeon holes" in the paragraph that make it easier to parse as readable text, but less "beautiful."  To support this, they've invented a myth that typewriters introduced the centuries old convention of two spaces after a period.  In contrast, typewriters temporarily revoked that convention to save money.

Oh well.  The "prettier" less readable paragraphs have prevailed in the larger scheme of convention.  I'm still using two spaces in comments.

-[Unknown]

**Comment by hrydgard** [comment]
Double space after period is an older convention that's no longer in very wide use. Web browsers also render two (or any number of spaces) as one, and I never saw the double space convention growing up, it's only later that I've encountered practitioners here and there :) (plus in various unix editors).

https://en.wikipedia.org/wiki/Sentence_spacing

**Comment by unknownbrackets** [comment]
Whitespace of all kinds (tabs for indentation, newlines) collapses in HTML, it's not some special thing to prevent spaces in sentences.  You can of course use `white-space: pre-line;` to have the spaces render, or elsewise convert to Unicode spaces.

My IDE renders two spaces after a period just fine in comments.

For me the benefit is quite simple: I can skim text using two spaces after a period more quickly, which is helpful for me.  I doubt it impacts comprehension when reading a paragraph in full in any way at all.  Sometimes it seems like other conventions (like integrity in business instead of anything for a pound) are "old-fashioned", but I do what's best, not what others do.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, I know about whitespace collapse. 

Oh, you meant code comments :) 

Well I don't really actually mind double spaces after sentences, I don't think I really notice them much anyway.

**Pull request merged**
