### PR TITLE
Try to improve depal precision on PowerVR

### PR DESCRIPTION
**Pull request by unknownbrackets**
Largely untested since I don't have a usable dev device with PowerVR.  But it should theoretically improve it.

I'm completely unclear on if precision qualifiers do anything in GLES3 or not, though... we definitely need highp ints in depal.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Even if this isn't needed, it's somehow interesting that it makes PowerVR worse, not better or the same.

But maybe Dragon Ball Z is a bad example, in case the absdiff blending is also borked.  Can you try running the depal test on the device?

https://github.com/hrydgard/pspautotests/tree/master/tests/gpu/rendertarget

Might need to tweak logging somewhere to capture the output and compare.  Headless doesn't work I think on Android with graphics right now (or maybe it does?)

-[Unknown]

**Comment by unknownbrackets** [comment]
With framebuffer fetch disabled, does this still have the same effect?

-[Unknown]

**Comment by brujo5** [comment]
I can not test.

My iphone cant go ingame. Still crashes in videos

**Comment by hrydgard** [comment]
As this did not seem to have the desired effect, maybe close?

**Comment by unknownbrackets** [comment]
Okay, I'll close, but if this makes it worse it seems to indicate to me that there are some issues somewhere with precision in depal for PowerVR.  IMHO.

-[Unknown]

**Comment by brujo5** [comment]
@unknownbrackets 

i have an galaxy s6 android 5.1.1 ES3.1

still no outline in characters for dbz vs tag

logcat it would be useful?

**Comment by unknownbrackets** [comment]
Logcat probably won't help.  This is with "disable slow effects" unchecked and buffered rendering, right?

Does it work in [v1.2.2-253-g861a30a] (http://buildbot.orphis.net/ppsspp/index.php?m=detail&rev=v1.2.2-253-g861a30a&platform=android)?

The problem with the outlines in this game is they rely on multiple features to work.  If depal is broken, they won't work... but if depal is working, but absdiff isn't, they also won't work.  I think there's other things, maybe even stencil or alpha testing, that can break them.

It makes it really hard to guess at which underlying cause might be having problems when they don't work....

-[Unknown]

**Comment by brujo5** [comment]
Yes I tried that and not work. Thx 

I thought it was a problem specific PowerVR but I see no.

**Pull request closed without merging**
