### PR TITLE
Added Vulkan disable and forced CPU detection options

### PR DESCRIPTION
**Pull request by hissingshark**
Addresses what's left of my original topic #10534 

1.  I need to hide my armv8 from the cmake processor detection as it forces a 64bit build and my userland is 32bit.  A toolchain file can now override using `set(FORCED_CPU <cpu_name>)`, e.g.
 `set(FORCED_CPU armv7)`.

2.  I'm not using Vulkan.  I should be able to build it even if I'm not planning on using it, but sadly it will not.  A toolchain file can now disable it from the build using `set(DISABLE_VULKAN ON)`.

Hopefully these options will be useful on other platforms also.

### CODE REVIEW

**Comment by hissingshark** [comment]
retest this please

**Comment by hissingshark** [comment]
Yeah we talked about it back [here](https://github.com/hrydgard/ppsspp/issues/10534#issuecomment-384755613).  I don't mind it sitting there in the least, but it wouldn't build and my system isn't X11.  I understand your suggestion of separation is not a high priority so I've been limping on with Vulkan plain disabled.  Just wanted to make it formal, so the likes of my Retropie fork wont have to patch CMakeLists.txt on the fly and risk breakage due to changes.

On a fresh pull at configuration I get:
> -- Could NOT find WAYLAND_CLIENT (missing:  WAYLAND_CLIENT_LIBRARIES WAYLAND_CLIENT_INCLUDE_DIR) 
> -- Could NOT find WAYLAND_SERVER (missing:  WAYLAND_SERVER_LIBRARIES WAYLAND_SERVER_INCLUDE_DIR) 
> -- Could NOT find WAYLAND_EGL (missing:  WAYLAND_EGL_LIBRARIES WAYLAND_EGL_INCLUDE_DIR) 
> -- Could NOT find WAYLAND_CURSOR (missing:  WAYLAND_CURSOR_LIBRARIES WAYLAND_CURSOR_INCLUDE_DIR) 
> -- Could NOT find WAYLAND (missing:  WAYLAND_LIBRARIES WAYLAND_INCLUDE_DIR)

Then building:
> [ 25%] Building CXX object CMakeFiles/Common.dir/Common/Vulkan/VulkanContext.cpp.o
> In file included from /home/osmc/ppsspp/Common/Vulkan/VulkanLoader.h:32:0,
>                  from /home/osmc/ppsspp/Common/Vulkan/VulkanContext.h:9,
>                  from /home/osmc/ppsspp/Common/Vulkan/VulkanContext.cpp:10:
> /home/osmc/ppsspp/ext/vulkan/vulkan.h:68:22: fatal error: X11/Xlib.h: No such file or directory
>  #include <X11/Xlib.h>

I can appease that by installing `libX11-dev` without breaking anything on my system, but then its:

> [ 21%] Building CXX object CMakeFiles/native.dir/SDL/SDLVulkanGraphicsContext.cpp.o
> /home/osmc/ppsspp/SDL/SDLVulkanGraphicsContext.cpp: In member function ‘bool SDLVulkanGraphicsContext::Init(SDL_Window*&, int, int, int, std::__cxx11::string*)’:
> /home/osmc/ppsspp/SDL/SDLVulkanGraphicsContext.cpp:64:64: error: ‘union SDL_SysWMinfo::<anonymous>’ has no member named ‘x11’
>    vulkan_->InitSurface(WINDOWSYSTEM_XLIB, (void*)sys_info.info.x11.display,
>                                                                 ^~~
> /home/osmc/ppsspp/SDL/SDLVulkanGraphicsContext.cpp:65:37: error: ‘union SDL_SysWMinfo::<anonymous>’ has no member named ‘x11’
>      (void *)(intptr_t)sys_info.info.x11.window, pixel_xres, pixel_yres);

**Comment by unknownbrackets** [comment]
Maybe we just need some cmake flag to disable `VK_USE_PLATFORM_XLIB_KHR`?

-[Unknown]

**Comment by hissingshark** [comment]
Yep, it builds with `VK_USE_PLATFORM_XLIB_KHR` set OFF.  I'll rework my PR.

**Comment by hrydgard** [comment]
My only remaining concern is, will that new option correctly default to ON on say a regular linux distro?

**Comment by hissingshark** [comment]
I think you're right.  They'd need to deliberately specify wanting it, which would break existing toolchains that were building for Vulkan.  As users such as myself are something of a corner case that seems unfair.

Would it be fair to say that `USING_GLES2` and `VULKAN` are mutually exclusive?  Couldn't we just disable Vulkan if building for GLES2 instead?

**Comment by hrydgard** [comment]
Nope, that combination is used on Android.

But you can set default ON for cmake variables, I think?

**Comment by hissingshark** [comment]
Thanks! Found that last night after you suggested a default. Sorry I overlooked such an obvious strategy.
Just need to update my branch.

**Comment by hrydgard** [comment]
The travis errors on Linux are rather odd.

```
WARNING: The following packages cannot be authenticated!
  libsdl2 libsdl2-dev
```
What might that be about? Feel like ignoring them...

**Comment by hissingshark** [comment]
That happened at one point with my other recent PR. Seemed odd so I triggered a rebuild by closing and reopening the PR and it was fine again.

The only other thing is that I've just added my toolchain file in the latest commit as it documents things better for those of a similar platform who come later. A factor?

**Comment by hissingshark** [comment]
Yep, that did it!

**Pull request merged**
