### PR TITLE
Increase the number of possible open files under Windows to maximum

### PR DESCRIPTION
**Pull request by Florin9doi**

### CODE REVIEW

**Comment by thedax** [comment]
Any more details on why this is needed? Does a game need this or something?

**Comment by unknownbrackets** [comment]
Apparently this solves a problem where > around 512 files in a directory would not work properly.  I feel like we shouldn't open every single file at the same time... there are fd limits on other systems too.

-[Unknown]

**Comment by Florin9doi** [comment]
The files are never closed. Not by scrolling away or navigating to another directory. It will open every single ISO or archive.

**Comment by unknownbrackets** [comment]
Does #7805 help?  Not that I'm against increasing the max files here (I'm surprised the default is so low), but would rather not "leak" system resources.

-[Unknown]

**Comment by Florin9doi** [comment]
#7805 has fixed the issue

**Pull request closed without merging**
