### PR TITLE
(Libretro) Add VS 2022 Build Support

### PR DESCRIPTION
**Pull request by ghost**
This attempts to allow the libretro core to be built with Visual Studio 2022, while also adding more specific instructions on what build commands to use depending on your version of Visual Studio. The core built just fine, and it also worked perfectly when tested under RetroArch. Although I attached a test build in case I missed something.

However, since VS 2022 now installs in the `C:/Program Files` directory instead of the x86 folder older versions used, I had some difficulties with getting the path to be recognized. I'm not sure if the current solution is optimal, hence the draft status. Any feedback is certainly welcomed here.

Test build: [ppsspp_libretro.zip](https://github.com/hrydgard/ppsspp/files/10072546/ppsspp_libretro.zip)

### CODE REVIEW

**Comment by hrydgard** [comment]
I don't mind it, though I guess it would be nice if the various vs configs in the file could share more of their setup, as they are pretty similar.

**Comment by ANR2ME** [comment]
I think instead of assuming VS2022 to always be installed on it's default directory, you should retrieve the `InstallDir` from registry https://stackoverflow.com/questions/30504/programmatically-retrieve-visual-studio-install-directory

**Comment by GABO1423** [comment]
Line 574 was change from `ProgramFilesw := C:/Program Files` to `ProgramFilesw := $(shell cmd /c "echo %PROGRAMFILES%")`, this avoids the hardcoded path and the core still built just fine. Does this seem like a satisfactory solution?

**Comment by hrydgard** [comment]
Whether it's satisfactory or not is really for the libretro people to decide, the libretro directory is basically their domain :)

As long as CI keeps building both here and there I'm happy.

Good to see you found a cleaner way though.

**Comment by GABO1423** [comment]
Managed to get this to work after hours of attempts (the main takeaway from this is that I now hate bash with a passion :D), however, the solution requires the addition of a new file to the libretro directory: `vswhere.exe`. I could not for the life of me get the compiler to use the `Program Files (x86)` directory, so this was the next thing.

I'll make a new PR with these changes, since this approach is decisively different from what the PR originally wanted to accomplish.

**Comment by unknownbrackets** [comment]
Can't you use `%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe`?  Or in bash, `$(env | awk -F= '/^ProgramFiles\(x86\)=/ { print $2; }')`.

-[Unknown]

**Comment by GABO1423** [comment]
> Can't you use `%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe`? Or in bash, `$(env | awk -F= '/^ProgramFiles\(x86\)=/ { print $2; }')`.
> 
> -[Unknown]

The former led to a syntax error nightmare no matter how much I tried. So no, that path didn't work. I ended up doing something else that I found much simpler. Should be getting close to finishing with testing that alternative.

**Comment by ANR2ME** [comment]
Someone use this kind of cmake script:
```
  find_program(_vswhere_tool 
    NAMES vswhere 
    PATHS "$ENV{ProgramFiles\(x86\)}/Microsoft Visual Studio/Installer")
  if (NOT ${vswhere})
    message(FATAL_ERROR "Could not locate vswhere.exe - unable to source vc redistributable")
  endif()

  execute_process(
    COMMAND "${_vswhere_tool}" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
    OUTPUT_VARIABLE _vs_install_loc_out
    RESULT_VARIABLE _vs_where_exitcode
    OUTPUT_STRIP_TRAILING_WHITESPACE
  )

  file(TO_CMAKE_PATH "${_vs_install_loc_out}" _vs_install_loc)
```

**Comment by GABO1423** [comment]
> Someone was using this kind of cmake script:
> 
> ```
>   find_program(_vswhere_tool 
>     NAMES vswhere 
>     PATHS "$ENV{ProgramFiles\(x86\)}/Microsoft Visual Studio/Installer")
>   if (NOT ${vswhere})
>     message(FATAL_ERROR "Could not locate vswhere.exe - unable to source vc redistributable")
>   endif()
> 
>   execute_process(
>     COMMAND "${_vswhere_tool}" -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath
>     OUTPUT_VARIABLE _vs_install_loc_out
>     RESULT_VARIABLE _vs_where_exitcode
>     OUTPUT_STRIP_TRAILING_WHITESPACE
>   )
> 
>   file(TO_CMAKE_PATH "${_vs_install_loc_out}" _vs_install_loc)
> ```

Cmake is not used by this build process, so it can't be used. Kind of a moot point anyway considering the new PR.

**Pull request closed without merging**
