### PR TITLE
Fix message running slow always show when game running stable speed

### PR DESCRIPTION
**Pull request by zminhquanz**
It's fixed , it's show when your speed emulation bellow than 98%

### CODE REVIEW

**Comment by hrydgard** [comment]
So, I forgot that a bunch of Android devices have a native framerate below 60hz (59hz is common), and we play along and stretch the audio slightly instead. Instead of comparing to a hardcoded number of 58.84 hz, please change it to compare to:

    System_GetPropertyInt(SYSPROP_DISPLAY_REFRESH_RATE) / 1000.0f

We might need a small offset as well but it should be based on this number, well, at least if this number is close to 60hz..

**Comment by unknownbrackets** [comment]
Although, actual gameplay in this case (whether audio is stretched or not) would be running 2-5% slow, depending on the framerate.

It should be `System_GetPropertyInt(SYSPROP_DISPLAY_REFRESH_RATE) / 1001.0f`, shouldn't it?  In case the rate is 60.  This is comparing against the vblanks per second, after all.

-[Unknown]

**Comment by zminhquanz** [comment]
Ok , i see that

**Comment by zminhquanz** [comment]
`static bool IsRunningSlow() {
	// Allow for some startup turbulence for 8 seconds before assuming things are bad.
	if (fpsHistoryValid >= 8) {
		// Look at only the last 15 samples (starting at the 14th sample behind current.)
		int rangeStart = fpsHistoryPos - std::min(fpsHistoryValid, 14);

		double best = 0.0f;
		for (int i = rangeStart; i <= fpsHistoryPos; ++i) {
			// rangeStart may have been negative if near a wrap around.
			int index = (fpsHistorySize + i) % fpsHistorySize;
			best = std::max(fpsHistory[index], best);
		}
		System_GetPropertyInt(SYSPROP_DISPLAY_REFRESH_RATE) / 1.001f;
		return best < 58.94;
	}`
I'm add this code in this line , right , for me it's worked

**Comment by zminhquanz** [comment]
return best < System_GetPropertyInt(SYSPROP_DISPLAY_REFRESH_RATE) / 1.001f;
That's look good

**Comment by zminhquanz** [comment]
@hrydgard would you merge this request ?

**Pull request merged**
