### PR TITLE
Add Simulate UMD slow reading speed in UI

### LINKED ISSUE #9993: Sengoku Musou 3Z Special: Error when choosing DLC Costumes
Just like in the title, i have problem concerning DLC costumes in this 

game, whenever i choose a costume the emulator freeze/Crash saying "ppsspp 

has stopped working".

I have tried with multiple version of ppsspp, (1.2.2, 1.3, 1.4, 1.4.2, 

1.4.2-196-gdfdf548-windows-amd64) and every backend resulting in the same 

error.

I've read a post on another forum, said that this DLC only work on real PSP 

with certain CFW, no one know a way to make this DLC work on emulator so i 

ask here.

This is how to reproduce the problem: (assuming you already have the game 

and its DLC) open the game, press square when in character selection screen 

and then press either L or R.

### LINKED ISSUE #11062: Aces of War (Europe) freezes up after chapter selection
PPSSPP v1.5.4-995-g373366911 Windows 64 bit
choose story mode then the chapter you want to play then choose a part of the story you want to play, after you choose it the game just freezes while music in the background plays

### LINKED ISSUE #12512: Sengoku Musou 3 Z Special: Popup error dialog box when select custom character
As shown in the picture.

Not error in blank unit. If you watched a existing unit, then move up  another  existing unit, it pop up the error dialog box .

> ---------------------------
> Critical
> ---------------------------
> Can't have both THROUGH and USE_HW_TRANSFORM together!
> 
> Try to continue?
> ---------------------------
> 是(Y)   否(N)   
> ---------------------------

It will force close when you select Y or N.

https://img.vim-cn.com/89/eb73da81a019749e64576813803a1bb6cf8283.gif

### PR DESCRIPTION
**Pull request by sum2012**
Fix #11062 fix https://github.com/hrydgard/ppsspp/issues/12512 fix https://github.com/hrydgard/ppsspp/issues/9993
A small note 400000 fail

### CODE REVIEW

**Comment by ANR2ME** [comment]
I wondered whether this game have issue with writing too or not, since usually writing is slower than reading.

**Comment by ANR2ME** [comment]
Could there be another issue if it need such a long delay just to open the file?

**Comment by sum2012** [comment]
There is the theory that Real PSP  can in-game in CSO format rather than ISO format, decompression using real PSP's CPU should be much slower.
The UMD might have copyright protection scheme so that it read data really slow.
This is only game that need this slow speed so that I don't interest to find another solution
JPCSPTrace of Aces of War (Europe) of CSO format
https://gist.github.com/sum2012/233b04ae988303655b103aa6f95c1fd0
(The hanging of PPSSPP of reading of the file timing )
20:11:21.106496 Load Thread - -> sceIoOpen 0x09F9ABB0('disc0:/PSP_GAME/USRDIR/UMAP/000.BIN'), 0x1, 0x0 = 0x0
20:11:21.113254 Load Thread - <- sceIoOpen 0x09F9ABB0('disc0:/PSP_GAME/USRDIR/UMAP/000.BIN'), 0x1, 0x0 = 0x4

**Comment by sum2012** [comment]
I also give a fix for jpcsp emulator
https://github.com/jpcsp/jpcsp/pull/510

**Comment by IrfanH495** [comment]
I hope this can help sengoku musou 3z to choose dlc costumes

**Comment by sum2012** [comment]
@IrfanH495 You can download this build of windows 64 bit in 
https://github.com/hrydgard/ppsspp/actions/runs/6574857743#artifacts
You need add the game in compat.ini in UMDReadSpeed section

**Comment by IrfanH495** [comment]
@sum2012 thank you, but unfortunately I don't have a PC/laptop to run it.

**Comment by sum2012** [comment]
@IrfanH495 
I am telling my friend to send the DLC to me (I have the game but not DLC )
In the while , I am trying to make it to menu (Under Simulate UMD Delay)

**Comment by sum2012** [comment]
@IrfanH495 confirm fixed the DLC
I do not play much so that I cannot test #12512
Do you have a save so that I can test #12512 ? (Upload in here in zip )

**Comment by IrfanH495** [comment]
@sum2012 Not long ago my save data was deleted, in this save state I created 9 characters, I think it's the same as the DLC costume 
[PPSSPP_STATE.zip](https://github.com/hrydgard/ppsspp/files/13069247/PPSSPP_STATE.zip)

**Comment by IrfanH495** [comment]
@sum2012 For #12512 ForceUMDDelay for me it's enough but for DLC costumes it still freezes

https://github.com/hrydgard/ppsspp/assets/78854859/a1c07ee6-d113-42fe-b603-0eda109edbc2

**Comment by sum2012** [comment]
I will try to increase reading speed to other sceio function

**Comment by sum2012** [comment]
I force it also make delay as ForceUMDDelay .
So it also fix https://github.com/hrydgard/ppsspp/issues/12512

**Comment by ANR2ME** [comment]
> edit: So the timing ~0.07 s = 70ms , much more than unknownbrackets measure

500ms is still far off from 70ms, although access time could get worse due to scratches or damages on the disc.
May be the delay should be spread out to other sceIo syscalls (ie. sceIoRead) instead of lumping it on sceIoOpen?

**Comment by sum2012** [comment]
Update Jpcsptrace log:
https://gist.github.com/sum2012/4d161b95c65e0a4d7c95ce5024f6321a

00:04:03.139435 Load Thread - -> sceIoOpen 0x09F9ABB0('disc0:/PSP_GAME/USRDIR/UMAP/001.BIN'), 0x1, 0x0 = 0x0
00:04:03.145797 Load Thread - <- sceIoOpen 0x09F9ABB0('disc0:/PSP_GAME/USRDIR/UMAP/001.BIN'), 0x1, 0x0 = 0x4
~ 0.006s = 60 ms
00:04:03.146031 Load Thread - -> sceIoLseek 0x4, 0xDEADBEEF, 0x0 = 0x0
00:04:03.146103 Load Thread - <- sceIoLseek 0x4, 0xDEADBEEF, 0x0 = 0x416180

00:04:03.194278 Load Thread - -> sceIoLseek 0x4, 0xDEADBEEF, 0x0 = 0x0
00:04:03.194369 Load Thread - <- sceIoLseek 0x4, 0xDEADBEEF, 0x0 = 0x0

00:04:03.194424 Load Thread - -> sceIoLseek 0x4, 0xDEADBEEF, 0x0 = 0x0
00:04:03.194481 Load Thread - <- sceIoLseek 0x4, 0xDEADBEEF, 0x0 = 0x0

too low value of compare sceIoLseek so that can ignore

00:04:03.194540 Load Thread - -> sceIoRead 0x4, 0x960B980, 0x416180 = 0x0
00:04:09.705600 Load Thread - <- sceIoRead 0x4, 0x960B980, 0x416180 = 0x416180

~6.5 s = 6500 ms

**Comment by unknownbrackets** [comment]
> edit: So the timing ~0.07 s = 70ms , much more than unknownbrackets measure

There's a few things here, but the measurements in PPSSPP are based on a high speed memory stick, and speeds of the memory stick could vary a lot (they had different price points.)  It's also true that many CFW had slow CSO decompression (in part because they usually re-read the index data and would often read block by block, slowly.  The timings in PPSSPP are just based on memory stick read timings, not based on any of these CFW drivers.

But there's another problem: you're simply measuring when the thread calls sceIoOpen() to when the sceIoOpen() call finishes.  While that may sound right, other threads are running on the device.  If it starts processing some audio data or does some other processing on another better-priority thread, you could easily see a sceIoOpen() call take milliseconds or even seconds to "finish".  It's necessary to look at the overall context of what's happening at the same time.  That said, it can be more useful looking at averages.  Often these won't have anything else happening.

Also, I found, at least on the PSP-3000 and with actual UMDs, that there was clearly some kind of path cache.  Opening files was pretty fast, but only after reading from it once.  It could even be that this cache is stored in volatile memory and is lost when volatile memory is locked (but probably not, just saying that I don't know the specific rules around it.)  I don't think this cache is in the PSP-2000+ cache RAM, though, because I saw this even running homebrew code that had the UMD cache RAM disabled.

`IOTIMING_REALISTIC` is probably a bad name.  I've said this before, but it is simply unrealistically fast timings for UMD (well, I have seen some evidence that maybe the UMD cache is even faster actually, but not sure of that) + some seek delay timings.

If you are able to play multiple PSP games without the game sometimes hanging when a new sound effect or graphical effect has to show, you can be pretty sure you're not getting realistic timing.  That was a common event on a real PSP: you'd cast a spell you hadn't used this play session, and suddenly the music would hang and all you could hear was the UMD drive spinning up.  This might take 2-3 seconds at least.  It obviously didn't happen in every game, but it did in many.  If you don't experience that in PPSSPP, you can be sure the timings are very very unrealistic.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets I have changed the timing on __IoRead ,do you agree ?
IOTIMING_REALISTIC ,I do not have idea to rename

**Comment by hrydgard** [comment]
I think something like this is OK to have as an option and compat setting, and the simplified version in your newest commits should be fine, that just adjusts the throughput of the reads.

The name "UMD slow read speed" gets the point across I guess.. I'll see if I can come up with something better until tomorrow, then we'll get this in.

**Review by hrydgard — APPROVED** [review]

**Comment by leoxxx** [comment]
> Simulate UMD delays = 模拟 UMD 延迟

where is the option?

**Comment by hrydgard** [comment]
@leoxxx System: IO Timing Method -> Simulate UMD slow reading speed"

**Comment by leoxxx** [comment]
@hrydgard
THX. I play the game with old verison setting is also O.K. The option default is: Fast (lag on slow storage) = 快速模式(存储低速时有延迟). Dose it auto set for game?

**Comment by hrydgard** [comment]
Yes, we force it on for some games using compat.ini.

**Pull request merged**
