### PR TITLE
I18N: Switch to getting categories by index instead of by string lookup

### PR DESCRIPTION
**Pull request by hrydgard**
Also gets rid of the shared_ptr usage, and generally makes things nicer.

Needed for later config refactorings, good to get in early.

It's not like the list of section changes much anymore, so having a static mapping defined makes sense.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Without looking at this hard, a reason for the previous shared_ptr usage was to handle language changes and reloads and crashes we saw in Google Play, if I recall.  It's actually not the categories as much as the associated data to the category.  That said, I'm not sure where it was potentially changing in flight with other threads.

Won't this now mean the returned category can have data changing on it?  Before, once you had a category shared_ptr, I think you could more or less count on it not changing - it just might be freed once you let it go if it had actually been swapped out.

-[Unknown]

**Comment by hrydgard** [comment]
Hm, yeah, I kinda forgot what the purpose of the shared_ptrs really were.

But, we don't ever reload these at runtime except when changing language and startup, and that's on the main thread which is also really the only thread that reads from them - or at least should be. I'll take another look and try to reason a bit about it, but I do think it can be a lot simpler than it was.

**Comment by unknownbrackets** [comment]
Well, I think you were the one who opened the issue (I guess it wasn't Play, though):
https://github.com/hrydgard/ppsspp/issues/12594

Is returning a shared_ptr that big a complexity?  But I guess it's fine.  Of course, on Windows, language changes can come from the Windows menu.  I guess that could be serialized using System_MakeRequest or something.  Perhaps that is "simpler"?

-[Unknown]

**Comment by hrydgard** [comment]
Hah you got me there. I honestly barely remember doing that, so many changes.

Yeah maybe I'll keep the shared_ptrs, heh. I'm just on a bit of crusade against unnecessary complexity and it feels like there is some here. It was more natural to have the shared_ptrs when in a map, now that I'm putting them in an array instead, I felt like I should just put the actual categories in there, rather than pointers to them, and then the rest fell out of that.

Of course, nothing technically wrong with an array of shared_ptrs..

**Review by kon0071235 — COMMENTED** [review]
aaaaaaaaaaaaaabbbbbbbbb

**Comment by hrydgard** [comment]
Restored the shared_ptrs, think it's pretty nice and safe now. You're right that they are probably the simplest solution to the concurrency issues in this case.

**Pull request merged**
