### PR TITLE
glcore context switching

### PR DESCRIPTION
**Pull request by barbudreadmon**
preparatory patch for https://github.com/libretro/RetroArch/pull/11368

### CODE REVIEW

**Comment by hrydgard** [comment]
I'm fine with this, not really sure what's going on in the discussion in libretro/RetroArch#11368 though?

**Comment by barbudreadmon** [comment]
It was mostly discussed at libretro's discord, the status is that @twinaphex must test the https://github.com/libretro/RetroArch/pull/11368 PR since he was the only one who reported issues with it a few months ago. Every core using hardware rendering needs a bit of support code before it's merged, otherwise the video driver will always be forced to whatever the core requests, or the core won't launch if the video driver mismatch and the "Allow cores to switch video driver" is toggled off.
Those PRs i sent to most of those cores should be harmless with current RetroArch, so i think they should be merged as soon as possible.

**Comment by barbudreadmon** [comment]
Also, i wonder if vulkan shouldn't be disabled in the libretro port for now, since it's crashing and i believe it's not an issue on my side ?

**Comment by barbudreadmon** [comment]
Other core PRs were already merged since they aren't breaking anything with current RA, so if you could merge this one too it would be perfect.
Most likely the RA PR will be merged after every core needing this are ready (i still have a few cores to deal with).

**Comment by barbudreadmon** [comment]
thanks :)

**Pull request merged**
