### PR TITLE
Make PPSSPP aware of Windows 10 (mostly for the info screen).

### PR DESCRIPTION
**Pull request by thedax**
Fixes https://github.com/hrydgard/ppsspp/issues/7894. I tested it on my Windows 10 laptop and it seems to work fine and dandy. ~~Windows XP is untested though. I'll try to test it in a virtual machine soon.~~ Windows XP works fine in the VM I tested.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
This doesn't affect XP right?  I assume it would tell 11 that we didn't officially support it but wouldn't prevent execution.

-[Unknown]

**Comment by thedax** [comment]
It shouldn't. I ran a self-compiled build and it started in my XP VM with no problems.

**Comment by unknownbrackets** [comment]
Oh, sorry, didn't see you updated the initial comment.

-[Unknown]

**Comment by thedax** [comment]
No worries.

**Comment by thedax** [comment]
Ignore that revert branch thingy. I hit revert by accident.

**Pull request merged**
