### PR TITLE
Function replace in MotorStorm: Arctic Edge

### PR DESCRIPTION
**Pull request by daniel229**
Fixes loading icons in MotorStorm: Arctic Edge

the function
https://cloud.githubusercontent.com/assets/3481559/5717400/18c6631a-9b3b-11e4-80cc-02b34cdbe66f.png

after

before

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Is that screenshot in OpenGL?  It looks offset... is that just an effect the game intentionally does?

-[Unknown]

**Comment by daniel229** [comment]
Yes,it's in OpenGL.Look offset is because it's not at 1x resolution.

**Comment by hrydgard** [comment]
Strange stuff...

**Comment by ufdada** [comment]
Doesn´t work for me. Is there anything special to do? My Gameid is UCES01250.

**Comment by daniel229** [comment]
If it doesn't work with default setting,possible UCES01250 is using different function.

**Comment by daniel229** [comment]
UCES01250 is still working here.So try default setting.In D3D or OpenGL make sure buffered rendering and simulate block transfer are checked,in PPSSPP.ini set FuncReplacements = True.

**Comment by unknownbrackets** [comment]
Make sure you're using the very latest git build from the download page, too.

-[Unknown]

**Comment by ufdada** [comment]
@daniel229 hm well i am using the same build as you, but it still doesn´t work. I even set it back to default....

I am using a nvidia geforce gtx 670

Here is my ppsspp config:
https://gist.github.com/ufdada/79f3f9d6a5069187d55b

the config i used before:
https://gist.github.com/ufdada/94fbf4d409497008e60b

**Comment by daniel229** [comment]
The config seems no problem.Can you run the game, then go to Disassembly(Ctrl+D) to see if the motorstorm_download_frame exists.

**Comment by ufdada** [comment]
No actually there are a lot of unnamed functions: 
image

**Comment by daniel229** [comment]
That seems FuncReplacements = False , and why the address start from 08800000 not 08804000.

**Comment by unknownbrackets** [comment]
If you have turned on symbol map files and have a .map or .ppmap file next to the iso, delete it.  It's remembering old function positions / information that are no longer correct.  This may actually fix things in the game and other games.

-[Unknown]

**Comment by ufdada** [comment]
> If you have turned on symbol map files and have a .map or .ppmap file next to the iso, delete it. It's remembering old function positions / information that are no longer correct. This may actually fix things in the game and other games.

> -[Unknown]
That was the problem. Thank you very much. Now it works.
Would be cool if ppsspp was smart enough to check it if the map-files very obsolete/outdated.

**Comment by unknownbrackets** [comment]
Well, I have customized map files and in cases I've marked functions that have been misdetected by PPSSPP (for debugging purposes.)  I would not want it to wipe out my map files just because they don't match its estimations.  A compiler might also generate a correct map file for a homebrew game, which would be far more useful than what PPSSPP would auto-generate.

So, it has both sides to it.

-[Unknown]

**Pull request merged**
