### PR TITLE
CMakeList: fix SDL+Wayland+Vulkan

### LINKED ISSUE #16163: linux/SDL: fails to run on Wayland (Vulkan backend)
### Game or games this happens in

<doesn't matter>

### What area of the game / PPSSPP

PPSSPP doesn't start on my linux machine.
I'm getting backend error (see logs)
A few days ago, I succeeded compiling the app on another linux machine.

### What should happen

app should start

### Logs

<details><summary>logs</summary>

44:01:524 Core/Config.cpp:649 I[G3D]: Longest display side: 1920 pixels. Choosing scale 2
44:01:536 UI/NativeApp.cpp:416 E[LOADER]: Failed graphics backends: OPENGL,VULKAN,ALL
44:01:536 Core/Config.cpp:751 E[LOADER]: Graphics backend failed for 0, trying another
44:01:536 Core/Config.cpp:776 E[LOADER]: All graphics backends failed
VulkanMayBeAvailable: Device allowed ('SDL:Linux')
VulkanMayBeAvailable: Library loaded ('libvulkan.so.1')
VulkanMayBeAvailable: Enumerating instance extensions
VulkanMayBeAvailable: Instance extension count: 19
VulkanMaybeAvailable: Instance extension found: VK_KHR_device_group_creation (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_display (00000017)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_fence_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_memory_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_external_semaphore_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_display_properties2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_physical_device_properties2 (00000002)
VulkanMaybeAvailable: Instance extension found: VK_KHR_get_surface_capabilities2 (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface (00000019)
VulkanMaybeAvailable: Instance extension found: VK_KHR_surface_protected_capabilities (00000001)
VulkanMaybeAvailable: Instance extension found: VK_KHR_wayland_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xcb_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_KHR_xlib_surface (00000006)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_drm_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_acquire_xlib_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_report (0000000a)
VulkanMaybeAvailable: Instance extension found: VK_EXT_debug_utils (00000002)
VulkanMaybeAvailable: Instance extension found: VK_EXT_direct_mode_display (00000001)
VulkanMaybeAvailable: Instance extension found: VK_EXT_display_surface_counter (00000001)
VulkanMayBeAvailable: Calling vkCreateInstance
VulkanMayBeAvailable: Vulkan test instance created successfully.
VulkanMayBeAvailable: Ineligible device found and ignored: 'llvmpipe (LLVM 14.0.0, 256 bits)'
VulkanMayBeAvailable: Found working Vulkan API!
VulkanMayBeAvailable: Destroying instance
DEBUG: Vulkan might be available.
Info: We compiled against SDL version 2.24.0 and we are linking against SDL version 2.24.0. :)
ThreadManager::Init(compute threads: 8, all: 16)
Pixels: 960 x 544
Virtual pixels: 960 x 544
Failed to initialize glew!
GL init error ''
loading control pad mappings from gamecontrollerdb.txt: SUCCESS!
Segmentation fault (core dumped)

</details>

### Platform

Linux / BSD

### Mobile phone model or graphics card

Fedora 36; AMD ATI Radeon Vega Series / Radeon Vega Mobile Series

### PPSSPP version affected

64c5b5e55

### Last working version

_No response_

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [X] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

### PR DESCRIPTION
**Pull request by gucio321**
fix #16163

**NOTE** Please verify carefully this change since I'm not familiar with CMake at all and I could destroy something :smile:

### CODE REVIEW

**Comment by unknownbrackets** [comment]
I think this is better, but there was #11536 for some reason.  Maybe a case of https://xkcd.com/1172/.

-[Unknown]

**Comment by gucio321** [comment]
ok, so how should I handle this?

**Comment by gucio321** [comment]
ok, nevermind, I see that cmake doesn't do this way ;-)

**Comment by hrydgard** [comment]
Hm. Not sure what to do here :) 

I feel that ideally we should always build with both X11 and wayland and chose at runtime...

**Comment by hrydgard** [comment]
Again I'm really not sure why https://github.com/hrydgard/ppsspp/issues/11536 was desired, but I also don't really see why this PR could be bad. So I'm inclined to merge it...

**Comment by yann-boyer** [comment]
I tested Wayland on PPSSPP SDL with the KDE desktop environment(it's very important to say it), it works relatively well(AMD Graphics Card) but I tested the same thing with same games on a Nvidia laptop with KDE and it's broken, some games have glitches and weird things happens, I also tested on GNOME and it was totally broken, when I launch PPSSPPSDL with Wayland the windows has no decorations and it goes white.. I don't know why.

**Comment by TheComputerGuy96** [comment]
Any updates on this? It isn't that great having to rebuild PPSSPP with Wayland WSI support if I want to use the Vulkan renderer with Wayland video driver enabled (right now I'm forced to use the OpenGL one with the Arch Linux package) 🐸

**Comment by gucio321** [comment]
I'll not do anything more here. Waiting for review
CC @hrydgard

**Comment by hrydgard** [comment]
Just tested on Mac and it doesn't break this time, nice :)

Will actually review the code a bit later, gotta run.

**Review by hrydgard — APPROVED** [review]

**Pull request merged**
