### PR TITLE
Turn Off Sound When Fast Forwarding

### PR DESCRIPTION
**Pull request by turbo420**
I am not 100% sure this is right way to do this but we will see

### CODE REVIEW

**Comment by Gamemulatorer** [comment]
What's the difference of this in **alternate speed volume** mute?
Screenshot_2021-11-17-07-08-09-588_org ppsspp ppsspp

**Comment by LunaMoo** [comment]
None, I suppose @turbo420 simply didn't knew we have that feature already.

**Comment by hrydgard** [comment]
It is not exactly intuitive, but hopefully googling for a solution will end up here or in similar issues though.

**Comment by unknownbrackets** [comment]
Maybe we could change the name slightly, but I personally like it applying:
 * Even when speed is decreased to 50%.
 * Only as a decrease in volume, not total silence.
 * Whether toggled alternate speed is used or fast forward is used.

And I think it'd be silly/more confusing to have multiple settings (one for fast forward, another for alternate speed.)

@turbo420 thanks for opening a pull request and contributing.  As some feedback for next time, I'd suggest implementing `g_Config.bFastForwardSoundOff` as a function or similar, and calculating based on `g_Config.bFastForwardSound && PSP_CoreParameter().fastForward`.  Not in this case, because I think we have this feature already... but I know I always appreciate feedback on my code.

-[Unknown]

**Comment by turbo420** [comment]
I didn't know that alternate speed volume did that lol. Maybe a slight name change will help. 
I did learn a lot about ppsspp code though.

**Comment by Gamemulatorer** [comment]
Maybe change alternate speed volume to like this?
Screenshot_2021-11-17-10-21-11-471_com github stenzek duckstation

**Comment by unknownbrackets** [comment]
So you think we should remove the feature to decrease the volume when using a speed other than fast forward, such as 50% or 200%?

-[Unknown]

**Pull request closed without merging**
