### PR TITLE
x86jit: Handle vmin/vmax and vsge correctly

### LINKED ISSUE #4268: NFS MW hangs when police siren heard (After FFMPEG new merge)
After FFMPEG merge NFS most wanted stops working after some time when playing I am on x64 bit windows

Btw when it stops the sound goes weird first it gains speed then starts cracking

giving same emulation stops with audio and without audio

LOG:-
https://gist.github.com/bhavin192/0ddacb72d075eda48fb9

https://gist.github.com/bhavin192/7044c9857cb5fd119177

### PR DESCRIPTION
**Pull request by unknownbrackets**
Unfortunately, this boots vmin/vmax from simd, currently.  I'm not sure how to do that in any kind of efficient way.... not that the non-simd path is super efficient either.

Expected to fix #4268.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm, do we really need to do it in C functions? Should not be that many instructions.. You can always check what the C functions compile down to, heh.

Would be nice to at least do it in functions with custom calling conventions (that we can create in JitAsm.cpp on start) so we don't have to save registers and stuff

**Comment by unknownbrackets** [comment]
Well, I can of course do it in asm, sure, I was just thinking it'd be a lot of code to emit, and hopefully rare to actually run it.  Mostly I want to be sure this fixes that issue before optimizing it more.

But yeah, I can probably do the custom convention sometime a bit later.  Really there are probably several other cases where that'd be better.

-[Unknown]

**Comment by hrydgard** [comment]
Sure :)

Btw, what other cases are you thinking about where we should call some pregenerated mini function but don't now?

**Comment by unknownbrackets** [comment]
Probably:
  * lvl.q/lvr.q
  * Rounding where we toggle MXCSR (since it's a lot of code and there's probably latencies there where we could have the j be free.)
  * bitrev (less code, but would use an EAX temporary.)
  * long vfpu funcs like vqmul.q (though we'd have to do something to have spare regs, might not be worth it.)

-[Unknown]

**Comment by hrydgard** [comment]
Right, all pretty good candidates.

**Pull request merged**
