### PR TITLE
D3D: Generate shaders from shader IDs, just like in GL

### PR DESCRIPTION
**Pull request by hrydgard**
Lets us share the shader ID generation code between the backends. Modern GPU feature sets are  mostly are the same no matter the API, so we mostly use the same workarounds and stuff anyway.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Minor fix: 6b905e8e18cf3f8ced1911a6edc6b2d1f79412ce

-[Unknown]

**Comment by unknownbrackets** [comment]
So a few ideas about reducing # shaders, not necessarily all for the best overall:

1. If we could tolerate garbage in weights > nweights, we could gen less vertex shaders.  Not sure if there's actually pressure there.

2. We could replace all the replaceAlphaWithStencilType values with uniform updates, as long as we toggled the u_stencilReplaceValue value.  Maybe worth it?  Depends how the value is calculated in the binary.

3. We *could* replace REPLACE_BLEND_PRE_SRC / GE_SRCBLEND_FIXA / GE_SRCBLEND_FIXB (which is common) with always multiplying by u_blendFixA, and just set it to 1.0f when we don't need it.  Not sure if cheap, but there's probably cases where games switch.

4. Currently we detect when alpha is flat 1.0 and use simpler frag operations.  I thought this gave better frag perf, but it may also cause more shader switches.  We could go the reverse route - detect that textures are safe to treat as with alpha, since that's likely the more common shader.

5. We could make fog static by twiddling v_fogdepth instead.  Again, not sure the trade-off.

6. We could eliminate Flip by reversing the coordinate system per your earlier experiments (will mean lots of trouble with framebuf upload/download, etc.)

7. We could have the vertex decoder ALWAYS generate texcoord data, just with 0s (which is what !hasTexcoord does.)  This might not cut shaders much, but it'd probably be low impact, since vertex data without texcoords is unlikely to be heavy duty.

8. We might be able to do the same with normal, but not color.  I'm not sure if it'd be worth it for normal, though?

9. We could bind a texture, always, but sometimes as 1x1 1.0f, then always use modulate + doTexture=true.  Texture access is cheap and non-textured draws are usually not that hot.

10. It's probably doable to remove throughmode from the vertex shader, possibly generating different values.

-[Unknown]

**Comment by unknownbrackets** [comment]
Oh, and separately, worth noting - I was thinking of doing depal in the frag shader - could cut down on full copies of larger textures in some cases, but this will take at least a bit+uniforms or several bits, and cause more shaders.  Should be wary of the trade offs...

-[Unknown]

**Comment by CarlKenner** [comment]
No worries, I just thought I should test the big merge since I had merge conflicts, and I just happened to test it on James Cameron's Avatar which uses a lot of alpha testing.

**Pull request merged**
