### PR TITLE
Cache computed planes used for BBOX culling

### PR DESCRIPTION
**Pull request by hrydgard**
This isn't a huge performance boost for the games that use BBOX (like Tekken), although it does cut down these particular computations to a quarter-ish, but it'll be more valuable if we start using soft culling more widely automatically without BBOX, see #17808 . It's starting to look pretty interesting for performance in many games (though definitely not all).

EDIT: Hm, this fails the tests, interestingly..

### CODE REVIEW

**Review by unknownbrackets — COMMENTED** [review]
This is missing:

 * `GPUgstate::Reset()` needs to dirty.
 * `GPUgstate::Restore()` needs to dirty.
 * `GPUStateCache::DoState()` maybe too on load?
 * `SoftGPU::Execute_*Mtx*()` which is probably key to the test failing, i.e. your changes are only in GPUCommonHW.  SoftGPU updates "visible" matrices more accurately and has separate dirty flags for flushing software rendering.

-[Unknown]

**Comment by hrydgard** [comment]
Ah, thanks for the list :)

**Comment by unknownbrackets** [comment]
It still doesn't use the "normal" dirtying flags from HW, i.e. for scissor.  These are mostly useless to softgpu because it sends primitives to the queue right away, but tries to flush as inoften as possible.  I think we could just override Execute_BoundingBox and always mark dirty there, or else check the `SoftDirty::BINNER_RANGE` flag (which covers everything here) and translate it to the cull dirty flag.

-[Unknown]

**Comment by hrydgard** [comment]
Right.. I like the option of checking SoftDirty::BINNER_RANGE flags and translating, though what would be good place to do that?

**Comment by unknownbrackets** [comment]
This would be the place, since it's where the flag is checked and cleared:
https://github.com/hrydgard/ppsspp/blob/a28acf26620753eed677747a162fb3eca33eccd7/GPU/Software/BinManager.cpp#L213

But it's only done on submit to the binner, so it'd also need to be checked before testing the bounding box (and couldn't be cleared then.)  Not super simple... well, we could add another dirty flag, but I'm not sure how much this would even help softgpu, for bbox tests alone.  And it's already culling verts on intake.

-[Unknown]

**Comment by hrydgard** [comment]
That seems to work and should be safe, so I'll go with that.

**Pull request merged**
