### PR TITLE
GE Debugger: Add step count dialog.

### PR DESCRIPTION
**Pull request by xebra**
Try to improve #11616 a bit.

- Modeless dialog.
- Preset value.
- 1-click to jump relatively/absolutely.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
If I press Ctrl-N, type 500, and press enter - will it jump?  Or will I have to press tab / click with the mouse to focus the field and activate the right button?

-[Unknown]

**Comment by xebra** [comment]
No, for now.
I'll try to fix it.

**Comment by xebra** [comment]
Done.

**Review by hrydgard — APPROVED** [review]

**Comment by hrydgard** [comment]
@unknownbrackets , I'll leave the merge to you

**Pull request merged**
