### PR TITLE
GPS: Improve emulation to enable Go!Explore navigation

### PR DESCRIPTION
**Pull request by Florin9doi**
Depends on #18665

go!explore

### CODE REVIEW

**Comment by hrydgard** [comment]
Very cool!

I'll take another look at #18665 soon, then this.

**Comment by anr2me** [comment]
Hmm.. could that `garbage1` and `garbage2` be `pdop` and `vdop` when looking at this data https://smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/GPSData/

**Comment by Florin9doi** [comment]
> Hmm.. could that `garbage1` and `garbage2` be `pdop` and `vdop` when looking at this data https://smartdevicelink.com/en/docs/android/master/com/smartdevicelink/proxy/rpc/GPSData/

`garbage1` and `3` are always 0 on my PSP, even after the position is established, only `garbage2` takes different values.
However I haven't seen `pdop/vdop` reported by any app so far : 
GoExplore
Homestar Portable
Maplus 1
Maplus 2
Maplus 3
Minna no Navi

**Review by hrydgard — APPROVED** [review]

**Comment by Darthagnon** [comment]
What are those GPS programs for PSP? I've only ever heard of Go!Explore, and would like to try some of the above on my real hardware...

**Comment by Florin9doi** [comment]
Excluding Go!Explore, everything else is Japan-exclusive and won't work abroad unless you use something like `Fake GPS location` app on Android. The titles/serials are visible in titlebar: Homestar Portable, Maplus 1/2/3 and Minna no Navi

**Pull request merged**
