### PR TITLE
Unification menu between Windows and Linux versions (need help)

### LINKED ISSUE #10484: Unification menus on Windows and Linux versions
Windows and Linux versions have different menus. Linux version has less points and English-only. Can you unify them?
Windows 7

Linux (Lubuntu 16.04.3, Ubuntu PPA)

### PR DESCRIPTION
**Pull request by TotalCaesar659**
I've tried to fix https://github.com/hrydgard/ppsspp/issues/10484. Some menu points are not implemented (cause I don't know how), some may be bugged, so I push it for checking.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Sorry for the lack of reply here.  I think it'd be better to break this up and start with just the items you know what do and are implemented.  That'll make it easier to review and easier to explain the ones that are still missing.

-[Unknown]

**Comment by TotalCaesar659** [comment]
Do you want me to close this PR and start it partially over again?

**Comment by unknownbrackets** [comment]
I'm generally a fan of updating existing pull requests, but either way is fine.  I think we should split up the commits to make it easier.

Some of these options I think are actually Windows specific or may require non-trivial work to implement for Qt.  But there are other menu items we could update and get in real soon.  I think splitting it up is the first step.

Some examples:
 * bVSync - this is actually forced on for Linux / Qt / etc. right now.  It may be possible to disable but it's going to be more work than just the menus.
 * Open directory is intended to open a folder/directory which is an extracted ISO.  It's usually used for rom hacking.

In general it looks like most of the menu items you added are working and look good, so it's hard for me to even tell which ones you're most concerned about.

-[Unknown]

**Comment by TotalCaesar659** [comment]
OK, I think I'll better to make fresh PR with split commits and only those options that I'm sure, thanks.

**Pull request closed without merging**
