### PR TITLE
[UI] Show a tip message when enabling "UPnP use original port" option.

### PR DESCRIPTION
**Pull request by anr2me**
Hopefully this can prevent users from randomly enabling options that may or may not work for them.

### CODE REVIEW

**Comment by iota97** [comment]
Mhhhh, I have trouble understanding the meaning, what is the role of the PC and Android? I should try to connect from a PC in another network, to connect the PC and the phone on the same LAN to test port offset?

I admit I kinda dislike networks and I don't know much about them, but probably most of our users know even less.

What about user that have only a phone and no PC? Can it be tested in another way?

I'm not sure if the attempt to describe a trouble shooting belong to a tip (even more a timed one that will expire, I can see people spamming on/off just to read it again).

Don't get me wrong I'm not against this one, just wondering if we can find better words for it :)

PS: I'm not a native english speaker but "Be sure" seems weird to me, shouldn't it be "Make sure"?

**Comment by MojoJojoDojo** [comment]
> Edit: did you mean that original port offset must work with 2 PC over LAN and that Android have the first 1024 unavailable for security reason? Hope not, seem a nightmare to explain ahahah

That restriction is just a pain in the ass... and it doesnt even apply to IOS for some reason.

**Comment by ANR2ME** [comment]
> Mhhhh, I have trouble understanding the meaning, what is the role of the PC and Android? I should try to connect from a PC in another network, to connect the PC and the phone on the same LAN to test port offset?
> 
> I admit I kinda dislike networks and I don't know much about them, but probably most of our users know even less.
> 
> What about user that have only a phone and no PC? Can it be tested in another way?
> 
> I'm not sure if the attempt to describe a trouble shooting belong to a tip (even more a timed one that will expire, I can see people spamming on/off just to read it again).
> 
> Don't get me wrong I'm not against this one, just wondering if we can find better words for it :)
> 
> PS: I'm not a native english speaker but "Be sure" seems weird to me, shouldn't it be "Make sure"?
> 
> Edit: did you mean that original port offset must work with 2 PC over LAN and that Android have the first 1024 unavailable for security reason? Hope not, seem a nightmare to explain ahahah

"Use original port" only related to port forwarding over public IP to simulate Port Offset = 0 over public IP, mapped/forwarded to a different port on local IP, so "Use original port" won't affect LAN/VPN multiplayer.
While Port Offset = 0 worked for all kind of network, but because some games are using ports under 1024, Android users won't be able to bind/listen on such ports (even with root access it won't work on zygote, may be only worked as background service but too complicated).

Isn't "Make sure" is some thing that you can do about to make it work? while "Be sure" is something you can't do about if it isn't working, right?

Because if someone can't play using Port Offset = 0, they won't be able to use "Use original port" either, and there are several reasons:
- PPSSPP need admin/sudo in order to bind ports under 1024 (usually binding to port < 1024 only worked on PC/Mac)
- Someone else using the same router is already using the port mapping for internet service (ie. web server, ftp server, telnet server, etc), thus the router might remap the port to a random public port.

**Comment by unknownbrackets** [comment]
Some ISPs will actually block some of the ports below < 1024 for various reasons.  One of the primary reasons is that when a person's device is compromised, it may often use these lower ports (i.e. to send spam, serve phishing websites, etc.)

Maybe it's best to be more general, and say something to the effect of, "May not work for all devices or games, see wiki."  I think the problems with this setting are too complex to explain in a tip.

-[Unknown]

**Comment by ANR2ME** [comment]
Ah yes, we should directs users to PPSSPP's wiki so they will know about it's existence and able to find out more info there.

**Comment by MojoJojoDojo** [comment]
> Also, at wiki it's titled "How to play multiplayer games with PPSSPP" :D LOL, we should probably mentioned "Ad-Hoc" too at that wiki page (but will need to change a lot of stuff due to link difference), and may be have a separate wiki page for Infrastructure multiplayer in the future.

TBH that page was made before you even worked on the infrastructure stuff lol didn't think of it as a possibilty.
And currently PPSSPP doesn't work with infrastructure yet.

**Comment by ANR2ME** [comment]
> > Also, at wiki it's titled "How to play multiplayer games with PPSSPP" :D LOL, we should probably mentioned "Ad-Hoc" too at that wiki page (but will need to change a lot of stuff due to link difference), and may be have a separate wiki page for Infrastructure multiplayer in the future.
> 
> TBH that page was made before you even worked on the infrastructure stuff lol didn't think of it as a possibilty. And currently PPSSPP doesn't work with infrastructure yet.

That's why i choose to replace "PPSSPP Ad-Hoc Wiki Page" with "Open PPSSPP Multiplayer Wiki Page" to match the wiki page title and to be more general, since infrastructure won't have too many options like what AdHoc have, probably just DNS-related settings.

**Comment by hrydgard** [comment]
I like the change to the wiki page choice name, but we have to do something about the translation inis too. Maybe just change the keys (a simple global search-replace should do it) so they point to the old translation which is better than nothing, at least, then they can be updated successively.

**Comment by ANR2ME** [comment]
Hmm.. apparently i can find "PPSSPP Ad-Hoc Wiki Page" using "Find in Files" feature of VS2019, it doesn't seems to be checking INI files in `assets\lang` folder.

What tools do you guys usually use to replace a key in all of those INI files?

**Comment by hrydgard** [comment]
Yeah, better than nothing for sure.

**Pull request merged**
