### PR TITLE
Add: -ffast-math compiler option to anything other then Intel

### PR DESCRIPTION
**Pull request by AreaScout**
as the title says

### CODE REVIEW

**Comment by hrydgard** [comment]
motivation?

**Comment by unknownbrackets** [comment]
I mean, don't we enable this in MSVC?  https://github.com/hrydgard/ppsspp/blob/a004196d4388b958963083dee4619bc6fbc438a8/Windows/PPSSPP.vcxproj#L132

If it's good for Windows, why not do it everywhere?

-[Unknown]

**Comment by hrydgard** [comment]
I'm fine with it, I just want to see more in the pull request description than to add an option. Also it's not clear why not for Intel?

Anyway, merging.

**Comment by unknownbrackets** [comment]
I think we should do it on all gcc/clang, arm/arm64/intel/whatever.

-[Unknown]

**Comment by Bigpet** [comment]
The exception is not about about Intel/ARM but about icc.
I don't think many people compile it with icc but my short research shows that it uses `-fp-model fast=1` by default.

**Comment by unknownbrackets** [comment]
Just a note for posterity: we've discovered behavior that was broken with fast-math (only certain versions of gcc/clang it seems, though) and we're not seeing a significant performance difference.  It's disabled now.

I recommend turning it off.  Most of the speed critical code in PPSSPP that would be affected by fast-math is actually already in jit.  I wonder if we should disable it for MSVC as well...

-[Unknown]

**Comment by hrydgard** [comment]
We probably should indeed, though as I don't know any issue with it I'll do the change after 1.8.0.

**Comment by AreaScout** [comment]
Did we add it explicitly for MSVC ? Can't remember ...

**Pull request merged**
