### PR TITLE
Implement sceSas' reverb effect, guessing that the reverb is the same as the one in PSX's SPU

### PR DESCRIPTION
**Pull request by hrydgard**
I tried to implement it straight from http://problemkaputt.de/psx-spx.htm#spureverbformula .

This works pretty well now, although there's some uncertainty about how the input to the reverb should be scaled - just passing the audio in directly ends up too loud.

### CODE REVIEW

**Comment by daniel229** [comment]
Uesd in Final Fantasy Tactics.

**Comment by hrydgard** [comment]
To find games to test you can also use http://report.ppsspp.org/logs/kind/772 

Do not start testing yet, it's pointless until it works better.

**Comment by daniel229** [comment]
Okay.

**Comment by hrydgard** [comment]
@daniel229 it's slightly more interesting now :)  Although it seems it's too loud in many games.

**Comment by daniel229** [comment]
Buzz noise in Final Fantasy Tactics in the first battle map.

**Comment by hrydgard** [comment]
So from my testing:

Sounds great in Wipeout, FF:Crisis Core, Loco Roco where used

Sounds a bit loud but often OK in GTA: LCS

Sounds too loud/broken in Tekken 6, and it seems, quite a few more.

Well, it's a start....

**Comment by unknownbrackets** [comment]
Tales of Phantasia when turning reverb OFF:

sceSasRevParam(core, 6, 6)
sceSasRevEVOL(core, 4096, 4096)
sceSasRevVON(core, 1, 0)

Tales of Phantasia when turning reverb ON:

sceSasRevType(core, 5)
sceSasRevParam(core, 6, 6)
sceSasRevEVOL(core, 4096, 4096)
sceSasRevVON(core, 1, 1)

In other words, it turns wet off to disable reverb.  I'm not sure what the difference/meaning is.  I know they can both be separately enabled/disabled...

Very cool.  Maybe we can do some tests to model the data against to figure out the volume.

-[Unknown]

**Comment by hrydgard** [comment]
Dry/Wet on/off makes sense, it's common audio mixing terminology. Just not checking for it yet :) Dry is the input signal, wet is the output from the effect. You could even play only the output if you wanted to by turning off Dry.

Will implement later. Yeah, figuring out the volume correctly will take some tests..

**Comment by hrydgard** [comment]
Should be no more buzzsaw noises now, although it can still be a bit loud at times I think.

**Comment by hrydgard** [comment]
This is still sometimes a little loud but really adds a lot to many games, and never sounds like a buzzsaw anymore. Also, it's quite fast, barely shows up on profiles. I'm merging. We can improve the volume control later.

**Comment by vnctdj** [comment]
@hrydgard 
This is an impressing feature :)

However, I have already spotted some sounds which actually are too loud.
How to properly report these cases in order to help fixing them ?

**Comment by hrydgard** [comment]
Well, you can create a new issue, listing the games that are too loud.

Hopefully some hardware testing will let us find the right volume levels so we can just fix them all at once later.

**Pull request merged**
