### PR TITLE
Adds --PS3 comand line option for PS3 controller support on SDL.

### PR DESCRIPTION
**Pull request by klyoungblood**
Per the request at the forum thread here http://forums.ppsspp.org/showthread.php?tid=20003 I've added support for a --PS3 runtime option to support the PS3 controller's default Linux mappings in the PPSSPP interface.

### CODE REVIEW

**Comment by hrydgard** [comment]
I wonder why the PS3 controller gets such a strange default mapping.

Is there a way to detect the PS3 controller instead? Otherwise I suppose we'll have to live with something like this.

**Comment by klyoungblood** [comment]
I will check tonight if SDL_JoystickName() returns something we can use to auto-detect a PS3 controller.

**Comment by klyoungblood** [comment]
"PLAYSTATION(R)3 Controller" is a pretty distinctive ID string. It wasn't difficult to match it, but I had to delay control mapping slightly (till after joystick detection). I've kept the --PS3 flag just in case there's an edge care where autodetection fails.

**Comment by hrydgard** [comment]
Ain't pretty, but that's great that you managed autodetection :)

**Pull request merged**
