### PR TITLE
Make sceMp3 more accurate, fix wrong output count

### PR DESCRIPTION
**Pull request by unknownbrackets**
This is based on the tests in hrydgard/pspautotests#198.

The most important change here is the one to `sceMp3GetMaxOutputSample()`.  Before, this simply returned 1/4 of the provided buffer (so, size of buffer in shorts, stereo.)  But the function is actually supposed to return the frame size.  On a PSP, I can only make it produce 1152.

Some games use this value to determine how much to read after decode.  Most games had enough space for 2 frames because that's the minimum size of the output buffer, which I suspect is why the "sound speed hack" helped.  Some games (like Orbit) rely on the "knowledge" that a frame is 1152, and don't call this function.

I suspect this will help #9379, but I only have limited games to verify with.

Other than that, this only touches/improves the tested functions, but fixes a few things:

 * Correct error codes throughout tested functions.
 * Reschedule on init functions more correctly.
 * Allocate handles as 0 and 1 only, which could've been relied on by a game as an array index.
 * Only modify stream metadata in `sceMp3NotifyAddStreamData()`, not `sceMp3GetInfoToAddStreamData()` (which is just a read only getter.)  May fix games that call GetInfo multiple times per add.
 * Ask for less data, better matching what the PSP asks for (still not exactly right, since after the initial filling, it should only ask for half the buffer at a time.)
 * Release handles on `sceMp3TermResource()`.
 * Allow mp3 frames to be offset within provided data (search for sync marker.)
 * Reject invalid mp3 frame headers (left it more forgiving than on a PSP.)

-[Unknown]

### CODE REVIEW

**Review by hrydgard — APPROVED** [review]
Really nice. Happy to just merge and see how it goes.

The hope is that this would completely replace https://github.com/hrydgard/ppsspp/pull/10783 , right? In that case, removing the "Audio speed hack" could also be included (or just as well committed afterwards).

**Comment by unknownbrackets** [comment]
Yeah, figured we could remove the hack once confirmed (perhaps by merging a tweaked #10783.)  Didn't want to remove the hack with just one song in one game as confirmation...

-[Unknown]

**Comment by hrydgard** [comment]
That's fair, let's await feedback (and CI, heh). I'll also try Wipeout Pulse custom background music, which used to be broken..

**Comment by hrydgard** [comment]
Hm, strangely, Wipeout Pulse custom soundtracks now don't play at all, instead of playing chopped up at half speed like before. I'll investigate tomorrow.

**Comment by LunaMoo** [comment]
EDGE and Mighty Flip Champs DX works fine with this, nice work;3. Quake II homebrew ~ #6842 also had a nasty mp3 issue not fixed previously that might be worth testing with this.

**Comment by unknownbrackets** [comment]
I've had trouble with mp3s for a few reasons, in case it helps.

1. I'm mostly sure it just searches for a sync and ignores/doesn't support ID3 directly at all.  Based on my tests, that means it can handle ID3 data that is at most 1439 bytes.

2. It may (?) only support CBR, but seems to support bitrates from 32 to 320 kbps.  What's odd is I know there are games which quote a max of 256 kbps or similar, so I may be missing something.

3. Cover images definitely seem to cause trouble (probably because of point 1.)

4. I can't get it to accept anything but MPEG v1 layer 3, even though it has a function `sceMp3GetMPEGVersion()` which returns the version bits from the header (implying that it would support more versions...)  Note that this pull doesn't give errors for such MP3s from PPSSPP, so such MP3s might just work improperly in PPSSPP and not at all on a PSP.

-[Unknown]

**Comment by unknownbrackets** [comment]
Anything logged in Pulse?  I don't have that one.

-[Unknown]

**Comment by hrydgard** [comment]
Actually, I take back what I said, I don't know what happened but getting different results today, which are the same as without this change.

Some MP3s play, but still at half rate and choppy, others don't.

Here's one that doesn't:

```
27:54:881 ThreadBGM    D[ME]: hle\scemp3.cpp:573 0=sceMp3NotifyAddStreamData(00000000, 6720)
27:54:882 Main thread  D[ME]: hle\scempeg.cpp:1604 0=sceMpegGetAvcAu(08d0c160, 00000003, 08d0c170, 09fb79b4)
27:54:882 Main thread  D[ME]: hle\scempeg.cpp:1092 video: bufferAddr = 09fb79b0, *buffer = 09462f80, *init = 08d0c0b4
27:54:883 Main thread  D[ME]: hle\scempeg.cpp:1153 sceMpegAvcDecode(08d0c160, 08d0c170, 512, 09fb79b0, 09fb79b8)
27:54:913 ThreadBGM    D[ME]: hle\scemp3.cpp:455 sceMp3GetLoopNum(00000000)
27:54:913 ThreadBGM    D[ME]: hle\scemp3.cpp:157 sceMp3Decode(00000000,09f94470)
27:54:913 ThreadBGM    I[ME]: hw\mediaengine.cpp:86 FF: Header missing
27:54:913 ThreadBGM    E[ME]: hw\simpleaudiodec.cpp:198 Error decoding Audio frame (6720 bytes): -1094995529 (bebbb1b7)
27:54:914 Main thread  D[ME]: hle\scempeg.cpp:1604 0=sceMpegGetAvcAu(08d0c160, 00000003, 08d0c170, 09fb79b4)
27:54:914 Main thread  D[ME]: hle\scempeg.cpp:1092 video: bufferAddr = 09fb79b0, *buffer = 095fafe0, *init = 08d0c0b4
27:54:915 Main thread  D[ME]: hle\scempeg.cpp:1153 sceMpegAvcDecode(08d0c160, 08d0c170, 512, 09fb79b0, 09fb79b8)
27:54:915 ThreadBGM    D[ME]: hle\scemp3.cpp:195 1=sceMp3CheckStreamDataNeeded(00000000)
27:54:915 ThreadBGM    D[ME]: hle\scemp3.cpp:560 0=sceMp3GetInfoToAddStreamData(00000000, 09f94440[08af5b40], 09f94444[00001a40], 09f94448[00000400])
27:54:915 readThread   D[ME]: hle\scempeg.cpp:1423 4=sceMpegRingbufferAvailableSize(08d0c0e0)
27:54:915 ThreadBGM    D[ME]: hle\scemp3.cpp:573 0=sceMp3NotifyAddStreamData(00000000, 6720)
27:54:915 ThreadBGM    D[ME]: hle\scemp3.cpp:157 sceMp3Decode(00000000,09f94470)
27:54:915 ThreadBGM    I[ME]: hw\mediaengine.cpp:86 FF: Header missing
27:54:915 ThreadBGM    E[ME]: hw\simpleaudiodec.cpp:198 Error decoding Audio frame (6720 bytes): -1094995529 (bebbb1b7)
27:54:915 readThread   D[ME]: hle\scempeg.cpp:1517 sceMpegRingbufferPut(08d0c0e0, 4, 4)
27:54:915 readThread   D[ME]: hle\scempeg.cpp:1487 packetAdded: 4 packetsRead: 1784 packetsTotal: 512
27:54:915 readThread   D[ME]: hle\scempeg.cpp:1423 0=sceMpegRingbufferAvailableSize(08d0c0e0)
27:54:915 ThreadBGM    D[ME]: hle\scemp3.cpp:195 1=sceMp3CheckStreamDataNeeded(00000000)
27:54:915 ThreadBGM    D[ME]: hle\scemp3.cpp:560 0=sceMp3GetInfoToAddStreamData(00000000, 09f94440[08af5b40], 09f94444[00001a40], 09f94448[00000400])
27:54:915 ThreadBGM    D[ME]: hle\scemp3.cpp:573 0=sceMp3NotifyAddStreamData(00000000, 6720)
27:54:948 Main thread  D[ME]: hle\scempeg.cpp:1604 0=sceMpegGetAvcAu(08d0c160, 00000003, 08d0c170, 09fb79b4)
27:54:948 Main thread  D[ME]: hle\scempeg.cpp:1092 video: bufferAddr = 09fb79b0, *buffer = 09572fc0, *init = 08d0c0b4
27:54:948 Main thread  D[ME]: hle\scempeg.cpp:1153 sceMpegAvcDecode(08d0c160, 08d0c170, 512, 09fb79b0, 09fb79b8)
27:54:948 readThread   D[ME]: hle\scempeg.cpp:1423 4=sceMpegRingbufferAvailableSize(08d0c0e0)
27:54:948 readThread   D[ME]: hle\scempeg.cpp:1517 sceMpegRingbufferPut(08d0c0e0, 4, 4)
27:54:948 readThread   D[ME]: hle\scempeg.cpp:1487 packetAdded: 4 packetsRead: 1788 packetsTotal: 512
27:54:948 readThread   D[ME]: hle\scempeg.cpp:1423 0=sceMpegRingbufferAvailableSize(08d0c0e0)
27:54:949 ThreadBGM    D[ME]: hle\scemp3.cpp:455 sceMp3GetLoopNum(00000000)
27:54:949 ThreadBGM    D[ME]: hle\scemp3.cpp:157 sceMp3Decode(00000000,09f94470)
27:54:949 ThreadBGM    I[ME]: hw\mediaengine.cpp:86 FF: Header missing
27:54:949 ThreadBGM    E[ME]: hw\simpleaudiodec.cpp:198 Error decoding Audio frame (6720 bytes): -1094995529 (bebbb1b7)
27:54:949 ThreadBGM    D[ME]: hle\scemp3.cpp:195 1=sceMp3CheckStreamDataNeeded(00000000)
27:54:949 ThreadBGM    D[ME]: hle\scemp3.cpp:560 0=sceMp3GetInfoToAddStreamData(00000000, 09f94440[08af5b40], 09f94444[00001a40], 09f94448[00000400])
27:54:949 ThreadBGM    D[ME]: hle\scemp3.cpp:573 0=sceMp3NotifyAddStreamData(00000000, 6720)
27:54:949 ThreadBGM    D[ME]: hle\scemp3.cpp:157 sceMp3Decode(00000000,09f94470)
27:54:949 ThreadBGM    I[ME]: hw\mediaengine.cpp:86 FF: Header missing
```

And here's one that does.

```
32:00:259 ThreadBGM    D[ME]: hle\scemp3.cpp:157 sceMp3Decode(00000000,09f94470)
32:00:259 ThreadBGM    D[ME]: hle\scemp3.cpp:195 1=sceMp3CheckStreamDataNeeded(00000000)
32:00:259 ThreadBGM    D[ME]: hle\scemp3.cpp:560 0=sceMp3GetInfoToAddStreamData(00000000, 09f94440[08af5b40], 09f94444[00000240], 09f94448[0002ff00])
32:00:260 ThreadBGM    D[ME]: hle\scemp3.cpp:573 0=sceMp3NotifyAddStreamData(00000000, 576)
32:00:293 Main thread  D[ME]: hle\scempeg.cpp:1604 0=sceMpegGetAvcAu(08d0c160, 00000003, 08d0c170, 09fb79b4)
32:00:293 Main thread  D[ME]: hle\scempeg.cpp:1092 video: bufferAddr = 09fb79b0, *buffer = 095fafe0, *init = 08d0c0b4
32:00:293 Main thread  D[ME]: hle\scempeg.cpp:1153 sceMpegAvcDecode(08d0c160, 08d0c170, 512, 09fb79b0, 09fb79b8)
32:00:326 ThreadBGM    D[ME]: hle\scemp3.cpp:455 sceMp3GetLoopNum(00000000)
32:00:326 ThreadBGM    D[ME]: hle\scemp3.cpp:157 sceMp3Decode(00000000,09f94470)
32:00:326 ThreadBGM    D[ME]: hle\scemp3.cpp:195 1=sceMp3CheckStreamDataNeeded(00000000)
32:00:326 ThreadBGM    D[ME]: hle\scemp3.cpp:560 0=sceMp3GetInfoToAddStreamData(00000000, 09f94440[08af5b40], 09f94444[00000240], 09f94448[00030140])
32:00:326 ThreadBGM    D[ME]: hle\scemp3.cpp:573 0=sceMp3NotifyAddStreamData(00000000, 576)
32:00:326 ThreadBGM    D[ME]: hle\scemp3.cpp:157 sceMp3Decode(00000000,09f94470)
32:00:326 ThreadBGM    D[ME]: hle\scemp3.cpp:195 1=sceMp3CheckStreamDataNeeded(00000000)
32:00:326 ThreadBGM    D[ME]: hle\scemp3.cpp:560 0=sceMp3GetInfoToAddStreamData(00000000, 09f94440[08af5b40], 09f94444[00000240], 09f94448[00030380])
32:00:326 ThreadBGM    D[ME]: hle\scemp3.cpp:573 0=sceMp3NotifyAddStreamData(00000000, 576)
32:00:327 Main thread  D[ME]: hle\scempeg.cpp:1604 0=sceMpegGetAvcAu(08d0c160, 00000003, 08d0c170, 09fb79b4)
32:00:327 Main thread  D[ME]: hle\scempeg.cpp:1092 video: bufferAddr = 09fb79b0, *buffer = 09572fc0, *init = 08d0c0b4
32:00:327 Main thread  D[ME]: hle\scempeg.cpp:1153 sceMpegAvcDecode(08d0c160, 08d0c170, 512, 09fb79b0, 09fb79b8)
32:00:327 readThread   D[ME]: hle\scempeg.cpp:1423 4=sceMpegRingbufferAvailableSize(08d0c0e0)
32:00:327 readThread   D[ME]: hle\scempeg.cpp:1517 sceMpegRingbufferPut(08d0c0e0, 4, 4)
32:00:328 readThread   D[ME]: hle\scempeg.cpp:1487 packetAdded: 4 packetsRead: 4412 packetsTotal: 512
32:00:328 readThread   D[ME]: hle\scempeg.cpp:1423 0=sceMpegRingbufferAvailableSize(08d0c0e0)
32:00:359 Main thread  D[ME]: hle\scempeg.cpp:1604 0=sceMpegGetAvcAu(08d0c160, 00000003, 08d0c170, 09fb79b4)
32:00:359 Main thread  D[ME]: hle\scempeg.cpp:1092 video: bufferAddr = 09fb79b0, *buffer = 094eafa0, *init = 08d0c0b4
32:00:359 Main thread  D[ME]: hle\scempeg.cpp:1153 sceMpegAvcDecode(08d0c160, 08d0c170, 512, 09fb79b0, 09fb79b8)
```

Anyway, I'm alright with merging this now as it doesn't seem to be any kind of regression here, even though it doesn't work right yet.

**Comment by unknownbrackets** [comment]
"FF: Header missing" - I think this is because of the buggy ID3 handling.  I haven't really mucked with that yet, as mentioned.  If I kill the ID3 handling, it works more often for my MP3s with ID3 tags, but I don't have Hanayaka Nari Wa ga Ichizoku to validate.

-[Unknown]

**Comment by unknownbrackets** [comment]
Just for clarity: I've tested more mp3 functions and already created some fixes for them (for example `sceMp3GetFrameNum()` is very wrong in current master), but I don't want to change the entire sceMp3 world in one go, especially because of how few games I have that use it.

-[Unknown]

**Comment by LunaMoo** [comment]
Henrik already approved and this does fix the minis so going to press that merge button:3.
 If it's not already part of incoming mp3 changes I changed my pr to just remove the sound speed hack which could be merged after this as it's no longer valid.

**Pull request merged**
