### PR TITLE
Vulkan: Update shaders/state when dirty properly

### PR DESCRIPTION
**Pull request by unknownbrackets**
Can't have been right before, unless I'm totally crazy?  I'm not sure how things were working so well without this...

Doesn't help #10573 but saw it while looking for is dirty checks.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
@unknownbrackets It's worked because lastPipeline_  is always zero currently. But good catch :)

**Comment by unknownbrackets** [comment]
Ah, right:
https://github.com/hrydgard/ppsspp/blob/e7d07aff71389dd67791346476c03b6a5e52c665/GPU/Vulkan/DrawEngineVulkan.cpp#L587

-[Unknown]

**Comment by unknownbrackets** [comment]
Could we make the pipeline caching renderManager's responsibility?  `renderManager->LastPipeline()` or something that becomes nullptr on new render passes...

-[Unknown]

**Comment by hrydgard** [comment]
That could make sense...

**Pull request merged**
