### PR TITLE
General crash and hang fixes

### PR DESCRIPTION
**Pull request by hrydgard**
The Play console gained improved crash and ANR (application not responding) reporting, I'm going through them and finding some issues.

The top crashes is ManagedTexture related, and that means it's likely related to the GameInfoCache, so I've made some reliability improvements to that.

### CODE REVIEW

**Comment by hrydgard** [comment]
Ooh, found a fun deadlock between eventMutex_ in view.cpp and inputLock_ in screen.cpp:

```
  native: pc 00000000004496af  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (ScreenManager::push(Screen*, int)+26)
  native: pc 000000000044c777  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::PopupMultiChoice::HandleClick(UI::EventParams&)+814)
  native: pc 0000000000452c05  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::DispatchEvents()+260)
  native: pc 000000000045e805  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::UpdateViewHierarchy(UI::ViewGroup*)+1084)
  native: pc 00000000003e445f  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (GameSettingsScreen::update()+10)
  native: pc 00000000003adbbf  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (NativeUpdate()+366)
  native: pc 00000000003a7e3d  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (Java_org_ppsspp_ppsspp_NativeRenderer_displayRender+40)
  native: pc 0000000000004ea7  /data/dalvik-cache/arm/data@app@org.ppsspp.ppsspp-1@base.apk@classes.dex (Java_org_ppsspp_ppsspp_NativeRenderer_displayRender__+82)
  at org.ppsspp.ppsspp.NativeRenderer.displayRender (Native method)
  at org.ppsspp.ppsspp.NativeRenderer.onDrawFrame (NativeRenderer.java:57)
  at android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1522)
  at android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1239)
```
vs
``` native: pc 000000000045296b  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::EventTriggered(UI::Event*, UI::EventParams)+34)
  native: pc 0000000000453217  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::Event::Trigger(UI::EventParams&)+54)
  native: pc 0000000000453ac7  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::Clickable::Click()+46)
  native: pc 0000000000453d19  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::Clickable::Touch(TouchInput const&)+376)
  native: pc 0000000000459cc9  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::ViewGroup::Touch(TouchInput const&)+56)
  native: pc 0000000000459cc9  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::ViewGroup::Touch(TouchInput const&)+56)
  native: pc 000000000045b933  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::ScrollView::Touch(TouchInput const&)+338)
  native: pc 0000000000459cc9  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::ViewGroup::Touch(TouchInput const&)+56)
  native: pc 0000000000459cc9  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::ViewGroup::Touch(TouchInput const&)+56)
  native: pc 000000000045e395  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UI::TouchEvent(TouchInput const&, UI::ViewGroup*)+24)
  native: pc 000000000044b147  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (UIScreen::touch(TouchInput const&)+18)
  native: pc 00000000004491eb  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (ScreenManager::touch(TouchInput const&)+74)
  native: pc 00000000003add19  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (NativeTouch(TouchInput const&)+20)
  native: pc 00000000003a8643  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (Java_org_ppsspp_ppsspp_NativeApp_touch+62)
  native: pc 0000000000008c8b  /data/dalvik-cache/arm/data@app@org.ppsspp.ppsspp-1@base.apk@classes.dex (Java_org_ppsspp_ppsspp_NativeApp_touch__FFII+110)
  at org.ppsspp.ppsspp.NativeApp.touch (Native method)
  at org.ppsspp.ppsspp.NativeGLView.onTouchEvent (NativeGLView.java:111)
```

**Comment by hrydgard** [comment]
I'm starting to think we should serialize touch events and similar and process them once per frame in the UI layer (we'll still immediately forward them to the emulation during gameplay)...

**Comment by hrydgard** [comment]
Here's one I don't know what to make of: 

```
"GLThread 27158" prio=5 tid=11 Native
  | group="main" sCount=1 dsCount=0 obj=0x12c03080 self=0xb8696438
  | sysTid=15996 nice=0 cgrp=default sched=0/0 handle=0xa33b5930
  | state=R schedstat=( 0 0 0 ) utm=6827 stm=2137 core=1 HZ=100
  | stack=0xa32b3000-0xa32b5000 stackSize=1038KB
  | held mutexes=
  native: pc 00000000000435c4  /system/lib/libc.so (gettimeofday+12)
  native: pc 0000000000037da5  /system/lib/libc.so (time+8)
  native: pc 00000000003a4913  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer16GetTimeFormattedEPc+22)
  native: pc 00000000003a4911  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer16GetTimeFormattedEPc+20)
  native: pc 00000000003a490f  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer16GetTimeFormattedEPc+18)
  native: pc 00000000003a490d  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer16GetTimeFormattedEPc+16)
  native: pc 00000000003a490b  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer16GetTimeFormattedEPc+14)
  native: pc 00000000003a4909  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer16GetTimeFormattedEPc+12)
  native: pc 00000000003a4907  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer16GetTimeFormattedEPc+10)
  native: pc 00000000003a4905  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer16GetTimeFormattedEPc+8)
  native: pc 00000000003a4903  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer16GetTimeFormattedEPc+6)
  native: pc 00000000003a4901  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer16GetTimeFormattedEPc+4)
  native: pc 00000000003a48ff  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer16GetTimeFormattedEPc+2)
  native: pc 00000000003a48fd  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer16GetTimeFormattedEPc)
  native: pc 00000000003a48fb  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+90)
  native: pc 00000000003a48f9  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+88)
  native: pc 00000000003a48f7  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+86)
  native: pc 00000000003a48f5  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+84)
  native: pc 00000000003a48f1  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+80)
  native: pc 00000000003a48ef  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+78)
  native: pc 00000000003a48ed  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+76)
  native: pc 00000000003a48eb  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+74)
  native: pc 00000000003a48e9  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+72)
  native: pc 00000000003a48e7  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+70)
  native: pc 00000000003a48e5  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+68)
  native: pc 00000000003a48e3  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+66)
  native: pc 00000000003a48e1  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+64)
  native: pc 00000000003a48df  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+62)
  native: pc 00000000003a48dd  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+60)
  native: pc 00000000003a48db  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+58)
  native: pc 00000000003a48d9  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+56)
  native: pc 00000000003a48d7  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+54)
  native: pc 00000000003a48d5  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+52)
  native: pc 00000000003a48d3  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+50)
  native: pc 00000000003a48d1  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+48)
  native: pc 00000000003a48cf  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+46)
  native: pc 00000000003a48cd  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+44)
  native: pc 00000000003a48c9  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+40)
  native: pc 00000000003a48c7  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+38)
  native: pc 00000000003a48c3  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+34)
  native: pc 00000000003a48c1  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+32)
  native: pc 00000000003a48bf  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+30)
  native: pc 00000000003a48bb  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+26)
  native: pc 00000000003a48b9  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+24)
  native: pc 00000000003a48b5  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+20)
  native: pc 00000000003a48b3  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+18)
  native: pc 00000000003a48b1  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+16)
  native: pc 00000000003a48af  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+14)
  native: pc 00000000003a48ad  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+12)
  native: pc 00000000003a48ab  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+10)
  native: pc 00000000003a48a9  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+8)
  native: pc 00000000003a48a7  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+6)
  native: pc 00000000003a48a5  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+4)
  native: pc 00000000003a48a3  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev+2)
  native: pc 00000000003a48a1  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer24GetLocalTimeSinceJan1970Ev)
  native: pc 00000000003a489f  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer19GetTimeSinceJan1970Ev+54)
  native: pc 00000000003a489d  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer19GetTimeSinceJan1970Ev+52)
  native: pc 00000000003a489b  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer19GetTimeSinceJan1970Ev+50)
  native: pc 00000000003a4899  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer19GetTimeSinceJan1970Ev+48)
  native: pc 00000000003a4895  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer19GetTimeSinceJan1970Ev+44)
  native: pc 00000000003a4893  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer19GetTimeSinceJan1970Ev+42)
  native: pc 00000000003a4891  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer19GetTimeSinceJan1970Ev+40)
  native: pc 00000000003a488f  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer19GetTimeSinceJan1970Ev+38)
  native: pc 00000000003a488d  /data/app/org.ppsspp.ppsspp-1/lib/arm/libppsspp_jni.so (_ZN6Common5Timer19GetTimeSinceJan1970Ev+36)
  at org.ppsspp.ppsspp.NativeRenderer.displayRender (Native method)
  at org.ppsspp.ppsspp.NativeRenderer.onDrawFrame (NativeRenderer.java:57)
  at android.opengl.GLSurfaceView$GLThread.guardedRun (GLSurfaceView.java:1535)
  at android.opengl.GLSurfaceView$GLThread.run (GLSurfaceView.java:1240)
```

That's the only thread running (the GL thread). The main thread is paused but has Activity.pause() (java) in the callstack.

**Comment by hrydgard** [comment]
```

**Comment by hrydgard** [comment]
This one is surprisingly common. I think people are somehow enabling the software renderer by accident...

```
  native: pc 0000000000347952  /data/app-lib/org.ppsspp.ppsspp-1/libppsspp_jni.so (VertexDecoder::Step_PosS16Through() const+25)
  native: pc 0000000000348673  /data/app-lib/org.ppsspp.ppsspp-1/libppsspp_jni.so (VertexDecoder::DecodeVerts(unsigned char*, void const*, int, int) const+90)
  native: pc 000000000036bd51  /data/app-lib/org.ppsspp.ppsspp-1/libppsspp_jni.so (TransformUnit::SubmitPrimitive(void*, void*, unsigned int, int, unsigned int, int*)+160)
  native: pc 000000000036a367  /data/app-lib/org.ppsspp.ppsspp-1/libppsspp_jni.so (SoftGPU::ExecuteOp(unsigned int, unsigned int)+2234)
  native: pc 0000000000369a8f  /data/app-lib/org.ppsspp.ppsspp-1/libppsspp_jni.so (SoftGPU::FastRunLoop(DisplayList&)+74)
  native: pc 000000000035e741  /data/app-lib/org.ppsspp.ppsspp-1/libppsspp_jni.so (GPUCommon::InterpretList(DisplayList&)+620)
```

**Comment by Sarkie** [comment]
Could you share a screenshot of the anpr stuff in the new console?

I'm really interested in this as I naively thought it'd already be there

**Comment by hrydgard** [comment]
@Sarkie crash reporting has been there forever, but ANR reporting is new (or maybe just greatly improved). Here:

anr

**Comment by hrydgard** [comment]
I'm finding a lot more variations on the deadlock above, should be fixed with that change though.

Guess it's time for 1.4.1....

**Comment by Sarkie** [comment]
@hrydgard yeah I just assumed ANPRs were there as I as get them the most, especially on old devices and wondered why developers never fixed them, as I assume they run their apps with the best hardware, the ANPRs don't appear.

So this is great news.

**Comment by hrydgard** [comment]
The travis fails seems to be a bad mac buildbot....

**Comment by hrydgard** [comment]
@Sarkie  I'll fix. 

Here's more details about the new stuff in the Play Console, about 10 minutes in:

 https://events.google.com/io/schedule/?section=may-17&sid=a3bec051-b37b-4bca-a3bf-1a45a7e9bba2

**Comment by Sarkie** [comment]
@hrydgard Thanks for the link, can't believe they only just added this!

**Comment by unknownbrackets** [comment]
Hm, that BATTERY_LOW one is odd.

The ManagedTexture ones aren't shutdown, though, are they?  I mean, GameInfo should only destruct on shutdown, so we can see in the stack trace if that will help (not saying it's a bad change either way.)

I wonder if the software rendering is some game that has or had corruption.  Possible that it may even be improved now versus v1.4.0, but who knows.

-[Unknown]

**Pull request merged**
