### PR TITLE
Update readme for 1.4.1, which will be released soon

### PR DESCRIPTION
**Pull request by hrydgard**
I always forget stuff so let me know. Did quickly scroll through all the commits though :)

### CODE REVIEW

**Comment by kobol123** [comment]
Even if you use MainScreen over here not means other classes are complete loaded. How you guarantee that?


void MainScreen::sendMessage(const char *message, const char *value) {
	// Always call the base class method first to handle the most common messages.
	UIScreenWithBackground::sendMessage(message, value);

	if (!strcmp(message, "boot")) {
		screenManager()->switchScreen(new EmuScreen(value));
	}
	if (!strcmp(message, "control mapping")) {
		UpdateUIState(UISTATE_MENU);
		screenManager()->push(new ControlMappingScreen());
	}
	if (!strcmp(message, "display layout editor")) {
		UpdateUIState(UISTATE_MENU);
		screenManager()->push(new DisplayLayoutScreen());
	}
	if (!strcmp(message, "settings")) {
		UpdateUIState(UISTATE_MENU);
		screenManager()->push(new GameSettingsScreen(""));
	}
	if (!strcmp(message, "permission_granted") && !strcmp(value, "storage")) {
		RecreateViews();
	}
}

**Comment by kobol123** [comment]
Don't close threads like that. If I'm wrong just say it in the face like a man.

**Comment by kobol123** [comment]
Why just not accepted when something is wrong. Like i do and everyone.... "Sorry i forget that you are right" duhhh. Just be a man. You don't know all just like me. Is difficult?

**Comment by kobol123** [comment]
Comon free yourself be free from yourself and not a slave of your mind....

**Comment by kobol123** [comment]
And don't make others slave please i prefer be free..So i finish now.

**Comment by unknownbrackets** [comment]
Was removing alpha test in 1.4?

Might be worth calling out Windows touch device fixes, and #9566 which fixed a crash in Persona 3 / D3D11 (probably more relevant than the vertexdecoder optimizations - since Persona 3 is probably seeing some limelight and people may have tried it and got the crash very early on.)

We may want to disable #9666 (at least on NVIDIA) before a point release, since it's failing for at least one configuration, so probably more... also considering #9702 (which I somehow have not seen...)

-[Unknown]

**Comment by hrydgard** [comment]
I'm going to disable #9666 (the partial restart) in release mode. Useful to keep it in debug builds.

Already mentioning the Windows touch improvements.

I'll add a line for #9566. Thanks!

**Comment by unknownbrackets** [comment]
Hmm, it's still very useful in release builds.  Maybe if the debugger is attached, instead?

-[Unknown]

**Comment by hrydgard** [comment]
Oh yeah, that's better. I'll just use IsDebuggerAttached.

**Comment by hrydgard** [comment]
#9709 takes care of that.

**Pull request merged**
