### PR TITLE
update build.gradle

### PR DESCRIPTION
**Pull request by TacoTheDank**
4.4 -> 4.8.1

com.gladed.androidgitversion 0.4.3 -> 0.4.4

sdk from 27.0.3 to 28.0.0
compileSdkVersion from 26 to 28
targetSdkVersion from 26 to 28

sorry if im an idiot and did this wrong somehow or wasnt the right time

### CODE REVIEW

**Comment by hrydgard** [comment]
It might be time indeed. Are you on Canary/Beta Studio? I'll double check later which versions the stable Android Studio recommends today before merging.

**Comment by hrydgard** [comment]
Yeah, this seems right.

**Comment by hrydgard** [comment]
@Orphis  This probably means you'll have to go install the latest SDK on the buildbot :)

**Comment by TacoTheDank** [comment]
:3

**Comment by TacoTheDank** [comment]
one of the travis builds errored, the debian one i think

**Pull request merged**
