### PR TITLE
iOS: Expose iOS 12.1+/13/14 buttons

### LINKED ISSUE #13824: iOS Build Issue Since Commit b403853
https://github.com/hrydgard/ppsspp/commit/b40385396a3c1b988228657df82a2218f4fd5fc3

The following build commands failed:
        CompileC build-ios/PPSSPP.build/Release-iphoneos/native.build/Objects-normal/armv7/ViewController.o ios/ViewController.mm normal armv7 objective-c++ com.apple.compilers.llvr
(1 failure)

### PR DESCRIPTION
**Pull request by unknownbrackets**
Now with corrected version checks.  I think this'll fix the compilation error, but I still don't have anything to test with.

Fixes #13824.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
If this doesn't build on the build bot, we may want to figure out how to make GitHub Actions fail to build in the same way.

-[Unknown]

**Comment by hrydgard** [comment]
@W-MS  any way you can confirm that this will build on your bot before merging?

**Comment by W-MS** [comment]
Yes, each version could be found here:
https://p.xx.wtf/Archive/ipa

**Comment by W-MS** [comment]
///cd ppsspp
mkdir build-ios
cd build-ios
cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchains/ios.cmake -GXcode ..
xcodebuild clean build -project PPSSPP.xcodeproj CODE_SIGNING_ALLOWED=NO -sdk iphoneos -configuration Release
///
Main part of my buildbot.

**Comment by W-MS** [comment]
Oh wait. I’ll test this tonight.

**Comment by W-MS** [comment]
Commit 43948d4 built successfully. It could be merged now.

**Comment by Halo-Michael** [comment]
https://github.com/hrydgard/ppsspp/commit/92173d5ac4403ab4d67754dc2322ee14a2c0dc11#r45628995

**Review by lodee77 — COMMENTED** [review]
Ok

**Pull request merged**
