### PR TITLE
Manually read packets in sceAtrac, skipping ffmpeg

### PR DESCRIPTION
**Pull request by unknownbrackets**
This avoids relying on ffmpeg seeking at all.  It means rewinding doesn't have to manually seek from start, and moves us closer to reading directly from the PSP RAM buffers like happens on real firmware.

This won't currently merge; it will require removing the GTA hacks.

It should work properly with ATRAC3, ATRAC3+, AA3 (OMA), and low-level audio.  But it may break things, so would appreciate testing.

If GTA doesn't work with this, it virtually proves that packets are being incorrectly placed in the "virtual file buffer".  That means improvements to that logic or more accurate buffer handling will fix it.  If GTA does work with this, it probably means we were using ffmpeg wrong or hit a bug with its seeking/buffers.

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
Did not work in GTA.
```
06:06:398 mix sound th W[ME]: HLE\sceAtrac.cpp:1487 This is an atrac3+ mono audio
06:06:399 mix sound th I[ME]: HLE\sceAtrac.cpp:1043 0=sceAtracGetBufferInfoForResetting(0, 24938854, 0bfd6e38)
06:06:432 mix sound th I[ME]: HLE\sceAtrac.cpp:1331 sceAtracResetPlayPosition(0, 24938854, 262144, 0)
06:06:532 mix sound th I[ME]: HW\MediaEngine.cpp:87 FF: Frame data doesn't match channel configuration!
06:06:532 mix sound th E[ME]: HLE\sceAtrac.cpp:396 avcodec_decode_audio4: Error decoding audio -1094995529 / bebbb1b7
06:06:532 mix sound th E[ME]: HLE\sceAtrac.cpp:1123 UNIMPL sceAtracGetInternalErrorInfo(0, 0bfd6e74)
06:06:532 mix sound th I[ME]: HLE\sceAtrac.cpp:1318 sceAtracReleaseAtracID(0)
```

**Comment by unknownbrackets** [comment]
I'm pretty sure the GTA issue is actually related to sceAtracGetBufferInfoForResetting and sceAtracResetPlayPosition.

How about Last Ranker or games that use sceSas to play ATRAC3 voices?

-[Unknown]

**Comment by daniel229** [comment]
Last Ranker is still randomly happen,I don't remember which games that use sceSas to play ATRAC3 voices 
```
04:35:782 ATRAC3 play  W[ME]: HLE\sceAtrac.cpp:1487 This is an atrac3+ mono audio
04:35:858 ATRAC3 play  I[ME]: HLE\sceAtrac.cpp:1318 sceAtracReleaseAtracID(1)
04:35:887 ATRAC3 play  I[ME]: HLE\sceAtrac.cpp:1318 sceAtracReleaseAtracID(2)
04:35:984 ATRAC3 play  I[ME]: HW\MediaEngine.cpp:87 FF: Frame data doesn't match channel configuration!
04:35:984 ATRAC3 play  E[ME]: HLE\sceAtrac.cpp:396 avcodec_decode_audio4: Error decoding audio -1094995529 / bebbb1b7
04:35:984 ATRAC3 play  E[ME]: HLE\sceAtrac.cpp:1123 UNIMPL sceAtracGetInternalErrorInfo(0, 0bfdf66c)
04:35:987 ATRAC3 play  E[IO]: HLE\sceIo.cpp:1155 sceIoLseek(4, 10d308, 0) - ERROR: invalid file
04:35:987 ATRAC3 play  W[IO]: HLE\sceIo.cpp:872 sceIoRead(4, 099b7c80, 0): error 80020323
04:35:987 ATRAC3 play  I[ME]: HLE\sceAtrac.cpp:1318 sceAtracReleaseAtracID(0)
```

**Comment by unknownbrackets** [comment]
The following games use the feature somewhere or other:

```
NPEG00050_1.00 - Jungle Party
NPEZ00327_1.05 - MadBlockerAlpha
NPEZ00327_3.00 - MadBlockerAlpha
NPEZ00448_1.03 - L.A. GRIDLOCK
NPEZ00475_1.01 - Angus hates Aliens
NPJH00094_1.00 - 探偵オペラ ミルキィホームズ 1.5 体験版 ～第１話「結成、ミルキィホームズ！」
NPJH50279_1.01 - セカンドノベル～彼女の夏、15分の記憶～
NPJH50352_1.01 - GOD EATER BURST 通常版
NPJH50372_1.03 - 弹丸论破：希望的学园与绝望的高中生汉化版
NPJH50468_1.01 - FRONTIER GATE
NPJH50468_2.03 - FRONTIER GATE
NPJH50515_1.00 - Danganronpa: Hope's Academy and Despair's Students
NPJH50535_1.00 - 幻想水滸伝　紡がれし百年の時
NPJH50619_1.01 - SOL TRIGGER
NPJH50721_1.01 - FRONTIER GATE Boost+
NPJH50832_1.00 - GOD EATER 2
NPJH50832_1.01 - GOD EATER 2
NPJH90164_1.01 - DANGANRONPA
NPJH90167_1.00 - GOD EATER BURST 体験版
NPJH90182_1.00 - ????? ???????????
NPJH90216_1.01 - FRONTIER GATE
NPJH90291_1.00 - SOL TRIGGER ???
NPJH90323_1.00 - FRONTIER GATE Boost+ ???
NPJH90338_1.01 - GOD EATER 2 体験版
NPUH10186_1.04 - Street Kix Freestyle
NPUZ00210_1.02 - MadBlockerAlpha
UCES01459_1.01 - Jungle Party
ULES01447_1.00 - Despicable Me
ULES01519_1.00 - GODS EATER™ BURST
ULJM06006_1.03 - ?????????????
ULJM06007_1.02 - ????????????????????????
ULJM06036_1.02 - PrincessEvangile PORTABLE
ULJM06192_1.04 - 黄昏のシンセミア portable
ULJM06200_1.01 - Solomon's Ring ～火の章～
ULJM06232_1.03 - グリザイアの果実 -LE FRUIT DE LA GRISAIA- DISC1
ULJM06233_1.03 - ???????? -LE FRUIT DE LA GRISAIA- DISC2
ULJS00343_1.01 - 探偵オペラ ミルキィホームズ
ULJS00350_1.01 - GOD EATER BURST アペンド版
ULJS00435_1.00 - 三極姫～三国乱世・覇天の采配～
ULJS00485_1.01 - 探偵オペラ　ミルキィホームズ　１．５
ULJS00516_1.01 - パチパラＳＬＯＴ＋
ULJS00520_1.01 - 探偵オペラ　ミルキィホームズ　２
ULJS00575_1.01 - 三極姫２～天下覇統・獅志の継承者～
ULUS10534_1.00 - Despicable Me
ULUS10563_1.00 - GODS EATER BURST
```

I think I confused Sol Trigger for Last Ranker.

-[Unknown]

**Comment by unknownbrackets** [comment]
探偵オペラ ミルキィホームズ体験版 seems to work, at least, so sceSas/Atrac support is probably working as well as before.

-[Unknown]

**Comment by daniel229** [comment]
Tested some of those games,don't know when they use the feature,seems good so far.

Flatout head on throws garbage log nonstop and the game freeze.

**Comment by unknownbrackets** [comment]
Oh, right, I need to fix it to advance with a blank packet when that happens now.

-[Unknown]

**Comment by unknownbrackets** [comment]
This currently includes a hack for GTA.  It probably won't loop correctly, but I doubt it was looping correctly before.  I've also removed the related code added in #4483, which now makes sense based on all the related code.

Right now, the code attempts to reconstruct the file in memory based on add commands.  This isn't how the PSP works; the PSP does buffer packets while decoding, but it only reads them into the decoder (even on loop) from the PSP RAM you point it to.  It doesn't have its own larger buffer, but if your buffer is big enough for the file, then it will "reconstruct" the file into that buffer.

I've also tested Trails in the Sky and Ys Seven, which I think are working.

A correct fix for the buffer management mostly necessitates implementing the "second buffer", which seems sorta complicated.  But reading directly from PSP RAM will probably fix other games, like #3650.

Anyway, this now cleans up a bit more - a savestate issue, and also some leaks that we've apparently had for a while in some FFmpeg pointer management (you were supposed to use avcodec_close then av_free/av_freep, but then they added avcodec_free_context to do that for you.)

-[Unknown]

**Comment by sum2012** [comment]
Code Lyoko still stuck at "No problem screen" 
log:
https://gist.github.com/sum2012/604030eb126942aafabe

**Comment by unknownbrackets** [comment]
Right, this doesn't change how that stuff works yet, intentionally.

-[Unknown]

**Comment by unknownbrackets** [comment]
Rebased against latest changes to Compatibility.  I previously added something to handle bad packets better.

What I'm most interested in is: does this break any games that were previously working (even before the changes that broke GTA?)  Currently, it should be a step in the right direction, and it should also improve games like e.g. Trails in the Sky from current master.

I want to change buffer management separately, because I want to make sure the regression ranges are manageable.

-[Unknown]

**Comment by sum2012** [comment]
I agree to merge this to let more people test

**Comment by hrydgard** [comment]
Great! Let's try it and see what the fallout is.

**Comment by daniel229** [comment]
The music issue return in Tales of Radiant Mythology 2 https://github.com/hrydgard/ppsspp/issues/5353 broke by https://github.com/unknownbrackets/ppsspp/commit/60378dd59d3c72df9bb89db57540840b7da907a3.

**Pull request merged**
