### PR TITLE
Correct full alpha for render-to-texture

### PR DESCRIPTION
**Pull request by unknownbrackets**
We shouldn't care how it was drawn, what matters is how we're using it.

-[Unknown]

### CODE REVIEW

**Comment by ThePhoenixRises** [comment]
Would this also fix the Alpha problems on Outrun game as well, as the cars were being drawn correctly, but the final sheen / reflections were drawn incorrectly.

**Comment by unknownbrackets** [comment]
Dunno, don't have the game.  Figured this out because Split / Second had a demo.

-[Unknown]

**Comment by hrydgard** [comment]
Definitely correct but still a bit scared to merge for 1.0.1 .. what do you think?

**Comment by unknownbrackets** [comment]
Well, probably safer to wait.  It's been like this since forever, so it's definitely not a recent regression.

-[Unknown]

**Comment by thedax** [comment]
This does affect Outrun, but in a slightly negative way; it completely removes the sheen/shine that the cars have, making them look flat and dull. However, the blue glitch colours are gone as a result.

**Comment by unknownbrackets** [comment]
Well, that probably means we still have stencil/alpha issues with those render-to-textures, because the sheen must've only been showing up because we *thought* alpha was 100% when it wasn't.

-[Unknown]

**Comment by daniel229** [comment]
The reflection is also missing in split/second.

**Pull request merged**
