### PR TITLE
Implement various sceNet* socket functions

### PR DESCRIPTION
**Pull request by kevinbchen**
This is primarily focused at getting the multiplayer part of CSPSP, a homebrew game, working. Basically just wrapping the corresponding system socket calls.

Tested with CSPSP by checking that I could login to the master server and connect to a game server (locally hosted). Tested on windows and android. Did run into some sporadic hanging/crashing in the multiplayer mode on android, but might be unrelated to these network changes (e.g. worked around a crash by switching from vulkan to opengl).

Relevant links:
CSPSP: https://github.com/kevinbchen/cspsp/releases/tag/v1.92b
Server application: https://github.com/kevinbchen/cspspserver/releases/tag/v1.51b

### CODE REVIEW

**Comment by ANR2ME** [comment]
This will be conflicting with the infrastucture branch i'm currently working and has been tested on many games (including CSPSP) https://github.com/hrydgard/ppsspp/issues/14256#issuecomment-1136256118

And using socket id directly from `socket` on the host/OS like that will have memory corruption issue when the game are using `FD_SET` macro, similar to the current issue i had.
Also, a lot of the struct that contained a flags will need to be converted from Host2PSP and PSP2Host (some of them will need to be ignored when not supported)

For example:
```c++
static int sceNetInetSocket(int domain, int type, int protocol) {
	WARN_LOG(SCENET, "UNTESTED sceNetInetSocket(%i, %i, %i) at %08x", domain, type, protocol, currentMIPS->pc);
	DEBUG_LOG(SCENET, "Socket: Domain = %s, Type = %s, Protocol = %s", inetSocketDomain2str(domain).c_str(), inetSocketType2str(type).c_str(), inetSocketProto2str(protocol).c_str());
	int retval = socket(convertSocketDomainPSP2Host(domain), convertSocketTypePSP2Host(type), convertSocketProtoPSP2Host(protocol));
	if (retval < 0) {
		inetLastErrno = errno;
		return hleLogError(SCENET, retval, "errno = %d", inetLastErrno);
	}

	//InetSocket* sock = new InetSocket(domain, type, protocol);
	//retval = pspSockets.Create(sock);

	// Ignore SIGPIPE when supported (ie. BSD/MacOS)
	setSockNoSIGPIPE(retval, 1);
	// TODO: We should always use non-blocking mode and simulate blocking mode
	changeBlockingMode(retval, 1);
	// Enable Port Re-use, required for multiple-instance
	setSockReuseAddrPort(retval);
	// Disable Connection Reset error on UDP to avoid strange behavior
	setUDPConnReset(retval, false);

	inetLastSocket = retval;
	return hleLogSuccessI(SCENET, retval);
}

static int sceNetInetSetsockopt(int socket, int level, int optname, u32 optvalPtr, int optlen) {
	WARN_LOG(SCENET, "UNTESTED %s(%i, %i, %i, %08x, %i) at %08x", __FUNCTION__, socket, level, optname, optvalPtr, optlen, currentMIPS->pc);
	u32_le* optval = (u32_le*)Memory::GetPointer(optvalPtr);
	DEBUG_LOG(SCENET, "SockOpt: Level = %s, OptName = %s, OptValue = %d", inetSockoptLevel2str(level).c_str(), inetSockoptName2str(optname, level).c_str(), *optval);
	timeval tval{};
	// InetSocket* sock = pspSockets.Get<InetSocket>(socket, error);
	// TODO: Ignoring SO_NBIO/SO_NONBLOCK flag if we always use non-bloking mode (ie. simulated blocking mode)
	if (level == PSP_NET_INET_SOL_SOCKET && optname == PSP_NET_INET_SO_NBIO) {
		//memcpy(&sock->nonblocking, (int*)optval, std::min(sizeof(sock->nonblocking), optlen));
		return hleLogSuccessI(SCENET, 0);
	}
	// FIXME: Should we ignore SO_BROADCAST flag since we are using fake broadcast (ie. only broadcast to friends), 
	//        But Infrastructure/Online play might need to use broadcast for SSDP and to support LAN MP with real PSP
	/*else if (level == PSP_NET_INET_SOL_SOCKET && optname == PSP_NET_INET_SO_BROADCAST) {
		//memcpy(&sock->so_broadcast, (int*)optval, std::min(sizeof(sock->so_broadcast), optlen));
		return hleLogSuccessI(SCENET, 0);
	}*/
	// TODO: Ignoring SO_REUSEADDR flag to prevent disrupting multiple-instance feature
	else if (level == PSP_NET_INET_SOL_SOCKET && optname == PSP_NET_INET_SO_REUSEADDR) {
		//memcpy(&sock->reuseaddr, (int*)optval, std::min(sizeof(sock->reuseaddr), optlen));
		return hleLogSuccessI(SCENET, 0);
	}
	// TODO: Ignoring SO_REUSEPORT flag to prevent disrupting multiple-instance feature (not sure if PSP has SO_REUSEPORT or not tho, defined as 15 on Android)
	else if (level == PSP_NET_INET_SOL_SOCKET && optname == PSP_NET_INET_SO_REUSEPORT) { // 15
		//memcpy(&sock->reuseport, (int*)optval, std::min(sizeof(sock->reuseport), optlen));
		return hleLogSuccessI(SCENET, 0);
	}
	// TODO: Ignoring SO_NOSIGPIPE flag to prevent crashing PPSSPP (not sure if PSP has NOSIGPIPE or not tho, defined as 0x1022 on Darwin)
	else if (level == PSP_NET_INET_SOL_SOCKET && optname == 0x1022) { // PSP_NET_INET_SO_NOSIGPIPE ?
		//memcpy(&sock->nosigpipe, (int*)optval, std::min(sizeof(sock->nosigpipe), optlen));
		return hleLogSuccessI(SCENET, 0);
	}
	// It seems UNO game will try to set socket buffer size with a very large size and ended getting error (-1), so we should also limit the buffer size to replicate PSP behavior
	else if (level == PSP_NET_INET_SOL_SOCKET && (optname == PSP_NET_INET_SO_RCVBUF || optname == PSP_NET_INET_SO_SNDBUF)) { // PSP_NET_INET_SO_NOSIGPIPE ?
		// TODO: For SOCK_STREAM max buffer size is 8 Mb on BSD, while max SOCK_DGRAM is 65535 minus the IP & UDP Header size
		if (*optval > 8 * 1024 * 1024) {
			inetLastErrno = ENOBUFS; // FIXME: return ENOBUFS for SOCK_STREAM, and EINVAL for SOCK_DGRAM
			return hleLogError(SCENET, -1, "buffer size too large?");
		}
	}
	int retval = 0;
	// PSP timeout are a single 32bit value (micro seconds)
	if (level == PSP_NET_INET_SOL_SOCKET &&  optval && (optname == PSP_NET_INET_SO_RCVTIMEO|| optname == PSP_NET_INET_SO_SNDTIMEO)) { 
		tval.tv_sec = *optval / 1000000; // seconds
		tval.tv_usec = (*optval % 1000000); // microseconds
		retval = setsockopt(socket, convertSockoptLevelPSP2Host(level), convertSockoptNamePSP2Host(optname, level), (char*)&tval, sizeof(tval));
	}
	else {
		retval = setsockopt(socket, convertSockoptLevelPSP2Host(level), convertSockoptNamePSP2Host(optname, level), (char*)optval, optlen);
	}
	if (retval < 0) {
		inetLastErrno = errno;
		hleLogError(SCENET, retval, "errno = %d", inetLastErrno);
	}
	return hleLogSuccessI(SCENET, retval);
}

static int sceNetInetGetsockopt(int socket, int level, int optname, u32 optvalPtr, u32 optlenPtr) {
	WARN_LOG(SCENET, "UNTESTED %s(%i, %i, %i, %08x, %08x) at %08x", __FUNCTION__, socket, level, optname, optvalPtr, optlenPtr, currentMIPS->pc);
	u32_le* optval = (u32_le*)Memory::GetPointer(optvalPtr);
    socklen_t* optlen = (socklen_t*)Memory::GetPointer(optlenPtr);
	DEBUG_LOG(SCENET, "SockOpt: Level = %s, OptName = %s", inetSockoptLevel2str(level).c_str(), inetSockoptName2str(optname, level).c_str());
	timeval tval{};
	// InetSocket* sock = pspSockets.Get<InetSocket>(socket, error);
	// TODO: Ignoring SO_NBIO/SO_NONBLOCK flag if we always use non-bloking mode (ie. simulated blocking mode)
	if (level == PSP_NET_INET_SOL_SOCKET && optname == PSP_NET_INET_SO_NBIO) {
		//*optlen = std::min(sizeof(sock->nonblocking), *optlen);
		//memcpy((int*)optval, &sock->nonblocking, *optlen); 
		//if (sock->nonblocking && *optlen>0) *optval = 0x80; // on true, returning 0x80 when retrieved using getsockopt?
		return hleLogSuccessI(SCENET, 0);
	}
	// FIXME: Should we ignore SO_BROADCAST flag since we are using fake broadcast (ie. only broadcast to friends), 
	//        But Infrastructure/Online play might need to use broadcast for SSDP and to support LAN MP with real PSP
	/*else if (level == PSP_NET_INET_SOL_SOCKET && optname == PSP_NET_INET_SO_BROADCAST) {
		//*optlen = std::min(sizeof(sock->so_broadcast), *optlen);
		//memcpy((int*)optval, &sock->so_broadcast, *optlen); 
		//if (sock->so_broadcast && *optlen>0) *optval = 0x80; // on true, returning 0x80 when retrieved using getsockopt?
		return hleLogSuccessI(SCENET, 0);
	}*/
	// TODO: Ignoring SO_REUSEADDR flag to prevent disrupting multiple-instance feature
	else if (level == PSP_NET_INET_SOL_SOCKET && optname == PSP_NET_INET_SO_REUSEADDR) {
		//*optlen = std::min(sizeof(sock->reuseaddr), *optlen);
		//memcpy((int*)optval, &sock->reuseaddr, *optlen);
		return hleLogSuccessI(SCENET, 0);
	}
	// TODO: Ignoring SO_REUSEPORT flag to prevent disrupting multiple-instance feature (not sure if PSP has SO_REUSEPORT or not tho, defined as 15 on Android)
	else if (level == PSP_NET_INET_SOL_SOCKET && optname == PSP_NET_INET_SO_REUSEPORT) { // 15
		//*optlen = std::min(sizeof(sock->reuseport), *optlen);
		//memcpy((int*)optval, &sock->reuseport, *optlen);
		return hleLogSuccessI(SCENET, 0);
	}
	// TODO: Ignoring SO_NOSIGPIPE flag to prevent crashing PPSSPP (not sure if PSP has NOSIGPIPE or not tho, defined as 0x1022 on Darwin)
	else if (level == PSP_NET_INET_SOL_SOCKET && optname == 0x1022) { // PSP_NET_INET_SO_NOSIGPIPE ?
		//*optlen = std::min(sizeof(sock->nosigpipe), *optlen);
		//memcpy((int*)optval, &sock->nosigpipe, *optlen);
		return hleLogSuccessI(SCENET, 0);
	}
	int retval = 0;
	// PSP timeout are a single 32bit value (micro seconds)
	if (level == PSP_NET_INET_SOL_SOCKET && optval && (optname == PSP_NET_INET_SO_RCVTIMEO || optname == PSP_NET_INET_SO_SNDTIMEO)) {
		socklen_t tvlen = sizeof(tval);
		retval = getsockopt(socket, convertSockoptLevelPSP2Host(level), convertSockoptNamePSP2Host(optname, level), (char*)&tval, &tvlen);
		if (retval != SOCKET_ERROR) {
			u64_le val = (tval.tv_sec * 1000000LL) + tval.tv_usec;
			memcpy(optval, &val, std::min(static_cast<socklen_t>(sizeof(val)), std::min(static_cast<socklen_t>(sizeof(*optval)), *optlen)));
		}
	}
	else {
		retval = getsockopt(socket, convertSockoptLevelPSP2Host(level), convertSockoptNamePSP2Host(optname, level), (char*)optval, optlen);
	}
	if (retval < 0) {
		inetLastErrno = errno;
		hleLogError(SCENET, retval, "errno = %d", inetLastErrno);
	}
	DEBUG_LOG(SCENET, "SockOpt: OptValue = %d", *optval);
	return hleLogSuccessI(SCENET, retval);
}
```

I have most of the function already implemented and tested, except for `sceNetInetRecvMsg` (because i didn't know which game use that function to be tested with, but recently fiound a game that use that function thanks to @MojoJojoDojo ), but currently stashed, so it will take a longer time to separate such large stash into several commits as they're mixed up with some adhoc and dialog changes too, for example https://github.com/hrydgard/ppsspp/pull/15421 will need to be merged first.

Currently i still have a 2 or 3 of things that need to be done on AdHoc first before moving on to Infrastructure, which are AdhocMatching, AdhocDiscover (still have 1 more function to be implemented, based on decompiled official prx), and fixing the socket buffer issue on Linux on "Hokuto no Ken" by creating a socket wrapper class (the base class will also be used on infrastructure)

**Comment by kevinbchen** [comment]
Oh good to know, thanks for the detailed reply! Definitely sounds like you've thought about this much more thoroughly than I have. I've only been testing with CSPSP, so only implemented the small subset of socket functionality needed to get that game working.

In this case, it probably makes sense to just wait for your work then. Let me know if there's anything I can help with though!

**Comment by Anuskuss** [comment]
I can't believe that @kevinbchen is still alive and just opened a PR to make CSPSP multiplayer playable. You've been a small but memorable part of my childhood and I want to thank you for making this fun little homebrew! I remember feeling like a total Hackerman after figuring out how to jailbreak my PSP and loading custom games onto it :)

In case you don't know, CSPSP has been [revived](https://wololo.net/talk/viewtopic.php?p=424694) a few years back and there have been some servers hosted throughout the years (most recently by Zero1UP's PS2 Rewired effort). Unfortunately those servers were never filled with enough players but I can attest that it works. I don't really follow that scene much but there is a [Discord server](https://discord.com/invite/eUXuYWv) in case you wanna take a look. I joined back when @ANR2ME made https://github.com/hrydgard/ppsspp/issues/14256#issuecomment-798839184 but we could never get enough players to play an actual game.

Anyway, I can confirm that the code in this PR works. But as has been said it's probably best to wait for @ANR2ME's PR because that covers this and more.

**Comment by kevinbchen** [comment]
@Anuskuss - haha thanks, the psp homebrew scene back then was definitely fun to be a part of.  Will close this PR request out and wait for ANR2ME's work.

**Pull request closed without merging**
