### PR TITLE
softgpu: Optimize (bi-)linear texture filtering

### PR DESCRIPTION
**Pull request by fp64**
Seeing as SampleLinearLevel is near the top in the profiler, optimize actual bilinear filtering using SSE2. Solid win in the synthetic benchmark (https://godbolt.org/z/fqh3xvbGx, also doubles as correctness check), no visible difference in actual PPSSPP. Note: profiler suggests that hot part of SampleLinearLevel is elsewhere.

### CODE REVIEW

**Comment by hrydgard** [comment]
I keep making various optimizations myself that locally look like great wins but seems to have barely a measurable effect overall... but it's hard to measure. Machines clock up and down according to load, etc.

This one has to be a win on some dimension, maybe power consumption :P I'm all for merging it, though I'll let @unknownbrackets click merge.

**Review by hrydgard — APPROVED** [review]

**Comment by fp64** [comment]
Well, in my case "observable difference" would constitute going from 7 FPS on average to 8 - 12.5% improvement, pretty significant for a single function change. It oscillating between 6 and 9 FPS does not help measuring.

Offtopic, but while eyeing softgpu for more optimization opportunities, I have several questions, which I'm not sure where to ask. The discord would seem a logical choice... if the damn thing would actually work for me. Maybe I'll just create "softgpu optimization opportunities" issue, or something.

**Comment by unknownbrackets** [comment]
This would only apply for 32-bit Intel, you're not going to end up in this function on x86_64.  So it probably won't actually make any difference for most users.  I'd tried to avoid over optimizing this code for SSE given that we're already using a jit for it that is much faster (especially with AVX2.)

-[Unknown]

**Comment by hrydgard** [comment]
Oh right, forgot about that, hah.

**Comment by fp64** [comment]
Oh, looks like I'm blind. I somehow thought that `DrawPixelX86.cpp` was the only special JIT path, but `SamplerX86.cpp` is a thing too.
While I care about 32-bit perf on x86 (and am mildly hopeful about improving it to more palatable levels there), I realize that most people don't.

**Review by unknownbrackets — APPROVED** [review]
Well, this seems reasonable, so I'll merge.

-[Unknown]

**Pull request merged**
