### PR TITLE
Basic mappable motion gesture

### PR DESCRIPTION
**Pull request by iota97**
Was testing if some gesture could make sense for control mapping and swipe/drag seem pretty nice for camera.

Still a draft, but as someone might have some idea/suggestion I'll just place it here if you don't mind.

### CODE REVIEW

**Comment by Saramagrean** [comment]
Hi. Can you make the analog buttons not combined with the swipe gesture screen? I try with Monster Hunter, when walking with analog buttons, the camera angle rotates while swiping the screen. sorry for my english not good. 😂

Example video.
https://youtu.be/VGlAbYIsiRQ

**Comment by iota97** [comment]
I can't reproduce it on neither my PC nor my phone, `usedPointerMask` should prevent other button press to drag the camera.

You may try to comment out any `usedPointerMask = 0;` when it input is `TOUCH_RELEASE_ALL` as that is the only part I can think could broke the check, but I don't see any reason for it to happen...

I'm kinda puzzled TBH on this.

**Comment by Saramagrean** [comment]
Oops, my bad. I missing add code in some line. It work well now. thanks!

**Comment by XiaomiRedmi9** [comment]
How about this now?

**Comment by hrydgard** [comment]
Not fully understanding what exactly this is or how it's used - can you extend the PR description a bit?

**Comment by iota97** [comment]
This add a screensized button that handle every input on the screen that is not already handled by other touch button and use it for 2 touch gesture: swipe (with smoothing using the same logic of the mouse input) and a double tap.

The 4 swipe direction and the double tap can be mapped to PSP button.

Not sure if is worth the complexity of bitmasking the touch pointers tho' :)

**Comment by iota97** [comment]
I think this is not worth the complexity in the end, closing.

**Comment by unknownbrackets** [comment]
I haven't tried this but I think it makes sense for some games.  For example, I can imagine swipe right is X and swipe left is O, which could be convenient for a game with longer dialog sections.  It'd be convenient in that case maybe to keep the controls hidden if a swipe is detected, though, which might be a bit complex.

The implementation looks relatively clean here.  I know I commented about "stealing" the views in the other PR but definitely not a general comment on your PRs which I think have been interesting and useful, and are appreciated.

Hadn't really commented on this one yet because I've found Android more and more annoying to deal with, and it wasn't really what interested me in contributing to PPSSPP in the first place.  I haven't really been using touch controls much for a while in PPSSPP, so I didn't want to give unfounded opinions.

-[Unknown]

**Comment by iota97** [comment]
I didn't really like the idea of ending up bitmasking input pointer (a bit afraid of bugs given we have some weird stuff already like when 3 finger get the input stuck with android system gesture enabled for some reason), but I guess there can be some utility in this (I'll reopen for now).

About "stealing" views I knew it probably wasn't a clean implementation, I just wanted to give it a try out of curiosity and insomnia :P

**Comment by hrydgard** [comment]
Not against this at all, sorry I kind of lost track of it.

I'll try to play around with it soon and most probably merge.

**Comment by hrydgard** [comment]
For a future version of this I think it would be cool if swipes could be mapped to all the virtual keys, and that you could simply input swipes when mapping controls in the control editor. That may require a bit of a rework of the mapping system though...

I'm OK with this as is.

**Pull request merged**
