### PR TITLE
Last update id_ID.ini

### PR DESCRIPTION
**Pull request by PutuDesca**

### CODE REVIEW

**Comment by hrydgard** [comment]
Do you really want to change all these words to start with uppercase in the middle of sentences? It's a pretty common convention in English but rarely seen in other languages.

**Comment by hrydgard** [comment]
I mean, if it is commonly done in Indonesian languages, then it's fine. But just wondering.

**Comment by PutuDesca** [comment]
I canceled doing this project because the spelling of the language is not right so I think for this translation it looks a little strange

**Comment by PutuDesca** [comment]
So the results are not quite right because the grammar of Indonesian writing is very much so a lot of vocabulary that I made may not be right

**Pull request closed without merging**
