### PR TITLE
Change jpn0 font

### PR DESCRIPTION
**Pull request by nassau-tk**
jpn0.pgf remaked to include Chinese font.

### CODE REVIEW

**Comment by nassau-tk** [comment]
#13652 wiil be solved.

**Comment by nassau-tk** [comment]
@hrydgard 

Oops!!Error? i OS?
How should I do?

**Comment by hrydgard** [comment]
It has started to error randomly, don't worry about it.

**Comment by hrydgard** [comment]
So this is the final version? :)

**Comment by nassau-tk** [comment]
Yes, Sure.
I believe and wish it by myself.  (^o^; )

I had discussion and check with @sum2012 few days.
Maybe, This one is best answer at this time.

And sorry I misstake the PL.
> @ nassau-tk Modified "ltn0/1/2/3/4/5/6/7 .pgf" … e47e83f

This one is other font.
I want delete this in this branch.
How to do that?

**Comment by hrydgard** [comment]
From your git command prompt, to delete the last commit, you can do:

`git reset --hard HEAD~1`

And then to push it:

`git push -f`

**Comment by nassau-tk** [comment]
??? Error ???

**Comment by hrydgard** [comment]
So the jpn0.pgf from the last commit (46dc6a3) is the one you want to use? I can take that and resolve the git conflict above for you.

**Comment by nassau-tk** [comment]
Yes, (46dc6a3) is latest jpn0.pgf.
Please!

**Comment by hrydgard** [comment]
I know git can be tricky :)  I'll take care of it.

**Comment by hrydgard** [comment]
Merged, I'll close this.

**Comment by nassau-tk** [comment]
Thank you for your care.  :smile:

**Pull request closed without merging**
