### PR TITLE
x86jit: Add a few Vec4 and Float ops

### PR DESCRIPTION
**Pull request by unknownbrackets**
On top of #17948 (required, so commits are here too), this also adds some vec4 and float ops.

At this point it's about 2x the speed of IR Interpreter and half the speed of the regular jit in LittleBigPlanet.  And most of it still isn't implemented.  Not too shabby.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Now that 17948 is in, could you rebase? Just to linearize the history a little bit although in practice it doesn't matter that much..

**Comment by hrydgard** [comment]
Actually I'll just have github autorebase. Nice, btw!

**Comment by unknownbrackets** [comment]
Hm, they are the same shas so it would've merged without duplicates.  But the rebase is fine.

-[Unknown]

**Comment by hrydgard** [comment]
Oh hm, that's true, since they're a prefix of this change it'll be clean. I'll keep that in mind for next time.

**Pull request merged**
