### PR TITLE
OpenXR - Enable user to switch between topdown and fps camera

### PR DESCRIPTION
**Pull request by lvonasek**
This is a feature which the 2016 version of PPSSPP VR has and users were asking for that:
https://www.youtube.com/watch?v=gDrqVlCrlTs

### CODE REVIEW

**Comment by hrydgard** [comment]
That's an interesting trick, didn't know it had that. Just curious, how's game compatibility with this?

**Comment by lvonasek** [comment]
It is basically just rotating the camera by 90 degrees. Users need to use the camera adjust feature to fit the camera view.

To sum up the game compatibility, it is any game where:
" has world unit scale defined or not extremely off
* game camera doesn't change the view too much
* culling is somehow acceptable
* geometry isn't 2D or missing

**Comment by hrydgard** [comment]
Hehe, alright. Users are already presumably aware that running PSP games in VR has some limitations..

**Comment by lvonasek** [comment]
Yeah, this feature is under VR settings group "Experts only".

**Pull request merged**
