### PR TITLE
Noticed that the UWP build has been broken for some time, fix it.

### PR DESCRIPTION
**Pull request by hrydgard**
Should probably set up a buildbot if we care about this...

### CODE REVIEW

**Comment by Orphis** [comment]
So... Do we care about this? :)

**Comment by hrydgard** [comment]
I don't know, do we? :) Personally not so much...

**Comment by Toff-kun** [comment]
I reported this a while ago [here](https://github.com/hrydgard/ppsspp/issues/9575), probably should've opened another issue. But thank you for the fix, I thought it will never be fixed. There are people who still care. :)

**Comment by Toff-kun** [comment]
Getting the following error now:
```
PPSSPP_UWPMain.cpp(324): error C2039: 'T3DCreateD3D11Context': is not a member of 'Draw'
...\ppsspp\Core/CoreParameter.h(37): note: see declaration of 'Draw'
1>PPSSPP_UWPMain.cpp(324): error C3861: 'T3DCreateD3D11Context': identifier not found
```

**Comment by hrydgard** [comment]
My fault, will fix it soon.

**Comment by Toff-kun** [comment]
The error above is fixed, but the build now halts due to expired certificates. I checked the ones generated during the earlier builds, and all of them did expire on February 25th this year. I suppose those can only be updated by you, right?
```
4>PPSSPP_UWPMain.cpp
4>UWP.vcxproj -> ...\ppsspp\UWP\ARM\Release\UWP\PPSSPP_UWP.exe
4>...\Visual Studio 2017\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(2014,5): warning APPX0108: The certificate specified has expired. For more information about renewing certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.
4>...\Visual Studio 2017\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets(3781,5): error APPX0108: The certificate specified has expired. For more information about renewing certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.
4>Done building project "UWP.vcxproj" -- FAILED.
```

**Comment by hrydgard** [comment]
@Toff-kun Had completely forgotten about those darn things, I'll try to look into it soon..

**Comment by Toff-kun** [comment]
@hrydgard I just noticed that my Feedback to Microsoft where I reported the missing FlushInstructionCache for UWP was deleted, and [the page you linked](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679350(v=vs.85).aspx) now lists FlushInstructionCache as being available in UWP apps as well. :) 
Hope you can give it another look, maybe there's a chance to get a working JIT on ARM at last.

**Comment by hrydgard** [comment]
Oh! That's good. Unfortunately won't help if devices don't get upgraded anymore, I fear my Lumia is out of luck (though not sure?).

**Comment by Toff-kun** [comment]
Most, if not all, phones running W10M are still [on mainstream support](https://support.microsoft.com/en-us/lifecycle/search?alpha=Windows%2010%20Mobile) with monthly bugfixes and security updates, and March update was pretty huge in size. So there's hope they've ported the fix to mobile. At least my feedback was in the mobile section.

P. S.: If you need me to test the availability of that function somehow, you can tell me.

**Comment by hrydgard** [comment]
Oh, interesting. Haven't charged my Lumia in half a year, heh, will try to update.

**Pull request merged**
