### PR TITLE
Hack to Fix Earth Saver Plus font

### PR DESCRIPTION
**Pull request by sum2012**
Work around #11055

### CODE REVIEW

**Comment by Panderner** [comment]
Wrong font using real PSP font
NPJH00052_00001

Correct font here:
https://github.com/hrydgard/ppsspp/issues/11055#issuecomment-678722585

**Comment by sum2012** [comment]
@hrydgard how about this ?

**Comment by sum2012** [comment]
@hrydgard This pr don't include v1.13.2 release ?

**Comment by hrydgard** [comment]
Not really sure what do with this but thanks to being a compat flag, while ugly, it's at least very safe. So I'm leaning towards getting it in.

**Pull request merged**
