### PR TITLE
assets/lang: Update zh_CN.ini

### PR DESCRIPTION
**Pull request by Croden1999**

### CODE REVIEW

**Comment by hrydgard** [comment]
This is a big change, I'll wait until the 1.16 release process is done, and also for some more feedback. 

@sum2012 ? @Narugakuruga ?

**Comment by Croden1999** [comment]
> This is a big change, I'll wait until the 1.16 release process is done, and also for some more feedback.
> 
> @sum2012 ? @Narugakuruga ?

Some punctuation fixes, and updated translations, Mr. Hrydgard.

**Comment by Narugakuruga** [comment]
image
Personally I would say the interval for blanket is too wide, you would less likely to associate the setting with what's in the blanket.

image

the space for English word is to distinguish Hanzi and Alphabet word, I think keep them as they were is okay. (But yeah it need some unification I think)

image
These ellipsis are too long for UIs. You usually use 6 dots ellipsis to stress some emotion. It is not necessary for UI

**Comment by Narugakuruga** [comment]
The translation fixes are nice.
ellipsis and blanket are a bit off in actual display.
Deleting Space for English word can be optimized more. That's the tricky one. (for unfamiliar words, usually, add space for more clearness, or it will be a mess)

Imagine an example: 
Iuseppsspponxiamishoujianditsfun → Iuseppssppon xiamishouji anditsfun

**Comment by Croden1999** [comment]
> 1. The translation fixes are nice.
> 2. ellipsis and blanket are a bit off in actual display.
> 3. Deleting Space for English word can be optimized more. Don't have to delete every space. That's the tricky one. (for unfamiliar words, usually, add space for more clearness, or it will be a mess)
> 
> Imagine an example: Iuseppsspponxiamishoujianditsfun → Iuseppssppon xiamishouji anditsfun

but here is for Chinese punctuation is need fix and corrent, not other lang, is uniform format here

**Comment by Narugakuruga** [comment]
I think there's no "correct" in punctuation.
In tencent's QQ they use the same English blanket for UI.
And it looks tidy too. 
IMG_20230922_220245

**Comment by hrydgard** [comment]
I took the new WAV format string and merged only that for now, until you guys have figured out how things should be :)

**Comment by Narugakuruga** [comment]
Okay, 
Here's another example show 3 dots used in China's Uber (滴滴打车）

**Comment by Croden1999** [comment]
> Okay, Here's another example show 3 dots used in China's Uber (滴滴打车） IMG_20230922_225547

不一定非要跟着其他应用走，这是在PPSSPP中的显示，也参考了PSP和PSVita上的语言

**Comment by hrydgard** [comment]
Just noting that when you guys agree, I'm happy to merge this. Let me know by posting here - I'll wait for a bit longer first to see if @sum2012 has any additional feedback.

**Comment by sum2012** [comment]
I have no additional feedback.

**Comment by Narugakuruga** [comment]
Look good to me

**Pull request merged**
