### PR TITLE
x86jit: Bake emuhack mask into jitbase

### PR DESCRIPTION
**Pull request by unknownbrackets**
And do the same on RISC-V.  Plus an assert fix.

This is a change I made in #18059 that should be equally beneficial in other backends.

At this point, LittleBigPlanet is about 9% faster (FPS, though it varies 8-10%) in game using the new IR based x86 jit versus the old x86 jit.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Cool to see the new jit win by such a margin!

That's a neat trick to bake the offset in, well spotted. Not very often we manage to shave instructions in the hot part of the dispatcher - would transfer to the old dispatcher too I think.

**Review by hrydgard — APPROVED** [review]

**Comment by unknownbrackets** [comment]
Yeah, we can transfer some of these things to the old dispatcher or merge them at some point, but I'm for now trying to keep it separate in case I optimize something wrongly and so there's an easy way to compare on older devices (I'm of course mainly testing on a newer CPU, which needs optimization far less.)

-[Unknown]

**Comment by hrydgard** [comment]
Well, transferring pure dispatcher optimizations would lead to more fair comparisons of the actual compilation part of the new JIT vs the old JIT. Still, of course - let's not do that until after the release at the earliest.

**Comment by unknownbrackets** [comment]
Well, I mean that for example - using downcount in a reg might not be faster somehow on older devices or something.  Probably this one is safe to be faster.

-[Unknown]

**Pull request merged**
