### PR TITLE
Fixed PGF All

### PR DESCRIPTION
**Pull request by nassau-tk**
These fixed PGF files modified some games text appearance.(example:SnakeWarriors/eragon/FieldRunners/PC-Engine Archives Series) See issue #13718

### CODE REVIEW

**Comment by nassau-tk** [comment]
Did I strange pull request?
(Conflict?)

**Comment by hrydgard** [comment]
Yeah I guess you based it on some older commits, so github now thinks there's a conflict between your old updated fonts and your new updated fonts. Don't worry I'll resolve it for you when merging.

**Comment by nassau-tk** [comment]
I'm so sorry everytime...

**Comment by hrydgard** [comment]
Hm, something has gone really wrong with your commit - the fonts in it are exactly the same one we have in master.

please update your master, create a new branch, and put your new fonts in it and make a new PR...

**Comment by nassau-tk** [comment]
Really?!

OK.
I will try do it.
And,close this.

**Pull request closed without merging**
