### PR TITLE
Revert an IR optimization.

### LINKED ISSUE #15735: Black screen GTA Vice City Stories, Tekken 6, Gran Turismo
### Game or games this happens in

GTA Vice City Stories, Tekken 6, Gran Turismo

### What area of the game / PPSSPP

Black screen when opening these games.

I'm using Ipad Pro IOS 15.5

### What should happen

Should load correctly.

### Logs

_No response_

### Platform

iOS

### Mobile phone model or graphics card

Ipad Pro 12.9

### PPSSPP version affected

v1.13

### Last working version

_No response_

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes #15735

Though see below.

~~Though the real problem might be in PurgeTemps, will look into that next~~ - yup

### CODE REVIEW

**Comment by hrydgard** [comment]
Alternatively, disabling the PurgeTemps() pass also works to fix the issue. So the bug is in there.

**Comment by hrydgard** [comment]
Specifically, disabling this case fixes it:

```
				if (!mutatesReg && !cannotReplace && check.srcReg >= 0 && lastWrittenTo[check.srcReg] < check.index) {
					// Replace with the srcReg instead.  This happens with non-nice delay slots.
					inst = IRReplaceSrcGPR(inst, check.reg, check.srcReg);
				} else if 
```
Though, I'm not sure what's wrong with it. @unknownbrackets , any idea?

**Comment by hrydgard** [comment]
Switched approach to the above-mentioned.

**Comment by ANR2ME** [comment]
Removing this condition can also fixes the issue:
```c++
        case IRTEMP_LR_SHIFT:
			// Unlike other ops, these don't need to persist between blocks.
			// So we consider them not read unless proven read.
			lastWrittenTo[dest] = i;
			// If this is a copy, we might be able to optimize out the copy.
			/*if (inst.op == IROp::Mov) {
				Check check(dest, i, false);
				check.srcReg = inst.src1;
				checks.push_back(check);
			} else*/ {
				checks.push_back(Check(dest, i, false));
			}
			break;
```
May be related to the changes on srcReg?

**Comment by hrydgard** [comment]
That's interesting too! Good information towards narrowing it down.

**Comment by hrydgard** [comment]
Seems to work, switching method again to that. Probably gonna go with this, unless @unknownbrackets has another idea. Totally fine if you don't have time to dig into this for real right now of course.

**Comment by unknownbrackets** [comment]
#15739 should be the right fix.  The two recent changes are more-or-less equivalent, because the one if has `if (srcReg >= 0)` and the other if sets `sercReg = ` to something other than -1.  I would say that the clearest way to disable would be `check.reg = 0;` instead of `inst = IRReplaceSrcGPR(inst, check.reg, check.srcReg);`.

-[Unknown]

**Pull request closed without merging**
