### PR TITLE
Dynamically reallocate buffers when out of space

### PR DESCRIPTION
**Pull request by unknownbrackets**
I also reduced the starting size, although maybe we should do more testing to see what's ideal there.  Happy to increase it back.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Really nice.

**Comment by unknownbrackets** [comment]
For using allocating textures in larger blocks, we only realistically need to worry about device-only images, right?  We're using push buffers for the upload.

In that case maybe:

```c++
class VulkanDeviceAllocator {
public:
	VulkanDeviceAllocator(VulkanContext *vulkan, size_t minSlabSize);
	~VulkanDeviceAllocator();

	void Destroy();

	void Begin();
	void End();

	size_t Allocate(const VkMemoryRequirements &reqs, VkDeviceMemory *deviceMemory);
	void Free(VkDeviceMemory deviceMemory, size_t offset);

private:
	void AllocateSlab(size_t minBytes, uint32_t memoryTypeIndex);
	void Decimate();

	static const size_t SLAB_GRAIN_SIZE = 1024;
	static const uint8_t SLAB_GRAIN_SHIFT = 10;

	struct Slab {
		VkDeviceMemory deviceMemory;
		uint32_t memoryTypeIndex;
		std::vector<u8> usage;
		std::unordered_map<size_t, size_t> allocSizes;

		size_t Size() {
			return usage.size() * SLAB_GRAIN_SIZE;
		}
	};

	VulkanContext *vulkan_;
	std::vector<Slab> slabs_;
	size_t minSlabSize_;
};
```

The only downside is that it could get fragmented.  At best, if minSlabSize_ isn't enough, it could up it for new slabs, but old slabs may hang around with fragmentation... though, likely it wouldn't be too bad as long as the initial minSlabSize was large enough.

Potentially, it sounds like we can rely on them all using one memoryTypeIndex and move that to the constructor, and just validate it matches the reqs.

-[Unknown]

**Comment by hrydgard** [comment]
Yes, exactly! I don't think fragmentation will be a huge problem. If it will, we can consider defragmenting and allowing to pass in a callback to be notified when a block is moved, or something...

Regarding formats, I was thinking that if we need more "heaps" like this with different memory types, we'll just use a second one. The memory type could be a parameter when creating the VulkanDeviceAllocator.

About mapping, I think that's the user's responsibility, not this class, although it may be nice with some convenience functions, we'll see.

Oh yes, copy-buffer-to-stencil will be great for that :)  Just need to reformat from top 8 bits of 32 bits into a contiguous array of 8-bits. Can maybe even do that on the GPU...

**Comment by unknownbrackets** [comment]
Completely untested stab:

https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:vulkan-mem?expand=1

-[Unknown]

**Comment by hrydgard** [comment]
Nice stuff.

Yeah, FBO is also a good use case. The distinction between textures and FBOs may become even blurrier going forward, by the way... FBOs are of course always "special" because they have depth/stencil buffers, but still.

Some comments:

   * I'd take the memoryType as a parameter in the constructor. It's Vulkan style to specify things early :)
   * Within each slab, we could even reuse the BlockAllocator that we use for PSP memory although that's probably not a good idea...
   * Maybe implement a frame-delayed Free, or make it possible to put Free calls on the VulkanContext's deleter? That way textures can simply delete their resources and things will be fine even though we buffer up a whole frame and it can still be used by the GPU for another frame.
   * Maybe each slab should be twice the size of the last one, or something?

Also,

    // Let's hope we don't get any double-frees or misfrees.

should be more like

    // Die immediately, we have a bug

so they don't slip through :) And changed to an assert that is also active in release mode. We need to make some better asserts...

**Comment by hrydgard** [comment]
Also maybe the allocator should return some opaque object that contains the slab number etc, for speed in Free(). Though I don't think the load on the allocator will be that heavy...

**Comment by unknownbrackets** [comment]
Well, in usage, how will we know the memory type?  We only know the memory type when we ask for the texture requirements, and so we can only get that with the requirements.  So then we need to create a texture before we can create the allocator.

I'm not against, that, I guess we just have an == nullptr check in texture creation?

I expect Free to be very fast.  Normally we would not have many slabs, and then it would have an unordered_map lookup to find the block.  Setting the usage to 0 should be quick.  Destroys only happen at the start of a frame, though.

I'm more concerned that allocating may be slow than worried about Free... we already need/use allocSizes to make allocating fast, so I don't think having an opaque object would make the free faster.  But maybe it'd make it more future proof.

Yeah, maybe we should increase the slab size, that's not hard...

I did put it in Common/Vulkan/VulkanMemory.cpp, no?

-[Unknown]

**Comment by hrydgard** [comment]
We can get requirements for texture formats without actually creating a texture though.

Well, we can't reuse that memory space for something else until all pending command buffers that use a texture whose memory has just been freed have fully executed. The delayed Deleter is to handle that sort of thing - when you have used and no longer need an object, you can just chuck it in the deleter pool without caring about exactly when it needs to go away.

Sorry I misread the diff, it began with VulkanImage.cpp but I missed the transition to VulkanMemory.cpp.

**Comment by unknownbrackets** [comment]
Hmm.  I feel like it'd be nice if I could just drop a std::function or something onto the delete queue, rather than make it understand what freeing subsections of device memory means.  What do you think?

-[Unknown]

**Comment by hrydgard** [comment]
I'm not a big fan of std::function for this kind of thing, they are a little heavy, just look at the call stacks you get in debug mode :)  but a regular callback+userdata should be fine.

**Comment by unknownbrackets** [comment]
Hmm, I ended up just using new/delete, probably okay, but maybe not great... also, made the callback take two args, so we can potentially use separate device memory objects on separate threads (feels like it makes the most sense?)

https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:vulkan-mem?expand=1

-[Unknown]

**Comment by hrydgard** [comment]
I'm not quite sure how the two userdata args help that use case, but either way, this looks alright. I think the class deserves a comment that it implements a slab based allocator with bitmaps for suballocation inside the slabs.

Did you try hooking it up to VulkanImage? I guess the texturecache should own the DeviceAllocator, then you just pass it in as an argument at appropriate points..

**Comment by unknownbrackets** [comment]
Sorry, at first I was sending a pointer and lookup up via an STL object, because I wanted to avoid the new/delete... now it doesn't need the two params.

Haven't had the free time to do more than write that out this week.

-[Unknown]

**Comment by unknownbrackets** [comment]
Hmm, it mostly works, but vkBindImageMemory is sometimes returning VK_ERROR_INVALID_PARAMETER_NV.  Found the bug, I was allowing allocations beyond the end (as long as it started within).. d'oh.  Long week.

-[Unknown]

**Comment by unknownbrackets** [comment]
So, I tested it on top of the latest decoding changes in FF2 (which decodes a bunch of textures, freeing and allocating a lot.)  I tried around 6 runs each, averaged maybe around 1% faster, but timings were pretty inconsistent between runs, so that's definitely within margin of error.

Anyway, at least it doesn't seem any slower... probably also isolates us better from driver-specific allocator performance issues.

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets Sounds great. Yeah, I wouldn't expect nVidia to be slow at allocation, but given experience with glBufferData on other vendors this is something we really want control over, heh.

**Pull request merged**
