### PR TITLE
sceKernelFindModuleByName:Add delay for Fake module

### LINKED ISSUE #13601: Preformance of Dissidia Final Fantasy Chinese patch
The game call this function often
W[SCEMODULE]: hle\scekernelmodule.cpp:2441 0 = sceKernelFindModuleByName(sceFont_Library): Module Not Found or Fake
Mobile Phone preformance  may be poor.
JPCSPtrace of sceKernelFindModuleByName
https://gist.github.com/sum2012/4d9c69313272f66301e8ec59ac451cb2
Notice last call is
18:13:09.131250 main_thread - <- sceKernelFindModuleByName660 0x8820C498('sceFont_Library') = 0x880CFB54
but our ppsspp return 0 for fake module.

I try something test
ppsspp full log:
https://gist.github.com/sum2012/11888fcc5a93261183e675a72e5b41ec

### PR DESCRIPTION
**Pull request by sum2012**
Fix #13601

### CODE REVIEW

**Comment by ANR2ME** [comment]
Does `sceKernelFindModuleByName` can take as much as 1 second like that on real hardware?

**Comment by sum2012** [comment]
It keep request non-zero result so that delay 1 second is okay.

**Comment by ANR2ME** [comment]
Does using a lower value (ie. 1000 or 10000) on `hleDelayResult` will also trigger the invalid memory address?

i'm just worried if delaying a thread for 1 second like that will cause a timing issue when a game is calling `sceKernelFindModuleByName` in the middle of multiplayer.

**Comment by sum2012** [comment]
Return non-zero result would raise invalid address,don't affect lower value (ie. 1000 or 10000) on hleDelayResult
It only delay for fake module (I.E :sceFont_Library  ) so that it is safe

**Comment by unknownbrackets** [comment]
Well, this seems like a hack because I doubt 1 second is really how long this function blocks, but it's also only a kernel-accessible function so this is likely to only impact patched games/hacks, not regular games.  Given that most kernel functions don't work / don't work correctly anyway, I don't think it's a big concern.

-[Unknown]

**Comment by hrydgard** [comment]
Right. Yeah, seems low-risk. If something bad happens we'll just revert or reduce the delay and maybe also reduce the logging..

**Pull request merged**
