### PR TITLE
Improve sceAtracGetStreamDataInfo(), read PSP RAM directly

### LINKED ISSUE #2539: Code Lyoko stuck at "No problem screen"
PPSSPP v0.8.1-109

It just replay sound voice in the screen

JPCSP also have this probrem.
(and It can solved by disable decode audio by SonicStage)

PPSSPP Debug log:
(I have disabled log in hle\scekerneltime.cpp:67 /DEBUG_LOG(HLE, "sceKernelGetSystemTime(out:%16llx)", t);)

https://docs.google.com/file/d/0B3OaSdeV0L8kclhHR2czaGtuZGM/edit?usp=sharing

### LINKED ISSUE #3122: Last Ranker crashes when battle in the Coliseum
disable atreac3+ plugin can "fix" this issue.

savedata
https://docs.google.com/file/d/0BzGZGDfFE68zNUZvdDIxMi1VbEU/edit?usp=sharing

### LINKED ISSUE #3650: Puyo Pop Fever and Puyo Puyo Fever 2 Atrac3+ issues
This bug has been occuring for a while now and it happens in both PPF and its sequel, PPF2.
Here's the log: http://pastebin.com/tdCukL1W

### LINKED ISSUE #6363: Gensou suikoden 1&2 new issues
~~1.a lot of Invalid address during gameplay,it would log too many,and crashes,~~
1.Missing BGM after the BGM changing

~~2.another black background,one is fixed before~~  fixed by the function replacement
~~https://cloud.githubusercontent.com/assets/3481559/3311862/f17432f8-f6c9-11e3-8ec1-74e40319fc4e.png~~

~~psp~~
~~https://cloud.githubusercontent.com/assets/3481559/3311864/fa58415c-f6c9-11e3-8dcd-15065b67a94b.png~~

~~that texture only appearing in Gedebugger every 5 frames(drawing a whole screen is one frame)~~
~~https://cloud.githubusercontent.com/assets/3481559/3311885/484bf3c2-f6ca-11e3-887a-3a59c61823c8.png~~

3.button sound effect laggy.
debuglog (rename jpg to rar)
ppsspplog

### LINKED ISSUE #8179: SOCOM - U.S. Navy SEALS - Fireteam Bravo 3 atrac error
happen in the end of the cutscene. The demo also happen. Since https://github.com/hrydgard/ppsspp/pull/8011 ,https://github.com/hrydgard/ppsspp/pull/8176 does not help

```
55:57:226 Streamer Thr I[ME]: HW\MediaEngine.cpp:87 FF: Frame data doesn't match channel configuration!
55:57:226 Streamer Thr E[ME]: HLE\sceAtrac.cpp:442 avcodec_decode_audio4: Error decoding audio -1094995529 / bebbb1b7
55:57:230 Streamer Thr I[ME]: HW\MediaEngine.cpp:87 FF: Frame data doesn't match channel configuration!
55:57:230 Streamer Thr E[ME]: HLE\sceAtrac.cpp:442 avcodec_decode_audio4: Error decoding audio -1094995529 / bebbb1b7
55:57:233 user_main    I[ME]: HLE\sceAtrac.cpp:1413 sceAtracReleaseAtracID(1)
55:57:233 user_main    I[ME]: HLE\sceAtrac.cpp:1413 sceAtracReleaseAtracID(2)
```

the cutscene

demo download
CAMPAIGN->select map STOCKPILE
https://onedrive.live.com/?id=46301D80532F136C!108&cid=46301D80532F136C&group=0&parId=46301D80532F136C!111&authkey=!ABcGX_37t7ik7Kg&action=locate

### PR DESCRIPTION
**Pull request by unknownbrackets**
This improves it mainly only for halfway buffered situations, but also a little for streamed.

For streamed and looped buffers, it's still wrong.  Mainly, it allows the wrong number of writable bytes, and asks for them to be put in the wrong place.

Anyway, this fixes #2539.  The readOffset needs to wrap around at the end, and I think this game (and probably others) lazily enable looping on ALL audio, and then check for this to wrap to know when it has looped.

Fixes #3650, fixes #8179, fixes #6363, fixes #3122.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Since sceAtracGetStreamDataInfo was really the last missing piece, I went ahead and added a bit more to this:

It now reads directly from the PSP RAM buffer for halfway buffered and fully buffered data.  There's all sorts of scenarios in which this may be more correct, including minor timing issues.

Streaming buffers are more complicated, especially looping.  There's more bugs to work out there, so I used a flag to track (in savestate) which buffer is used.

I'm trying to decide the best way to handle BC.  Eventually, I may want to copy the data_buf contents partially into PSP RAM from a savestate, and continue streaming from there... just to avoid dragging the data_buf complexity along with us forever.

-[Unknown]

**Comment by daniel229** [comment]
Great.
Fixes https://github.com/hrydgard/ppsspp/issues/3650  https://github.com/hrydgard/ppsspp/issues/8179   https://github.com/hrydgard/ppsspp/issues/6363

**Comment by daniel229** [comment]
Fixes https://github.com/hrydgard/ppsspp/issues/3122

**Comment by unknownbrackets** [comment]
Awesome, all these things I thought might be related to this same problem actually were.  Usually it's not this lucky, heh.  I bet getting streaming right will fix some more.

-[Unknown]

**Comment by daniel229** [comment]
Breaks Prince of Persia Boukyaku no Suna.https://github.com/unknownbrackets/ppsspp/commit/f3d7ea6d2f9ec565ece6dcb24e62beb651a19449

**Comment by daniel229** [comment]
Shin Ken to Mahou to Gakuen Mono Toki no Gakuen is also broken.

**Comment by daniel229** [comment]
Boku no Natsuyasumi and Brave Story crash

**Comment by unknownbrackets** [comment]
Darn, oops.  Accidentally snuck another change into that commit.  Just pulled it out.

Brave Story seems to work with that reverted.  Good to know, I didn't mean to commit it yet, but I didn't realize it was broken.

-[Unknown]

**Comment by daniel229** [comment]
Above problems are fixed.

**Pull request merged**
