### PR TITLE
Improve consistency with PSP output for sas reverb

### PR DESCRIPTION
**Pull request by unknownbrackets**
With these changes, hrydgard/pspautotests#176 passes.  There are some bugfixes to e.g. volume handling, etc.

To me, it sounds fine (maybe better?) with these changes, but I don't have the sharpest ears.

-[Unknown]

### CODE REVIEW

**Comment by vnctdj** [comment]
This has improved the volume for too loud sounds introduced by https://github.com/hrydgard/ppsspp/pull/8116 in *Monster Hunter Freedom Unite*, nice :)
However, the following error appears at some points :
```
20:18:396 CsePspSndDrv E[SCESAS]: HLE\sceSas.cpp:474 80420020=__sceSasRevType(08a8b200, 65535): invalid type
```

**Comment by unknownbrackets** [comment]
I just validated on my PSP that 65535 returns that error.  Could potentially be different per version, but more likely it's a bug in the game - seems like it's *trying* to set it to -1, but using an unsigned short that's been truncated.

-[Unknown]

**Comment by vnctdj** [comment]
Oh, ok...
If I understand correctly, "-1" means "off", right ? Then it would make sense given that this error appears when I go to another area in the game (a loading screen with no sound happens at this moment).

**Comment by hrydgard** [comment]
Yeah. Nothing to worry about, really - games do make bad API calls from time to time. As it's not spamming, no need to even reduce logging of it.

**Comment by vnctdj** [comment]
Ok, thank you for your explanations guys :)

**Pull request merged**
