### PR TITLE
Update README.md for 1.6

### PR DESCRIPTION
**Pull request by hrydgard**
Looks too short, I must have forgotten a lot of things...

### CODE REVIEW

**Comment by leopard20** [comment]
I assume "Fixing crashes on backend switch" falls into one of those categories?
Or maybe just simplify it to "Lots of crash fixes"!

**Comment by unknownbrackets** [comment]
Some random thoughts of potential other items (some probably too detailed to include):
 * #8975 (I don't follow adhoc closely so not sure how noteworthy)
 * SDL/Linux now supports Vulkan (#10413)
 * Might be worth mentioning jit working on iOS specifically, not just "a few fixes" (#10465)  Although there are other good fixes.
 * Now uses a core profile on Mac, improving compatibility (#10113)
 * Probably should mention texture replacement fixes / some v1.5.4 replacements incompatible due to a bug? (#10796)
 * Maybe add Vulkan as the default on the Vulkan improvements line?
 * Maybe "Assorted bugfixes and compatibility improvements" again?  Not sure if it's needed to repeat that each time.  Otherwise maybe include #10658 specifically?
 * Save state undo feature worth mentioning?  Maybe not, since there's not enough UI yet.  Maybe next time around.
 * If you end up adding PR #s might want #10911 in the Vulkan list.  Might be worth mentioning the previously unplayable games this makes work (not entirely sure how popular they are.)
 * Might also note app file browser on iOS line? (#10921)
 * Further Android widget fixes? (#10855)

-[Unknown]

**Comment by unknownbrackets** [comment]
> not good leaving sth unfinished

Definitely good to finish things, but this is a dangerous mentality.  PPSSPP is still unfinished.  It's better to leave things unfinished than try to build Rome in a day.  What we have now is already a lot more awesome than 1.5.4.

The train's gotta stop to take new passengers at some point, can't wait until we're at the end of the line for that.

My worry about the UI anyway is awkward and tiny touch areas.

-[Unknown]

**Comment by vnctdj** [comment]
@hrydgard I think we should mention my last pull request, it may interest some users like Linux distribution packages maintainers.
Maybe the following:
```
Added "--version" command line option for SDL and Qt platforms (#11028)
```

**Comment by Jinzombie** [comment]
I think 1.6.0 is ready 👍😀

**Comment by marosis** [comment]
Yes. I think too!👍

**Comment by unknownbrackets** [comment]
Actually 1.6.0 is gonna have a complete PS2/PS3 emulator, a special "superultrashader" that will make 10x render resolution look good in all games and run faster than 1x on even the weakest mobile devices, and a checkbox to download extra RAM and ISO storage space for low-memory devices.

None of this code has been tested or seen by anyone yet, so it's possible that when it first sees the world it will be so buggy that it won't even exist.

All the improvements in git since 1.5.4 were just the prep work for these great features that we decided could be made public.  The code name of this update is PPSSPP: The Emperor's New Clothes Edition.

-[Unknown]

**Comment by iOS4all** [comment]
Wow it’ll be very nice at least to support ps2 games on this amazing emulator.
We really hope we can get a Nintendo Switch port as well.

Thanks a lot for your efforts.

**Comment by hrydgard** [comment]
Some people should maybe check their sarcasm detectors :)

Again I'm gonna have a busy weekend but I'll really try to get it out next week...

**Comment by leopard20** [comment]
Hope you don't mean me! Because then you need to check yours!

**Comment by marosis** [comment]
I really love this emulator! !GUYS! You are best😉!

**Comment by unknownbrackets** [comment]
> Please also add a PS4 emulator! Maybe even create PS5 while you're at it!  😂

Yes, PS5 emulation should take very little time to add.  I bet it will run all the PS5 games that have been released to date with very little effort.

-[Unknown]

**Comment by leopard20** [comment]
Yes. Thank you! 😂

**Comment by Jinzombie** [comment]
Add also PS ViTa please 🙇
hahaha 😂✌

**Comment by leopard20** [comment]
Is it just me or is this thread really turning into a joke?!

**Comment by Jinzombie** [comment]
YES FINALLY!!!
1.6.0 is going to release 🎇🙌🎉

**Pull request merged**
