### PR TITLE
Update README.md for 1.7.0

### PR DESCRIPTION
**Pull request by hrydgard**
Probably forgot something important as usual...

### CODE REVIEW

**Comment by unknownbrackets** [comment]
May or may not be worth mentioning:

 * Post-shaders fixed for OpenGL. (#11182)
 * Significant performance improvement in some Gundam and Earth Defense games. (#10973)
 * Initial APIs for debuggers, tools, and trophy or streaming apps (#10909)

Less notable, probably:

 * Android app bundles?
 * Compilation on Linux/EGL. (#11144)
 * Ability to select rendering device on multi-GPU systems (#10922)
 * Suggestions for settings when reporting bad gameplay (#11132)
 * Extra alternate speed option (#11187)

-[Unknown]

**Comment by leopard20** [comment]
@unknownbrackets Regarding the alternate speed options, what are they and what is their purpose exactly? I really don't see any difference with or without them. Are they used in unthrottling?

**Comment by AkiraJkr** [comment]
it may *probably* be worth mentioning hotlinking is working properly for non-XInput devices?

**Comment by unknownbrackets** [comment]
Yes, that's there - "Detects DirectInput devices when running (#11461)".

-[Unknown]

**Comment by leopard20** [comment]
@unknownbrackets Is the new touch controls style worth mentioning?

**Comment by unknownbrackets** [comment]
Yeah, maybe that one too.  Honestly neither that or alternate speed seem major enough, probably.

Looking forward to the spline improvements for 1.8.x.

-[Unknown]

**Review by unknownbrackets — APPROVED** [review]

**Comment by Emulatorer** [comment]
v1.7.0 will release today?

**Comment by hrydgard** [comment]
Depends if there's any issues with the new "Android Bundle" stuff. Probably this week at least.

**Pull request merged**
