### PR TITLE
Use framebuffer fetch more and on more devices

### PR DESCRIPTION
**Pull request by unknownbrackets**
This adds support for EXT_shader_framebuffer_fetch, which is available on PowerVR devices, specifically Apple A7 (comes up as a GPU?), PowerVR Rogue, and PowerVR SGX 535+.

Additionally, we currently avoid copying FBOs for some blending modes where overlap is more of an issue, and it's a bit hacky.  But framebuffer fetch should be ordered, and therefore safe to use in these situations for more accurate blending.

These two changes may solve issues like the one noted in #1313.

I don't have any working devices with support, so this is basically untested.  So, it may also break things horribly...

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Worth pulling in GL_ARM_shader_framebuffer_fetch and testing for it too?

Definitely seems supported on Mali-T624+ and possibly on Mali-400 and Mali-450 (might cause shader complexity there, anyway, though... so might want to blacklist it.)

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, why not?

**Comment by unknownbrackets** [comment]
Okay, added, but I didn't blacklist since it could also really help performance.  Would like to see what happens on Mali-400 devices advertising the extension...

-[Unknown]

**Comment by ThePhoenixRises** [comment]
Excuse me, are you guys going to merge this to master? 
As I have both a PowerVR SGX 544 MP & a CnM Mali-400 MP tablets available to test this once merged, will be very interesting to see if there are improvements on both tablets.

**Comment by unknownbrackets** [comment]
Well, it will only improve performance when non-standard blending is being used.  Normally this will only be during effects and things, not constant.  But when such effects are being used, this could theoretically improve performance a good bit.

It's also likely to make such effects look more correct, since it'll be applying the effect correctly, rather than using workarounds.

Examples of games with such effects:
 * http://report.ppsspp.org/logs/kind/571?status=any
 * http://report.ppsspp.org/logs/kind/353?status=any (I think it's used throughout in Simpsons and Dragon Ball Z)
 * http://report.ppsspp.org/logs/kind/622?status=any (Lunar battle effects, Dragon Ball Z special move thing, etc.)

And I think also Persona or Persona 2, but I think we already optimized that out a different way.

-[Unknown]

**Comment by unknownbrackets** [comment]
@ThePhoenixRises unfortunately, that device or at least its drivers does not appear to support framebuffer fetch.  So this change won't affect it.

It might be that some of the PowerVR devices that came up as having it were lies.  Some users install hacks that make OpenGL report that it supports GL extensions which it doesn't.  This inevitably makes things worse when using PPSSPP, never better, and also confuses us (or at least me) when we look at reporting data.  It's unfortunate.

-[Unknown]

**Comment by unknownbrackets** [comment]
So, thinking about it, on a device that supports framebuffer fetch (e.g. not Adreno and not any desktop card), we could fully support:

1. RGB and alpha masking (currently we do a "best attempt" on all platforms.)
2. Logic ops (currently we do a "best attempt" on d3d9 and gles, but not desktop.)
3. Obscure blending (as done in this pull request.)

This might correct shadows in Dragon Ball Z and maybe the flashlight in Silent Hill (I seem to remember it uses masking.)  I suppose it might be possible on desktop GL and Adreno 4xx cards using image load/store...

-[Unknown]

**Comment by ThePhoenixRises** [comment]
Thanks for your answer, @unknownbrackets, do you think looking at the list of extensions available though, that some optimisation's could be implemented that other GPU's don't have available, so as to improve performance in places that other cards would struggle.

**Comment by unknownbrackets** [comment]
Not really.  I'm sure there's more options, but aside from uniform buffers I'm not noticing anything.  But I'm no GL expert.

Looks like GL_CONSTANT_COLOR may possibly just not work on (certain?) PowerVR devices:
http://forums.ppsspp.org/showthread.php?tid=3968&pid=103987#pid103987

Anyway, I'm thinking we ought to merge this and find out what impact it has.

-[Unknown]

**Comment by unknownbrackets** [comment]
There are a few reports of `Undeclared variable 'gl_lastFragColorARM'`, though not a ton.  It's not coughing on the `#extension GL_ARM_shader_framebuffer_fetch : require` line, so I assume it's not Chainfire3D or something.

It matches the sample, do I need to declare vars like `gl_lastFragColorARM` in GLES 3 (I know the output frag color is defined)?  All of the errors have `#version 300 es` at the top.

-[Unknown]

**Comment by hrydgard** [comment]
Probably just some bad driver revision, not sure what to do about it..

**Comment by unknownbrackets** [comment]
Maybe... only 6 total hits only, and has happened even on a non-ARM with the EXT_ version.  On the following:

Mali-T624 ES 3.0
Mali-T760 ES 3.0
PowerVR Rogue Hood ES 3.0 build 1.3@2876724

I guess I could force it off if there's been a shader compile error, like with the hardware transform thing...

-[Unknown]

**Comment by unknownbrackets** [comment]
Maybe rather than bad drivers just a stupid me.  e45daac41c365f64b61279c7ef120d13cdff6059.  It was even correct before...

Let's see if that improves anything.

-[Unknown]

**Pull request merged**
