### PR TITLE
Cleanup GPU vendor detection a bit, use it to avoid the issue mentioned in #9545

### PR DESCRIPTION
**Pull request by hrydgard**

### CODE REVIEW

**Comment by LunaMoo** [comment]
Seems like you reverted that recent armips update by accident.:)

**Comment by hrydgard** [comment]
Oops, the perils of using multiple computers. Fixed.

**Comment by hrydgard** [comment]
@LunaMoo Please check if this does the right thing on you GPU - it should, though. 

Build errors seems to be the usual, apple stuff build server down..

**Comment by LunaMoo** [comment]
It's good, compat hack doesn't activate.:)

**Pull request merged**
