### PR TITLE
Minor optimizations in software transform

### PR DESCRIPTION
**Pull request by hrydgard**
For best speed, we'd need a JIT of course. But this optimizes a few common matrix operations a bit with NEON/SSE.

Plus, shrinks the screen rotation to a 2x2 matrix operation in the shader.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Looks good, not sure what we need to do on macOS M1, though...

-[Unknown]

**Review by unknownbrackets — APPROVED** [review]

**Comment by hrydgard** [comment]
I'll take a look at mac, I just tested on Android ARM64 and thought it'd be fine.  I know some intrinsics have changed name over time, it's probably something like that...

**Comment by hrydgard** [comment]
OK turns out it's ARM32 that doesn't have that instruction variant, it does have vmulq_lane_f32 (note: not laneq). 

I'll just ifdef it out for now.

**Comment by unknownbrackets** [comment]
A few people on older devices (i.e. Adreno 3xx / Cortex A53) have reported issues, I wonder if there could be some issue affecting those CPUs here?  Or somehow in culling entirely?  Those devices wouldn't support shader cull distance, I think, but I wasn't seeing the problems forcing that scenario...

-[Unknown]

**Comment by hrydgard** [comment]
Hm, wacky. Maybe shader compiler bugs around mat2? This has to be OpenGL right? Also I just realized that lowp is too low for the orientation number since it doesn't need to be able to carry larger integers than 2, but shouldn't matter in orientation 0...

**Pull request merged**
