### PR TITLE
OpenXR - Gran Turismo camera shaking workaround

### PR DESCRIPTION
**Pull request by lvonasek**
Since https://github.com/hrydgard/ppsspp/pull/18438 there is VR camera shaking in Gran Turismo. This PR fixes that on all headsets.

### CODE REVIEW

**Comment by lvonasek** [comment]
Interesting. I wouldn't expect the shaking is an intention. I leave it on you but I find pity that the best looking PSP game don't work out of the box (even that it worked in the previous version). The new compat flag is basically switching between an old projection matrix Hack and new projection matrix hack.

**Comment by hrydgard** [comment]
How did it work in VR previously?

**Comment by lvonasek** [comment]
It used the projection matrix from OpenXR and changed the sign of all 16 values to match the sign of the game projection matrix. This for some reason is very broken on Quest3.

**Comment by lvonasek** [comment]
I am closing this. Let's keep the VR integration simple.

**Pull request closed without merging**
