### PR TITLE
Unified bicubic upscaler

### PR DESCRIPTION
**Pull request by fp64**
A stab at implementing #17294.
~~Explicitly WIP~~. Ok now. Basically, something you can play with, and comment your impressions.
Haven't deleted the existing versions, so you can compare quality/speed.
Parameters to upscaler are named simply "B" and "C".
Existing ones should be equivalent to:
```
Bicubic (Catmull-Rom) Upscaler:        B=0.0,         C=0.5
Bicubic (Mitchell-Netravali) Upscaler: B=0.333333333, C=0.333333333
```
Ranges on B and C are for now [-1;+2] just to showcase that values outside [0;1] are legal, just not good-looking.

No translation strings so far.

Unfortunately, I *can* tell the difference in speed on my (pretty weak) GPU, though it is not large. But maybe there are optimizations possible.

Feedback is welcome.

### CODE REVIEW

**Comment by fp64** [comment]
As for naming, parhaps:
```
SettingName1=Sharpness
SettingDefaultValue1=1.0
SettingMaxValue1=1.0
SettingMinValue1=0.0
SettingName2=Anisotropy
SettingDefaultValue2=0.0
SettingMaxValue2=1.0
SettingMinValue2=-1.0
```
with
```
B=1-Sharpness+Anisotropy/2
C=Sharpness/2+Anisotropy
```
so that Sharpness,Anisotropy are orthogonal axes in B,C coordinates.

**Comment by hrydgard** [comment]
How are you seeing the performance difference, is the perf actually tanking at high resolutions, for example?

**Comment by fp64** [comment]
Here's FPS I'm getting in Valkyria Chronicles II (OpenGL, 1x internal resolution, no frameskip):

2D scene (mission map):
Resolution | Off | Old | New | Spline36
-----------|-----|-----|-----|---------
   480x272 |  30 |  30 |  30 |  30
   960x544 |  30 |  30 |  30 |  15
 1280x1024 |  30 |  30 |  28 |  10

3D scene (mission):
Resolution | Off | Old | New | Spline36
-----------|-----|-----|-----|---------
   480x272 |  30 |  30 |  30 |  30
   960x544 |  30 |  28 |  26 |  12
 1280x1024 |  30 |  24 |  23 |   9

with "old" being "Bicubic (Catmull-Rom) Upscaler".

**Comment by fp64** [comment]
As a byproduct, here's an interactive demo: https://www.shadertoy.com/view/Dlc3Rn. None of shadertoy's default textures seem to be particularly good for showcasing filters.

**Comment by fp64** [comment]
And here's the actual version.

Didn't do anything with translation strings.
Parameter naming is not great but should be workable.
Left it as 2-parametric after all (to allow expressing all filters in this class, just in case). If 99% users don't ever touch "Anisotropy" slider - so be it.
Range is somewhat large ([-2;+2]) to allow people to try "ah, so that's what it does - yeah, don't want to set it this far" (I personally like how e.g. VLC allows volume outside 0..100%, though it is not quite the same thing).

**Comment by fp64** [comment]
Erm... would be just editing [UWP/UWP.vcxproj.filters](https://github.com/hrydgard/ppsspp/blob/master/UWP/UWP.vcxproj.filters) enough to resolve it?

**Comment by hrydgard** [comment]
Not quite, UWP.vcxproj too. Quick git grep (before your PR):

```bash
hrydg@THREADRIPPER MINGW64 /c/dev/ppsspp (master)
$ git grep upscale_mitchell_netravali
UWP/UWP.vcxproj:    <None Include="Content\shaders\upscale_mitchell_netravali.fsh">
UWP/UWP.vcxproj:    <None Include="Content\shaders\upscale_mitchell_netravali.vsh">
UWP/UWP.vcxproj.filters:    <None Include="Content\shaders\upscale_mitchell_netravali.fsh">
UWP/UWP.vcxproj.filters:    <None Include="Content\shaders\upscale_mitchell_netravali.vsh">
assets/shaders/defaultshaders.ini:Fragment=upscale_mitchell_netravali.fsh
assets/shaders/defaultshaders.ini:Vertex=upscale_mitchell_netravali.vsh

hrydg@THREADRIPPER MINGW64 /c/dev/ppsspp (master)
$ git grep catmull_rom
UWP/UWP.vcxproj:    <None Include="Content\shaders\upscale_catmull_rom.fsh">
UWP/UWP.vcxproj:    <None Include="Content\shaders\upscale_catmull_rom.vsh">
UWP/UWP.vcxproj.filters:    <None Include="Content\shaders\upscale_catmull_rom.fsh">
UWP/UWP.vcxproj.filters:    <None Include="Content\shaders\upscale_catmull_rom.vsh">
assets/shaders/defaultshaders.ini:Fragment=upscale_catmull_rom.fsh
assets/shaders/defaultshaders.ini:Vertex=upscale_catmull_rom.vsh
```

**Comment by fp64** [comment]
Yeah, that seems to do the trick.

**Comment by hrydgard** [comment]
I'm happy to merge as it (and I'll fix up any translation issues after).

Your PR still says "Explicitly WIP" - ready?

**Comment by fp64** [comment]
Yes, good to go.

**Pull request merged**
