### PR TITLE
Allow to append some configs

### LINKED ISSUE #16129: Add extra configuration files when starting from the command line
### What should happen

ppsspp should have an extra configuration file that, when launched from the command line, can load the game's custom diff configuration.

for example:

PPSSPPWindows64 "Silent Hill Origins (USA).iso" --appendconfig=FILE1
PPSSPPWindows64 "God Of War - Chains Of Olympus.iso (USA).iso" --appendconfig=FILE2

This extra configuration file usually only contains the difference from the main configuration file(ppsspp.ini), and has a small size.

### Who would this benefit

All users who use a fancy frontend to manage game startup and loading will benefit

### Platform (if relevant)

_No response_

### Games this would be useful in

All games

### Other emulators or software with a similar feature

_No response_

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

### PR DESCRIPTION
**Pull request by iota97**
Fixes #16129.

It will update config on start up and every time a new different game with specific setting is loaded. This should allow to change the setting once loaded with no problem.

Tested on Linux only, should work on Windows too :)

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm, do we really need the vector with the game IDs? is it bad if it gets loaded again, if you start up a game twice?

**Comment by iota97** [comment]
> Hm, do we really need the vector with the game IDs? is it bad if it gets loaded again, if you start up a game twice?

I'm mostly afraid of some frontend ends up using this and we get report and complain about setting not being saved properly when changed from UI.

This probably won't be used much, so I guess we can go for the "naive" approach too and avoid some code complexity.

**Comment by unknownbrackets** [comment]
Hm, I feel like it's a bit confusing either way.  As current, if you start PPSSPP with --appendconfig...
1. After loading game A, you'll get the appended settings.
2. If you quit the game and load it again, you won't get the appended settings.
3. If you quit and switch to game B, you'll get appended settings again.

That seems weird.  Maybe it'd be better to show a banner at the top of the config section that some settings are being overridden and may not apply, if we're worried about modifying settings.

-[Unknown]

**Comment by iota97** [comment]
> 2. If you quit the game and load it again, you won't get the appended settings.

This won't happen as appended setting get saved in the game config. Would be somewhat better not to, but that would require too much complexity imho.

Well it will happen if you change them in the UI during the first run, but that's what I wanted in the first place :)

**Comment by unknownbrackets** [comment]
Oh, I see.  I guess that's probably not that confusing then, as long as another arg to set `bSaveSettings = false;` isn't specified.  But that's probably rare and only really used for debugging.

-[Unknown]

**Comment by hrydgard** [comment]
I don't feel I completely understand the implications of this, but since it's a command line option, I'm fine with merging it now for 1.15. Just needs a little rebase.

**Pull request merged**
