### PR TITLE
Android TV

### PR DESCRIPTION
**Pull request by hrydgard**
While the banner icon is ugly and the UI could be made more TV-style, this mostly completes Android TV support. For example, it removes on-screen touch controls, as they don't make a lot of sense.

Has been tested to work on an Android TV device.

With this, you need Android SDK v22 (Lollipop 5.1) to compile, although the minimum SDK compatibility has not been raised from v9 (Gingerbread 2.3).

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Looks swell to me.  But great, now Travis is giving ICEs on Android building MIPSTables, in addition to the outdated NDK.  Ugh.

-[Unknown]

**Comment by hrydgard** [comment]
@unknownbrackets , you think it's running out of memory? can you decrease compiler parallelism further or something?

**Comment by unknownbrackets** [comment]
Yes, definitely.  We're running `./ab.sh -j2` now (da6375d89d35aff27b13651c9921a4f0526efc19) so I guess that means `-j1`...

-[Unknown]

**Comment by hrydgard** [comment]
Alright, I'll merge this as is anyway. Feel free to single thread the travis build.. rather sad, heh.

**Pull request merged**
