### PR TITLE
Plug some Vulkan leaks

### PR DESCRIPTION
**Pull request by unknownbrackets**
Now shuts down clean with validation enabled, at least through UI and softgpu.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
FWIW, thin3d->DrawIndexed is definitely broken.  thin3d->Draw works fine.

-[Unknown]

**Comment by unknownbrackets** [comment]
Still not seeing where DrawIndexed is wrong, but I did find https://github.com/hrydgard/ppsspp/commit/5815b65db3c781d65261105929de7d6c330435f4... https://github.com/hrydgard/ppsspp/compare/master...unknownbrackets:vulkan-softgpu?expand=1

It didn't help/break anything, though...

I also tried aligning ibuf (since it's 12 bytes) just in case, but it didn't help...

-[Unknown]

**Comment by hrydgard** [comment]
Not seeing it either, weird...

**Comment by hrydgard** [comment]
Wait, I know what it is. In thin3d we use 32-bit indices, but DrawIndexed is drawing using 16-bit indices.

**Pull request merged**
