### PR TITLE
Add support Crc32 calc

### LINKED ISSUE #13964: Program CRC32 crash
I don't know what is wrong.
Please help.Thanks
Change:
https://github.com/sum2012/ppsspp/commit/a36907e68761eed2fc3c5f63f8b3f16ea909fa15

Crash:

edit,upload wrong picture

### PR DESCRIPTION
**Pull request by sum2012**
Fix #13964 

1588mb 51 second in windows 
Android not tested

Will test @unknownbrackets another method

### CODE REVIEW

**Comment by unknownbrackets** [comment]
This won't work for remote disc streaming of compressed ISOs (PBP/CSO) as is.

It might also cause ANRs on Android for large ISOs.  It'd be better to calculate the CRC32 in the background (like we do for reporting, but with some tweaks to not just wait.)  Reporting's current logic is just to make sure we calculate CRC32's at most once per ISO even from multiple other threads.

-[Unknown]

**Comment by unknownbrackets** [comment]
`init_crc32_tab` isn't defined on Linux/Android.  But again, you don't need this.  `zlib.h` already has a crc32().  We use it right here:

https://github.com/hrydgard/ppsspp/blob/master/Core/FileSystems/BlockDevices.cpp#L54-L65

This function already supports all formats, including ISO, PBP, CSO, etc. whether they are read from disk or over network, etc.  There's no need to start over.  And zlib already creates a crc32 table and initializes it in the right places.

You just need to include `Reporting.h` and then call `crcvalue = Reporting::RetrieveCRC(gamePath_);`.  This will be equivalent to what you have, except it will support CSO/PBP/network files.  Better would be to use `Reporting::HasCRC(gamePath_)` in `GameScreen::update()` after they click the button, and set `CRC32string` once `HasCRC()` returns true.

-[Unknown]

**Comment by sum2012** [comment]
This only test compile,do not mean merge

在 2021年1月26日週二 上午10:58，Unknown W. Brackets <notifications@github.com> 寫道：

**Comment by sum2012** [comment]
I have done convert to @unknownbrackets version.
But I check 1 day before pull another request

**Comment by sum2012** [comment]
@unknownbrackets method is 10 second much fast than my code.
Closing

**Pull request closed without merging**
