### PR TITLE
Display old render mode when load status

### PR DESCRIPTION
**Pull request by sum2012**
#7500

### CODE REVIEW

**Comment by Bigpet** [comment]
you need `extern u32 oldRenderingMode;` in the header and `u32 oldRenderingMode = 0;` in one *.cpp

**Comment by sum2012** [comment]
Thanks @Bigpet 
I need to do more test before commit

**Comment by sum2012** [comment]
@hrydgard This pull request is ready

**Comment by LunaMoo** [comment]
If you need that information for #7500, what if someone used for example read framebuffers to memory, his game got glitched by some memory corruption, he changed to buffered rendering, glitch was still there, so he made a savestate and sent it to you.
 In such situation this would if I understand correctly print the information that savestate was made in buffered rendering? That seems useless if not misleading, not to mention lots of other settings could cause issues.

**Comment by unknownbrackets** [comment]
This also isn't very useful to end users, it's a lot of UI for something 99% of people don't care about.

That's why I "hid" the feature in the checkbox of "enable compatibility reports".  We don't want reports for corrupted games anyway, so it makes sense there, but it's not very in-your-face so it doesn't confuse users.

-[Unknown]

**Comment by hrydgard** [comment]
Hm. This feature is indeed a bit strange, I think most users won't understand what the message means..

**Comment by sum2012** [comment]
How about add a checkbox like "enable compatibility reports" or just make a log ?

**Comment by unknownbrackets** [comment]
But, what's wrong with the current functionality of the disabled checkbox to find this out?

I mean, it also disables the checkbox if you use cheats, which can (and do) corrupt things.  It also disables the checkbox if you don't have the pgf font files (e.g. if you run the exe alone from a zip without extracting the other files.)  If the checkbox is greyed out, it means something is wrong and the game will probably not work correctly.

And this is already included in the savestate as necessary.  I don't think we need to add more to the savestate since we already have it?

-[Unknown]

**Comment by sum2012** [comment]
ok,I close this

**Pull request closed without merging**
