### PR TITLE
Wipe the volatile RAM when a dialog ends (hack for NBA Live 08)

### PR DESCRIPTION
**Pull request by hrydgard**
Unsafe hackfix attempt for NBA Live 08! 

See issue #8288

Please test.

### CODE REVIEW

**Comment by sum2012** [comment]
Yes ,fix NBA Live 08
I remember unknown made a  HLEHelperThread in Core\HLE\

**Comment by hrydgard** [comment]
Okay, cool. Yeah we have the mechanism to create fake threads for things like this, but it's a lot more work than this quick test.

Really not sure how safe this will be as-is with other games... But probably pretty safe? Needs more testing, anyway.

**Comment by sum2012** [comment]
Can we merge in v1.12 to test which game get effect ?

**Comment by hrydgard** [comment]
Yeah, or we'll fix it properly. I don't think I'm merging for 1.11. Maybe behind a compat.ini option...

**Comment by unknownbrackets** [comment]
I suspect that initstart locks volatile memory (is there a timeout?  does it fail or wait?) and unlocks it when done.  An open question is if unlocking it should generally clear it.

-[Unknown]

**Comment by shenweip** [comment]
If don't create a fake thread like JPCSP, I think a possible solution is to delay the state change until the dialog get the volatile memory lock.

**Comment by unknownbrackets** [comment]
Confirmed some things:

1. Locking/unlocking volatile does not clear the RAM.  Example: clear all volatile to 0xCC, unlock, lock again - and it's still all 0xCC.
2. Dialogs refuse to move from STATUS_INITIALIZE to STATUS_RUNNING until volatile memory is unlocked.
3. While volatile memory is unlocked, access causes an illegal address violation.
4. While the dialog is running, and until it's STATUS_NONE, volatile memory can't be locked.
5. After doing a MsgDialog, memory from 0x08400000 to 0x08600000 was modified.  Memory from 0x08600000 to 0x08700000 was untouched, and 0x08700000 to 0x08800000 was modified again.  Pockets of memory in the modified regions were unmodified (as verified by alternating the marker.)
6. Most of the RAM modified by MsgDialog was changed to values other than 0, such as 0x0000004D (lots of that for some reason.)  It's probably not necessary to replicate exactly the VRAM, though.

-[Unknown]

**Comment by unknownbrackets** [comment]
I think this can be closed, given #13943.

-[Unknown]

**Pull request closed without merging**
