### PR TITLE
Allow exporting previews in the GE debugger

### PR DESCRIPTION
**Pull request by unknownbrackets**
This works for the texture, partial framebuffer/depth/stencil, and even for the CLUT.

Convenient when trying to look at rendering midway at > 1x, etc.

-[Unknown]

### CODE REVIEW

**Comment by LunaMoo** [comment]
Nice.

 I'm thinking this could also be pretty useful for saving textures for replacement when just trying to get one or two to avoid dumping whole scene. Could address + clut hash + texture hash be written to log while exporting texture? Or GE debugger doesn't have all that information easily accessible?

**Comment by unknownbrackets** [comment]
Yeah - that's all in the texture code, but we could probably make it ask for it.

A separate option, "Copy replacement hash" that sends a debugger request through gpuDebug to the texture cache might be the best way... then it could safely use all the ini settings, etc. consistently.

Other things that might be nice to add:
 * Checkmark option to toggl highlight of prim preview i.e. "Show prim preview"
 * Actual size / fit toggle potentially (as alternative UI to double click) i.e. "Zoom to fit" / "Show actual size"
 * "Show in memory viewer"
 * "Add memory breakpoint" (mostly for framebuffers, could prefill size maybe...)

-[Unknown]

**Comment by hrydgard** [comment]
Neat. Another thing that might be nice in the future would be to change this ConvertBufferTo888RGB function to ConvertBufferTo8888RGBA, as we can easily store RGBA images in PNGs, at least, and it might be nice to be able to look at the alpha channel in high res, though of course a bit of an edge case.

**Comment by unknownbrackets** [comment]
Ah, of course.  That's easy to add.

-[Unknown]

**Pull request merged**
