### PR TITLE
Process rendered CLUTs on the GPU

### LINKED ISSUE #6754: Brave story - graphics glitches (debugged)
Hi, I found a few issues in brave story (hardware graphics) and debugged them to varying degrees.
In order of most to least simple to fix / likely to be fixed:

1) Smoke & fire are colored oddly with hardware graphics (also see https://github.com/hrydgard/ppsspp/issues/6332).
From debugging, it looks like the smoke primitives contain various color data and the GE's shademodel is set to GE_SHADE_FLAT.
The software renderer appears to check for the value of shademodel and ignore all but the first color in this case, resulting in the correct image.
However, it looks like no other renderers check shademodel, likely resulting in the colorful smoke.
This should be easy for a dev to fix, I think.   (NOW FIXED)

2) Enemy colors don't always differ in hardware graphics: (Notice color of right bunny in below screenshot in software vs hardware)
From debugging, it looks like brave story sets the framebuffer to the clut area (with inappropriate framebuffer height) and draws colors into it. It then uses the clut for drawing the texture.
In software, you can see that the clut area in memory gets updated between the first and second rabbit.
In hardware, you can see that the clut area in memory doesn't get updated in this case.
(I'm not sure how it's updated at all in hardware, to be honest)

3) With vertex cache set (which is the default), there is serious flickering in the worldmap. Perhaps vertex cache shouldn't be enabled by default until it's more reliable?

screens of bug 1 & 2:
Hardware:
hardware
Software: (no bug)
software

### PR DESCRIPTION
**Pull request by unknownbrackets**
Unfortunately, this is not ready for merge yet.  There are some issues.

Improvements:
- OpenGL and D3D9 upload indexed textures correctly.
- OpenGL and D3D9 properly processes CLUTs for regular textures - fixes #6754.

Not working:
- Rendered CLUT with rendered texture -> colors are totally wrong, but shape is right in the only testcase I have.

~~I debugged through D3D9 with debugging enabled, and couldn't find anything.  If I set the indexed texture, I get grey, so it does create that texture right.  But it always renders transparent black... even if I change the shader.~~

As for the OpenGL rendered issue (Kurohyou 2 demo), it flickers the wrong colors, which is really weird.  I'm thinking it's because I need to copy the framebuffer in LoadClut, e.g. maybe the game is drawing over it.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Hmm.  Using a temp FBO for the CLUT affects Kurohyou, but makes it worse (mostly just black.)  Also rachets down Brave Story's performance from ~620-650% to 550%...

-[Unknown]

**Comment by daniel229** [comment]
The shadows show up agains,but still not right in Heroes' VS.

**Comment by daniel229** [comment]
The weird shadows is missing in silent hill shattered memories.

**Comment by daniel229** [comment]
Almost 50% speed down under water in ikuze gen san

**Comment by daniel229** [comment]
FF Type 0 missing shadows.

**Comment by unknownbrackets** [comment]
Hmm.  Obviously I impacted render-to-texture in some way I did not intend.  Can you bisect?

-[Unknown]

**Comment by daniel229** [comment]
Heroes' VS， silent hill shattered memories， FF Type 0 are affected by https://github.com/unknownbrackets/ppsspp/commit/86fb081b4678b66f3a80011a126e2db9205e5e46

slow down in ikuze gen san is affected by https://github.com/unknownbrackets/ppsspp/commit/17675ca418d94ffd9a245889a00b6eece47a2ce8

**Comment by daniel229** [comment]
White screen, even slow and memory leaking in Sonic rivals 2,up to 2GB ram usage and increasing.
Also affected by https://github.com/unknownbrackets/ppsspp/commit/86fb081b4678b66f3a80011a126e2db9205e5e46 and https://github.com/unknownbrackets/ppsspp/commit/17675ca418d94ffd9a245889a00b6eece47a2ce8

**Comment by unknownbrackets** [comment]
Duh, I didn't consider that obviously `clutRenderAddress_` could be `0` if I set it to `fb_address`.  Arg.

-[Unknown]

**Comment by unknownbrackets** [comment]
That fixes that problem, I think, but not any of the problems listed in the first post...

-[Unknown]

**Comment by daniel229** [comment]
Still memory leaking.

**Comment by unknownbrackets** [comment]
Oops, see it now.  Should be fixed as well.

-[Unknown]

**Comment by daniel229** [comment]
Yeah,memory leak is fixed.
another games Burnout Dominator gets red artifact.


```
59:14:273 idle0        I[G3D]: GLES\ShaderManager.cpp:153 Linked shader: vs 91 fs 92
59:17:512 idle0        W[G3D]: Common\FramebufferCommon.cpp:781 Block transfer download 04000000 -> 04170000
59:17:518 idle0        I[G3D]: GLES\ShaderManager.cpp:153 Linked shader: vs 16 fs 94
59:17:520 idle0        I[SCEGE]: GLES\Framebuffer.cpp:682 Resizing FBO for 00000000 : 512 x 272 x 3
59:17:523 idle0        I[G3D]: GLES\ShaderManager.cpp:153 Linked shader: vs 42 fs 96
59:17:524 idle0        W[G3D]: Common\FramebufferCommon.cpp:830 Block transfer upload 04170000 -> 04000000
59:17:526 idle0        W[G3D]: GLES\TextureCache.cpp:331 Render to texture with different formats 3 != 0
59:17:526 idle0        I[SCEGE]: Common\FramebufferCommon.cpp:417 Creating FBO for 00176000 : 512 x 272 x 0
59:17:527 idle0        E[G3D]: GLES\TextureCache.cpp:389 4 and 8-bit CLUT format not supported for framebuffers
59:17:527 idle0        W[G3D]: GLES\TextureCache.cpp:405 Render to texture with incompatible formats 5 != 3 at 00000000
59:17:527 idle0        W[G3D]: GLES\StateMapping.cpp:318 Unsupported RGB mask: r=ff g=1f b=07
59:17:552 idle0        I[SCEGE]: GLES\Framebuffer.cpp:682 Resizing FBO for 00088000 : 512 x 272 x 3
59:17:744 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1885 Decimating FBO for 00000000 (480 x 272 x 3), age 6
59:17:777 idle0        I[SCEGE]: GLES\Framebuffer.cpp:1885 Decimating FBO for 00088000 (480 x 272 x 3), age 6
59:18:317 idle0        I[G3D]: GLES\ShaderManager.cpp:153 Linked shader: vs 16 fs 101
```

**Comment by unknownbrackets** [comment]
Does it improve if you change this:

```c++
		} else if (entry->format == GE_TFMT_CLUT8 || entry->format == GE_TFMT_CLUT4) {
			ERROR_LOG_REPORT_ONCE(fourEightBit, G3D, "4 and 8-bit CLUT format not supported for framebuffers");
		}
```

To:

```c++
		} else if (entry->format == GE_TFMT_CLUT8 || entry->format == GE_TFMT_CLUT4) {
			ERROR_LOG_REPORT_ONCE(fourEightBit, G3D, "4 and 8-bit CLUT format not supported for framebuffers");
			return;
		}
```

I wonder if this is trying to use 4/8 bit...

-[Unknown]

**Comment by daniel229** [comment]
Yes, the glitch is gone.

**Comment by unknownbrackets** [comment]
In the last commit in TextureCache.cpp, what if you change:

```c++
		VirtualFramebuffer *clutVfb = nullptr;
		for (size_t i = 0, n = fbCache_.size(); i < n; ++i) {
			auto clutFramebuffer = fbCache_[i];
			if (clutFramebuffer->fb_address == clutRenderAddress_) {
				clutVfb = clutFramebuffer;
			}
		}
```

To:
```c++
		VirtualFramebuffer *clutVfb = nullptr;
		for (size_t i = 0, n = fbCache_.size(); i < n; ++i) {
			auto clutFramebuffer = fbCache_[i];
			if (clutFramebuffer->fb_address == clutRenderAddress_ && clutFramebuffer->drawnFormat == clutFormat) {
				clutVfb = clutFramebuffer;
			}
		}
```

-[Unknown]

**Comment by daniel229** [comment]
Still no change.

**Comment by unknownbrackets** [comment]
Rebased.  Now it works just as well and just as badly in Direct3D 9, I think.

It still doesn't work correctly for render-to-texture using a rendered CLUT.

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, it still doesn't work, but now I know for sure why.

The issue with Kurohyou is that it DRAWS the palette using fmt=565, but uses it as 8888.  Possibly this was mainly to be able to "draw" the alpha bits.

When we download and then create a texture from that, this works swimmingly, because we create the texture in the right format.

But when we render from the FBO, we don't convert the 565 bits into 8888 bits and halve the width.  So the colors are all completely wrong.

At this point, I feel like forgetting about doing it on the GPU, and just leaving it to #8389.  Maybe the indexing can be used for more efficient upload of textures to the GPU, but it's hard to detect when the palette thing will be a problem - so we will have to still readback the CLUT framebuffer, and lose most of the performance benefit of this approach.

That being said, #8389 is not universal so I haven't given up just yet.

The following games have been reported as using rendered CLUTs:

Broken / shenanigans:
 * Kurohyou (probably)
 * Kurohyou 2

Working:
 * Brave Story

Not tested
 * Tales of Rebirth (don't know where)
 * RIDGE RACER (don't know where)
 * BURNOUT DOMINATOR
 * Need for Speed™ Shift
 * Gallery Fake
 * ATV Offroad Fury® Pro
 * Harukanaru Toki no Naka de Hachiyō Shō
 * Harukanaru Toki no Naka de 5
 * Rockman DASH 2

-[Unknown]

**Comment by daniel229** [comment]
Those are broken,not sure about other.
BURNOUT DOMINATOR (probably broken / shenanigans)
ATV Offroad Fury® Pro
Harukanaru Toki no Naka de Hachiyō Shō
Harukanaru Toki no Naka de 5 

Black box on the text


balck color on the text


missing text

**Comment by daniel229** [comment]
Kurohyou also broken

**Comment by daniel229** [comment]
FF4 Saving dialog broken.

**Comment by unknownbrackets** [comment]
FF4 is just weird.  It's reusing the drawn white background as a CLUT for a single-color texture (and interpolating based on vertex colors), afaict?  I'm not sure what's going wrong with this, but it might again be a format conversion thing.

Are all of these fine with current master?  FF4 is.

-[Unknown]

**Comment by daniel229** [comment]
Yes,looks fine with current master.

**Comment by hrydgard** [comment]
@unknownbrackets  maybe the game is just drawing the palette to that memory normally using the CPU and using it ... it just happens to be the same memory it just used for a framebuffer, so no readback necessary, although perhaps hard to tell...

**Comment by daniel229** [comment]
Gallery Fake not fine with current master,the brown color is correct.

**Comment by hrydgard** [comment]
This one will be nasty to rebase :)

**Comment by unknownbrackets** [comment]
Yeah, I'll look at it later.  I guess it might end up being faster on Vulkan?

-[Unknown]

**Comment by hrydgard** [comment]
This is cool stuff which should be implemented, but by now this pull has a ton of conflicts so can't be easily merged. Close or rebase?

**Comment by hrydgard** [comment]
Oops I just commented recently heh. Going through these old pulls a bit too quickly.

**Comment by hrydgard** [comment]
Depends on how it's implemented but I'm sure it's possible to get it to perform well.

**Review by finansar222 — APPROVED** [review]
/ *สร้าง hash แบบเดียวโดยใช้ข้อมูลและโหมดที่ระบุ
   ข้อมูลและข้อมูลที่สอดคล้องกันต้องเป็นทวีคูณของ 0x10
   cryptkey เป็น NULL สำหรับ savedata * /
int  build_hash ( unsigned  char * output,
	       unsigned  char * data,
	       unsigned  int len,
	       unsigned  int alignedLen,
	       โหมดint ,
	       unsigned  char * cryptkey)

**Review by finansar222 — CHANGES_REQUESTED** [review]
/ *สร้าง hash แบบเดียวโดยใช้ข้อมูลและโหมดที่ระบุ
   ข้อมูลและข้อมูลที่สอดคล้องกันต้องเป็นทวีคูณของ 0x10
   cryptkey เป็น NULL สำหรับ savedata * /
int  build_hash ( unsigned  char * output,
	       unsigned  char * data,
	       unsigned  int len,
	       unsigned  int alignedLen,
	       โหมดint ,
	       unsigned  char * cryptkey)

**Comment by AkagiShiroe** [comment]
does this fix SD Gundam Generation Overworld Texture replacement issue? the game create random hash except the CLUT (example 00000000b4fc5ab800000000, that 00000000 are constantly randomized everytimes making huge texture replacement have slowdown and stutter loading), the problem is.. the texture hash will change everytime the texture used (only CLUT remain same) and dumped texture aren't perfect (there's slight error in here and there)..

**Comment by marosis** [comment]
Sorry for asking, but why isn't still merged

**Comment by Gamemulatorer** [comment]
This pr can help burnout dominator and brave story lag issue?

**Comment by hrydgard** [comment]
It can help some things yes (though I don't think Burnout is one of them), but it had issues and is now very old - it'll need quite some work to bring it up to date so it can be merged.

**Comment by unknownbrackets** [comment]
I think if anything the approach will change significantly.  I'm going to finally close this.

-[Unknown]

**Pull request closed without merging**
