### PR TITLE
iOS/macOS : set bundle version

### PR DESCRIPTION
**Pull request by Florin9doi**
Screenshot 2020-04-30 at 20 00 34
Screenshot 2020-04-30 at 20 19 59

beforeafter

### CODE REVIEW

**Comment by hrydgard** [comment]
Looks great, weird errors on CI though. Maybe need to add something to the travis script to install something?

**Comment by unknownbrackets** [comment]
```
char: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “char” couldn’t be opened because there is no such file." UserInfo={NSFilePath=char, NSUnderlyingError=0x7faf8f40bec0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
```

Seems like a parsing issue, where it's keeping `char` as part of the command line argument.

-[Unknown]

**Comment by Florin9doi** [comment]
The errors are comes from de by plutil becuase it receives too many parameters, 

```
plutil -replace CFBundleVersion -string xx yyy Release-iphonesimulator/PPSSPP.app/Info.plist

yyy: file does not exist or is not readable or is not a regular file (Error Domain=NSCocoaErrorDomain Code=260 "The file “yyy” couldn’t be opened because there is no such file." UserInfo={NSFilePath=yyy, NSUnderlyingError=0x7f8849707330 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}})
```

**Comment by Florin9doi** [comment]
`const char *PPSSPP_GIT_VERSION = "a8fc080";`
travis does not fetch the tags?

**Comment by unknownbrackets** [comment]
Ah, it probably doesn't.  Can add `git fetch origin --tags` here most likely:
https://github.com/hrydgard/ppsspp/blob/f82e7a4e7b5670cd80c7debcbb45441609fceefc/.travis.sh#L33

-[Unknown]

**Pull request merged**
