### PR TITLE
Add Simple highlight in Savedata Manager

### PR DESCRIPTION
**Pull request by zminhquanz**
I implement about this , but i don't know how to implement pic1 in save data direction to show on background
Like this on real PSP
snap000

### CODE REVIEW

**Comment by xiushudongfang** [comment]
Maybe #9501 is a good reference.

**Comment by zminhquanz** [comment]
@xiushudongfang i didn't mention about that , i want to implement savedata manager to show in background like picture on above , not choose another picture custom background

**Comment by xiushudongfang** [comment]
I mean that it is a reference.

**Comment by zminhquanz** [comment]
I closed this because i need to more time to read this code

**Pull request closed without merging**
