### PR TITLE
Update NativeActivity.java

### PR DESCRIPTION
**Pull request by sails**
fix javaGL bug

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Thanks, dumb mistake.  Been a while since I used Java, totally forgot about compares.... obviously I didn't log enough when I tested before.

@hrydgard checking briefly, `if (Build.MANUFACTURER == "OUYA") {` seems potentially suspicious?

-[Unknown]

**Comment by hrydgard** [comment]
Hm, yes indeed...

**Comment by unknownbrackets** [comment]
Is it possible that check doesn't work?  Should we change it?  I don't have an Ouya.

-[Unknown]

**Comment by hrydgard** [comment]
Very possible, would explain why it didn't improve color quality the way I expected it to, IIRC. Though, they Ouya in general is pretty much dead. Mine works though so might get around to it someday...

**Pull request merged**
