### PR TITLE
Add an option to ignore gamepads when not focused

### PR DESCRIPTION
**Pull request by unknownbrackets**
Personally, I greatly prefer it allowing it while not focused, but this way people can pick.

Not sure if "Ignore gamepads when not focused" is the best or clearest wording...

Windows only for now since I don't want to mess with Qt/etc.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Okay, I made it so that it doesn't even process mouse clicks outside the window.  I think it's weird to process a mouse click on another window, especially the right mouse button.

-[Unknown]

**Comment by sum2012** [comment]
The pull request is good.
I just say that I feel.
I think that make translate thing of code of people should change(or pull request) responsibility in en_US.ini

**Comment by vsub** [comment]
Thanks,I was waiting for that option for a long time(It was really annoying that ppsspp will accept controls when I pause the game and try to use the gamepad on another emulator or a game...the only way to avoid ppsspp to receive gamepad inputs was to pause the emulation(not go to the pause screen))

**Comment by hrydgard** [comment]
@sum2012 , yeah, that's reasonable.

**Pull request merged**
