### PR TITLE
Show warning when PPSSPP is saving to a temp directory

### LINKED ISSUE #11114: Detect when PPSSPP is running inside a temp folder
https://forums.ppsspp.org/showthread.php?tid=24383

I'm making an assumption, but a mistake users sometimes make is running an executable file from a zip.  Compression programs will create a folder inside Temp, run the program, and then delete once you exit.  Users may not understand why their saves and settings are "lost".

Ideally we should either show a message to the user (so they know their saves will be lost), or else just use the My Documents/PPSSPP approach.

-[Unknown]

### PR DESCRIPTION
**Pull request by unknownbrackets**
PPSSPP saving in temporary storage warning

This makes the assumption in the message that it's caused by a compressed folder.  Open to suggestions for better wording.

Fixes #11114.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
@hrydgard opinions?  Too heavy handed?

-[Unknown]

**Comment by hrydgard** [comment]
It's more that I'm thinking of making this even more heavy handed, even preventing use entirely within a temp directory.

**Comment by unknownbrackets** [comment]
Hmm.  I could easily imagine someone testing a dozen git builds to trace down an issue, using a temp folder each time (intentionally) to ensure they have clean settings.

I'd say PPSSPP should let you do it as long as you have the opportunity to know something might be wrong.

-[Unknown]

**Comment by hrydgard** [comment]
Oh yeah, I didn't think about that use case. Let's go for it.

**Pull request merged**
