### PR TITLE
Correct universally for clamped depth range

### LINKED ISSUE #1788: [Graphics, OGL && D3D] [Phantasy Star Portable 2 US][x64] Draw distance, draw priority bugs, and transparency.
In Phantasy Star Portable 2 US there's a few bugs but they don't appear everywhere. First the one cutting the feet of the characters when camera is default.
image

When camera looks downwards the whole body is cut off.
image

When camera looks upwards the whole body is showing.
image

Also if you look closely, not only the body is cut off, but parts of the background too, light-like effects and transparent hologram-like screen don't show on default and downwards camera. And the door appears sometimes and sometimes it doesn't.

When in complete upwards looking camera position everything is displayed (it seems) but as soon as you move the camera just an inch up a lot of the background disappears.

---

Some Background Objects only appear when close to them  which is wrong. (notice the bug in the font, the "i" are too thin, and spacing is wrong)
image
image

---

Also, photon weapons should be tranparent but they're not, they're also missing their glow (you know the glow that hovered over the characters quite a few revisions back)
Also weapons are not drawn correctly when a character is behind.
image

---

There are no errors in Debug Log, except the issue I mentioned there : https://github.com/hrydgard/ppsspp/issues/1785

Get this fixed and a lot of the game will be playable as now as of 0.7.6 - 547 there are character portraits and game is running pretty well, and I CAN LOAD MY PSP CHARACTERS FINE !!

### PR DESCRIPTION
**Pull request by unknownbrackets**
Fixes #1788.  This really can just be seen as a minor extension to @level99procrastinator's work to make it work everywhere.

I don't have any of the games noted as broken in #7069, but I didn't find any games broken by these changes.  That being said, this probably needs testing especially for depth-rounding related changes.

I know for sure that Phantasy Star Portable 1 and Phantasy Star Portable 2 work fine, including the text.  I also went through several other games to make sure depth in general was working okay.

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
Looks good,Phantasy Star Portable 2 (JP) flickering with DepthRounding enable though.

**Comment by daniel229** [comment]
Seems like it broke the back ground in Danbal Senki W

**Comment by daniel229** [comment]
something change in https://github.com/hrydgard/ppsspp/issues/7223
The tree seems correct,background is flickering.

**Comment by daniel229** [comment]
breaks Sonic Rivals 2,the screen just stay there.


before

**Comment by unknownbrackets** [comment]
I made a couple dumb mistakes, which I just fixed.  D'oh.  Thanks for checking.

Also, I corrected an issue in depth rounding that may prevent flicker, potentially.  Not sure, though.

-[Unknown]

**Comment by daniel229** [comment]
Phantasy Star Portable 2 (JP) is still flickering with DepthRounding enable
Sonic Rivals 2 seems fine.
https://github.com/hrydgard/ppsspp/issues/7223 also get a little change
Danball Senki W background is back, but missing outlines.

**Comment by daniel229** [comment]
Boku no Natsuyasumi 4 is also broken



before

**Comment by unknownbrackets** [comment]
Hmm.  Sometimes the z is going outside the [-1, 1] range when the depth value is saturated.  Maybe I'm wrong about the rounding...

-[Unknown]

**Comment by unknownbrackets** [comment]
I pulled out 7d01f9b1e0916a2788c1a37cf51d84e9326a2448... although I'm not sure it's wrong.  In Direct3D 9, without it, I get wrong depth values.

-[Unknown]

**Comment by daniel229** [comment]
Danball Senki W and Boku no Natsuyasumi 4 look fine now.

**Comment by unknownbrackets** [comment]
Was Phantasy Star Portable 2 (JP) not flickering with the old hack?  Does it flicker also with PixelDepthRounding?

The US version doesn't seem to flicker... hmm.

-[Unknown]

**Comment by daniel229** [comment]
old hack is the same,seems to work fine with PixelDepthRounding.Phantasy Star Portable 2 (US) 's text is fine without DepthRounding,Phantasy Star Portable 2 (JP) isn't.

**Comment by unknownbrackets** [comment]
Ahh, I see.  So this is still a strict improvement from before, but it's still not fixing that...

Well, we could mark the JP ones to use pixel depth rounding - although it doesn't help GLES2.  Do you know if this happens with Infinity as well?  Unfortunately it seems like the demo for Phantasy Star Portable 2 Japan is no longer available... (「公式サイトからのダウンロードは終了しました。」)

I wonder why it's flickering, though... it might be that a slight offset would help.  I suspect the PSP may actually round up at 0.625.

-[Unknown]

**Comment by daniel229** [comment]
Infinity looks good with NoDepthRounding.

**Comment by hrydgard** [comment]
Heh, the three overage calculations are so similar that it might even be possible to do them together with SIMD. But dirty flags is probably an easier solution to the problem of our ever growing state translation calculations...

**Pull request merged**
