### PR TITLE
Analog Testing Display Fix

### PR DESCRIPTION
**Pull request by cabral450**
For analog testing the Y axis always went in the opposite direction now it goes in the right direction, unless the Y axis was meant to be backwards?

### CODE REVIEW

**Comment by hrydgard** [comment]
Actually, it depends. Some joysticks do go the other way and look correct - we display the input before mapping. Which maybe should be changed, though...

**Comment by hrydgard** [comment]
@Roceso1337 Hm, was looking at this again and it looks like something called "Darkfrost" was pushed in, can you explain what that is?

**Comment by vnctdj** [comment]
It looks like this is a cheating plug-in...
This as nothing to do with analog testing, and I don't think we need this as we already have cheating support...

**Comment by LunaMoo** [comment]
Yeah I second vnctdj opinion.
 Our current cheat engine is not a clone of any of the existing plugin and can expanded if someone needs more stuff(and does it without braking existing features). It supports only cwc format since that was most common/popular one out there which most plugins supported, but they all really do the same thing and would suffer from same problems ~ memory allocation issues with ppsspp which is primary reason people tend to think our cheat engine sucks and plugins would solve it.

 And this ~ with the name and logo looks like a plugin advertisement inside emulator heh.

**Comment by unknownbrackets** [comment]
I think this person posted on the forum about their CFW plugin.  Most likely they made additional commits to the same branch after issuing this pull and didn't realize it would update it automagically.

I feel like GitHub should more aggressively message that feature to new GitHub users after they open their first pull request.  I frequently see people who have no idea GitHub pull requests update.

-[Unknown]

**Pull request closed without merging**
