### PR TITLE
[iOS Port] Add logo in Launch Screen.storyboard

### PR DESCRIPTION
**Pull request by mygizli04**
Hey! I'm a beginner so please don't judge me too hard and tell me if i made any mistakes. This is a small one but it really annoyed me. The difference is minor ( [this](https://youtu.be/CaqCVi0Oa5o) vs [this](https://youtu.be/mhnx0ilUo8c) ) but it still annoyed me. Thanks in advance!

### CODE REVIEW

**Comment by mygizli04** [comment]
Also i couldn't find a logo file anywhere? If someone can tell me where it is i'll change it

**Comment by hrydgard** [comment]
Hi!

My only hesitation about this is the increase in toolsVersion version required, but I have no idea if that would actually cause any issue for anyone. If that's not likely to be a problem, I'm fine with this.

**Comment by mygizli04** [comment]
It shouldn't be a problem, since the minimum required XCode version is still 8.0. That's just beacuse i edited it with a newer version of XCode.

**Comment by unknownbrackets** [comment]
Just a note: I've been told that the Apple recommended approach for launch screens is to avoid text (for translation reasons) and try to match the UI that will eventually show, so that text appears to fade in once the app has loaded.

The logo normally used, fwiw, is in assets/ui_atlas.zim.  It's probably hard to access there, but the source parts are source_assets/image/logo.png and source_assets/image/icon_regular_72.png.  The zim is a sprite sheet built via atlasscript.txt.

Not suggesting anything needs to change here, just answering questions.

-[Unknown]

**Pull request merged**
