### PR TITLE
[UI] Minor changes to PRO ad hoc server IP address selection

### PR DESCRIPTION
**Pull request by anr2me**
- Added `psp.gameplayer.club` public adhoc server, as it have been at `#multiplayer-adhoc` channel's pinned message since 2019
- Updated IP selection UI to get a better view on Window Size 2x

Before:
image image

After:
image image

### CODE REVIEW

**Review by hrydgard — APPROVED** [review]

**Comment by unknownbrackets** [comment]
The downside of GONE at the higher resolutions is that things might move right as you're tapping them, which is a disorienting experience on touch based UIs.

-[Unknown]

**Comment by ANR2ME** [comment]
Is there anyway to make the progressView to be absolute, aligned to the bottom of the scrollView? so the scrollBar won't changed height when the message appeared

**Comment by unknownbrackets** [comment]
It could be put in an anchor on the root or something.  I think it's probably not too bad here, just wanted to mention the general thing for other UI.

-[Unknown]

**Comment by hrydgard** [comment]
To get even more space here we could also just remove the title bar from this dialog. And we might want to revisit spacing and scale a bit eventually...

**Pull request merged**
