### PR TITLE
Update framebuffer from memory when game manipulate framebuffer in memory(Open Season).

### LINKED ISSUE #13252: Open Season Title Screen does not display
The crashing issue of this game i've mentioned in #10972 is now fixed in latest build leading this game is now playable on PPSSPP.

But i have a problem the title screen does not display.

PPSSPP:
Screenshot_2020-08-06-02-34-50-61_2f85358b2198d26f8aca533d68bee793
PSP:
IMG_20200806_024113

### PR DESCRIPTION
**Pull request by shenweip**
This will fix #13252 .Some games may write directly to PSP VRAM to update the framebuffer, but the virtual framebuffer will not be updated. Maybe the right thing to do is to use PSP VRAM instead of virtual framebuffers, but may need some refactoring.

### CODE REVIEW

**Comment by shenweip** [comment]
@unknownbrackets The game seems to use this function to decode data, and it will call multiple times to complete the decoding. I agree that managing the flag for each games is unsatisfactory, is it better now?

**Comment by sum2012** [comment]
@hrydgard @unknownbrackets how about this now ?

**Comment by unknownbrackets** [comment]
What's this func look like that you need to ignore some `jr ra`s?

-[Unknown]

**Comment by shenweip** [comment]
It look like:
0x00000000&emsp;addiu sp,sp -0x380(func entry)
&emsp;&emsp;⋮&emsp;&emsp;&emsp;&emsp;&emsp;⋮
0x00000010&emsp;jal 0x00000040
&emsp;&emsp;⋮&emsp;&emsp;&emsp;&emsp;&emsp;⋮
0x00000020&emsp;jal 0x00000060
&emsp;&emsp;⋮&emsp;&emsp;&emsp;&emsp;&emsp;⋮
0x00000030&emsp;jal ra
0x00000034&emsp;addiu sp,sp 0x380(real func exit)
&emsp;&emsp;⋮&emsp;&emsp;&emsp;&emsp;&emsp;⋮
0x00000040&emsp;???????????????
&emsp;&emsp;⋮&emsp;&emsp;&emsp;&emsp;&emsp;⋮
0x00000050&emsp;jr ra(not real func exit)
&emsp;&emsp;⋮&emsp;&emsp;&emsp;&emsp;&emsp;⋮
0x00000060&emsp;???????????????
&emsp;&emsp;⋮&emsp;&emsp;&emsp;&emsp;&emsp;⋮
0x00000070&emsp;jr ra(not real func exit)

**Comment by unknownbrackets** [comment]
But are those separate functions that we're just misdetecting as part of the function, or are they actually other valid exits?

I'm worried that we might break an existing hook with this, since I remember at least one being a func that legitimately had two exits.  But it's probably just that one and I think it was a leaf (no add sp.)

-[Unknown]

**Comment by shenweip** [comment]
I think those aren't separate functions because some of them are located in front of the exit. Um... do you mean having a func that pushes stack(has add sp) at the start of func but not pop stack(no add sp) at the exit? This is interesting, it seems likely to break the stack frame?

**Comment by unknownbrackets** [comment]
No, I've seen cases where it does the add sp out of order when it has two exits.  It's very uncommon, I just don't know if any of these hooked functions do it.  I'm most worried about the simd optimized memcpys, but I think they are okay.  It's likely not an issue.

-[Unknown]

**Comment by shenweip** [comment]
Got it, so let's specify func exit in this case for the compatibility.

**Comment by sum2012** [comment]
@hrydgard how about this? ( allthough change need rebase)

**Comment by sum2012** [comment]
@hrydgard how about this? ( although change need rebase)

**Comment by unknownbrackets** [comment]
Is this function called in a loop, or is it called separately?  Wondering if we could combine into one upload.

Also, rather than a new method on GPUCommon and using UpdateFromMemory, I recommend using `gpu->PerformMemoryUpload(...);`.  The only trouble is that it'll want the transfer to be aligned to the framebuffer stride.

Perhaps we could just do something like...

```c++
static int Hook_openseason_data_decode() {
	static u32 firstWritePtr = 0;

	u32 curWritePtr = currentMIPS->r[MIPS_REG_A0];
	u32 endPtr = currentMIPS->r[MIPS_REG_A1];
	u32 writeBytes = currentMIPS->r[MIPS_REG_V0];
	u32 startPtr = curWritePtr - writeBytes;
	if (Memory::IsVRAMAdress(startPtr) && (firstWritePtr == 0 || startPtr < firstWritePtr)) {
		firstWritePtr = startPtr;
	}
	if (Memory::IsVRAMAdress(endPtr) && curWritePtr == endPtr) {
		gpu->PerformMemoryUpload(firstWritePtr, endPtr - firstWritePtr);
		firstWritePtr = 0;
	}
	return 0;
}
```

That would combine it into one upload, which should perform much better.  Would that work?

We wouldn't need to change any files other than Core/MIPS/MIPSAnalyst.cpp and Core/HLE/ReplaceTables.cpp this way either.  No need to add extra methods when we already have code to do this for other games.

-[Unknown]

**Comment by sum2012** [comment]
@unknownbrackets I don't understand what your last said.Can you make another pull request for me to test ? Thanks.

**Comment by sum2012** [comment]
Finally I figure that what is the @unknownbrackets chnage,
I will open another pull request

**Comment by hrydgard** [comment]
Closing in favor of #14192 .

**Pull request closed without merging**
