### PR TITLE
Cleanup some Vulkan bug checks

### PR DESCRIPTION
**Pull request by unknownbrackets**
This makes it so more respect the ini setting and also stops working around the bug on newer drivers (as a reminder, it affects both drawing and stencil upload.)

I think COLORWRITEMASK_BROKEN_WITH_DEPTHTEST may have not been present on Adreno 6xx but can't currently confirm.

It might be nice to cleanup the Intel check, but I'm not sure a super clear place to validate.  It didn't seem like dual source blending was broken on my driver...

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm, I wonder if g_Config.bVendorBugChecksEnabled = false should simply automatically make all bug checks return false instead..

**Comment by hrydgard** [comment]
Heh, I see now that you intended this for v1.11, but I think it's okay for 1.10.

**Comment by unknownbrackets** [comment]
I thought about that, but some of the bug checks seemed more severe so I wasn't sure if we still wanted them separate.  And was trying to keep g_Config out of Draw.

-[Unknown]

**Comment by hrydgard** [comment]
Does make sense to keep g_Config out of draw, but we could also have it as a setting on Draw that's controlled by the g_Config setting. 

But yeah, let's revisit later.

**Pull request merged**
