### PR TITLE
Improve UI space for different translation a bit.

### LINKED ISSUE #14913: [Translate][Appearance] Some text box width is not enuogh space for Japanese translation.
### What should happen

Some text box is not enough space for Japanese.
It should be shrink the text automatically or change to more wide.

example) In Edit touch control layout...
image

example) In Control mapping
image

example) In Gesture mapping
image

Very unshapely.:weary:

### Who would this benefit

All Japanese　user.

### Platform (if relevant)

_No response_

### Games this would be useful in

All

### Other emulators or software with a similar feature

_No response_

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

### PR DESCRIPTION
**Pull request by iota97**
While a general solution would be great I'm not really sure how without having to redo/recheck most of our UI screen.

For now:
- Increase column width for gesture mapping and touch control layout
- Make control binding wave when too long
- Wrap text in analog calibration

Fixes #14913, didn't touch #14522 tho' as I'm having trouble reproducing all but the chat one there (probably different font or something?)

Just to be sure is this the correct translation, it seem really long compared to english "calibrated"? @nassau-tk
Screenshot_2021-09-24_11-12-34

Nit: that wrap on the bracket hurt :P

### CODE REVIEW

**Comment by unknownbrackets** [comment]
I feel like we should make the control mapping rows a bit taller (increase itemH...)  IMHO it's really distracting when a button I don't even care about starts animating back and forth.  I feel like I'm on a crappy website from 20 years ago with gifs everywhere whenever I see it.  So I'd hope we can avoid it where possible.

It'd probably be tricky to make the rows size to the height, but that'd be best.  The tricky thing would be resizing the first row of buttons on the right to match so it doesn't look weird.  I think we'd have to implement a custom Measure...

-[Unknown]

**Comment by nassau-tk** [comment]
@iota97 
uuuum...
51% Japanese can't understand "ENGLISH". 
48% Japanese will feel "ENGLISH".
1% Japanese can understanding or searching English.

I translated for 51% people. :grin:
So, probably. I can make more short sentence. 
Like bellow.
キャリブレーション（調整）された動作
→調整後の動作

But, Some translation are can't do that.
Because, They are just word.  Not sentence.
exa)　Grid　→　グリッド
This word appear like below......

グリッ
ド

oh...

When a new paragraph can be started optionally, it can be avoided by adjusting the height.
But that isn't made, so I think whether a margin is reserved has no choice but to do the size small.

**Comment by unknownbrackets** [comment]
I think we could add an explicit newline for the calibrated case if we want to keep the full text.

-[Unknown]

**Comment by iota97** [comment]
Removed the sine animation and increased the item height a bit so its still fine when it get displayed in 2 lines.

**Review by unknownbrackets — APPROVED** [review]

**Pull request merged**
