### PR TITLE
Rebased adhoc by ANR2ME

### PR DESCRIPTION
**Pull request by hrydgard**
This is pretty much https://github.com/hrydgard/ppsspp/pull/6749 , but rebased into a linear sequence on top of master, so easier to bisect etc.

This still has the issue that it does an illegal mipscall from the wrong thread, but I will fix that in master (using some work Bigpet did earlier), because it's much easier to get master builds tested.

Before merging this, can someone who plays a lot of adhoc confirm that this is actually working as well as the other branch?

@sum2012

### CODE REVIEW

**Comment by unknownbrackets** [comment]
```c++
static u32 sceNetAdhocctlInit(int stackSize, int prio, u32 productAddr) {
	INFO_LOG(SCENET, "sceNetAdhocctlInit(%i, %i, %08x) at %08x", stackSize, prio, productAddr, currentMIPS->pc);
	/*if (!g_Config.bEnableWlan) {
		// Pretend success but don't actually start the friendfinder thread and stuff.
		// Dunno if this is the way to go...
		netAdhocctlInited = true;
		return 0; //Faking success to prevent GTA:VCS stuck in Host/Join screen
	}*/
	
	if (netAdhocctlInited) return ERROR_NET_ADHOCCTL_ALREADY_INITIALIZED;
	
	if(g_Config.bEnableWlan)
	{
		if (initNetwork((SceNetAdhocctlAdhocId *)Memory::GetPointer(productAddr)) != 0) WARN_LOG(SCENET, "sceNetAdhocctlInit: Faking success");

		if (!friendFinderRunning) {
			friendFinderRunning = true;
			friendFinderThread = std::thread(friendFinder);
		}

	}
	netAdhocctlInited = true; //needed for cleanup during AdhocctlTerm even when it failed to connect to Adhoc Server (since it's being faked as success)
	return 0;
}
```

We either need another flag or to not set `netAdhocctlInited` to true if `initNetwork` fails.  We really should probably return an error code, if this is the correct place to actually attempt to connect (is it?)

Also, in that case, we can't start `friendFinderThread` because we'll crash on SIGPIPEs, unless we add checks there and etc.

But, I'm not really sure, should it block the cpu on connect?  I somehow doubt the PSP does that.  Probably only blocks the thread.

-[Unknown]

**Comment by sum2012** [comment]
I compile windows build for other test first.

windows 32 bit build:
https://drive.google.com/file/d/0B3OaSdeV0L8kNTZnMFJXUm1Wa2s/view?usp=sharing
windows 64 bit build:
https://drive.google.com/file/d/0B3OaSdeV0L8kSjFnQ2JxN0hoeVU/view?usp=sharing

**Comment by sum2012** [comment]
I tested Metal Slug XX and Virtua Tennis 3 work

**Comment by tywald** [comment]
Looks like it fixed <a href=https://github.com/hrydgard/ppsspp/issues/7237>#7237</a>

**Comment by miknibus** [comment]
I dont understand the technical jargon, but this version seems to have created another bug.
Occasionally all the online guildhalls become "full" in mhp3rd; making it impossible to enter any of the 24 guildhalls. It does also work very well occasionally without the previously obnoxious entrance 'hanging'
For the time being I cannot identify what triggers this. 
I have tested this with a clean version of ur build.

**Comment by hrydgard** [comment]
@miknibus  hm, thanks for reporting. I would expect this to work exactly as well or badly as the other branch as there has reallly only been cleanups, except for #47f624c...  What version are you comparing with where it works?

**Comment by miknibus** [comment]
@hrydgard I was using v0.9.9.1-1384-ga440a2a. This one had the 'hanging' bug.
The above did fix the hanging bug as i tried repeatedly to check if it did work.

I dont know if this means anything but i have copied the debug log when the "full" message pops up.

32:21:627 user_main    I[NET]: HLE\proAdhoc.cpp:1169 Incoming Group Information...
32:21:629 user_main    I[NET]: HLE\proAdhoc.cpp:1169 Incoming Group Information...
32:21:631 user_main    I[NET]: HLE\proAdhoc.cpp:1169 Incoming Group Information...
32:21:633 user_main    I[NET]: HLE\proAdhoc.cpp:1169 Incoming Group Information...
32:21:635 user_main    I[NET]: HLE\proAdhoc.cpp:1169 Incoming Group Information...
32:21:637 user_main    I[NET]: HLE\proAdhoc.cpp:1226 FriendFinder: Incoming Scan complete response...
32:21:678 user_main    I[NET]: HLE\sceNetAdhoc.cpp:957 sceNetAdhocctlGetScanInfo([0bfff410]=812, 093e7ec8)
32:21:738 user_main    I[UTIL]: HLE\sceUtility.cpp:405 00000000=sceUtilityNetconfInitStart(08ab3a4c)
32:21:778 user_main    I[NET]: HLE\sceNetAdhoc.cpp:1349 sceNetAdhocctlCreate(MHP3Q005) at 0887cff4
32:21:896 user_main    I[NET]: HLE\proAdhoc.cpp:1055 Received 139 Bytes of Data from Adhoc Server
32:21:896 user_main    I[NET]: HLE\proAdhoc.cpp:1111 Incoming Peer Data...
32:22:059 user_main    I[NET]: HLE\proAdhoc.cpp:1055 Received 146 Bytes of Data from Adhoc Server
32:22:059 user_main    I[NET]: HLE\proAdhoc.cpp:1111 Incoming Peer Data...
32:22:061 user_main    I[NET]: HLE\proAdhoc.cpp:1062 FriendFinder: Incoming OPCODE_CONNECT_BSSID
32:22:063 user_main    E[UTIL]: HLE\sceUtility.cpp:425 UNIMPL 00000000=sceUtilityNetconfUpdate(2)
32:25:170 user_main    I[NET]: HLE\sceNetAdhoc.cpp:1084 sceNetAdhocctlDisconnect() at 0887c9a4 [group=MHP3Q0057:J���]
32:25:270 user_main    W[NET]: HLE\sceNetAdhoc.cpp:1153 UNTESTED sceNetAdhocctlDelHandler(0): deleted handler 0
32:25:302 user_main    I[NET]: HLE\sceNetAdhoc.cpp:1163 sceNetAdhocctlTerm()
32:25:304 user_main    I[NET]: HLE\proAdhoc.cpp:1266 FriendFinder: End of Friend Finder Thread
32:25:336 user_main    I[NET]: HLE\sceNetAdhoc.cpp:1460 sceNetAdhocTerm()
32:25:369 user_main    W[NET]: HLE\sceNet.cpp:107 UNTESTED sceNetTerm()

**Comment by miknibus** [comment]
@hrydgard ok we have kind of figured out how its triggered.
I have tested with mhfu and mhp3rd which has multiple guildhalls. 
Whenever i switch between empty halls it has no problem. But when going into a hall with 3 people or 4 and then switching onto any other hall causes the emulator to think the new hall is full too.
3 people is also the case as upon entering the hall becomes full. The obvious difference between 3 ppl and 4 is that for 3, we can enter the initial try.

**Comment by hrydgard** [comment]
Something is causing sceNetAdhocctlDisconnect ... but what? hm

**Comment by hrydgard** [comment]
It's been lingering long enough, I'm just gonna merge it now as soon as the buildbot is happy, and we'll fix the MipsCall and other issues afterwards.

**Comment by sum2012** [comment]
Thanks :)
This is big change for ppsspp v1.0

**Pull request merged**
