### PR TITLE
OpenXR - CI build for VR apk

### LINKED ISSUE #17065: Setup Orphis' Buildbot for VR builds
@hrydgard , @Ivonasek
### What should happen

Add dev VR builds to Buildbot

### Who would this benefit

VR community

### Platform (if relevant)

Android

### Games this would be useful in

Medievil Resurrection,Motostorm Arctic, etc...

### Other emulators or software with a similar feature

_No response_

### Checklist

- [X] Check the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already implemented.
- [X] [Search for other requests](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same feature.

### PR DESCRIPTION
**Pull request by lvonasek**
An attempt to fix https://github.com/hrydgard/ppsspp/issues/17065. 

It seems this doesn't run until it is merged.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Well, this would add a "manual" step to generate an APK, but the buildbot doesn't use GitHub Actions at all currently, and I don't know that anyone would be manually clicking this button:

image

It might be better to use a push trigger if you're goal is to make builds available.  Something like:

```
on:
  push:
    branches:
      - master
    tags:
      - v*
```

-[Unknown]

**Comment by lvonasek** [comment]
Thanks, I somehow cannot figure out where the Android CI build is called from.

**Comment by lvonasek** [comment]
I close this for now, will reopen it if I figure out how the Android building works.

**Comment by unknownbrackets** [comment]
The Android building is handled on a separate server unrelated to GitHub Actions, buildbot.orphis.net.  It's got its own configuration which is not managed within GitHub which is why Henrik @'d him.

-[Unknown]

**Pull request closed without merging**
