### PR TITLE
Fix #9814 android x86-64 cmake problem.

### LINKED ISSUE #9814: App crashes on Lenovo Yoga after it was updated to Android 6.0
Presumably this resulted in it now using the x86-64 build, and that build seems to have issues according to Intel, who have informed me that it is unstable. Multiple users have reported the Yoga as an affected device.

### PR DESCRIPTION
**Pull request by mrcmunir**
I hope finally workaround https://github.com/hrydgard/ppsspp/issues/9814

tested in androidx86-64 images and android sdk avd images and no crash

### CODE REVIEW

**Comment by hrydgard** [comment]
Cool! Thanks for this.

**Comment by unknownbrackets** [comment]
Oh, right, I avoided -Bsymbolic in ec491ef because it has side effects:
https://blog.flameeyes.eu/2012/10/symbolism-and-elf-files-or-what-does-bsymbolic-do/

Hopefully we're never comparing pointer / function pointers in a way that gets broken by this.  Assuming it only uses this on the final linkage I guess we're likely safe.

-[Unknown]

**Comment by mrcmunir** [comment]
@unknownbrackets not sure what if the -Bsymbolic ignore this but with gc-sections cause crash in java part.
 ```10-17 18:21:22.430 2453-2453/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.ppsspp.ppsspp, PID: 2453
                                                 java.lang.UnsatisfiedLinkError: No implementation found for void org.ppsspp.ppsspp.NativeActivity.registerCallbacks() (tried Java_org_ppsspp_ppsspp_NativeActivity_registerCallbacks and Java_org_ppsspp_ppsspp_NativeActivity_registerCallbacks__)
                                                     at org.ppsspp.ppsspp.NativeActivity.registerCallbacks(Native Method)
                                                     at org.ppsspp.ppsspp.NativeActivity.onCreate(NativeActivity.java:448)
                                                     at org.ppsspp.ppsspp.PpssppActivity.onCreate(PpssppActivity.java:92)
                                                     at android.app.Activity.performCreate(Activity.java:6237)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 ```

**Comment by hrydgard** [comment]
Yeah, it garbage collects all our JNI entry points and the .so shrinks by quite a bit, so something is not right with gc-sections.

**Comment by unknownbrackets** [comment]
I mean, NDK has talked about doing this: https://github.com/android-ndk/ndk/issues/436

See here: https://www.ibm.com/developerworks/aix/library/au-aix-symbol-visibility/index.html

Easiest ways to solve would be:
1. Add `__attribute__(( visibility("default") ))` on all the Java things.
2. Put `#pragma GCC visibility push(default)` at the top of files with Java exports.

It might also be worth, separately, considering `-fvisibility-inlines-hidden`.  I thought gc-sections only collected things that were not visible...

-[Unknown]

**Comment by mrcmunir** [comment]
I push better safe path for x86_64 in case not found -landroid later will test with -fvisibility-inlines-hidden Proposed to see such behavior.

**Pull request merged**
