### PR TITLE
More translation fixes

### PR DESCRIPTION
**Pull request by hrydgard**
Adds missing lines to the ini files.

I'm struggling a little with the "Auto-hide buttons after seconds" string. What would be a good wording for that, now that we show units by the value?  "Hide butons after time"? "Button hide delay?". Or simply "Auto-hide buttons" and let the interval imply a delay?

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm? This is how it currently looks in the UI, with the unit added:

Auto-hide buttons after seconds:  20 seconds

which is repetitive (where ":" is the separator between left and right side). So we don't want % or "seconds" at all on the left side.

**Comment by Felipefpl** [comment]
> Hm? This is how it currently looks in the UI, with the unit added:
> 
> Auto-hide buttons after seconds: 20 seconds
> 
> which is repetitive (where ":" is the separator between left and right side). So we don't want % or "seconds" at all on the left side.

I see, then just "Auto-hide after:" is fine imo. At least for me. :)

**Comment by TotalCaesar659** [comment]
Wouldn't just "Auto-hide buttons in" fit in?

**Comment by unknownbrackets** [comment]
Maybe just "Auto-hide buttons after delay"?  It's nice to remove words but I think "Auto-hide buttons after" reads like an incomplete thought and might cause more cognitive confusion.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, that was my thought as well, and incomplete sentences are hard to translate, too.

"delay" is pretty good as a last word. Think I'll go with it.

**Pull request merged**
