### PR TITLE
Add Warriors Orochi to [ReportSmallMemStick]

### LINKED ISSUE #16827: Warriors Orochi don't enough free space to save
### Game or games this happens in

ULUS10341 - Warriors Orochi

### What area of the game / PPSSPP

At the beginning
I tried [ReportSmallMemStick] and [MemstickFixedFree] in compat.ini still fail

### What should happen

No problem
like jpcsp emulator

### Logs

psspp-v1.14.4-253-g03f64a021-windows-amd64 log: https://gist.github.com/sum2012/62b3d5f1e0c59f37209b8327bb475774
Real PSP log: https://gist.github.com/sum2012/1e8e6f5f2249c5a818a0c313e8c7121b

### Platform

Windows

### Mobile phone model or graphics card

Nvidia Geforce 710

### PPSSPP version affected

v1.14.4-253-g03f64a021

### Last working version

None

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [X] Try without any cheats and without loading any save states.
- [X] Include logs or screenshots of issue.

### PR DESCRIPTION
**Pull request by sum2012**
in compat.ini
Close #16827

### CODE REVIEW

**Comment by Panderner** [comment]
What size limit for warriors orochi that saves work properly?

**Comment by sum2012** [comment]
> What size limit for warriors orochi that saves work properly?

Need < 4 gb

**Comment by Panderner** [comment]
> > What size limit for warriors orochi that saves work properly?
> 
> Need < 4 gb

But it does happen for real PSP?

**Comment by sum2012** [comment]
> But it does happen for real PSP?

I don't have >= 4 gb memory struck to confirm.
But at least don't have this message.

**Comment by hrydgard** [comment]
That's good enough proof for me - this is quite a common bug in games, that didn't anticipate memsticks larger than 4GB...

**Comment by sum2012** [comment]
Just a question ,why do we default 16gb memory free space ?

**Comment by hrydgard** [comment]
That's actually a good question, with no answer other than "that's what we've always been doing"... Hm.

**Comment by unknownbrackets** [comment]
I will say 16 GB memory stick pro duo cards were quite common later in the PSP's life, and so were 8 GB.  I might remember wrong, but I think it was common to see PSP-2000 and especially PSP-3000 devices packaged with 8 GB+ cards.

I think I personally started with 2 GB, upgraded to 8 GB (which eventually had a failure after a lot of use), and then switched to an unofficial microsd thing so I could buy higher quality microsd cards.

If we lowered the limit, I think it does account for PSP/GAME at least, it would mostly affect games like Dissidia (which export video) or games that export screenshots, I suppose.

-[Unknown]

**Pull request merged**
