### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by Arashvscode**
Addition of runOnUiThread for better management in the background, as well as tidying up some code and upgrading to Java 8

### CODE REVIEW

**Comment by unknownbrackets** [comment]
We've had a lot of problems with the wrong size being detected on full screen or rotate in the past, although there haven't been many recent reports.

What does this change help or fix?  Does this help sizing while it is not the active app?

-[Unknown]

**Comment by Arashvscode** [comment]
> 

This small change helps the program not to freeze even if the size is uncertain. Thanks

**Comment by hrydgard** [comment]
Thanks, will look at this and probably merge it after the 1.14 release process is over, as these windowing changes on Android are very risky - even if they fix something, something else can break.

**Comment by Arashvscode** [comment]
> 

Ok, thank you for answering my question

**Comment by Gamemulatorer** [comment]
This might help https://github.com/hrydgard/ppsspp/issues/11016?

**Comment by hrydgard** [comment]
I think this change can be boiled down to simply:

```
	activity.runOnUiThread(() -> {
					Log.d(TAG, "checkDisplayMeasurements: checking now");
					updateDisplayMeasurements();
				});
```

the rest is just style changes and making a local constant for the build version, which I don't really prefer over the current code. So I'm going to commit that change alone after testing it.

**Comment by hrydgard** [comment]
Replacing this with #16800, closing.

**Pull request closed without merging**
