### PR TITLE
Add "Half skip" Mode

### PR DESCRIPTION
**Pull request by sum2012**
My random idea from https://github.com/hrydgard/ppsspp/issues/16900#issuecomment-1903906739

Added as another mode to the speedhack setting Skip GPU readbacks.

May help #18607

### CODE REVIEW

**Comment by LunaMoo** [comment]
Why making it random if you want "half"(which would imply every other frame)?

 Random pretty much means it might break things sometimes and sometimes it will not, doesn't feel like an useful thing to have, even less for performance reasons as lower framerate is better than unpredictable one.

**Comment by hrydgard** [comment]
One argument for making it random is that it will work to halve the work "evenly" whether the game does 1, 2 or 3 readbacks per frame for example - if you do every second readback, you run the risk of falling into stuck patterns and always skipping the same read every frame.  But, obvious drawbacks are of course uneven framerates etc.

Either way, this idea of skipping readbacks randomly highly depends on what the game is doing, if it makes sense or not...

What game do you feel this is the most beneficial in, sum2012?

**Comment by sum2012** [comment]
MotorStorm Artic Edge, gpu readback the sun to adjustment the sky

**Comment by hrydgard** [comment]
Oh, yeah, I guess it can be a pretty good option for that game, since the effect isn't very frame-critical.. 

Hm. I'm gonna play with it soon.

**Comment by sum2012** [comment]
@hrydgard how about this ? ( although need rebase )

**Comment by hrydgard** [comment]
Is it actually a good gameplay improvement, and doesn't just get weirdly choppy?

**Comment by sum2012** [comment]
Yes

在 2024年9月17日週二 下午9:02，Henrik Rydgård ***@***.***> 寫道：

**Comment by hrydgard** [comment]
ok. i'm gonna manually rebase this and do some minor changes (naming, initialization).

**Comment by hrydgard** [comment]
Replacing this with #19469 

Not super succesful for me, something weird is going on in Motorstorm.

**Pull request closed without merging**
