### PR TITLE
Reduce Savedata shutdown delay time

### LINKED ISSUE #7744: Juiced Eliminator (JPN) freeze
Since https://github.com/hrydgard/ppsspp/pull/5369

debuglog(rename jpg to 7z)
ppsspplog

jpcsptrace of savedata
https://gist.github.com/daniel229/2e4e7400226856f9c8e2

### PR DESCRIPTION
**Pull request by sum2012**
Fix #7744

### CODE REVIEW

**Comment by hrydgard** [comment]
Looks fine but this will need a lot of testing with various games to make sure it doesn't break stuff.. On the other hand, merging is a good way to test :P 

So before I merge, you did try at least a bunch of games with no issues, right?

**Comment by unknownbrackets** [comment]
See also #5319.  I'm practically certain that such a small delay is impossible to reproduce on real hardware.  I think there's probably something else to the timing issue - imho.

-[Unknown]

**Comment by sum2012** [comment]
My phone damaged in toilet so that I was sad
Anyway I test 10 game no problem

**Comment by sum2012** [comment]
I have a better solution

**Pull request closed without merging**
