### PR TITLE
Thread: Default to kernel threads from kernel. by @unknownbrackets 

### PR DESCRIPTION
**Pull request by sum2012**
This is an experiment.  In most cases, allowKernel will be false.
After merge this,I can test other chinese patched game.
edit: not only #7960

### CODE REVIEW

**Comment by hrydgard** [comment]
Does this fix #7960 ?

**Comment by sum2012** [comment]
No,But this is the first step to fix.

**Comment by unknownbrackets** [comment]
Well, I should at least clean up the extra noisy logging before this is merged.  It likely makes sense to default to the module, though.

-[Unknown]

**Comment by sum2012** [comment]
I use my own  batch instead

**Pull request closed without merging**
