### PR TITLE
Move toward supporting OpenGL Core Profile 3.3 - 4.5

### LINKED ISSUE #764: Use Vertex Array Objects when available
http://www.opengl.org/wiki/Vertex_Array_Object#Vertex_Array_Object

VAO is an extension to OpenGL ES 2.0 (and standard in ES 3.0 and desktop GL) and may provide the vertex cache with an additional speed boost.

Just adding it here so I don't forget about it, I'll do it one of these days.

### PR DESCRIPTION
**Pull request by unknownbrackets**
Specifically:
- Stop loading GL_EXTENSIONS in a deprecated way on GL 3.x+ / GLES 3.x+.
- Switch to VAOs (when supported) for thin3d and GE debugger.

Fixes #764.

The remaining things I'm aware of are:
- [x] Add a supports flag for VAOs, so we can turn it off easily in compat context (not sure of perf.)
- [x] Use VAOs/VBOs in depal.
- [x] Use VAOs/VBOs in framebuffer drawing.
- [x] Always use VAOs/VBOs in transform.
- [x] Use VAO/VBO for software rendering.

One thing I had trouble with - in the vertex preview code, I had to re-upload the index and vertex data.  Simply rebinding wasn't even enough, and I couldn't find anywhere it might've been getting overwritten.  Not sure what I'm doing wrong...

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Awesome! Will finally be able to use 3.x features on Mac...

**Comment by unknownbrackets** [comment]
Oh, so just bind a single VAO the whole time and then "business as usual"?

Well, the most work is VBOs anyway.  I feel like VAOs allow us to avoid tracking enable/disable vertex flags on our side, but probably doesn't matter either way.  If drivers are less optimized than we already are for that, that's annoying.

You mentioned in #764 and 2f36eeb1ec7621afd3bed7e3dacb03633fa64bf1 that it might benefit somewhere, although that was some time ago.  It might cut a small number of duplicate state calls (attrib pointers, etc.) if it is optimized by the driver.

-[Unknown]

**Comment by hrydgard** [comment]
Yes, a lot of apps do that and drivers still has to keep that reasonably fast, so it works.

If there's a benefit to VAO it'll probably be small. They're badly designed as a feature, would be better if you could create the layout once and use it together with any buffer, instead of binding layout and buffer together as VAO does.

**Comment by unknownbrackets** [comment]
Actually, the VBO is not part of the VAO state (but the element buffer is.)

-[Unknown]

**Comment by hrydgard** [comment]
Actually, it is.

**Comment by unknownbrackets** [comment]
Ah, okay, sorry.  Maybe this explains the vertex preview problem I was having... I misunderstood the docs, I didn't realize the binding was "saved" by the attrib pointer call for that attribute.  That is pretty silly.

-[Unknown]

**Comment by unknownbrackets** [comment]
At this point, on Windows, the UI and softgpu work with a core profile.  However, there's still an issue on Mac with `#version` and `fragColor0` type things in various utility shaders.  Need to fix those to not be compile time anyway.

-[Unknown]

**Comment by unknownbrackets** [comment]
I guess it'll require messing with the projection/etc. matrices to determine the "width" of one pixel, right?

For points, I just have to find the delta to the positive screen x/y direction, and add that for the bottom right.

For lines... I'll basically determine the angle (slope) of the line, right?  And then offset perpendicular to that toward either the positive screen x or y direction for the other set of verts.

I'm thinking these are used most often in throughmode, where they're unlikely to point at pixel centers (at least as straight lines.)  But I'm not so sure about diagonal lines, or transform mode.  In those cases, maybe centers are better.

-[Unknown]

**Comment by unknownbrackets** [comment]
At this point, everything (except line widths) seems to work with a core profile on Windows.

-[Unknown]

**Comment by hrydgard** [comment]
Very nice. I will try to fix it up on Mac before merging.

**Comment by hrydgard** [comment]
For lines, I just wish we had geometry shaders everywhere. But we can essentially use a similar code path as with RECTs - we software transform to screen space first, then form the perpendicular vector to the line vector (x' = y; y' = -x), normalize it, scale by width and offset the verts.

**Comment by daniel229** [comment]
It seems slower.

**Comment by unknownbrackets** [comment]
I don't think we transform rects to screenspace first?

@daniel229 what if you change GL_STREAM_DRAW in all the changes to GL_STATIC_DRAW or GL_DYNAMIC_DRAW?  Is there any impact on performance?

Yeah, sounds like we're going to want to only do this when we obtain a core profile.

-[Unknown]

**Comment by daniel229** [comment]
GL_STATIC_DRAW or GL_DYNAMIC_DRAW is same as GL_STREAM_DRAW in speed.

**Comment by hrydgard** [comment]
@unknownbrackets , well, we send them through software transform. True, we transform it to the space right before the projection matrix, that's true, so I guess we need to apply the proj matrix too before we expand the lines, and then use an identity proj matrix to do the actual drawing...

**Comment by unknownbrackets** [comment]
Okay, I've added `gl_extensions.IsCoreContext`.  Mac will just have to set this.

Wow, that is horrible.  Ugh.

I'm thinking I can just calculate the dx/dy of one pixel (a "1x" pixel, mind you) from the transform matrices, and then I have the positive screen direction too, right?  I could continue to use our existing drawing code.  A perpendicular vector shouldn't be any different calculated before or after transformation, right?  I mean, as long as it gets transformed too, which it would.

But that's probably best in a separate pull.

-[Unknown]

**Comment by unknownbrackets** [comment]
UI doesn't work on a Mac with 4.1 and that set though, even with `#verson 330` in the shaders.  So I'm missing something.  `glGetError()` returning 0 too....

-[Unknown]

**Comment by daniel229** [comment]
Speed is back.

**Comment by unknownbrackets** [comment]
I've rebased and removed the partial progress on lines/points.  I've separated out the remaining #8277 and #8276.  I think these changes are still positive progress, as it brings us closer to compatibility.

-[Unknown]

**Pull request merged**
