### PR TITLE
All PGF Fixed

### PR DESCRIPTION
**Pull request by nassau-tk**
These fixed PGF files modified some games text appearance.(example:SnakeWarriors/eragon/FieldRunners/PC-Engine Archives Series) See issue #13718

### CODE REVIEW

**Comment by hrydgard** [comment]
Conflicts again! What are you doing? :) 

Are you using command line git or some UI?

If you are using command line git, please use the following sequence to create your branch:

```
git checkout master
git pull --rebase
git checkout -b my-new-pgf-branch
```

Now replace the font files. Then:

```
git add assets
git commit -m "Update PGF fonts"
git push origin my-new-pgf-branch
```

Now you can make a pull request.

**Comment by nassau-tk** [comment]
I'm really so sorry.  (T_ T)
I'm usuing "GitHub Desktop (GUI)".
Sorry,I have never been to use command line.

**Comment by hrydgard** [comment]
I've never used github desktop, but try to update the master branch before you create your new branches.

**Comment by nassau-tk** [comment]
STEP0 "Update from master."
STEP1 "Make new branch & Publish to Github."
STEP2 "Update new files in my local folder."
Notice:It means Copy from other working folder to my local git folder.
STEP3 "Make commit."
STEP4 "Make push."
STEP5 "Make pull request."

Is it right?

**Comment by hrydgard** [comment]
you don't need to publish the branch until you've actually made the commit with the new files,  but that sounds right

**Comment by hrydgard** [comment]
Oh yeah and note that you have to update your master from my master :) otherwise you'll be in the same situation again

**Comment by nassau-tk** [comment]
STEP0 "Update from master."   **<=It's can't do that before create new branch.**
STEP1 "Make new branch & Publish to Github."
STEP1.5 "Update from master."   **<=So,I did it here.**
STEP2 "Update new files in my local folder."
Notice:It means Copy from other working folder to my local git folder.
STEP3 "Make commit."
STEP4 "Make push."
STEP5 "Make pull request."

I try this flow.

**Comment by hrydgard** [comment]
Seems the github desktop client is kinda useless. You seem to have to do something like this to get the "upstream" (my) master: https://stackoverflow.com/questions/11394349/upstream-pulls-with-the-github-desktop-client

**Comment by hrydgard** [comment]
Just forget this silly desktop client and use the command line .. 

https://git-scm.com/download/win

Or just upload the files to google drive or something and I'll take care of it.

But what confuses me is that yesterday I did try to get your branch, manually copied all the files, and they were no different to what's currently in PPSSPP master...

**Comment by hrydgard** [comment]
Tried again, now they are different. I'll take care of this.

**Comment by hrydgard** [comment]
https://github.com/hrydgard/ppsspp/pull/13755

**Comment by nassau-tk** [comment]
>But what confuses me is that yesterday I did try to get your branch, manually copied all the files, and they were no different to what's currently in PPSSPP master...

maybe,This client will get the master data when finished push.
I don't know why that those data overwrite day of master data.
But,It happen.

OK.
I must study for about Github more more more.
But,I hope my work finished now.  (^_^;)

And,Really I’ｍ sosorry...

**Pull request closed without merging**
