### PR TITLE
Update the glslang submodule, fix the build afterwards.

### PR DESCRIPTION
**Pull request by hrydgard**
Time to update it just to not fall too far behind, it's been while. Also @orbea had some build issue that this might fix.

### CODE REVIEW

**Comment by orbea** [comment]
I was about the suggest the same, seems you got there first. :)

I imagine it did not fail to build for me because I have the header installed on my system.

**Comment by unknownbrackets** [comment]
Looks like it needs the include path too.

-[Unknown]

**Comment by hrydgard** [comment]
Okay I guess that didn't do it... hm.

**Review by unknownbrackets — APPROVED** [review]

**Comment by hrydgard** [comment]
Ugh, thanks!

**Comment by orbea** [comment]
Thanks!

**Pull request merged**
