### PR TITLE
Warn the user about bad CHDs

### PR DESCRIPTION
**Pull request by hrydgard**
If they're not created with "chdman createdvd", they will perform really badly.

See #18798

Sorry @TotalCaesar659 and @Saramagrean , another string for you :)

image

### CODE REVIEW

**Comment by TotalCaesar659** [comment]
It's alright, I'm already used to it ;-)

**Comment by nameless1** [comment]
So, it warns about bad chds that were made with createdvd... am I missing something?

E:\Playstation Portable\PSP Backups>chdman.exe info -i "Ape Escape on the Loose (USA).chd"
chdman - MAME Compressed Hunks of Data (CHD) manager 0.262 (unknown)
Input file:   Ape Escape on the Loose (USA).chd
File Version: 5
Logical size: 749,240,320 bytes
Hunk Size:    4,096 bytes
Total Hunks:  182,920
Unit Size:    2,048 bytes
Total Units:  365,840
Compression:  lzma (LZMA), zlib (Deflate), huff (Huffman), flac (FLAC)
CHD size:     279,415,049 bytes
Ratio:        37.3%
SHA1:         aabdebdb87d0363c4ba911dc72819dc5e014ad95
Data SHA1:    373098a849dcdc573499a28c89c92b63376e666d
Metadata:     Tag='DVD '  Index=0  Length=1 bytes

Screenshot 2024-02-05 220959

**Comment by hrydgard** [comment]
Yup it's the hunk size. No other hunk size than 2048 makes sense to use, since that's the sector size.

**Comment by pocafon** [comment]
How can we lower the hunksize to 2048 if it's not much to ask?

**Comment by hrydgard** [comment]
@pocafon using `chdman createdvd` will do it automatically.

You need a recent build of chdman though, such as the one shipped with the latest build of MAME.

**Pull request merged**
