### PR TITLE
Fix scePowerSetClockFrequency timing by JPCSPTrace

### LINKED ISSUE #4523: ULUS10442 - Kenka Bancho Badass Rumble stuck
The game crashes at the loading after this scene(first fight with a bancho)
before

It gets stuck in the loading screen:
stuck

and it goes black after a while.

I tried it with PPSSPP v0.9.5-339 Windows7 64bit, but it's reported to happen at least since v0.7.6-816-g2c4254d on the forum thread.

Here is the log when it starts loading (taken with "Ignore Illegal Reads/Writes" off).
start
then there is a lot of "Invalid address" and it ends with:
end

Full Log (35MB): http://www59.zippyshare.com/v/37371141/file.html
The game works great otherwise.

edit: Added some Images, modified the title and added full log.

### LINKED ISSUE #6813: Kenka Banchou 4 crash in-game
then

go inside crash
I think the problem is
MyThread-Mai E[G3D]: GLES\VertexDecoder.cpp:788 Vertices without position found

info log:
https://drive.google.com/file/d/0B3OaSdeV0L8kcS1FUm1LRjIzVUE/edit?usp=sharing
debug log:
https://drive.google.com/file/d/0B3OaSdeV0L8kLUpmaUxwUWxVSTA/edit?usp=sharing
disassumble

### PR DESCRIPTION
**Pull request by sum2012**
Fix #4523 Fix #6813

### CODE REVIEW

**Comment by hrydgard** [comment]
You're specifying 150us but the logs seemed to indicate 150ms. 

Though, if this works, I guess that's alright...   Waiting as long as 150ms seems dangerous anyway.

Can you try this again with 150000 instead of 150? If that works just as well, let's go with that, otherwise this is fine.

**Comment by sum2012** [comment]
Yes, 150000 work
Fix #6813 too

**Comment by hrydgard** [comment]
I think you should also change the INFO_LOG back to DEBUG_LOG, then merge :)

**Comment by sum2012** [comment]
Can leave scePowerSetBusClockFrequency INFO log ?
We might need to fix the timing,

**Comment by hrydgard** [comment]
Hm, you're right that there might be more to do here. We can keep them all for a while.

**Comment by unknownbrackets** [comment]
Seems like a good candidate for a release notes entry in v1.3.0, this game has never worked afaik.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, agreed.

**Comment by sum2012** [comment]
I think that we can use this method to fix sceUtility timing,
At least 2 games effect in timing.

**Comment by unknownbrackets** [comment]
I think we may end up needing to use a fake HLE thread for that.  We've already timed it, but the timing is different between games because of other thread behavior, iirc.

-[Unknown]

**Pull request merged**
