### PR TITLE
Windows Dark Mode: initial support

### PR DESCRIPTION
**Pull request by hrydgard**
Windows 11-style (Windows 10 also had limited support) dark mode on classic Win32 is a hellscape of hacks. Googling around a bit, I managed to bodge together something that works for the basics (though the dialogs still need a lot of work).

~~Not sure if this is even worth pursuing, or how to get rid of that annoying white line under the menu bar.~~

image

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Does `DwmSetWindowAttribute(hWnd, DWMWA_USE_IMMERSIVE_DARK_MODE, &value, sizeof(value))` help per https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes?

Well, I'm still sticking with 10 for now.

-[Unknown]

**Comment by hrydgard** [comment]
That function alone just gets us a dark titlebar, menus and dialogs are not affected.

**Comment by hrydgard** [comment]
It's a lot of work to convert all the debug windows to support dark mode, so skipping that for now. With the last commits, we have a "consistent-ish" look: everything follows the dark mode setting except the debug windows, which most people won't see, so the user experience is pretty good.

**Comment by hrydgard** [comment]
I'm just gonna get it in, I think it looks quite nice. Let's see if we end up with any compatibility issues with old Windows, or something.

**Pull request merged**
