### PR TITLE
Correct a potential typo

### LINKED ISSUE #12002: [Regression] Recoverable periodic softlocks excepting music in Wolf3D homebrew
Get Wolf3D homebrew from [here](https://www.brewology.com/downloads/download.php?id=9730&mcid=1)
Save game to roam free the level and reproduce more easily:
[sodssav.zip](https://github.com/hrydgard/ppsspp/files/3124331/sodssav.zip)
Save is from spear of destiny shareware version included with homebrew.
### What happens?
Game softlocks after some time (2-5 minutes) and it recovers after more time passes (1-3 minutes)
### What *should* happen?
This shouldn't happen.
### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.
CPU: Intel Core i3-2375M;
GPU: Intel HD Graphics 3000
Windows 10 v10.0.18362.86 (Release preview)
Known good: v1.8.0-102-g 057e720b2
Known bad: v1.8.0-105-g dcd2ff03b
This seams to be a JIT issue considering where bisecting with Orphis buildbot led me and most likely culprit is #11971

### PR DESCRIPTION
**Pull request by LunaMoo**
Fixes #12002 althrough I'll continue testing for a few more minutes just in case;p.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Hm, that makes me concerned there's some issue with the `lastGlobalTimeUs` adjustment.  Basically this change should make the adjustment happen with a space of 222x as often.  So maybe the problem will still happen, just not as often?

The thought behind this change was:

`ticksSinceLast * 1000000` is increasing `ticksSinceLast` quite a bit.  If it gets up to `INT64_MAX / 1000000`, it will overflow and we'll calculate `usSinceLast` incorrectly (it would probably be negative.)  I used `UINT_MAX` (which is much smaller than the overflow point) just to be safe.

In theory, the operation inside that if should be a zero-sum operation.  Meaning, `if (ticksSinceLast > 222000) {` or `if (ticksSinceLast > INT64_MAX / 1000000) {` should behave equivalently.  The only flaw would be slight rounding errors if it's too often (i.e. `if (ticksSinceLast > 100) {`.

So if changing the frequency of that if does something, it probably means it is somehow not a zero-sum operation which is a problem.

-[Unknown]

**Comment by unknownbrackets** [comment]
Ah, I see it - `usSinceLast = 0;` should be inside the if.  That will probably fix it.

-[Unknown]

**Comment by LunaMoo** [comment]
Will test that in a moment and push it here if it works :3

**Review by unknownbrackets — APPROVED** [review]
Thanks - sorry.  Was double adding the delta on overflow, that explains that bad behavior... arg.

-[Unknown]

**Pull request merged**
