### PR TITLE
Android: Add new build config "legacyOptimized", which targets an older Android SDK version

### PR DESCRIPTION
**Pull request by hrydgard**
legacy logo

PPSSPP Legacy

This should allow working around the scoped storage problem on many Android TV devices by sideloading APKs built this way. Support for building this will be added to the buildbot soon.

Similar to what we do on Quest to avoid scoped storage for sideloaded PPSSPP VR.

Considering maybe making a special icon variant? Ideas?

This new edition gets a new apk ID, org.ppsspp.ppsspplegacy

See #16865

Not yet tested.

IMPORTANT: This build will be sideload-only. It cannot be published on the Play Store. It may also lose some minor OS features, not sure.

### CODE REVIEW

**Comment by anr2me** [comment]
Having a different icon would be nice (or may be a different color just like the gold version), since it use different ID, user can installed it a long with the newer SDK without getting confused which is which :)

**Comment by hrydgard** [comment]
I'm thinking some kind of sickly green color would be appropriate :)
conv

**Comment by hrydgard** [comment]
Tried it on my S21, it popped up a nasty warning (since this bypasses modern protection) but indeed works as intended!

Will merge and add to buildbot soon.

**Comment by hrydgard** [comment]
https://www.ppsspp.org/docs/reference/legacy-edition/

added some info on the website

**Comment by anr2me** [comment]
Btw, we don't need to install an older SDK to build this, right?

**Comment by hrydgard** [comment]
No

**Pull request merged**
