### PR TITLE
DarkStalkers: Handle the "normal" screen stretch too, not just "wide".

### PR DESCRIPTION
**Pull request by hrydgard**
To avoid a surprising performance drop just from tweaking in-game settings. Plus, you could argue that the game is meant to be played this way anyway.

A followup to #12443 .

@LunaMoo  FYI :) Anything else it's missing?

### CODE REVIEW

**Comment by Panderner** [comment]
How do you feel for this pull request on a real PSP or PS Vita Screen?

**Comment by hrydgard** [comment]
I don't understand that question at all.

**Comment by Gamemulatorer** [comment]
Maybe this pr could help the performance drops during fighting..

Introduction fight this game is smooth
Screenshot_20200524-235131
but during fight scene the performance drastically drops
Screenshot_20200524-235153

**Comment by hrydgard** [comment]
Yeah there's still more work to be done on performance, independently from this change. For now, it's at least OK on PCs and high power phones.

**Comment by Gamemulatorer** [comment]
I feel a little improvement thanks :)

**Pull request merged**
