### PR TITLE
Fix potential data race

### PR DESCRIPTION
**Pull request by HR1025**

### CODE REVIEW

**Comment by hrydgard** [comment]
Hm, care to explain?

**Comment by HR1025** [comment]
- Add lock protection in `GetSystem` and `Unmount` (I think it miss)
- Move `GetHandleOwner` from `public` to `private` to reduce the lock condition
- Use `MetaDummyFileSystem` to remove confuse `null` check
> At first I want use `EmptyFileSystem` directly, but in order to keep `Ioctl ` result as orign try `MetaDummyFileSystem`.

**Comment by hrydgard** [comment]
Well, what I meant is, what problem does this solve?

Do we actually have a serious race condition here that causes problems?

**Comment by HR1025** [comment]
Actually not, not problem ...

**Comment by hrydgard** [comment]
I'm going to add the two missing lock-guards separately, I don't think getting rid of the null checks is worth adding a dummy system, though.

**Pull request closed without merging**
