### PR TITLE
Add feature to auto-hide buttons after X seconds

### LINKED ISSUE #4855: Feature Request: Auto hide on screen controls?
Would anyone be interested if the on-screen controls fade away after like 10 seconds or so of non-interaction? IMHO, It would make watching cutscenes way more enjoyable, but I want your opinion of it.

Thanks!

EDIT - is it I ```want your opinion of it.``` or ```want your opinion on it.```? (English is not my first language :) )

### PR DESCRIPTION
**Pull request by unknownbrackets**
This fixes #4855.  I think it makes sense on phones.

Some minor lang changes to format it a bit clearer in the UI.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Nice!

I think we should default this to 10 seconds or something, otherwise this will be another one of those nice features that nobody use because they never came across the option to turn it on.

**Comment by unknownbrackets** [comment]
Hmm, I wonder if it should be longer - especially for first time users, who might not see the controls for too long if it's 10 seconds.  Not sure...

-[Unknown]

**Comment by hrydgard** [comment]
If the controls appear when touching the screen anywhere, they'll figure it out soon enough...

**Comment by unknownbrackets** [comment]
FWIW I updated it to 20 seconds.  Sounds good to me.

-[Unknown]

**Comment by xiushudongfang** [comment]
Can RewindFlip  work on mobile device ? You may del "#ifndef MOBILE_DEVICE" in UI/GameSettingsScreen.cpp(518) by by accident.

**Comment by xiushudongfang** [comment]
I test it ,it cause speed drop

**Comment by unknownbrackets** [comment]
Some mobile devices can handle it, I meant to make that a separate commit, though.  But yes, rewind can work on mobile.

-[Unknown]

**Pull request merged**
