### PR TITLE
WIP: Fix for artifacting on Mali on Android O in Wipeout. Ugly fix for now.

### PR DESCRIPTION
**Pull request by hrydgard**
It appears that we need a barrier when we render to, let's call it, RT1, then render to RT2, then switch back to RT1 (using a LOAD renderpass) and render some more. 

However, even doing so, on Android O, Galaxy S8+ I get artifacts. Using the image layout GENERAL fixes it (which disables transaction elimination), and so does transitioning to GENERAL and back to COLOR_OPTIMAL in this situation.

Not sure yet what the right fix is.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Hmm, interesting.

Is this a scenario where we could reorder and combine the two render passes to RT1?  If RT1 and RT2 aren't cross dependent, maybe that's the optimal fix?

But I guess it makes sense we need a barrier, but only when `step.render.color == VKRRenderPassAction::KEEP` right?  I guess this may affect depth too?

How much perf impact does the extra transition have?

-[Unknown]

**Comment by hrydgard** [comment]
Correct, ideally we'd re-order the render passes to avoid this. In this case, it's like this:

* Game clears main buffer (R1).
* Switches to R2, starts rendering one of the animated signs.
* Switches to R1, draws the animated sign using R2 as a texture, and some level geometry.
* Switches to R2, starts rendering another animated sign
* Switches to R1, draws that animated sign, and some more level geometry.
* Switches to R2, starts rendering yet another animated sign
* Switches back to R1, draws the rest of the scene, then even more RT switches for the bloom effect

To re-order this, we have to shadow R2 into multiple render target. We'd really want this:

* Switch to R2, start rendering the first animated sign
* Switch to R3, start rendering the second animated sign
* Switch to R4, start rendering the third animated sign
* Switch to R1 (clear mode), renders all the signs and level geometry

We don't have the shadowing implemented so we can't currently do the full re-ordering. Also nice to keep this suboptimal path working for 

I've reported the driver bug to ARM for investigation, with a frame dump which repro's it nicely on S8+ Android O.

The performance is still quite good even with the workaround, especially when I only do this hack in KEEP mode (committing that soon), as you suggest.

**Comment by HansKristian-ARM** [comment]
Yes, this is a driver bug, it's narrowed down to:
- A renderpass with loadOp = CLEAR which does not contain any draw calls will risk corruption if the image content is otherwise static. It's triggered here because the rendering is split into two. CLEAR is one render pass, LOAD in the other which completes the rendering. This of course is a really poor way of doing it, but I understand emulators don't have the luxury of using the APIs optimally.

There are three simple workarounds for this.
- Keep all render targets in GENERAL.
- Take an extra roundtrip through COLOR_OPTIMAL -> GENERAL -> COLOR_ATTACHMENT.
- If the render pass is empty and CLEAR was used, make a dummy draw call which renders outside the screen.

No. 3 is the preferred option, the overhead is tiny/non-existent.
No. 2 has some cost in that this layout transition to GENERAL will queue up some work on the GPU (but it's pretty small).
No. 1 also works, but you'll risk more bandwidth.

**Comment by hrydgard** [comment]
Turns out it was pretty easy to avoid the situation, at least in the case of Wipeout. I just merge the clear from the empty renderpass into the next renderpass affecting the same framebuffer, which mostly fixes the issue in Wipeout (the glitch is still visible during a single frame at the start of a race, I think the game alters its rendering then for some reason). If this turns out to affect more games in trickier ways, I'll look into the workarounds.

**Pull request closed without merging**
