### PR TITLE
Add custom log expressions to the debugger

### PR DESCRIPTION
**Pull request by unknownbrackets**
This allows you to log the value of a register, and not break, on a breakpoint.

It works for both memory and CPU breakpoints.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Real nice functionality, for some reason Symbian seems to be failing to link though.

Someday we'll have to drop it..

**Comment by unknownbrackets** [comment]
Ugh... not sure, maybe gcc is running out of RAM again?

I'm able to build this fine on a local linux VM with all the Symbian stuff (same way I built ffmpeg for it.)  No linker errors.... grr.  Not sure how to debug.

-[Unknown]

**Comment by sum2012** [comment]
/home/travis/build/hrydgard/ppsspp/GPU/Software/TransformUnit.cpp:298: undefined reference to `Clipper::ProcessTriangle(VertexData&, VertexData&, VertexData&)' 
This pull request doesn't change the file (TransformUnit.cpp)

**Comment by unknownbrackets** [comment]
It looks like this was somehow related to the clang/ffmpeg changes and ccache.  I cleared all the caches in Travis and now it's fine.  It could be it was running out of memory using cache and will just happen again, though.

-[Unknown]

**Pull request merged**
