### PR TITLE
Limit Projection Matrix Data count to <= 16

### LINKED ISSUE #7024: The Red Star: only the hud is visible when you actually start the game
Tried OGL,DX9 and software mode and also check the GE Debugger but nothing other than the hud is rendered(you see the elements that are supposed to be loaded on the left side but they are not displayed on the right side of the GE Debugger)

### LINKED ISSUE #8110: The Red Star - In game but black screen
Windows 7 64 bit
PPSSPP v1.1.1-103-g05687e6
In game, Select your character --> but black sreen
npeh00024_00000
npeh00024_00001
npeh00024_00002
npeh00024_00003

### PR DESCRIPTION
**Pull request by LunaMoo**
:3 two to go:
Fixes #8110, Fixes #7024 

~rebased.

### CODE REVIEW

**Review by finansar222 — APPROVED** [review]

**Review by finansar222 — APPROVED** [review]

**Comment by hrydgard** [comment]
@LunaMoo  did you make some new changes or just rebase?

Yeah I should really get around to writing a HW test for this, but on the other hand .. it seems likely to be right. So I might just decide to merge :P

**Comment by LunaMoo** [comment]
Just rebased since all the HW side code is in common now(was repeated for each backend before, so much shorter now). Appveyor seems to be endlessly laggy, so will add that it's compiling/working fine for me on windows.

 Yeah I think this is pretty safe to merge, so far I didn't saw any other game aside from the broken one which this fixes that shows similar behaviour, this seems like a game bug that was working on psp.

 Just noticed, but there seems to be some regression with software rendering affecting all games, current master is looks even worse than with this branch which at least allowed me to see enough to confirm those changes are working, so it seems it was messed by more than one recent changes.

**Comment by hrydgard** [comment]
Ah yes, that's nice. I'm gonna go ahead and merge.

**Comment by unknownbrackets** [comment]
Based on some hardware tests, it seems like the previous behavior of wrapping at 0xF is correct - including how the number worked before this pull request.  The test is gpu/ge/get, it actually already shows it (although I just tested a bit more to be sure.)

I know we used to have some crashes from reading past things on matrix loads, etc.  Is it possible that this had multiple problems, and reverting this change doesn't break it?

Otherwise, there may be something going on with firmware versions (I tried with 6.61, though) or something more complex...

-[Unknown]

**Comment by hrydgard** [comment]
Since the matrix commands are presumably handled in hardware, would seem unexpected for a firmware version to affect it. But who knows, maybe it sets some hidden mask..

We'll ideally need to figure out what is actually going on in that Red Star game though if we are to revert this..

**Comment by unknownbrackets** [comment]
Further tests are interesting, but haven't seen the whole story yet.

The behavior of wrapping doesn't depend on firmware version.

However, I got my hands on a frame dump of this game and confirmed that before many prims, it's simply issuing a `PROJMTXDATA 0x800000` (which is suspiciously 0x3F800000.)  The frame dump draws properly on the PSP, as if this was skipped.

[#7024_NPUH10040_redstar_blackscreen.zip](https://github.com/hrydgard/ppsspp/files/8009180/7024_NPUH10040_redstar_blackscreen.zip)

#7024_NPUH10040_redstar_blackscreen

But even logging sceGeGetCmd / sceGeGetMtx during the frame dump playback says the projmtxnum has wrapped around, and the get matrix includes the negative values.  I wonder if the matrix num value wrapping is all a lie, and even though sceGeGetMtx somehow reports it, but it's somehow not used for rendering?  That seems really odd, though...

-[Unknown]

**Pull request merged**
