### PR TITLE
Update README.md for 1.14

### PR DESCRIPTION
**Pull request by hrydgard**
First draft, definitely some important stuff missing.

After this release, I think I'm going to start progressively update the README as we go - simply include README.md lines in commits that fix stuff. Collecting these at the end of the release process is a lot of work and inaccurate :)

### CODE REVIEW

**Comment by ThirteenAG** [comment]
I guess do mention new api for plugins:
```
EMULATOR_DEVCTL__TOGGLE_FASTFORWARD
EMULATOR_DEVCTL__GET_ASPECT_RATIO
EMULATOR_DEVCTL__GET_SCALE
```

**Comment by hrydgard** [comment]
Went through the commits and added a ton more issue links.

**Comment by unknownbrackets** [comment]
Added a few more of those, might add the texture upscaling perf/alpha fix and some more pull #s to the rendering fixes.

Here are some possibly notable pulls from me reviewing that I didn't check were in the list yet / think hard about if they should be:

```
Improve Mali bugs related to missing graphics on Vulkan (#15059, #16043, #16142, #16162, #16165, #16448)
Correct Adreno bugs related to missing graphics on Vulkan (#16379)
Depth optim/texturing/field (#15700, #15772, #15858, #15859, #15924, #16127, #16361, #16383)
Graphics quality (#15710, #15775)
D3D9 fixes (#15723, #15815, #15926, #16100, #16232, #16550)
3D tex (#15727, #15743)
Plugins/API (#15748, #16121, #16141, #16187, #16198, #16389)
Graphics glitches - wipeout (#15796), hunter x hunter (#15822), digimon/kof (#16358), marvel alliance (#16359), phantasy star games (#16504)
Fix clamp issues when GPU clipping available (#16049, #16068)
Reduce game effect glitches matching rendered textures more correctly (#15857, #15888, #15900, #15907, #15934)
Implement blending/logic operations in Vulkan (#15944, #15960)
Texture upscaling speedup for CPU bicubic (#15803)
Texture upscaling alpha fix (#16125)
Audio playback hack to prevent crash/hang in games (#15838)
Expand UWP file type support (#15847)
Handle "undefined" delay slot behavior more accurately, fixing some games (#15952, #15957)
Simulate rendering matrix update hardware bug correctly (#15976, #16123)
Hack workaround for softlock in Rewrite (#16006)
Fix line width (#16067)
Fix hardware tessellation (#16077, #16078)
Fix netplay in Cars (#16089)
JPEG artifacts - Tiger & Bunny, Yu-Gi-Oh, GEB (#16179, #16184)
Add LCD persistence shader (#16531)
```

-[Unknown]

**Comment by hrydgard** [comment]
Some of those are already in but far from all. List is getting long, but this is a big release, so at least a bunch of those are probably motivated to add, and some can be merged with existing lines too. I'll do that tomorrow.

**Comment by unknownbrackets** [comment]
Feel free to cull, I added the relevant ones from my list but may have been a little liberal with it.

-[Unknown]

**Pull request merged**
