### PR TITLE
SDL/Vulkan window resize improvements

### LINKED ISSUE #11014: [Vulkan] Resizing the window freezes the UI (SDL, Linux)
Resizing the window freezes the UI when using Vulkan (it stops drawing anything), however the process doesn't seem to hang.

There is no problem with OpenGL.

**OS:** Debian GNU/Linux testing (buster) x86_64
**Kernel:** 4.16.0-1-amd64
**CPU:** Intel i7-6700HQ (8) @ 3.500GHz
**GPU:** NVIDIA GeForce GTX 960M
**PPSSPP:** v1.5.4-971-g97546d30f

It may matter that I use i3 as window manager.

### PR DESCRIPTION
**Pull request by hrydgard**
~~Starting to work, but I think there's some sync issue left as it's not completely stable.~~

More stable now, for whatever reason.

Mostly fixes #11014

### CODE REVIEW

**Comment by unknownbrackets** [comment]
What I'd seen before when someone else tried this, was that resizing up consistently worked, but resizing down usually crashed.

Gonna requeue Travis.

-[Unknown]

**Comment by mrcmunir** [comment]
I tested it on ANV Intel driver is working window mode resize except the maximize button can't rezize display correct on rendering games.

captura de 2018-10-12 10-15-32

captura de 2018-10-12 10-19-26

This is not affected the UI PPSSPP

**Comment by hrydgard** [comment]
Moving to 1.8.0, no point in blocking 1.7.0 since we don't do official Linux releases.

**Comment by unknownbrackets** [comment]
I think we should at least merge in 8261e6f and f1dbef0.  Not sure if the other resize improvements have made the rest of this work.

Although my comment on the latter now: perhaps it makes more sense to show it everywhere now, or at least everywhere but UWP.  It does mean we show it on iOS, but we may eventually get Metal/MoltenVK there.  I don't think it's that misleading/confusing to show the backend even if it's the only one.

-[Unknown]

**Comment by hrydgard** [comment]
Rebased on master. Not sure if it's drivers or the improved handling of swapchain size in VulkanContext, but it seems stable enough to be usable now.

**Review by unknownbrackets — APPROVED** [review]

**Comment by mrcmunir** [comment]
Fullscren mode Working fine but in Windows mode the resize screen random size wrong (Only in game not affected by UI).
image

image

image

In spite of that it is completely stable now :)

**Pull request merged**
