### PR TITLE
Vulkan: Discard negative width/height framebuffer blits. 

### LINKED ISSUE #12531: Iron Man (USA) (En,Fr,Es) critical error (block transfer negative extent)
during the intro a critical error appears
ironman
[ppsspplog.zip](https://github.com/hrydgard/ppsspp/files/4002416/ppsspplog.zip)

### PR DESCRIPTION
**Pull request by hrydgard**
Should fix #12531 .

However, the root cause is still a little unclear..

### CODE REVIEW

**Comment by Gamemulatorer** [comment]
I think  #12531 not #12563.

**Comment by unknownbrackets** [comment]
This must mean that one of the input params (srcX, dstX, w, etc.) is negative, right?

-[Unknown]

**Comment by hrydgard** [comment]
Oops, dunno how I got the issue number so wrong, maybe issue number autocomplete messed it up.

I'm thinking it could be a result of the clipping acting on one of the rectangles being entirely outside their framebuffer, in the above clipping calculations..

Should be looked into deeper (and possibly also in the other backends) but this will fix the immediate issue...

**Comment by unknownbrackets** [comment]
Yeah, I actually reported a bug to GitHub - our issue #s are too long, anything over 5 digits autocorrects to some other issue # when you type "."... it's very annoying.

-[Unknown]

**Pull request merged**
