### PR TITLE
Initial texture replacement support

### PR DESCRIPTION
**Pull request by unknownbrackets**
See #4630 for more info.

This is already fairly usable, but we may want to not merge it until "stable".  I did add a version so we can maintain compatibility if we want to.

Not tested on Android, only on Windows.

Supports an ini with this syntax (ini file is optional, and all sections are optional):

```
[options]
version = 1
hash = quick

# By default, a file with .png at the end of the hash is used.
# Override below to share filenames or use custom filenames.
# To skip a texture (like videos) use a blank filename on the right side.
# Syntax: hash = filename.png
[hashes]
# Ignore the intro video textures.
099bf1c000000909 =
0993698000000909 =
09a47a0000000909 =
09ad024000000909 =
# Water animation.
099c0db096c0500ecd2f3e6e = water/frame1.png
099c2db0d26dc9a7966195cf = water/frame2.png
099c4db0fa2cbcfec0bd3e0f = water/frame3.png
099c6db0d17d9a67c7591d4f = water/frame4.png
# This texture is loaded at two addresses.  The content is the same.
094b89907dcca1a5ee284131 = 094b5a707dcca1a5ee284131.png
# Alias the extra mip level too.
094b89907dcca1a5ee284131_1 = 094b5a707dcca1a5ee284131_1.png

# This allows customizing the range of a texture that is hashed.
# Careful: sometimes the same address is reused later for a texture that needs more hashing.
# Syntax: address,w,h = w,h
[hashranges]
# Force the intro video to hash 480x272.
0x09936980,512,512 = 480,272
0x099bf1c0,512,512 = 480,272
0x09a47a00,512,512 = 480,272
0x09ad0240,512,512 = 480,272
# Clip logos to actual texture size.
0x090056d0,256,256 = 176,160
0x0900c4d0,256,64 = 208,56
```

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Cool!

Some ideas for further improvements (of course not required for merge):

  * I may have missed this in the code (just skimmed it), but an idea to ignore videos for replacement: In 99% of cases (well, every case except LBP) we know where the video decoder wrote a texture. So we could automatically mark it as not needing replacement, by just adding the addresses into aliases_ directly, for example.

  * As for mip levels, it may make sense to allow DXT or KTX texture files, both of which can store mipmaps directly.

  * If a user only provides the top mipmap, we could autogenerate the rest, if the game expects a mip chain.

**Comment by unknownbrackets** [comment]
Well, skipping videos was just an example.  Theretically, you could upscale each frame of the video as a separate png and it'd probably be fine.  But, yes, we could automatically skip videos.

Yeah, not against auto-generating mipmaps.  I'm assuming we would likely want more mip levels when using replaced upscaled textures, if anything (which is why this supports adding more miplevels.)

-[Unknown]

**Comment by hrydgard** [comment]
Well, ignoring videos automatically will be very useful to avoid having the SaveNewTextures mode writing hundreds of megabytes of PNGs in many games...

For video replacement it would be better to replace with a video file than a series of PNGs anyway (though, fan-producing upscaled video is not an easy task, heh), though that's a wholly different project (as we'd need to do things rather differently).

**Comment by unknownbrackets** [comment]
Hmm, video replacing is a complicated thing in some games.  I made some notes in #4630 on that subject a while ago.  One of the problems is some games implement their own looping, or switch video streams on the fly based on gameplay.  In that case, it'd be a lot easier to replace the video on the ISO than trying to do it via PPSSPP.

-[Unknown]

**Comment by LunaMoo** [comment]
Cool:3, thanks [Unknown] for working on it.

 When folders doesn't exist yet and SaveNewTextures is disabled it spams "Replacement not enabled" popup ~ every single texture doesn't matter if texture ReplaceTextures is enabled or disabled, other than that it works really well already:).

**Comment by i30817** [comment]
Thankfully PPSSPP already has 2d scalers unlike dolphin which apparently punted all 2d texture improvements to texture replacement.

(i find it ridiculous that games like RE2 and RE3 look better on the epsxe than the dolphin because of this).

**Comment by i30817** [comment]
Another thought is that if there existed a specialized extensible rom format - like in a certain closed issue for maxcso ;) - for reversible_translations/manuals/hacks/compression, another header could very well be texture replacement.

**Comment by unknownbrackets** [comment]
This still doesn't build on Qt, and I don't have a Qt environment set up to debug the linking problem.  It links fine elsewhere.

It doesn't even work on Qt so I'm halfway inclined to just ifdef it off on Qt.

-[Unknown]

**Comment by unknownbrackets** [comment]
I've implemented video replacement skipping now, and also removed the "g_iNumVideos" hack.

-[Unknown]

**Comment by hrydgard** [comment]
Very nice!

**Comment by unknownbrackets** [comment]
I've also hacked the Qt linking issue away.  It's not perfect, though, but maybe it can be improved later by someone maintaining the Qt build.

-[Unknown]

**Comment by hrydgard** [comment]
Good enough for me :)

**Comment by hrydgard** [comment]
LGTM, merge at will

**Comment by unknownbrackets** [comment]
> BTW, those games have problems with texture replacement and the fast texture cache showing outdated 'replacements' when you use stuff in the inventory. I dunno if PPSSPP has a equivalent problem, just a thought.

This could happen here too, but I think in general our hash is strong enough that this should be rare.  Using lazy texture hashing will affect replacements the same as regular textures, too.

-[Unknown]

**Comment by fuhuan416** [comment]
Excuse me, now can only save the textures please? I've already enabled the replacetexture and savetexture in ppsspp.ini. Also found a lot of textures appears in titleID folder. But i don't know what to do next? How to replace texture?

**Comment by unknownbrackets** [comment]
Modify the images and move them from ULUS12345/new/ to ULUS12345/.  Then it will use the modified versions.

It places them in `new/` by default so you can tell which ones you haven't modified yet.

-[Unknown]

**Comment by fuhuan416** [comment]
It's worked! It's awesome! Thank you guys, i love you all :)

**Comment by unknownbrackets** [comment]
In general, KTX support looks fairly desirable - people could use various tools like the "Mali Texture Compression Tool" to generate compressed textures with that too, which would work at least on any GLES3 device.

Potentially this could even be used to improve performance, as a "compressed texture pack" rather than a "HD texture pack".  Warning: there is some overhead added by texture replacement, though.

I noticed the Khronos loader can even decompress if ETC is unsupported:
https://github.com/KhronosGroup/KTX/blob/master/lib/loader.c

Unfortunately, it goes direct to GL, though.  Would be nice to support Vulkan and etc.

-[Unknown]

**Comment by johannes21j** [comment]
> See #4630 for more info.
> 
> This is already fairly usable, but we may want to not merge it until "stable". I did add a version so we can maintain compatibility if we want to.
> 
> Not tested on Android, only on Windows.
> 
> Supports an ini with this syntax (ini file is optional, and all sections are optional):
> 
> ```
> [options]
> version = 1
> hash = quick
> 
> # By default, a file with .png at the end of the hash is used.
> # Override below to share filenames or use custom filenames.
> # To skip a texture (like videos) use a blank filename on the right side.
> # Syntax: hash = filename.png
> [hashes]
> # Ignore the intro video textures.
> 099bf1c000000909 =
> 0993698000000909 =
> 09a47a0000000909 =
> 09ad024000000909 =
> # Water animation.
> 099c0db096c0500ecd2f3e6e = water/frame1.png
> 099c2db0d26dc9a7966195cf = water/frame2.png
> 099c4db0fa2cbcfec0bd3e0f = water/frame3.png
> 099c6db0d17d9a67c7591d4f = water/frame4.png
> # This texture is loaded at two addresses.  The content is the same.
> 094b89907dcca1a5ee284131 = 094b5a707dcca1a5ee284131.png
> # Alias the extra mip level too.
> 094b89907dcca1a5ee284131_1 = 094b5a707dcca1a5ee284131_1.png
> 
> # This allows customizing the range of a texture that is hashed.
> # Careful: sometimes the same address is reused later for a texture that needs more hashing.
> # Syntax: address,w,h = w,h
> [hashranges]
> # Force the intro video to hash 480x272.
> 0x09936980,512,512 = 480,272
> 0x099bf1c0,512,512 = 480,272
> 0x09a47a00,512,512 = 480,272
> 0x09ad0240,512,512 = 480,272
> # Clip logos to actual texture size.
> 0x090056d0,256,256 = 176,160
> 0x0900c4d0,256,64 = 208,56
> ```
> 
> -[Unknown]

when i open the game it is normal when i paly it kick me out then i delete Textures configuration setting then it stop kick me out please help

**Comment by hrydgard** [comment]
@johannes21j Please file a new issue instead of posting in old pull requests.

**Review by XLA23 — APPROVED** [review]

**Pull request merged**
