### PR TITLE
Adhoc Fix - various fix

### PR DESCRIPTION
**Pull request by anr2me**
Hopefully each commits can be compiled without error, because it was a pile of uncommitted changes where one unrelated stuff can get mixed up due to sharing the same variable.

Here are the main changes:

1. Removal of hardcoded workaround that was used to fix the stuck MessageBox on Naruto Shippuden Ultimate Ninja Heroes 3 and .hack//Link where the workaround have a side effect of 0.5 second lag when creating/connecting/joining a group.
2. Implement Adhocctl (and Apctl) state change timings properly to fix the stuck MessageBox on Naruto SUNH 3 and .hack//Link, which apparently also fix the joining issue on LEGO Indiana Jones 2 https://github.com/hrydgard/ppsspp/issues/13289
3. Making a better message transition on NetconfDialog using the new Apctl and Adhocctl timings.
4. Updated GameMode to fix Bomberman, and improved performance on BattleZone (currently only these 2 games are known to use  GameMode API)
5. Fix games developed by Falcom which have similar issue (Ys vs. Sora no Kiseki, Vantage Master Portable, and probably more since their netcode looked similar) https://github.com/hrydgard/ppsspp/issues/13493
6. An attempt to reduce stutters related to socket buffers.
7. Making the workaround that originally fix GvG Next Plus to be Optional (previously hardcoded) since this workaround affects/fix connecting issue on many games, and able to improve connectivity on high latency networks (ie. internet)
8. Games that are known to be affected by GvG workaround and have been fixed properly are:  (there should be more games but need to wait for reports from players)
- Gundam vs Gundam Next Plus
- Bleach Heat the Soul 7
- Dissidia 012
- Carnage Heart EXA
- Fate Unlimited Codes
9. Added socom.cc as an alternative Public Adhoc Server, due to similarity to myneighborsushicat.com (ie. have statistic web page)
~~10. Added an Optional workaround to slowdown FPS on games that runs too fast in multiplayer (ie. Fate Unlimited Codes, Bleach Heat the Soul 7) https://github.com/hrydgard/ppsspp/issues/13452~~

**Test builds:**
Win32&64: https://www.dropbox.com/s/i6699cyf1tzu29b/PPSSPP_1.10.3-adhocfix_Win32x64.zip?dl=0
Android(ARMv7): https://www.dropbox.com/s/dmz6jvesmm3uwp2/PPSSPP_1.10.3-adhocfix_ARMv7.apk?dl=0

### CODE REVIEW

**Comment by hrydgard** [comment]
So the bSlowdownNetworkFPS one, since it's apparently only needed in one game, do you think it might be a candidate for a compat.ini flag instead of an obscure .ini option_

**Comment by Pik-a-boo** [comment]
> So the bSlowdownNetworkFPS one, since it's apparently only needed in one game, do you think it might be a candidate for a compat.ini flag instead of an obscure .ini option?

It's needed for more then 2 games even because a Burnout game also got that issue in addition.
There could be even more games like that.

**Comment by ANR2ME** [comment]
> 
> 
> So the bSlowdownNetworkFPS one, since it's apparently only needed in one game, do you think it might be a candidate for a compat.ini flag instead of an obscure .ini option?

Well it's just a temporary workaround until a proper fix can be found, so it will most likely to be removed in the future, as it could have side effect of slowing down FPS in the wrong scene (which already runs at normal speed)

Based on the timestamp on the log when using JPCSP + prx files the AdhocPollSocket function returns within 1ms most of the time, so making it 7.5ms all the time is kinda absurd, amongst the 5 functions that were used during battle:
```
sceNetAdhocGetPtpStat(09fbf9f8, 09713900)
sceNetAdhocPollSocket(09fbfa0c, 2, 0, 1)
sceNetAdhocPtpAccept(1, [09fbfa54]=00:00:00:00:00:00, [09fbfa5a]=0, 0, 1)
sceNetAdhocPtpRecv(2,08bbb520,09fbfa5c,0,1)
sceNetAdhocPtpSend(2,08bbc060,09fbfa5c,0,1)
```
PtpSend have the most delay but varies (1~10ms) and i couldn't tell why it was varies, and GetPtpStat didn't get logged when using prx files so it could also have more than 1ms delay, but i couldn't get a stable 30 FPS by increasing the delay on these functions, while it was pretty stable on AdhocPollSocket function (only the characters intro scenes have the side effect of slower than 30 FPS)

PS: i can only use prx files as reference because i couldn't benchmark these functions on real hardware.

**Comment by ANR2ME** [comment]
> 
> 
> > So the bSlowdownNetworkFPS one, since it's apparently only needed in one game, do you think it might be a candidate for a compat.ini flag instead of an obscure .ini option?
> 
> It's needed for more then 2 games even because a Burnout game also got that issue in addition.
> There could be even more games like that.

i've updated the first post with test builds, have you test the workaround on Burnout games? does it gets a stable 30 FPS on that game?

**Comment by Pik-a-boo** [comment]
> > > So the bSlowdownNetworkFPS one, since it's apparently only needed in one game, do you think it might be a candidate for a compat.ini flag instead of an obscure .ini option?
> > 
> > 
> > It's needed for more then 2 games even because a Burnout game also got that issue in addition.
> > There could be even more games like that.
> 
> i've updated the first post with test builds, have you test the workaround on Burnout games? does it gets a stable 30 FPS on that game?

Didn't try specifically with that  but downclocking the emulated CPU might fix these speed-up issues anyway (as it fixed 1 game already).

**Comment by ANR2ME** [comment]
I'll remove the SlowdownNetworkFPS workaround as it's pretty useless without Force real clock sync :( it barely have any effect and the result are too varies on different hardware configuration.

It will probably takes a much longer time to investigate & fix the too fast FPS issue during multiplayer. Actually, i couldn't even tell whether it was related to networking code or not, because all those 5 networking functions that were used during battle doesn't seems to have any kind of delaying mechanism on JPCSP HLE, buat able to run at normal speed 30 fps.

**Comment by ANR2ME** [comment]
> 
> 
> > > > So the bSlowdownNetworkFPS one, since it's apparently only needed in one game, do you think it might be a candidate for a compat.ini flag instead of an obscure .ini option?
> > > 
> > > 
> > > It's needed for more then 2 games even because a Burnout game also got that issue in addition.
> > > There could be even more games like that.
> > 
> > 
> > i've updated the first post with test builds, have you test the workaround on Burnout games? does it gets a stable 30 FPS on that game?
> 
> Didn't try specifically with that but downclocking the emulated CPU might temporarily fix these speed-up issues anyway (as it fixed 1 game already).

Does down clocking the CPU to 55 mhz gives you a stable 30 fps even during lobby or menu? 
if it's it might be worth investigated if the game actually try to change the clock during the transition between 30 & 60 fps.

**Comment by Pik-a-boo** [comment]
The transition between menus was 60 fps for some reason when I downclocked.
But yeah it seems like 30 fps on menus and ingame.
And without sound issues as well.

**Comment by somepunkid** [comment]
Got it set to 222 currently. In same machine/2 instances/MP matches, I have stable sound and 30fps. Well then.

**Comment by ANR2ME** [comment]
> 
> 
> Got it set to 222 currently. In same machine/2 instances/MP matches, I have stable sound and 30fps. Well then.

So basically Fate Unlimited Codes only need a fixed 222 mhz clock? After investigating it, this game doesn't seems to use any function that can change CPU clock/frequency, so may be we can just use compat.ini for Fate Unlimited Codes and Bleach Heat the Soul 7 to set a fixed clock

**Comment by Pik-a-boo** [comment]
Seems like downclocking is different between hardware too though.
Although I had force real clock enabled here.

**Comment by somepunkid** [comment]
Yeah I just tried Bleach HTS7 with the same settings and was still getting 60fps. Seems like an issue.

**Comment by ANR2ME** [comment]
> 
> 
> Yeah I just tried Bleach HTS7 with the same settings and was still getting 60fps. Seems like an issue. Tried Fate again with and without clock sync/222 and got 40fps, just total inconsistency across the board. Somethings missing.

You need to disable the SlowdownNetworkFPS when using fixed clock, that things is not useful because the result too varies on different hardware.

Anyway, the fix for the FPS issue on Fate Unlimited Codes and Bleach Heat the Soul 7 will be made on a different PR as it will probably takes a really long time to have a proper fix, since it even hard to make a consistent result like this LOL.

**Comment by hrydgard** [comment]
OK, so you consider this PR finished? Almost wanna break it up like your previous massive multi-PR but not sure I can be bothered :)

**Comment by ANR2ME** [comment]
Yes, it's finished now :)
I tried to group related changes into a single commit to prevent getting compile errors, but didn't actually tried to compile each commits tho.

**Comment by ANR2ME** [comment]
Okay, it's done, each commits can be compiled now.

**Comment by Pik-a-boo** [comment]
Didn't you said you gonna remove the workaround?

**Comment by hrydgard** [comment]
I'll update the gradle thing :)

**Comment by hrydgard** [comment]
Thanks @ANR2ME , gonna go ahead and merge.

**Comment by Shawnjius** [comment]
@ANR2ME I did some more testing with Ys vs. and Vantage Master, and both worked with no issue between my PC and other players who are also on PC. All of that was with WLAN, Ad-Hoc, and upnp enabled; using myneighborsushicat.com. PC to PC works great.

However, I ran into issues with the Android apk. Although I can connect to others, I'll get a wi-fi disconnected error after playing for a few minutes. I also seem to have a problem with the Android apk consistently crashing on me. I have no clue why, as it always happens under different circumstances. It might just be a "me" problem, though. I'm running it on a Galaxy S10.

Another thing I can't figure out, is that while one friend was able to connect multiple instances locally, I can't seem to make the same thing happen on my end, or set up a match between my phone and my PC. This was using 127.0.0.1 and 127.0.0.2 as the proAdhocServer addresses respectively. When I attempted to connect two different instances on PC, one would always get an 80410b10 error.

Anyway, just wanted to share my findings.

**Comment by ANR2ME** [comment]
That error 80410b10 is ERROR_NET_ADHOCCTL_BUSY, usually only occurred within an instance if it tried to access Adhocctl again while previous access is still in progress (ie. still waiting for reply from AdhocServer), but shouldn't have anything to with other instances.

Anyway, we should probably discuss it at https://github.com/hrydgard/ppsspp/issues/13493 instead of here.

**Pull request merged**
