### PR TITLE
Update README.md for 1.10.0.

### PR DESCRIPTION
**Pull request by hrydgard**
Draft of README.md update, I'm sure I've missed lots, I just skimmed through the PR history.

Please add anything major that's missing (mainly user-visible changes here).

### CODE REVIEW

**Comment by iota97** [comment]
Here a few more:

* Add PPSSPP specific CWCheat (#12816, #12912)
* Allow rebinding of right touch screen analog (#12486)
* Reintroduce Cardboard VR (#12449)
* Support multipass shader and allow shader custumization with setting (#12905, #12901)
* Add option to prevent mipmaps from being dumped (#12818)
* Tilt control now have a base radius to help with deadzone (#12756)
* Auto rotating analog stick (#12749)
* Touch control position can now be snapped to a grid (#12517)
* Camera support on linux and mac (#12580, #12607)
* HiDPI redina display support (#12552)
* Rapid fire on touch control (#12601)
* Toggle mute button (#12643)
* Add option to resize game icon and more (#12646, #12637)
* Inflight frame in now configurable to reduce input lag (#12660)
* Add toggle mode to combo button (#12623)
* Chat (#12667)
* SDL mouse support (#12612)

**Comment by unknownbrackets** [comment]
Should mention the rpi4 mesa fix.

> * Fix missing CJK characters in in-game dialogs

Not on Linux/iOS, though... also Hebrew, Cyrllic, Greek, etc.  Maybe just "Support more languages within in-game dialogs"?

"Fix some state bugs in GLES" probably falls into "Graphics and compatibility fixes".

Might also add #12836 there for people on Intel.

Is #12519 a popular game, should we mention it specifically?

Might be worth mentioning Pangya (#12718) specifically too?

> * VSync fixes, support for frame duplication for 30Hz games

I'd say, "VSync now supported on all backends, frame duplication option added for 30 Hz games"?  I don't want people getting all excited that vsync will be "fixed" on their opengl device if they think it's not working.

> * HLE timing fixes, helping some games (#12635)

Might not be worth mentioning, or else we should mention that game.  I got the impression it helped, but it wasn't clear...

> Camera support on linux and mac (#12580, #12607)

We should just have one line for camera support.

> SDL mouse support (#12612)

Maybe we group this with #12817?  And we should definitely mention #12916 too, maybe a different line... not sure.

-[Unknown]

**Comment by hrydgard** [comment]
Thanks iota and unknown, incorporated your feedback.

**Comment by hrydgard** [comment]
Thinking about dropping the "1." from the version number at some point, it's getting more and more pointless.... There's no clear path to a 2.0 :)

**Comment by unknownbrackets** [comment]
Introducing the new PPSSPP 10, because a single digit can no longer contain our major version number.

Without any definition on what would mean a 2.0.0, I'd say it doesn't matter whether we go to 2.0.0 or 1.24.0 or what, but I'd have to double check if 42.0.0 would confuse the poor reporting system...

-[Unknown]

**Comment by Gamemulatorer** [comment]
Worth mentioning?

(#12898) SW rendering now support on OpenGL 2.0?

(#12857) Fixed Mumbo Jumbo games freeze on loading

(#8714) Allow 5X resolution for all devices

(#12652) Speed up game loading

**Comment by HiImBrala** [comment]
New Language Submodule?

**Comment by hrydgard** [comment]
Thanks Gamemulatorer.

What new language submodule?

**Comment by HiImBrala** [comment]
> Thanks Gamemulatorer.
> 
> What new language submodule?

Croatian(Hrvatski)?

**Comment by hrydgard** [comment]
Oh, new language, not new language submodule. Yes :)

**Comment by Panderner** [comment]
How about the grey screen intro video in Strike Witches Hakugin no Tsubasa (#11898) is fixed in 1.10.0?

**Comment by Panderner** [comment]
And fixed antialias-lines glitches in Persona 3 Portable and Summon Night 5 (#12695)

**Comment by leopard20** [comment]
> Thinking about dropping the "1." from the version number at some point, it's getting more and more pointless.... There's no clear path to a 2.0 :)

Might as well do it now. Personally speaking, I never quite liked seeing two digits in the minor version number. It looks a bit confusing (e.g 1.10.0 looks like 1.1.0 at first glance), and also, if someone kept multiple versions of your emu on their computer,the sorting file would put 1.10.0 before 1.9.3.
And even regardless of that, after all these years, I suppose it does make sense to go to v2.0.

**Comment by LunaMoo** [comment]
> (...)
> if someone kept multiple versions of your emu on their computer, the file sorting would put 1.10.0 before 1.9.3.

 As it would put version 10.0.0 before 2.0.0 so it's more about fixing your file sorting than anything about versioning.

 Imo it's better to go with 1.10 etc. because many people place too much expectations into primary digits of version and it's confusing to many of them, some could get the idea that PPSSPP 2.0 is PSVita emu if PPSSPP 1.0 was PSP emu just as PCSX and PCSX2, or that it brings some crucial change or even decision ie. some FOSS changed primary version number after becoming closed source and paid software etc. 
 Some people even go with the idea that software they like "deserves" new primary digit as if it was something glorious, when it's not and people should learn to stop placing weight at it, they should learn to read the new features and fixes in readme, learn to update and stop concentrating soo much on what version PPSSPP has.

**Comment by Gamemulatorer** [comment]
> And even regardless of that, after all these years, I suppose it does make sense to go to v2.0, just like how you moved from 0.9 to 1.0.
I agree ppsspp v2.0 is the right version compare to v1.10 imoo :)

**Comment by HiImBrala** [comment]
Also fixed Shrek Smash'n Crash Racing Atrac3+ issue

**Comment by Panderner** [comment]
> Also fixed Shrek Smash'n Crash Racing Atrac3+ issue

No @HiImBrala this issue is not fixed maybe the next version or future. for me still freezing in title screen.

**Comment by HiImBrala** [comment]
> > Also fixed Shrek Smash'n Crash Racing Atrac3+ issue
> 
> No @HiImBrala this issue is not fixed maybe the next version or future. for me still freezing in title screen.

:|

**Comment by leopard20** [comment]
> As it would put version 10.0.0 before 2.0.0 so it's more about fixing your file sorting than anything about versioning.

I was mentioning one example as to why it would be confusing. Plus, at the current pace of development, it'll take many many years to get to version 10.0. And it is not MY sorting algorithm. Some Android file explorers, for example, use that method of sorting.

> PPSSPP 2.0 is PSVita emu if PPSSPP 1.0 was PSP emu just as PCSX and PCSX2

That "2" in front of PCSX2 is part of the emulator's name, not it's version.

> or that it brings some crucial change or even decision ie.

Are you saying when moving from 0.9 to 1.0, there were any crucial changes? I would say the changes are even more significant now than then.

> Some people even go with the idea that software they like "deserves" new primary digit as if it was something glorious, when it's not and people should learn to stop placing weight at it, they should learn to read the new features and fixes in readme, learn to update and stop concentrating soo much on what version PPSSPP has.

That's not what I said. I'm talking about consistency between major version changes.
0.9 -> 1.0
1.9 -> 2.0

Either way, I don't care that much, so no point in arguing.

**Comment by Anuskuss** [comment]
@leopard20 v2.0 is reserved for XMB emulation and UMD Video support ;)

**Comment by HiImBrala** [comment]
> @leopard20 v2.0 is reserved for XMB emulation and UMD Video support ;)

Won't probably happen,since UMD Videos are 18+ most of time,and XMB support would violate copyright from Sony itself

**Comment by hrydgard** [comment]
I think I'll stick to 1.10. So be it if it's a little confusing :)

**Comment by RokkumanX** [comment]
I vote for PPSSPP Super Mecha Death Christ 2000 BC Version 4.0 Beta, honestly it just feels so right to say it, you feel the tongue roll so good in your mouth.

Say it out loud, **PPSSPP Super Mecha Death Christ 2000 BC Version 4.0 Beta**

**Comment by iota97** [comment]
`VSync now supported on all backends, frame duplication option added for 30 Hz games` should mention PR as well: #12659, #12602.

**Comment by Anuskuss** [comment]
@HiImBrala Please educate yourself. Emulation is not illegal nor does it violate copyright. If that was the case the whole project would be gone by now.

**Comment by HiImBrala** [comment]
> @HiImBrala Please educate yourself. Emulation is not illegal nor does it violate copyright. If that was the case the whole project would be gone by now.
> 
> **Edit:** Also AFAIK PPSSPP has support for 18+ games so your first point is nonsensical as well.

First of all,emulation is not illegal,yes,but using Sony's material to emulate something is illegal,since emulating PSP's XMB would result in some issue

DOA:Paradise and Criminal Girls aren't really 18+,as UMD Videos are not supported

**Comment by boy13epic** [comment]
better pro online

**Comment by hrydgard** [comment]
PPSSPP is not doing XMB both because it makes no sense on touchscreens, and because there's a lot of stuff that needs to be implemented if we wanted to get the real XMB to boot that's not needed for games. No need to discuss that here.

**Comment by HiImBrala** [comment]
> better pro online

My last in Ad-Hoc conversation to light up some facts.Henrik said himself that Ad-Hoc is not their priority.Why?If you ask me,it would be waste of time to make better Ad-Hoc functions,while for same time,you could make like games that don't run at all perfectly playable,not to mention that Ad-Hoc isn't actually very requested,because of ways to do online sucks(DMZ opens your ports,and sometimes you need to disable firewall,and that means problems),and there are other people working on it and they have their own forks of PPSSPP,sadly,i doubt you'll find them since God Complex non-rightfully deleted link to a build of user AdamN which implemented chat and UPnP support.If you want better Ad-Hoc,lurk around forums,you will find it,i can't help you.

**Comment by sum2012** [comment]
Add real support "Hatsune Miku Project Diva Extend" chinese patched version
#13028

**Comment by HiImBrala** [comment]
Should we mention Sims 2 Castaway Lag on Android fix.Even tho,i'm not sure does it work as intended

**Comment by HiImBrala** [comment]
Also Sega Rally Revo,black sky with Vulkan backend is fixed - #12819

**Comment by Gamemulatorer** [comment]
@hrydgard ETA of v1.10.0?

**Comment by HiImBrala** [comment]
> @hrydgard ETA of v1.10.0?

Saturday if nothing goes wrong

**Comment by Anuskuss** [comment]
Thank you @hrydgard and @unknownbrackets (and countless other contributors) for yet another awesome release. I'd like to suggest a tiny QoL change: I always like to read the changelog and maybe even read up on the issues related to it. Would be great if instead of just the issue number it would actually be a clickable link.
Just replace `(?:#(\d+))` with `[https://github.com/hrydgard/ppsspp/issues/$1]\(#$1\)`.

**Comment by hrydgard** [comment]
You're right, I'll try to get around to implementing that on the site, at least (where I have a script that processes the page anyway).

**Pull request merged**
