### PR TITLE
UI: Add simple support for a custom background

### PR DESCRIPTION
**Pull request by unknownbrackets**
Essentially, this is a cleaned up version of xiushudongfang's implementation that supports all platforms, but no selection UI.  

This allows customizing per #8568 - if you put your file in PSP/SYSTEM/background.png.

Potentially could add the ability to select a game's background from GameScreen, or a setting to select an image using a browser.

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Maybe should remove the floating X/O/square/triangle if background is set? They might not always fit.

Not really sure it makes that much sense to change background but not things like selection color etc...

**Comment by unknownbrackets** [comment]
We can remove - they show as a 10% opacity white, so most of the time they will either look mostly fine, or not be visible.  To me they seem like a nice way to feel like the UI isn't frozen.

We already show most things on top of game backgrounds while in game.  I've mainly tested this by copying pic0.png over to background.png.

That being said - I'll make some quick updates to make more colors configurable, shouldn't be hard.

-[Unknown]

**Comment by unknownbrackets** [comment]
Okay, now you can specify colors under `[Theme]`.  Still no UI for either, and can't customize the icons (currently.)

-[Unknown]

**Comment by DarkLegend481** [comment]
.gifs are compatible with this resource?

**Comment by xiushudongfang** [comment]
Unfortunately not.

**Comment by unknownbrackets** [comment]
Only jpeg and png are supported.  Animation is a whole different problem.

-[Unknown]

**Pull request merged**
