### PR TITLE
VK: Re-apply the old Adreno driver bug workaround. Fixes #13910.

### LINKED ISSUE #13910: Rockman Dash 1 and 2 graphics broken since v1.10.3-1000-g349fc7071
This issue has graphics glitches for Rockman Dash games for Vulkan.

Rockman Dash 1:
Screenshot_2021-01-12-07-40-42-992_org ppsspp ppsspp
Screenshot_2021-01-12-07-47-05-463_org ppsspp ppsspp
Screenshot_2021-01-12-07-47-14-876_org ppsspp ppsspp

Rockman Dash 2:
Screenshot_2021-01-12-07-40-54-143_org ppsspp ppsspp
Screenshot_2021-01-12-07-41-13-345_org ppsspp ppsspp
Screenshot_2021-01-12-07-47-31-385_org ppsspp ppsspp

Last build work: v1.10.3-987-g327eb21e0
First bad: v1.10.3-1000-g349fc7071

### LINKED ISSUE #13923: Space Invaders Extreme Sprites are not transparent for Vulkan
Look at the screenshot below:
Screenshot_2021-01-16-18-30-54-425_org ppsspp ppsspp

Last build work: v1.10.3-987-g327eb21e0
First bad: v1.10.3-1000-g349fc7071

### PR DESCRIPTION
**Pull request by hrydgard**
Fixes #13910.

Fixes #13923 too.

### CODE REVIEW

**Comment by sum2012** [comment]
Does it have bad effect of Mali GPU ?

**Comment by hrydgard** [comment]
No, I don't think so.

**Comment by sum2012** [comment]
We already break Mali GPU  in Vulkan in  between v1.7.3 to v1.8.
I have told ANR2ME  to make android build to me to test.

**Comment by hrydgard** [comment]
This just restores this particular check to how it was in Vulkan before -1000, so should be safe.

**Pull request merged**
