### PR TITLE
Fix case sensitivity messup in sceIoDread.

### PR DESCRIPTION
**Pull request by LunaMoo**
Check Wolf3D homebrew as an example:
-[download](http://www.brewology.com/downloads/download.php?id=9730&mcid=1)
the game checks for lowercase files in it's code, however only returns results when the files are all caps.

 On PSP it should work with both lower and upper case, so I assume we have to list all files as uppercase and that's the proposed change in this pr.

### CODE REVIEW

**Comment by BenMcLean** [comment]
I helped discover this :)

**Comment by unknownbrackets** [comment]
I haven't tested it, but I did see jpcsp/jpcsp@63aa33d.

I wouldn't be at all surprised if 8.3 filenames got lowercased only.

-[Unknown]

**Comment by LunaMoo** [comment]
I'm not sure if I understand "if 8.3 filenames got lowercased only", but looking at jpcsp I guess this needs a bit of change to affect only all lowercase with filename shorter than or equal 8 and extension shorter than or equal 3:].

**Comment by unknownbrackets** [comment]
What I mean is this:

https://en.wikipedia.org/wiki/8.3_filename
Also see: https://en.wikipedia.org/wiki/Design_of_the_FAT_file_system#VFAT_long_file_names

PSP uses VFAT for memory sticks.  This behavior may likely only occur for memory sticks, and probably lowercase names , although there are limitations on ISOs, I would not assume they behave the same way.  I'd guess this is a side-effect of the peculiar behavior when the basename or extension is entirely lowercase, and I wonder if it only happens when Windows CREATES the files (i.e. by USB mount) or if it also happens when sceIo creates the file.

-[Unknown]

**Comment by LunaMoo** [comment]
How does it look now? I guess 8.3 filenames can include other signs, but it's untested how psp handles those, so I followed jpcsp tests and added 0-9 since this game can use it in filenames as well.

**Comment by unknownbrackets** [comment]
Hmm, did you try running tests?

https://github.com/hrydgard/pspautotests/commit/5a542d1dd2ebf9464d0789462682d54bc296a36b
https://github.com/hrydgard/pspautotests/blob/5a542d1dd2ebf9464d0789462682d54bc296a36b/tests/io/directory/directory.c

It looks like this would fail that test, but maybe that's only for host: - definitely makes me think this doesn't happen for all filesystems.

Again, I would guess this is because Windows XP saves "test.txt" as "TEST.TXT" with a flag to say "basename is lowercase, extension is lowercase."  This is described in the Wikipedia articles linked above.  Probably only happens when Windows 2000 and higher create the file, but not when a PSP creates the file (since it would likely create an LFN record for "test.txt".)  This may mean that if you used Windows 98, and tried to put Wolf3D on your PSP, it might also fail.

-[Unknown]

**Comment by LunaMoo** [comment]
No idea how to run those tests, if they should be ran on psp ~ don't have any to test it.

 If you propose a better solution that's fine, I know you like to nitpick and it's great when it improves the code, but if this is about badly handling a situation when someone will get some files from outdated operating system that was not releavant for at least 15 years, then I don't know what to think about it and I think I'm too tired today to understand anything else in this.:|

 The actual situation is simple, PSP sees some filenames as uppercase, PPSSPP does not, game fails to load unless the user renames the files to uppercase, no outdated windows involved.

**Comment by unknownbrackets** [comment]
I don't like this "you like to nitpick" attitude of yours.  You're not even reading what I'm writing, so I'm going to stop wasting my time.

This code is wrong.

-[Unknown]

**Review by unknownbrackets — CHANGES_REQUESTED** [review]
@hrydgard Please do not merge, read my comments.  LunaMoo does not care about affecting umd0 filesystems.

-[Unknown]

**Comment by LunaMoo** [comment]
Ok, I don't like this "I don't like this" attitude either, I do read, just not understand what you really mean and linking to a wall of text doesn't help anyone.

**Comment by unknownbrackets** [comment]
You should probably open a separate issue for that; it should be fixed, but not in a way that breaks disc based games.  Usually contributing to open source projects in general falls apart when someone says, "I don't care about your nitpicks, my code is right."

-[Unknown]

**Comment by hrydgard** [comment]
I think it's a bit uncharitable to say that LunaMoo doesn't care, but unknown is right in that we definitely should not make global changes that might affect the behaviour of listing files from other filesystems like UMD, which do not use FAT, to fix issues that are quite obviously somehow related to FAT backwards-compatibility. Needs more investigation - while we do have some ugly hacks here and there, I do like my hacks a lot more focused.

**Pull request closed without merging**
