### PR TITLE
SDL: support HiDPI on wayland

### PR DESCRIPTION
**Pull request by hch12907**
So this is really just #17651 with additional fixes to try and nail down where the bugs are on MacOS.

I still don't own a Mac so I am marking this as a draft until that platform is tested.

(I included a commit from #17757 because I can't test the build otherwise)

### CODE REVIEW

**Comment by hch12907** [comment]
Slight note: I forced the DPI to be 1.0 because it seems like the automatically calculated DPI would make everything look much bigger.

You can printf `g_DesktopDPI` in `UpdateScreenDPI()` if you want to know what the DPI is. Use `--dpi` to force the program to show in a specific DPI.

**Comment by hrydgard** [comment]
This still breaks things badly unfortunately (mouse input not working or maybe clicking in the wrong place) and after a window resize, scale is busted.

**Comment by hch12907** [comment]
Turns out MacOS needs a flag to be set in `Info.plist` for HiDPI.

Some sources also mention something about setting the `NSPrincipleClass` to `NSApplication`, but I'm not entirely sure about that...

**Comment by hrydgard** [comment]
I'll check this again shortly. There's a merge conflict that needs resolving, btw.

**Comment by hch12907** [comment]
You mean the UI was larger than the window itself? Strange...

What do the debug messages show? This is what mine looks like on Wayland (130% scale factor):
```
drawable_width = 1868, window_width = 1437, calculated DPI = 1.300626
drawable_width = 1877, window_width = 1444, calculated DPI = 1.300554
drawable_width = 1891, window_width = 1455, calculated DPI = 1.300344
drawable_width = 1920, window_width = 1477, calculated DPI = 1.300609
```

**Comment by hrydgard** [comment]
Sorry, could you rebase again? I pushed some broken code...

**Comment by hrydgard** [comment]
Sorry, I wasn't on the latest commit. Here are the current results on Mac:

* On startup:
image

drawable_width = 1692, window_width = 846, calculated DPI = 2.001182 (clicks are wrong)

* After resize:

image

drawable_width = 1712, window_width = 856, calculated DPI = 2.001168 (clicks match. Looks the same as above though)

master:

image

**Comment by hch12907** [comment]
I think I see why I couldn't reproduce the issue on Wayland now: SDL applications on Wayland receive a resize event immediately on the first frame, hence the (wrong) values used in initialization were overwritten.

**Comment by hrydgard** [comment]
Working perfectly now.

**Review by hrydgard — APPROVED** [review]

**Comment by hrydgard** [comment]
Actually, I take that back - we still have a problem with MoltenVK on Mac (Vulkan), for whatever reason:

image


Wonder if we should just add a check to ignore.. I'll try to take care of this soon.

**Comment by hch12907** [comment]
FWIW, you can do `if (backend == Vulkan) { g_ForcedDPI = 1.0 }` at the meantime...

(also, it seems like font atlas is still used for font rendering, possibly lack of sdl2_ttf package?)

**Comment by hrydgard** [comment]
yeah, I'll do a quickfix like that.

Gonna have to look into the font rendering. It indeed seems we'll want to ship a SDL2_ttf framework as well, it's not included in the SDL2 distribution we're missing. Or we should add native Mac font rendering.

**Pull request merged**
