### PR TITLE
Avoid polluting glstate in GetTempFBO()

### PR DESCRIPTION
**Pull request by unknownbrackets**
I think this is #8145.  Basically, when creating a temp FBO for blending (or for depal), we would kill some of the state setup for rendering.  And then proceed to render that way.

This could fix other things, maybe even #8035.

Maybe I can just preserve for all callers, but I was worried some might be setting state semi-intentionally.  It's called in a lot of places.

Anyway, this also adds `force()` methods to all the glstate properties.  My rationale is just to keep the syntax the same, so it's clearer.  I thought about doing an auto/smart thing, or `unforce()`, but decided against the complexity for now...

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
unfortunately,did not help https://github.com/hrydgard/ppsspp/issues/8035

**Comment by daniel229** [comment]
it helps https://github.com/hrydgard/ppsspp/issues/8145

**Comment by LunaMoo** [comment]
Yeah can confirm it does help, but doesn't seem to fix #8145 completely. When simulate block transfer is activated it still shows gray color instead of being fully transparent. Works fine without.

**Comment by unknownbrackets** [comment]
Is it the same draw that does the gray?  Maybe they are separate problems.  Also, are you loading a savestate?  It could be broken in the savestate.

-[Unknown]

**Comment by LunaMoo** [comment]
Same texture and nah that was without savestate. Also weirdly if I try to make screenshot of it it either shows black or correct - fully transparent. maybe it's actually changing very fast between the two appearing gray.

**Comment by hrydgard** [comment]
Ugh, state is bad... Can't wait for modern APIs.

**Pull request merged**
