### PR TITLE
Enable extra ram for The Elder Scrolls Travels Oblivion USA Beta and Melodie alpha

### PR DESCRIPTION
**Pull request by daniel229**
For boot up those games.

### CODE REVIEW

**Comment by daniel229** [comment]
download link
Enable extra ram for The Elder Scrolls Travels Oblivion USA Beta
https://drive.google.com/file/d/0BzGZGDfFE68zQ0g2ekNxcWUyb28/view?usp=sharing

Melodie alpha
https://drive.google.com/file/d/0BzGZGDfFE68zQ0l4SmZEMndvRms/view?usp=sharing

**Comment by LunaMoo** [comment]
Wonder how those commercial games get access to more memory when it supposedly only be a feature of CFW and used as a cache in normal situation:|.

 Is any of those games legit "demos" or all warez stuff that someone leaked on the net?

**Comment by daniel229** [comment]
Looks like it's not legit.

**Comment by unknownbrackets** [comment]
@LunaMoo devkit devices had extra RAM enabled to allow for debugging features.  Some future stage of development for these unreleased prototypes would've been to slim them down and use less RAM and work in production devices.

That's unfortunate.  I think it'd be a great PR move to release an unfinished demo, since it would likely only make people more excited about a future release - especially if it was still not very official or easily obtained and felt "skunkworks".  But, it's their content, and their decision.

-[Unknown]

**Comment by LunaMoo** [comment]
Oh I see, thanks for clearing that.

 People who own those copyrights have no idea what's popular nowadays, enough to check youtube to see much more alpha/beta/prototype/early access etc., even physics sandboxes being sold as simulators get more views than games. Free advertisement.

**Comment by hrydgard** [comment]
Well, adding the IDs can't hurt, in the unlikely case employees of those companies want to legally play their old betas... heh.

**Comment by unknownbrackets** [comment]
Who knows?  That doesn't sound so unlikely really, not like the employees can't have nostalgia.  And if they decided to do the PR thing, PPSSPP's debugger might help, heh.

-[Unknown]

**Pull request merged**
