### PR TITLE
Add Restart Emulation on pause screen

### PR DESCRIPTION
**Pull request by zminhquanz**
- Update credits
- It's convenient on mobile to restart emulation

### CODE REVIEW

**Comment by hrydgard** [comment]
Yes, but is it so frequently used that it merits its own button? The pause screen is quite complicated already. It's easy to just exit and restart the game by pressing its button on Recent. Not sure.

I'm fine with adding you to credits though :)

**Comment by zminhquanz** [comment]
But i think some people play games if someone having issues , or problems , they can easily to restart emulation , not to perform multiple actions to exit to menu , and click on games in Recent :)

**Comment by LunaMoo** [comment]
If you need a quick reset on all platforms, better to just make it into mappable key, quick reset is only really useful when debugging games or working with texture replacement, nothing else would require constant resets and there's no point bothering everyone with extra button just to make a rarely used function one less click to do.

 Realistically user-issues that could be solved by reset happen due to abusing savestates. From my forum experience affected people often wouldn't even have normal savedata and usually don't understand that loading state restores their problems, so whenever they have to click two or three times to reset doesn't solve anything. We would really have to have another on screen message to inform the users that they didn't saved/loaded for the last X hours and game might be unstable or something alike since that would in many more complex games happen even on real hardware due to tiny memory leaks and other issues they get released with and of course abusing savestates will simulate such situation even for people who would play only few minutes a day.

**Comment by zminhquanz** [comment]
I'll check out about that to make sure about this

**Comment by unknownbrackets** [comment]
I tend to agree that this isn't that commonly used.  What issue did you run into specifically that required restarts?

When I'm not actively coding, it's uncommon that I have a good reason to restart a game in PPSSPP.

-[Unknown]

**Comment by zminhquanz** [comment]
@unknownbrackets what do you mean ?

**Comment by unknownbrackets** [comment]
Was there a game you or someone had to restart a bunch of times that made you think of adding this feature?

-[Unknown]

**Comment by zminhquanz** [comment]
@unknownbrackets As you say , i explain about this on this above

**Comment by hrydgard** [comment]
No you don't. Our question is:   Do people really use Reset so much that it's worth taking up space on the pause screen for it? If they don't, it's still very easy to just exit the game and start again. 

If they are actually using Reset so much that it's worth a button, then the question is why? Why do people reset all the time? Shouldn't be necessary if everything is working correctly.

**Comment by zminhquanz** [comment]
I think it's still use it to much when you config too many or texture replacement

**Comment by zminhquanz** [comment]
if they are vote is unnecessary , i will close this

**Comment by zminhquanz** [comment]
If you don't accept about it , i will close this

**Pull request closed without merging**
