### PR TITLE
ignore vscode files

### PR DESCRIPTION
**Pull request by oltolm**
I use VSCode. If I change the settings git shows changes in the working directory. I removed the VSCode settings and added them to `.gitignore`.

### CODE REVIEW

**Comment by hrydgard** [comment]
But, the launch file and tasks files are useful. 

How about keeping these two files, but also keep your newly added ignore so that all other settings files remain ignored?

**Comment by bbb651** [comment]
If you just want to ignore them locally you can add them to `.git/info/exclude`, or gitignore them and `.gitignore`

**Comment by hrydgard** [comment]
Alright, I guess we can get rid of these and have example launch and task files somewhere instead.

**Comment by oltolm** [comment]
Thanks, ignoring files locally does not work if they are checked in. I already tried it.

**Pull request merged**
