### PR TITLE
Support drawing around notches on Android displays. Fixes #12261

### LINKED ISSUE #12261: Full-screen mode on phones with a camera inside the screen (notched)
### What happens?
PPSSPP doesn’t work in full screen mode, with the dive mode I get a white strip that cuts the space from the beginning of the camera.
PEQpQmXZtO4

### What *should* happen?

The image will stretch to full screen including the space around the camera. As in other emulators.
с

### What hardware, operating system, and PPSSPP version?  On desktop, GPU matters for graphical issues.

Samsung Galaxy A60
Android 9.0
PPSSPP v1.8.0

### PR DESCRIPTION
**Pull request by hrydgard**
Finally finished this up, but I'm struggling to see the point - all phones with notches are so wide anyway that you don't get any additional PSP display area, and do you really want to put controls out there in the limit? You'll just smudge up the camera. Anyway, it's not really any worse so... 

Here's what it looks like on a Pocophone F1:

### CODE REVIEW

**Comment by Panderner** [comment]
How about iPhone X, XS, and 11?

**Review by unknownbrackets — APPROVED** [review]
I mean, the menu looks better with the background behind it, at least.

-[Unknown]

**Comment by unknownbrackets** [comment]
This makes it easier to implement any similar change for iOS devices, but doesn't actually get the notch information from iOS.  Contributions welcome.

-[Unknown]

**Comment by Panderner** [comment]
Reverse landscape mode doesn't seem to be right

**Comment by hrydgard** [comment]
@Panderner can you take a picture?

**Comment by hrydgard** [comment]
Ah, I see, I could repro. When going directly from landscape to reverse landscape, it doesn't update the margins properly. I guess we might be doing the checks in the wrong place, I'll get this fixed.

**Comment by hrydgard** [comment]
Pushed a fix, should be ok now.

**Comment by Panderner** [comment]
And how about Touchscreen test and GPU Test at the developer tools menu? The letters blocked by the notch.

**Comment by hrydgard** [comment]
Oh, right, thanks for reminding me about those. They indeed don't properly take the notch into account, I'll fix them up later.

**Comment by hrydgard** [comment]
Fixed.

**Pull request merged**
