### PR TITLE
Vulkan: Force align verts to 4 on Apple devices

### PR DESCRIPTION
**Pull request by unknownbrackets**
Quick change based on comments in #15149, although I will be surprised if this somehow affects the NANs we saw...

-[Unknown]

### CODE REVIEW

**Comment by hrydgard** [comment]
Doesn't seem to change anything, unfortunately.

**Comment by ANR2ME** [comment]
Is this also includes unsupported vertex stride? https://github.com/cemu-project/Cemu/pull/445/files

> When an unsupported vertex stride is given, replace with zero. Trying to set to any other value makes all textures corrupted, flicker and cover the whole screen. Also added output to log
>
> Effects include many missing textures are now rendered visually correct. Any related missing textures may also be rendered but may have incorrect position and orientation.

**Comment by unknownbrackets** [comment]
This doesn't pass zero, which was changed in the newer linked PR (https://github.com/cemu-project/Cemu/pull/534.)  Even if it doesn't fix the M1 issue, it might make sense to merge it given Cemu presumably hit some sort of driver issue.  It seems fairly cheap.

It would mostly matter in cases where games are using 8-bit verts and not using 8888/etc.  It did seem like the GTA frame dump used an affected format, one way or another.

-[Unknown]

**Comment by hrydgard** [comment]
Whether this fixes anything or not, actually I think we should get this in. It can't possibly hurt.

**Pull request merged**
