### PR TITLE
State optimizations (experimental)

### PR DESCRIPTION
**Pull request by hrydgard**
Avoids recomputing things like blendstate, vertexshaderID etc per draw call if none of the underlying information has changed. Should result in a 1-4% speedup overall, which seems to be the case though needs more testing.

Actually for D3D11 the speed increase is a bit bigger than that.

- [x] Need to change vertexFullAlpha logic
- [ ] Validate allowShaderBlend dirties
- [x] Brave Story missing octopus (related to DIRTY_BLEND_STATE somehow)
- [ ] MAX_REASONABLE_BLITS_PER_FRAME?
- [ ] SetDepthUpdated?

### CODE REVIEW

**Comment by zminhquanz** [comment]
Do you see improvement in heavy games like GOW ?

**Comment by hrydgard** [comment]
Minor. Needs a lot more testing, there's also a couple more optimizations I want to do before merging this (avoiding recomputing fragment shader IDs too).

**Comment by daniel229** [comment]
Breaks brave story 
this branch


master

**Comment by hrydgard** [comment]
Thanks!

**Comment by hrydgard** [comment]
Just rebased on master. Issues probably still remain.

**Comment by hrydgard** [comment]
Rebased again. Can't be merged as is because the checks need to be added to the other three backends as well, otherwise they might break (though probably not really).

**Comment by hrydgard** [comment]
Now also optimizing out fragment shader ID calculation when possible.

With these changes, D3D11 goes from very fast to bonkers fast in games with many drawcalls.

Though there are still glitches to iron out so not ready for merge, this might have to wait for 1.5 because I'm intending to release 1.4 in about a week.

**Comment by unknownbrackets** [comment]
Brave Story should be fixed now in GLES.  It's still wrong in D3D11, and I didn't check anything in D3D9/Vulkan.  Updated pull description with checkboxes for some other possible issues.

-[Unknown]

**Comment by hrydgard** [comment]
I'm going to re-do this, by first reorganizing the state code without adding the dirty tracking, testing and merging that, and then applying the dirty tracking separately afterwards. 

That will make this more reviewable and less prone to bugs.

**Pull request closed without merging**
