### PR TITLE
Using `if constexpr` C++17 where actions are performed with constant template parameters

### PR DESCRIPTION
**Pull request by GermanAizek**
@hrydgard,
More info here: https://stackoverflow.com/questions/57210909/c-template-extract-bool-parameter#answer-57211067

### CODE REVIEW

**Comment by hrydgard** [comment]
Huh, would've thought the compiler could always do this on its own. I guess beneficial in debug builds? Hm, yeah, one of the comments mention that...

**Comment by GermanAizek** [comment]
@hrydgard, my clang-format broke code format in PR. how do I format commits?

**Comment by hrydgard** [comment]
I don't understand what you mean. Broke format?

**Comment by unknownbrackets** [comment]
There seem to be some whitespace and indentation issues.

-[Unknown]

**Comment by hrydgard** [comment]
@diegodorarocks793 Please stop thumb-downing everything, if you don't stop I'll block you from the project.

**Comment by hrydgard** [comment]
I've got a branch with the whitespace fixed now. What do you think @unknownbrackets , yay or nay? given that this will likely only affect debug builds in reality, i'm not sure. though it doesn't exactly make the code very much complicated, just an extra level of indentation here and there.

**Comment by unknownbrackets** [comment]
My opinion of it is probably similar to this: https://stackoverflow.com/a/54545744

I'm not convinced it helps optimization, but I think it can be good for readability if used properly.  For example, the Core/MIPS/IR/IRInterpreter.cpp changes are probably clearer.  The DecodeDXTBlocks changes seem like mostly a wash, but I guess maybe clearer.

I feel like the DrawPixel changes don't help, though, and the change of `if (pixelID.alphaBlend) {` is actually incorrect as it fails to apply dithering when alphaBlend is accidentally on during clearMode.  I think simple conditionals are better for that code and would want to see actual perf benefit (at least in debug mode) to motivate complicating it.

-[Unknown]

**Comment by hrydgard** [comment]
Replacing this with #17221, closing.

**Pull request closed without merging**
