### PR TITLE
Add new sceP3da (Positional 3D Audio Library)

### PR DESCRIPTION
**Pull request by dbz400**

### CODE REVIEW

**Comment by chrisp110** [comment]
Reading this many years after the fact, have you guys implemented anything for the sceP3da library other than just a stub? If not, I could give you some pointers on how this is supposed to work.

**Comment by hrydgard** [comment]
@chrisp110  We have not. Any information you have is appreciated, though can't promise I'll get around to implementing it anytime soon even if you've got complete info somehow - use of this library is not that common and the games work anyway without it...

**Comment by unknownbrackets** [comment]
Yeah, I'm only aware of like 3 games using it:

https://report.ppsspp.org/logs/kind/142 (Last Promise Story, Sol Trigger, and Criminal Girls)

If there are more, that'd be useful to know about.

-[Unknown]

**Comment by chrisp110** [comment]
I think Harry Potter and the Goblet of Fire used it during some of the cut scenes/videos.

**Comment by unknownbrackets** [comment]
If you play that game / area with "compatibility server reporting" enabled, any calls to sceP3daBridgeInit will be logged at the URL I gave.  Well, unless you have certain known-bad settings configured (such as active cheats, locked CPU speed, etc.)

But if you have details of how it works, that's be great.  Ideally would want to turn that into tests for the pspautotests repo.

Just to mention, another API we don't really emulate is sceVaudio.  I'm not sure if it's related, but here's the reporting URL for one of its functions in case it is:

https://report.ppsspp.org/logs/kind/152

-[Unknown]

**Comment by chrisp110** [comment]
Sorry, never had any exposure to sceVaudio. The API looks fairly simple though, just seems to be enabling a handful of audio effects. Who knows what those audio effects might be but if it's somehow possible to drive the audio interface (on real h/w) with various test signals and enable/disable the effects it might be possible to reverse engineer what these are and replicate them.

**Pull request merged**
