### PR TITLE
v1.13.2 hotfix branch

### PR DESCRIPTION
**Pull request by hrydgard**
This PR will not be directly merged, I'll manually merge the branch after tagging correctly and so forth, this is just to show what will be in the release.

Basically 1.14 is still some time away and I have to do a 1.13.2 bugfix release, since people are affected by #15990, which we now have a fix for.

So this is that fix, plus a bunch of random super-safe other fixes that we might as well get out there.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
#15874 might be nice, just for those using software rendering.  Was a foolish mistake and very low risk.  Probably also #15870, could just only do d61619d.

Possibly #15762 as well?

I guess we could also include #15881 or #15844, but they're not that important and are just for debugging - hopefully people messing with dumps or headless are using the latest git.

-[Unknown]

**Comment by hrydgard** [comment]
Thanks, I'm skipping the headless ones, but picking up the rest (doing only d61619d from #15870)

**Comment by hrydgard** [comment]
Hm, annoying that CI won't run since there are conflicts with master, but I also don't want to resolve those in the branch.

**Comment by unknownbrackets** [comment]
I changed the milestone on the pulls involved (some were partial, but I changed anyway since the main gist of the pull was included.)  This way we hopefully won't be confused later about what was included.

Gonna send a pull with a merge --theirs.

-[Unknown]

**Pull request merged**
