### PR TITLE
Improve FFmpeg detection on debian systems (cmake)

### PR DESCRIPTION
**Pull request by sergiobenrocha2**

### CODE REVIEW

**Comment by sergiobenrocha2** [comment]
any problem with this PR?

**Comment by hrydgard** [comment]
No, it looks fine, I've just had a couple of very busy days.

Can you explain what makes Debian so special though? Also you are deleting some packaging files? I don't know much about packaging, I'm just curious what's going on in this change.

**Comment by sergiobenrocha2** [comment]
The upstream tarball must not have a debian folder. And that packaging is very old too, I did a new package: http://mentors.debian.net/package/ppsspp

**Comment by hrydgard** [comment]
Thanks!

**Pull request merged**
