### PR TITLE
[Common/UI/Core/Debugger/HLE/GPU] Using try_emplace C++17 if possible

### PR DESCRIPTION
**Pull request by GermanAizek**
@hrydgard I think it's not worth describing why in some situations try_emplace has faster insertion speed than a regular emplace.

### CODE REVIEW

**Comment by hrydgard** [comment]
conflict, please rebase.

**Comment by unknownbrackets** [comment]
A lot of these cases don't construct the value (a value is just passed in, or is a constant like `1`.)  What benefit is expected in these cases?

-[Unknown]

**Comment by hrydgard** [comment]
This seems dangerous. try_emplace will not insert if the key already is present in the map, which might not always be the case, so it changes the semantics if the value isn't the same. I don't think any of this is on a very hot path anyway, so I'm closing.

**Comment by unknownbrackets** [comment]
I think emplace already also does that, like insert.  I don't think either one replaces.  This just allows skipping the value construction if it wouldn't insert.

-[Unknown]

**Comment by hrydgard** [comment]
Heh, you're right - I misremembered again.

**Pull request closed without merging**
