### PR TITLE
Update ja_JP.ini

### PR DESCRIPTION
**Pull request by maekawa-mugi**

### CODE REVIEW

**Comment by hrydgard** [comment]
hm, why close?

**Comment by maekawa-mugi** [comment]
I did'nt notice the commit https://github.com/hrydgard/ppsspp/commit/21d5257fbfaa281f8a527303519182d6fd0ef970#diff-631e5af29adba9c6075747735c7042645430876b308c3efc13cfc1d89616cde7. I will reopen later

**Comment by hrydgard** [comment]
oh, ok.

I probably won't add more strings now before the release. But it will be soon, so if you want to get your changes in, now's the time :)

**Comment by maekawa-mugi** [comment]
I made a mistake when operating my branch. Please merge this commit manually. My apologies.

**Pull request closed without merging**
