### PR TITLE
Rename GPU_SUPPORTS_* to GPU_USE_*

### PR DESCRIPTION
**Pull request by hrydgard**
These flags generally are not what the GPU actually supports (and we now have draw_->GetDeviceCaps() for that), but what code paths we have decided to use depending on the GPU, API and their capabilities.

So simply rename these flags so the code "reads" correctly. Makes things easier to reason about.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
It looks like this accidentally reverts the pspautotests submodule.

-[Unknown]

**Comment by hrydgard** [comment]
Oops, I'll fix.

**Comment by hrydgard** [comment]
Keep forgetting to `git submodule update --init`, so `git add .` results in a submodule revert. Wish it could be made automatic

**Review by unknownbrackets — APPROVED** [review]
Cool, it did start as supports (mostly/kinda), but it's kinda changed purpose along the way and with Draw.

-[Unknown]

**Comment by hrydgard** [comment]
Yup, sometimes gotta rename stuff to keep up with what it actually becomes :)

**Comment by unknownbrackets** [comment]
I just pretend `git add` doesn't function without using the `-p` flag.  Also usually saves me from adding files/debug code I don't want... usually.  But makes me more likely to miss binary files like that darn Osk.

I suppose you could use an alias to pull and submodule update, but I think it'd have to be a different keyword than pull.

-[Unknown]

**Comment by hrydgard** [comment]
Ended up conflicting with #16242 of course, I'll rebase and push -f .

**Comment by unknownbrackets** [comment]
Ah, sorry.

-[Unknown]

**Comment by hrydgard** [comment]
Oh nothing to be sorry about, just a fact of life :)

**Pull request merged**
