### PR TITLE
Collapsing view group

### PR DESCRIPTION
**Pull request by iota97**
PPSSPP setting menu is getting kinda crowed.

This is a attempt to make some setting group collapsing as a drop list.

This is applied only to graphic setting as a test (with just frame control section being collapsed by default for testing, no real reason for choosing this one).

Preview:
Screenshot_2021-02-07_20-45-45

Kinda want to hear what other people think about this and other possible solution or aids.

### CODE REVIEW

**Comment by unknownbrackets** [comment]
I'm worried people will tap while scrolling, and get confused just not seeing some settings.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah, accidental taps during scrolling is definitely a concern. There's probably a reason you don't see this much in touch interfaces...

**Comment by iota97** [comment]
I see, didn't really thought about that. I'll close this, thx for the advice :)

**Comment by unknownbrackets** [comment]
I think it was implemented well, fwiw.  But touch UX can be tricky indeed.

-[Unknown]

**Comment by hrydgard** [comment]
Yeah we could maybe even use it on desktop, though I do like to be consistent.

You're right that we should do something about the very long list of settings we have ...   Maybe even a search function :P

**Comment by iota97** [comment]
Not sure if the technical name of the setting will make a search kinda hard for the average user.

I find a bit a pain to test graphic setting as I have to scroll to the setting, check the result, scroll againt, etc...
Maybe just remembering the scroll position as in the main screen game list will do tho'.

**Comment by hrydgard** [comment]
Yeah, I know it's a pain. I'll try to think of something...

**Comment by unknownbrackets** [comment]
A find-as-you-type search wouldn't be terrible at all, though.  Remembering the scroll position doesn't seem bad, but might get confusing between tabs.

-[Unknown]

**Pull request closed without merging**
