### PR TITLE
Create screenshot directory if not exist when using Report Feedback

### PR DESCRIPTION
**Pull request by LunaMoo**
~otherwise it hangs

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Seems okay, but do you know why it hangs?  Wouldn't want it to hang if the directory failed to create either...

Actually, maybe this should use CreateFullPath?  Well, the parent should've been created already...

-[Unknown]

**Comment by LunaMoo** [comment]
Well from what I recall trying to debug it it was hanging when setting screenshot_ visibility ~ https://github.com/hrydgard/ppsspp/blob/master/UI/ReportScreen.cpp#L164 after failing to write the screenshot file earlier https://github.com/hrydgard/ppsspp/blob/master/Core/Screenshot.cpp#L74

**Comment by unknownbrackets** [comment]
Darn it, I forgot to set `screenshot_ = nullptr;` in the else with `includeScreenshot_ = false;`.... I think that would help, in addition to this change.

-[Unknown]

**Comment by LunaMoo** [comment]
Yup that helped, disabled my user rights to those folders just to test what happens if it fails to create it.

**Pull request merged**
