### PR TITLE
Allow delayed loading of texture replacements

### PR DESCRIPTION
**Pull request by unknownbrackets**
Delayed loading (pop in) is not really ideal, especially if replacements aren't just higher detail but have some differences (I think for more simplistic games, they can even be used to translate a game.)  But hitching is really annoying, so arguably the replaced images "hitching" in without affecting gameplay is also bad, but less bad.

This takes a very simple step and uses a frame budget to decode texture level data into RAM but avoid significant hitching.  It keeps this decoded data cached for a while, so it can skip decoding if the texture is needed again in a couple minutes.

It might be nice for this to be configurable (both whether you would allow popping, and maybe some way to balance RAM usage), but wanted to open this to allow people to experiment and see how this impacts hitching.

This doesn't move texture decoding to threads, but that wouldn't be much harder to do.  A more advanced technique (loading texture in thread until queue runner, and dynamically selecting texture and maybe shader at that point) is somewhat complex, but ultimately would probably result in *some* hitching or pop-in too, so this is an experiment to see how bad pop-in is.

Feedback on builds under Artifacts on the Checks tab appreciated.

-[Unknown]

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Blarg.  I got myself worried about the width changing and crashing from out of bounds and forgot to validate PNGs after changing, I seem to be forgetting to retest after minor changes more often these days... I thought I did.  Darn it.  Anyhow, fixed, just needed the `png.width * 4`.  Sorry.

-[Unknown]

**Comment by LunaMoo** [comment]
It replaces the textures nicely on boot, but then crashes when the video should start(movie is not replaced there), it also crashes when loading a savestate with texture replacement active.

**Comment by unknownbrackets** [comment]
Ah, sorry, D3D11 was still trying to use the texture.  Cleaned that up and centralized a bit.

-[Unknown]

**Comment by LunaMoo** [comment]
Thanks:),
unfortunately it still doesn't solve the stutter completely, when a dialog loads asking about savedata I can see the font pop in, but instead of one freeze on the start it kind of has multiply freezes now for each frame(the dialog is animate and stretches out). Same thing for other textures, they do pop in, but there's still a freeze despite running everything of ramdisk.

**Comment by LunaMoo** [comment]
That stuttery screen with dialog animation is actually much worse than without this feature, kind of looks like it invalidates the texture each frame as without the feature it just quickly loads and disappears without any delays.

**Comment by LunaMoo** [comment]
Combined ZIM + pop in is enought to have it practically stutter free:).
https://youtu.be/b5Y7WUPlW9Q

**Comment by LunaMoo** [comment]
If I understand correctly, threaded decoding would make it no longer require to fit within frame budget, so assuming no other bottlenecks, would make it silky smooth and just make it pop in later depending on hardware performance?

 If soo that'll be great, definitely a better choice for gameplay than freezes/stutter through an option to disable delay might still be nice to have for people that doesn't care about gameplay experience and just want to record video with built-in recorder.

**Review by hrydgard — APPROVED** [review]

**Comment by superostrich** [comment]
This has completely fixed the stuttering in the games I've made texture packs for!

The only downside is that re-loading from a save state or toggling texture replacement off and on no longer causes the textures to be read from disk, which is an important feature for authoring textures, since it lets you rapidly iterate and test in-game. 

It would be useful to be able to disable this feature, or flush the texture cache and re-load replaced textures from disk if the user toggles texture replacement off and on,

**Comment by unknownbrackets** [comment]
You can disable this using `ReplaceTexturesAllowLate = False` in the ini.  I suppose it might cache that the file doesn't exist?  Probably we can improve this, I think it might be the later pull that reduces IO if anything.

-[Unknown]

**Comment by superostrich** [comment]
Just tested; setting `ReplaceTexturesAllowLate = False` does not cause the textures to re-load from disk when toggling texture replacement, or loading from a save state. 

A hotkey to reload replaced textures from disk, would be very useful!

**Comment by unknownbrackets** [comment]
Please check #15740 when it's done building (Artifacts on the Checks tab.)  This should make disabling and re-enabling clear cache and reload them.

-[Unknown]

**Comment by superostrich** [comment]
> This should make disabling and re-enabling clear cache and reload them.

Works perfectly, thanks!

**Pull request merged**
