### PR TITLE
Made Rapid Fire work on every possible frame regardless of frame rate.

### PR DESCRIPTION
**Pull request by Alceris**
It wasn't even difficult, why did you guys overcomplicate it to make it
unreliable?

### CODE REVIEW

**Comment by hrydgard** [comment]
Well, I think the intention was to limit the speed a bit rather than compensating for various framerates. And not all games have input processing in sync with the drawn frames anyway (half or double, for example). 

But I might be wrong, @unknownbrackets ?

**Comment by Alceris** [comment]
I was sure there was a better way to do it even while I was doing it, but it's at least better than what's currently in.

**Comment by unknownbrackets** [comment]
I don't understand.  This change only makes it more unreliable.  Can you explain?  @hrydgard is completely right.

1. PSP games can sample input less/more frequently than flipping frames.  They're not connected, although they will be in *some* games (unreliably so.)

2. This change means that rapidfire in a 60fps game will press 30 times per second, but in a 30fps game will press 15 times per second.  Seems less reliable, compared to simulating me hammering the button which won't be affected by the FPS.

3. Some games seem to have a filter on presses or something, but this may have been a bug from years ago.  I picked 5 to ensure it was reliable in causing distinct presses.

I don't understand a single way in which this change can make the feature more reliable.  Where has it been "unreliable" and in what game (it has always worked in all my games)?

I want to understand the problem you're trying to solve, not the way you're trying to do it (which seems potentially wrong to me.)  /What/ specifically is this making better?

From my perspective, it may make more sense to configure the "per second" of rapid fire, e.g. instead of 12 presses per second.  Some games may require less or more.

-[Unknown]

**Comment by Alceris** [comment]
It was Kingdom Hearts: Birth by Sleep I was playing where it was not useful at the original speed and did not work at all if the FPS dropped below 60 (thanks to a 60 FPS code) if I set it to % 2 == 0. I haven't tested it with any other games, but at least in this game, this change makes it always fire at every possible frame regardless of base frame rate or lag, which is what _Rapid_-fire should do, in my opinion.

**Comment by unknownbrackets** [comment]
When you say, "did not work", do you mean that it doesn't register the button presses?  Or do you mean it's not triggering a combo you want it to?

Without any cheats, rapid fire causes presses just fine in Kingdom Hearts for me.  It presses 6 times a second for 1/12 of a second (from the game's perspective) each time, reliably, and does so regardless of how fast or slow the game is running.

When the game drops frames, I suppose it might sample less frequently.  As long as it samples > 12 fps, it should notice that the pressed state is changing.  Are you dropping to less than 12 FPS?  This pull will make the press rate unreliable in that case; when you get 60 fps, it'll press 30 times per second, when you get 12 fps, it'll press 6 times per second.

Maybe the 60 fps cheat messes with combo timing, and 6 times per second is no longer enough to trigger a combo?  If that's the case, it sounds like you're really just wanting a way to change the rapid fire rate.  Even in that case, I don't think you'd want to change rapid fire speed based on dropped frames.

-[Unknown]

**Comment by Alceris** [comment]
You didn't seem to read the whole thing, I said it didn't work below 60 FPS when I changed it to have no delay, and by didn't work I mean didn't register any button presses at all. What I did here, as I have stated several times now, is attempt to make it have as little delay as possible and also never fail to register the button presses.

**Comment by unknownbrackets** [comment]
@hrydgard So it sounds like this user doesn't really care about games not written the way he thinks games should be written, and more specifically does not care about games that aren't the one game he wants to play.  It's pretty clear he will not adjust the pull request based on our feedback.

Basically, it boils down to this:

The user wants a faster press rate.  They won't clarify why, but maybe because the combo rate is broken by the 60fps hack.  The user has decided that the only press rate that makes sense is the fastest possible, for no specified reason.  Games that won't support this don't matter and are stupid.

It sounds like a slider to adjust the speed would work, at least for the general case of being able to handle the broken combo rate from the 60fps hack.  But it won't satisfy this user's demand that it must be written the way he or she thinks is fastest and the only way PSP games (that aren't stupid) should've been written.

I think we should close.

-[Unknown]

**Comment by hrydgard** [comment]
Yup.

Current rapid fire is totally fine for the majority of uses and has proven reliable (for what it is) among all kinds of games, so not worth changing IMHO.

Would possibly accept a pull request that adds some sort of slider that defaults to the current behaviour, or maybe even preferably just an ini setting, though, to avoid having to localize yet another setting.

**Comment by Alceris** [comment]
You didn't just make some kind of judgement about me under the idea that unknownbrackets actually understands English, did you?

**Comment by unknownbrackets** [comment]
I know a faster rate has been requested by some users on the forum before, but yeah probably ini-only is enough.  I googled quickly and found someone quoting 15/s for one and 23/s for multiple buttons as the fastest button mashing known in rhythm gaming communities.

So I can see some cases where > 6/s makes sense, probably wouldn't need more than 15/s, though.

-[Unknown]

**Comment by hrydgard** [comment]
@Alceris You need to fix your attitude if you want help. I told you I might accept a pull request that adds an ini-only setting, if done nicely and keeping the current default. That should be good enough.

**Comment by Alceris** [comment]
@hrydgard I find it really unfortunate that you've decided to take the side of the guy that made me repeat myself several times before insulting me.

**Pull request closed without merging**
