### PR TITLE
Invalidate jit blocks on IO read and a few other places

### PR DESCRIPTION
**Pull request by unknownbrackets**
Seems this fixes the errors in #7617.  Safer in situations where new code is copied there.

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
Fixed https://github.com/hrydgard/ppsspp/issues/7617

**Comment by hrydgard** [comment]
Great stuff, obvious in retrospect...

**Comment by Bigpet** [comment]
Hm, I should retest #3854 or is this completely unrelated?

**Comment by unknownbrackets** [comment]
Worth retesting, yes.  But I think it probably doesn't use io reads.

-[Unknown]

**Pull request merged**
