### PR TITLE
Reuse 2 already translated strings

### PR DESCRIPTION
**Pull request by vnctdj**
Just a trivial edit :)

### CODE REVIEW

**Comment by unknownbrackets** [comment]
Is "Yes, please proceed with this" always the same word as "Yes, this is supported"?

"Debugger present - Yes" seems like a significantly different context to me than "Would you like to delete all your saves?"

-[Unknown]

**Comment by vnctdj** [comment]
For me, a "yes" is a "yes", it doesn't depend on the context.

The solution is to use more specific words when applicable. It makes me think of [this](https://ux.stackexchange.com/a/9960).
For example, the "yes/no" could be replaced by "supported/not supported".

**Comment by unknownbrackets** [comment]
I definitely don't disagree with using proper confirmation labels from a UX perspective, but I still think it's dangerous to mix contexts.

Example: "Bookmark".  In English, there is one word: "This site is so interesting, I will *bookmark* it" and "The *bookmark* has been created."

In Spanish (I'm not a Spanish expert), the noun might be "marcador" but the verb "marcar".  You probably can't use the same word for both.  So if a screen was titled "Bookmark" and a button somewhere else was labeled "Bookmark", you'd get a conflict.  You'd end up with a stilted translation.

Of course, "Create Bookmark" could be used in this context - but being overly verbose isn't necessarily a good thing for UX either.

-[Unknown]

**Comment by vnctdj** [comment]
I perfectly understand what you mean.
However, I have trouble seeing how this could apply to a word as simple as a "yes" :/
I know we are not machines, but how could a _boolean_ be misinterpreted?

Shouldn't we rather focus on finding a more specific word for ambiguous cases?
Which one(s) of this pull request look ambiguous to you?

**Comment by unknownbrackets** [comment]
Well, I guess this was all burned into me 15 years ago with [SMF](https://www.simplemachines.org/community/index.php?board=12.0).  Maybe it won't be the case for Yes/No, I just fear using the same strings in different contexts now.

-[Unknown]

**Comment by vnctdj** [comment]
I'm always impressed how rational you are, thanks for your thoughts :)

You are definitely right to say we must be careful about contexts, I believe it shouldn't be an issue here.
Anyway, anyone can open a new issue in the ppsspp-lang repository :)

Merge at will.

**Comment by hrydgard** [comment]
So, simple question: Did you check in all the language files that these are always translated to the same value?

If so, I'm fine with this. If you didn't check, I'm not :)

**Comment by vnctdj** [comment]
> So, simple question: Did you have a look in all the language files that these are always translated to the same value?

For _es_ES_ and _pt_BR_, yes : 
[es_ES - "No"](https://github.com/hrydgard/ppsspp-lang/commit/c06016cec102ba492883760dee24f5f691e1396a#diff-dbbc259b791c5b6b0b71cb8576e0c6c5R730)
[es_ES - "Yes"](https://github.com/hrydgard/ppsspp-lang/commit/c06016cec102ba492883760dee24f5f691e1396a#diff-dbbc259b791c5b6b0b71cb8576e0c6c5R753)
[pt_BR - "No"](https://github.com/hrydgard/ppsspp-lang/commit/3ec206b6548356339582dc303fac6af2d4414efe#diff-4b2697db63eccabaef7dde691de9e133R729)
[pt_BR - "Yes"](https://github.com/hrydgard/ppsspp-lang/commit/3ec206b6548356339582dc303fac6af2d4414efe#diff-4b2697db63eccabaef7dde691de9e133R752)

But for _th_TH_, it seems the translator has replaced "yes/no" by "supported/not supported" : 
[th_TH - "No"](https://github.com/hrydgard/ppsspp-lang/commit/0986a8cc8aa661db7d6e0728b2a9235d23e7f266#diff-9b3e736f0ea24e4a5fd2e2877eb8e2edR736)
[th_TH - "Yes"](https://github.com/hrydgard/ppsspp-lang/commit/0986a8cc8aa661db7d6e0728b2a9235d23e7f266#diff-9b3e736f0ea24e4a5fd2e2877eb8e2edR759)

However, this doesn't feel right to me.
While "yes/no" could be OK for the 4 cases concerned by my commit, "supported/not supported" couldn't.
I think about this : 

<pre>
si->T("Debugger Present")	di->T("Yes")
si->T("Core Context")		di->T("Supported")	di->T("Not supported")
si->T("RW/RX exclusive")	di->T("Yes")		di->T("No")
si->T("Sustained perf mode")	di->T("Supported")	di->T("Not supported")
</pre>

What do you guys think ?

**Comment by hrydgard** [comment]
In English it's fine to use Yes/No for Supported/Unsupported but I'm guessing that it's not in Thai, since the translation made that choice. That means that we probably don't want to make this change, which is a tiny, tiny savings anyway. Sorry :)

**Comment by vnctdj** [comment]
So you didn't consider my proposition ?
What a shame... I could just have pushed another commit :(

**Pull request closed without merging**
