### PR TITLE
Cleaned up branch of Xebra's hw tess

### PR DESCRIPTION
**Pull request by hrydgard**
Something has gone wrong with the merges in #9210 so I decided to just cherry-pick all the actual changes to a new branch for easier review and cleaner merge.

### CODE REVIEW

**Comment by DonelBueno** [comment]
It's not working properly for me.

Hardware tesselation:

1a- hardware tesselation

1b- hardware tesselation

2a- hardware tesselation

2b- hardware tesselation


Software tesselation:

1a- software tesselation

1b- software tesselation

2a- software tesselation

2b- software tesselation

**Comment by LunaMoo** [comment]
Are you really using GTX 770 or maybe running of integrated intel HD by accident? Because this should work on amd/nvidia gpu's just fine, on most other stuff will probably just have to be disabled. Intel graphics have quite likely just as poor drivers on windows as gles devices on android.

 Unless it's some windows 10 driver bug:|, what error does the log shows?

**Comment by DonelBueno** [comment]
My CPU doesn't have an integrated GPU. I'll check the log soon, thanks.

**Comment by LunaMoo** [comment]
Wasn't there anything earlier? Like actual errors printed with red colors?
 Your screenshots with missing graphics look like a shader compilation failure, but this log doesn't really show anything related or even specially wrong. I think I'll relog to win 10 and see if my AMD gpu is affected, it's unfortunately working fine on win 7:].

**Comment by DonelBueno** [comment]
These erros showed upon opening the game:

**Comment by LunaMoo** [comment]
None of those are related;p. Also can't reproduce it with amd gpu even on win 10 with like half year old drivers(aka previous time I logged on it).

 I can only guess it's at least partially the same thing as #9234 we'll have to improve this code to at least match GLSL specs, because it's now working only on pc's with better driver interpretation. And on some older devices this feature will most likely be completely disabled.

**Comment by DonelBueno** [comment]
Even after the merge of #9242, the glitch is still true. I'll try to update my drivers, this is really strange.

**Comment by DonelBueno** [comment]
My issue was fixed aside with issue #9249 =)

**Comment by xebra** [comment]
@DonelBueno Thank you for reporting :)

@hrydgard Nice work, thanks!

**Pull request merged**
