### PR TITLE
Imp sceKernelFindModuleByName

### PR DESCRIPTION
**Pull request by sum2012**
#13204
Is it wrong so that don't do before ?

### CODE REVIEW

**Comment by hrydgard** [comment]
I don't quite understand why we need to add one?

**Comment by unknownbrackets** [comment]
Typically, any kernel code calling these funcs is trying to patch kernel code - kernel code that doesn't exist in PPSSPP.  This is generally a function unlikely to ever really work under HLE.

That said, it could also be used to patch game code, I suppose, which might work.  But we'd want to create a test of what it's doing so we handle modules properly full the full thing.  I'm not sure this would work in that case as-is.

-[Unknown]

**Comment by sum2012** [comment]
@hrydgard 
https://github.com/hrydgard/ppsspp/blob/master/Core/HLE/HLE.cpp#L170
GetModuleIndex return -1 ,0,1,etc
so that sceKernelFindModuleByName  return should be 0,1,2,etc 
It mean GetModuleIndex + 1

@unknownbrackets jpcsp 's code work 99.9% with patched game  except #13204 

The game still not work,leave this is okay.

**Comment by hrydgard** [comment]
Oh so it's so that there's space for negative error codes, I see, although that's a rather odd interface if so. Anyway, I'll merge it...

**Pull request merged**
