### PR TITLE
fix building for rpi2 by disabling armv7.

### PR DESCRIPTION
**Pull request by joolswills**
added missing rpi include
correct cflags for rpi1/rpi2 (although rpi2 will build for armv6 for now)
only build Common/ColorConvNEON.cpp on armv7

### CODE REVIEW

**Comment by hrydgard** [comment]
I guess that's alright as a temporary workaround.

Would be nice if you could run on under gdb on the rpi2 and get a callstack from the crash, too :)

**Comment by joolswills** [comment]
Backtrace is here - can provide additional information if needed - https://github.com/hrydgard/ppsspp/issues/7479#issuecomment-150895112

**Comment by hrydgard** [comment]
@joolswills oh I missed that. Huh, crashing while compiling a shader. GPU driver bugs?

**Comment by joolswills** [comment]
I suspect it's something related to the RPI gpu drivers - I will open a ticket to get some feedback from the RPI firmware guys. No idea why this would only happen when building for arm7 - the driver binary blobs are built for armv6 though - so maybe something to do with differences in way data is passed in ? (complete uninformed guess)

**Comment by joolswills** [comment]
Opened a ticket here - https://github.com/raspberrypi/firmware/issues/491

**Comment by joolswills** [comment]
There has been a reply on the RPI ticket linked above - but I'm not all that experienced at C++, perhaps it is useful to you or not (or you could answer it) ? https://github.com/raspberrypi/firmware/issues/491#issuecomment-151069485

**Comment by joolswills** [comment]
Building a armv7 libstdc++ does fix it

see https://github.com/raspberrypi/firmware/issues/491#issuecomment-151607466

**Comment by joolswills** [comment]
woops. wrong thread - but I'll post here anyway. The issue it turns out is a GCC / libstdc++ bug which affects Raspbian as it's built for armv6 - see

https://github.com/raspberrypi/firmware/issues/491#issuecomment-151607466

**Comment by joolswills** [comment]
so really we don't want to disable armv7 on the RPI, but just disable it for Raspbian for now. Would you accept a patchset with a manual option to disable armv7 for use on raspbian until there is another solution ?

**Pull request merged**
