### PR TITLE
Support some patcher module

### LINKED ISSUE #7909: Naruto  Ultimate Ninja Heroes 3 black screen
I have black screen when im trying to start Naruto Ultimate Ninja Heroes 3

### PR DESCRIPTION
**Pull request by sum2012**
Fix #7909 

@unknownbrackets please help to merge because @hrydgard absent last week
Thanks

### CODE REVIEW

**Comment by unknownbrackets** [comment]
This feels like a not very pretty workaround.  I guess the base EBOOT renames the libs to these?

Can't the user just re-rip from their disc or etc., a clean version?

-[Unknown]

**Comment by hrydgard** [comment]
Alternatively, create CWCheat codes for the games that replace the Z etc with the correct letter?

**Comment by sum2012** [comment]
@Slarker0k Contributors seems do not agree my fix.
Can you re-rip from your disc ?

**Comment by Slarker0k** [comment]
should i re-rip version that u send me?

**Comment by sum2012** [comment]
Do you mean this ppsspp version (https://drive.google.com/file/d/0B3OaSdeV0L8kWkhSbjZxX2VmYm8/view?usp=sharing ) ?

You can continue to use but you would not get update to work with newest ppsspp 's version.

**Comment by Slarker0k** [comment]
ive 2 different versions of ppsspp, so ill use one Naruto ultimate ninja hero 3

**Comment by unknownbrackets** [comment]
> Alternatively, create CWCheat codes for the games that replace the Z etc with the correct letter?

I wonder if cwcheat runs early enough to affect the linking process...

-[Unknown]

**Pull request closed without merging**
