### PR TITLE
Swizzle video data when writing to VRAM mirors

### LINKED ISSUE #7809: Video is incorrectly swizzled in Tengai Makyou 4
http://puu.sh/imcuj/a04a3898e9.png

The frame is written to 0x04374000 by sceMpegAvcDecode, and is then deswizzled before displaying, resulting in the broken image. That was introduced in e979b3a, but that's likely only because it uncovered an issue. It's possible that it should be written in a swizzled state by sceMpegAvcDecode.

### PR DESCRIPTION
**Pull request by unknownbrackets**
This fixes #7809.

-[Unknown]

### CODE REVIEW

**Comment by daniel229** [comment]
Video flickers in three kingdom 9.

**Comment by daniel229** [comment]
Kingdom heart either.

**Comment by hrydgard** [comment]
That should be fixed after https://github.com/hrydgard/ppsspp/commit/4f3d18fcb7031da835b3a16b11ea78338d6531e3

**Comment by daniel229** [comment]
No,that fixes the Gundam Assault Survive,but did not fix the two games mention above.

**Comment by hrydgard** [comment]
Ok, I got it, fixed now.

**Comment by daniel229** [comment]
Perfect.

**Pull request merged**
